### ISSUE TITLE
TinyLetter shutting down

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#1011]
### Summary

I just received a notice that Mailchimp, which owns TinyLetter, is shutting that service down on February 29th. We use https://tinyletter.com/tedana-devs to send out infrequent updates to tedana users (last message sent May 2023). We need to decide what to do before the shutdown deadline.

### Additional Detail

I can send the full email announcing the sunset of TinyLetter to anyone who wants to read it.
I've already downloaded our past messages & list of 47 current subscribers. 

### Options

1. Get rid of list and remove all references to it in our documentation. We rarely send out messages and most users aren't even subscribers. We'd probably want to send out a message and query the current subscribers before doing this
2. Move the list to another system.
    * Free mailchimp is sufficient for our current needs, but probably takes more work to send out simple newsletters
    * Something more like groups.io (Easy to send out messages and archive, but would open up another discussion board location)
    * Something else

Thoughts?

**Comment by handwerkerd** [comment]
I saw a reference to https://buttondown.email/ as another simple newsletter option. Anyone have experience with it?
We should definitely discuss this issue at our January dev call.

**Comment by handwerkerd** [comment]
I just created https://groups.google.com/g/tedana-newsletter

Positives (with how I set it up):
-  Easy to set up and send out messages
-  Easy to add and remove people
-  Easy to give a small group of people permission to post and no one else
-  Group managers can post using `tedana-newsletter@googlegroups.com` rather than their personal addresses
-  History of messages are world-viewable without subscribing
-  I was able to port over all our tinyletter messages so the archive is in one place

Negatives:
-  This is Google so they might shut down groups next week
-  It looks like a discussion forum so the info message, welcome message, and rejected post message all direct people to neurostars or github
-  I've currently set up the messages to be world readable. This was true for tinyletter as well, but I suspect that site didn't pop up in human or bot searches as often. When I ported the messages from tinyletter I removed all personal email addresses and we might want to avoid personal email addresses in future posts as well.
-  We can't make draft messages within the system for others to review before posting

As for the discussed alternatives, buttondown and groups.io both start to charge money if we get over 100 subscribers. We're currently well below that, but that limit wasn't something I wanted to worry about. Mailchimp is over-featured / over-complex what we're trying to set up. substack might have worked, but this seemed simpler and makes having multiple managers really easy.

Subscribe and take a look at the site. We should announce in the next couple of weeks, so please raise any concerns soonish.

**Comment by handwerkerd** [comment]
@goodalse2019, As a way to get used to the tedana pull request / review system, you offered to make the edits to point to https://groups.google.com/g/tedana-newsletter instead of tinyletter. I think this just affects `./docs/index.rst` and `README.md`
I think we're ready for this so, let me know if you're still planning to do this. I or others can help you if any documentation is confusing. As a first time contributor, please also keep an eye for ways the contributor guidance docs can be improved.

Thank you

**Comment by goodalse2019** [comment]
@handwerkerd, perfect! I will check it out and do it this week. I'll let you know if I have any questions or updates to contributor guidance as I go. Thanks!

**Comment by handwerkerd** [comment]
The draft newsletter that includes this announcement is here: https://docs.google.com/document/d/1ZVeNGdCMmKiqpe-GHSSklpuS8o1KiT0JZFUNE07fPKI/edit?usp=sharing I've love to send it out by the end of this week, so prompt feedback is appreciated.
