### ISSUE TITLE
dynamics reports crashing with bokeh 3.4.0

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#1063]
### Summary

A user just sent me a crashed run and I think the issue is that they are using bokeh=3.4.0, which was released in March 2024.

### Additional Detail

The log contains
```
INFO.   tedana:tedana_workflow:903 Generating dynamic report
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.4.0 and will be removed, use 'scatter(size=...) instead' instead.
```
The trackback crashes here:
https://github.com/ME-ICA/tedana/blob/a21d65ec5b1682a52cb8fe0eee1689d5eb3154a3/tedana/reporting/dynamic_figures.py#L350

[The bokeh 3.4.0 version release](https://docs.bokeh.org/en/latest/docs/releases.html#release-3-4-0) includes _Deprecated `figure.circle(size=10)` in favour of `figure.scatter(size=10)` API ([pull request 13283](https://github.com/bokeh/bokeh/pull/13283))_

### Next Steps

- Confirm this really is causing a full crash with the newest version of Bokeh
- Figure out, if we switch from `circle` to `scatter` if that affects our visualizations or if we'll need to update the minimum acceptable version of bokeh

**Comment by gottss** [comment]
> ### Summary
> A user just sent me a crashed run and I think the issue is that they are using bokeh=3.4.0, which was released in March 2024.
> 
> ### Additional Detail
> The log contains
> 
> ```
> INFO.   tedana:tedana_workflow:903 Generating dynamic report
> BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.4.0 and will be removed, use 'scatter(size=...) instead' instead.
> ```
> 
> The trackback crashes here:
> 
> https://github.com/ME-ICA/tedana/blob/a21d65ec5b1682a52cb8fe0eee1689d5eb3154a3/tedana/reporting/dynamic_figures.py#L350
> 
> [The bokeh 3.4.0 version release](https://docs.bokeh.org/en/latest/docs/releases.html#release-3-4-0) includes _Deprecated `figure.circle(size=10)` in favour of `figure.scatter(size=10)` API ([pull request 13283](https://github.com/bokeh/bokeh/pull/13283))_
> 
> ### Next Steps
> * Confirm this really is causing a full crash with the newest version of Bokeh
> * Figure out, if we switch from `circle` to `scatter` if that affects our visualizations or if we'll need to update the minimum acceptable version of bokeh

A follow-up: Uninstalling Bokeh 3.4.0 and installing Bokeh 3.3.0 fixed this issue.

**Comment by eurunuela** [comment]
I would say let's limit the version of Bokeh to a maximum of `<3.4.0`. We can update this later in the future if necessary.
