### ISSUE TITLE
Proposal to release version 24.0.1

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#1093]
### Summary

I am proposing releasing a new version of tedana.

### Additional Detail

- The main reason for releasing now is that I'm getting a steady stream of users who have accidentally upgraded to bokeh v.3.40 and tedana is crashing. We fixed this problem (#1068) and it would be nice to get this into an official release so that I can stop asking people to either download the pre-release version or downgrade bokeh.
- This also includes the bug fixes for the adaptive mask and some additions to the report, which would be good to make more widely accessible.

### Next Steps

- Since we usually decide on new releases at dev calls, I checked our [contributors' rules](https://tedana.readthedocs.io/en/stable/contributing.html#when-to-release-a-new-version) on what we need to do before releasing a new version. It just says someone needs to open an issue.
- There are draft release notes that our [maintainers should be able to view here](https://github.com/ME-ICA/tedana/releases/edit/untagged-f401d8eb177ae8533c7d). If anyone else wants to see the draft, just ask.
- If we get at least two 👍 and no 👎 or concerns by Wed May 9th, I think it would be for @tsalo to push the release.
- If you are fine with this specific version release but have concerns with this approval method, please also speak up.

**Comment by eurunuela** [comment]
I think #1068 is worth a new release if it is affecting so many people.

**Comment by handwerkerd** [comment]
@tsalo There were no concerns, so could you push the release whenever you next have a chance? I already updated the draft release notes to include #1094
