### ISSUE TITLE
wrong T2* maps 

### ISSUE THREAD

**Issue by qiuge726** [ME-ICA/tedana#1107]
Dear tedana Expert,
![c114a06858451f77dec23bc2b502100c](https://github.com/ME-ICA/tedana/assets/31758821/f55e9dee-9771-47f7-a75e-4e27022bf3e1)

I am writing to seek your assistance regarding an issue I encountered while using tedana to generate T2* maps. After merging my data with tedana, the resulting T2* map appears to be problematic. Specifically, the values on the horizontal axis of the histogram seem incorrect. Additionally, when I open the T2star.nii file, the image appears abnormal.

Interestingly, when I do not use tedana for merging, the output T2* map is correct. Given this discrepancy, I am uncertain about the root cause of the issue and would greatly appreciate your guidance on how to resolve it.

Thank you very much for your time and assistance.

Best regards,
Ge Qiu

**Comment by tsalo** [comment]
Solved on Neurostars- this was the result of providing echo times in seconds, rather than milliseconds.
