### ISSUE TITLE
Document T2* map rationale

### ISSUE THREAD

**Issue by emdupre** [ME-ICA/tedana#111]
In a [previous issue comment](https://github.com/ME-ICA/tedana/issues/102#issuecomment-409406014), @rmarkello laid out the rationale for how signal across echoes is assigned to voxels in generating the T2* map. It would be great to add these text and illustrations (maybe with code !) to [the documentation](http://tedana.readthedocs.io).

**Comment by tsalo** [comment]
@rmarkello I've been working on a lot of documentation in #133. Would you mind taking a look at the proposed walkthrough of the pipeline? What else do you think should go in there, especially related to the T2* map rationale?

**Comment by tsalo** [comment]
I've added a note in #133 that briefly mentions how the different T2* maps are used in different places throughout the workflow, but it's just a jumping off point.

**Comment by jbteves** [comment]
@tsalo have there been any other updates on T2* rationale since your PR? Just checking since it's been 6 months and the issue's still open.

**Comment by tsalo** [comment]
There have been some minor updates. I think that there is probably enough information in the documentation about T2* estimation for most users, so we can close this issue.
