### ISSUE TITLE
July 2024 Developers' call (shifted to July 24th)

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#1110]
Due to conflicts with our standing meeting time, our next developers' call will be on Wednesday, July 24 at 7:00PM CEST / 12:00PM CDT / 1:00 PM EDT / 5:00PM UTC / 10:00 AM PDT / 3:00AM (Friday) AEST[ Check your time here](https://www.timeanddate.com/worldclock/fixedtime.html?msg=tedana+dev+call+July+2024&iso=20240724T13&p1=263&ah=1). 

~~I have a conflict that means I can attend, but it might be harder for me to lead/talk as much as usual. I also haven't heard from anyone else who is definitely planning to attend (scheduling in Summer is fun). Please 👍 if you can and 👎 if you cannot attend a meeting at the above time. I'm trying to figure out if it makes sense to reschedule.~~ @tsalo @eurunuela @dowdlelt @marco7877 @n-reddy @goodalse2019 @BahmanTahayori 

(I'm also still hoping for people to review/run #1064 )

https://nih.zoomgov.com/j/1611760345?pwd=8OdmBUaJr8q2GmVtaE4oQLPObqFXz3.1 
Meeting ID: 161 176 0345
Passcode: 507987

[Mostly drafted agenda](https://docs.google.com/document/d/1o4dsvFB1r6SeqdUOWEQyIODSWKYb15-B5135KLLhGgg/edit?usp=sharing)

**Comment by tsalo** [comment]
I thought it was at 12 PM EDT, not 10 PM?

--


From: Dan Handwerker ***@***.***>
Date: Wednesday, July 17, 2024 at 10:36 AM
To: ME-ICA/tedana ***@***.***>
Cc: Salo, Taylor ***@***.***>, Mention ***@***.***>
Subject: [External] [ME-ICA/tedana] July 2024 Developers' call (time shift?) (Issue #1110)

Our July developers' call is currently scheduled for Thursday, July 18 at CEST / 9:00AM CDT / 10:00 PM EDT / 2:00PM UTC / 7:00 AM PDT / 12:00AM (Friday) AEST Check your time here<https://www.timeanddate.com/worldclock/fixedtime.html?msg=tedana+dev+call+July+2024&iso=20240718T10&p1=263&ah=1>. I have a conflict that means I can attend, but it might be harder for me to lead/talk as much as usual. I also haven't heard from anyone else who is definitely planning to attend (scheduling in Summer is fun). Please 👍 if you can and 👎 if you cannot attend a meeting at the above time. I'm trying to figure out if it makes sense to reschedule. @tsalo<https://github.com/tsalo> @eurunuela<https://github.com/eurunuela> @dowdlelt<https://github.com/dowdlelt> @marco7877<https://github.com/marco7877> @n-reddy<https://github.com/n-reddy> @goodalse2019<https://github.com/goodalse2019> @BahmanTahayori<https://github.com/BahmanTahayori>

(I'm also still hoping for people to review/run #1064<https://github.com/ME-ICA/tedana/pull/1064> )

https://nih.zoomgov.com/j/1611760345?pwd=8OdmBUaJr8q2GmVtaE4oQLPObqFXz3.1
Meeting ID: 161 176 0345
Passcode: 507987

Mostly drafted agenda<https://docs.google.com/document/d/1o4dsvFB1r6SeqdUOWEQyIODSWKYb15-B5135KLLhGgg/edit?usp=sharing>

**Comment by eurunuela** [comment]
The calendar says 10 AM and I don't think it has been changed recently.

**Comment by handwerkerd** [comment]
Our rescheduled June call was at noon and I forgot to change from PM to AM in the text (just updated).

**Comment by handwerkerd** [comment]
Only one person has definitively said they can attend and it's a challenging time for me so I'm going to postpone. Can people fill out this https://www.when2meet.com/?25634138-uSrXH so that we can efficiently select a time for next week?

**Comment by goodalse2019** [comment]
Sorry just seeing this! Rescheduling is best for me as well. I am out of town this week.

**Comment by handwerkerd** [comment]
Of the people who responded, the most we have at a given time is 5 people so, barring some other issue, I'm scheduling for Wednesday, 7/24 at 1:00PM EST [Check your time here](https://www.timeanddate.com/worldclock/fixedtime.html?msg=tedana+dev+call+July+2024&iso=20240724T13&p1=263&ah=1)
