### ISSUE TITLE
Add documentation on interacting with other pipelines

### ISSUE THREAD

**Issue by emdupre** [ME-ICA/tedana#112]
We should have documentation on how to interact with other pipelines like AFNI and fMRIPrep !

**Comment by tsalo** [comment]
Based on poldracklab/fmriprep#1010, it seems like fMRIPrep will ultimately incorporate the full tedana pipeline. However, at the moment, I think the most appropriate approach is to take the fully preprocessed time series (`func/*bold_space-<space>_preproc.nii.gz`), and optionally also the brain mask (`func/*bold_space-<space>_brainmask.nii.gz`), from fMRIPrep to use in tedana.

One fMRIPrep setting to use is `--t2s-coreg`, and one to not use is probably `--use-aroma`. It's also probably not a good idea to output surfaces if we end up dropping surface support in tedana.

@emdupre Is that the kind of information you were thinking of?

**Comment by KevinAquino** [comment]
This is good info (I asked this question on here recently! :) )

As a suggestion it could be great to show some results within the documentation with open source data for example using: https://openneuro.org/datasets/ds000258/versions/00002

**Comment by tsalo** [comment]
I believe that that's something we're (slowly) working toward in the [tedana-comparison](https://github.com/ME-ICA/tedana-comparison) repository. The main goal there is to compare different versions of tedana across a number of public datasets, but it will include visual reports that we'll be able to feed into the documentation for tedana proper.

**Comment by KevinAquino** [comment]
awesome!

**Comment by emdupre** [comment]
Since both fmriprep and afni_proc.py will (soon -- see https://github.com/poldracklab/fmriprep/pull/1296) call tedana directly, it might also make sense to have documentation on what a pipeline including tedana minimally requires, in case users / developers want to build their own.
