### ISSUE TITLE
Revisit make_adaptive_mask

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#113]
Per discussion in #102, we want to take a closer look at how `make_adaptive_mask` determines which voxels have sufficient signal at each TE. The threshold applied below appears to be arbitrary:

https://github.com/ME-ICA/tedana/blob/0c5f93dc06e5fbbbe49811fa5eb717f7ea87ec22/tedana/utils/utils.py#L195-L210

As mentioned in #102, @rmarkello also thinks that the thresholds are hard-coded based on a three-echo dataset, so we'll want to look into that as well.

We have access to a five-echo dataset from @handwerkerd, so we can use that to investigate the method by which the signal quality threshold is determined and see if there's a better method out there. We can also use the quality of the log-linear fit to the decay model, and perhaps calculate TSNR for each echo's time series.

Does anyone have any thoughts on how we should do this?

BTW I've started looking into using TSNR to make an adaptive mask [here](https://github.com/tsalo/tedana/blob/7cd2abff339fd25a4d69ace95d295f52035053be/tsnr_mask.ipynb).

**Comment by tsalo** [comment]
Given a [recent problem case](https://neurostars.org/t/questions-about-the-fmri-denoising-algorithm-tedana-convergence-warnings-sensitivity-to-rounding-of-echo-times-and-differences-between-released-and-unreleased-versions/3458) that appears to have at least partially caused by poor automatic masking, I think we should make sure to circle back to this issue. In the linked case, `make_adaptive_mask` identified almost the whole bounding box, while using `nilearn.masking.compute_epi_mask` (run on the first echo) to generate an explicit mask returned reasonable results.

**Comment by tsalo** [comment]
Does anyone have any concerns about updating the workflow to use `nilearn.masking.compute_epi_mask` to create an initial mask (when no explicit mask is provided) prior to running `make_adaptive_mask`?

**Comment by dowdlelt** [comment]
It seems that having a standardized automated way to get things started is very useful. As long as the masking isn't removing too much, such that the denoised output data isn't useful, it seems fine to have something that prevents the 'whole bounding-box' problem.

**Comment by tsalo** [comment]
Sounds good to me. I've opened a new PR, #226, with the change. It doesn't solve all of the issues with `make_adaptive_mask`, but it's a start.

**Comment by tsalo** [comment]
Here's an idea for how we could improve `make_adaptive_mask`. It doesn't solve issues with the current method, but supplements it to flag _very bad_ echoes. You can see the code [here](https://github.com/tsalo/tedana/blob/24830c97c1d5584a11a2c515dd13315c6ba9188b/tedana/utils.py#L63). Basically, what I'm proposing is that we look at the mean value for each voxel at each echo, over time. Then we move through the echoes, and flag any voxel when the mean signal for that voxel _increases_ from one echo to the next. The logic there is that, regardless of changes in T2* or S0, we should see signal decreases from one echo to the next, so any increases must be purely artifactual. Below, you can see an example of such a situation.

![bad_echo](https://user-images.githubusercontent.com/8228902/53891205-dbe1ef80-3ff7-11e9-99a7-f4256f570d91.png)

There are probably a lot of ways in which we can improve this first pass (e.g., not using the mean, setting tolerances for the differences, etc.), but what does everyone think of the general logic?

**Comment by dowdlelt** [comment]
This is interesting to me - is there any particular spatial distribution of these bad echo voxels? That plot suggest that the 'bad echo' is very stable - always an increase across the entire timeseries, if I'm reading it correctly. The logic seems sound - but I am very curious as to why and where these baddies exist and if there is any useful information in that.

**Comment by tsalo** [comment]
At least in the five-echo test dataset, they seem to mostly be in the ventricles.

**Comment by dowdlelt** [comment]
Thanks! I was expecting there, or cardiac regions - but still not clear to me why it would be so consistent. In any case, that's really neat. Wonder if that info could be useful in some way, perhaps overlay with those areas as another metric for ICA acceptance/rejection, or just for generating a noise regressor.

**Comment by tsalo** [comment]
I was thinking of using the T2*/S0 log-linear model fit in calculating existing metrics, by deweighting the contributions of voxels with poor fit (see #230). Once I realized we could also use the more obvious artifact detailed here in `make_adaptive_mask`, I figured that the log-linear model fit could get at the same thing. There are some things we'll have to figure out in order to do that, but I think it's reasonable.

**Comment by tsalo** [comment]
Alternatively, what if we used only good echoes to calculate the pseudo F-statistics for each voxel?

**Comment by jbteves** [comment]
@dowdlelt I think in an in-person conversation you were saying something about the log-linear fit; would any of your findings contribute to this issue?

**Comment by tsalo** [comment]
I proposed some improvements to the adaptive mask generation in #231, but I don't know that anyone was interested in them. Those improvements just looked at the overall scale for the different echoes within a voxel to see if the mean value _increased_ from one echo to the next at any point (which shouldn't happen).

I don't think anyone has looked at fit quality as a metric of "good" signal yet.

I think that adaptive mask generation improvement has taken a back seat to metric calculation and component selection (for good reason). Perhaps it would be best to label this as low-priority (i.e., an enhancement that we might get to at some point) or to open two new issues: one for the improvement I proposed and one requesting an investigation of fit quality on echo signal.

**Comment by jbteves** [comment]
After waffling back and forth, I think I'd prefer to close this and open two issues as you suggested. Would you mind writing the issues, @tsalo ? We will then mark them both as low-priority and close this one if you agree with going that way.

**Comment by tsalo** [comment]
I've opened #312, although I can't figure out how to investigate fit quality's effect on echo signal so I haven't opened the second issue.

**Comment by emdupre** [comment]
I think this is ready to close -- please re-open @tsalo if you disagree !
