### ISSUE TITLE
Moving the RobustICA defaults to a different file

### ISSUE THREAD

**Issue by eurunuela** [ME-ICA/tedana#1132]
### Summary

The default values of variables needed by RobustICA are currently in `tedana/config.py`. These are not easily editable by users. We should think of a better approach that would allow users to edit these values when needed.

**Comment by BahmanTahayori** [comment]
Thanks @eurunuela. I am not sure if I understand this issue. In its current form, the user can change most of the default values from the command line using the available options. The ones that cannot be changed are the min, max and the warning threshold for the number of robust runs and the warning value for the Index Quality.  These values are setting the boundaries and is not critical for users to be able to change them.

**Comment by handwerkerd** [comment]
I mostly agree with @BahmanTahayori . If you see something a user might want to edit, we can make it a command line option. As an intermediate step, if you think a power user might want to alter any of those lower-level options, we can add them as function parameters and to the API, but not the command line interface. Thoughts?

**Comment by eurunuela** [comment]
I opened the issue after the discussion we had at the meeting. I understood we wanted to move them elsewhere. Feel free to close this if it's not the case.

**Comment by handwerkerd** [comment]
I don't remember or see this in our notes, but that doesn't mean we didn't discuss it. I'm going to close this for now and we can revisit later.
