### ISSUE TITLE
November 2024 Developers' Call

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#1149]
Our dev call is this Thursday, November 21, at 4:00 PM CET / 9:00AM CST / 10:00 AM EST / 3:00PM UTC / 7:00 AM PST / 2:00AM (Friday) AEDT[ Check your time here](https://www.timeanddate.com/worldclock/fixedtime.html?msg=tedana+dev+call+November+2024&iso=20241121T10&p1=263&ah=1).

https://nih.zoomgov.com/j/1618909603?pwd=RBDG90RbbnWpgfCztGK25hPtBNWhQ8.1
Meeting ID: 161 890 9603
Passcode: 193076

[Agenda](https://docs.google.com/document/d/1qAQaoEtPnbeONx19XKPSrCC3rkFbFekwzbicdzvZ-I8/edit?usp=sharing) Additions to the agenda are welcome!

**Comment by tsalo** [comment]
I invited a couple of folks from the nipreps group who are working on getting MRIQC to work nicely with multi-echo data. Not sure if they'll be able to make it but I'm hopeful.
