### ISSUE TITLE
Convert all docstrings to numpy style

### ISSUE THREAD

**Issue by emdupre** [ME-ICA/tedana#13]
_From @emdupre on November 15, 2017 16:41_

For some existing functions, docstrings are not in [numpy format](http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html). Convert these, and also confirm that newly created functions (as in #4) also provide numpy format docstrings.

_Copied from original issue: emdupre/tedana#9_

**Comment by emdupre** [comment]
I think @tsalo and @rmarkello closed this with #24 and #22 ! LMK if y'all agree that this is ok to close 😄

**Comment by rmarkello** [comment]
Agreed, I think this is close-worthy at the current juncture!

**Comment by emdupre** [comment]
Ok, closing ! @tsalo, please LMK if you think this should be reopened ! 😄
