### ISSUE TITLE
Rename existing modules

### ISSUE THREAD

**Issue by emdupre** [ME-ICA/tedana#135]
In discussing #131, we seemed to reach a consensus on renaming and reorganizing a few of the existing modules for clarity. Specifically:

 - renaming `model.monoexponential` to `decay`
- renaming `model.combine` to `combine`
- reorganizing `io` and `utils` into separate modules such that:
      - `io` holds functions for handling reading and writing data, including consolidating components into relevant time series, and
      - `utils` holds miscellaneous utility functions supporting the general package (e.g., `new_nii_like()`, `filewrite()`, `load_data()`)

A clipped version of the tree would thus look like:
```
tedana/
...
├── combine.py
├── decay.py
├── io.py
└── utils.py
```

If this does not match your understanding, @ everyone, please let us know here !

**Comment by tsalo** [comment]
I think the proposed module names are good, although `filewrite` and `load_data` probably belong in `io`, right?

**Comment by frodeaa** [comment]
they are moved from `utils` into `io` by https://github.com/ME-ICA/tedana/pull/136

**Comment by tsalo** [comment]
This was handled in #136, so I think we can close this now.
