### ISSUE TITLE
update derivatives documentation

### ISSUE THREAD

**Issue by alioco** [ME-ICA/tedana#145]
The medn, mefc, mefl, and ctab [derivatives](https://tedana.readthedocs.io/en/latest/approach.html#derivatives) are not currently part of tedana's outputs. Rather than using medn for task analysis, it is recommended to use dn_ts_OC, the optionally combined time series, removing components identified as noise.

**Comment by tsalo** [comment]
Thank you for bringing this up. It should be resolved in #133, which will add detailed descriptions of the workflow's current derivatives.

**Comment by tsalo** [comment]
@alioco We've merged #133, so would you mind taking a look at the updated [Outputs of tedana page](https://tedana.readthedocs.io/en/latest/outputs.html) to see if the documentation looks good to you?

**Comment by alioco** [comment]
@tsalo this is great, thank you! We have seem to have a few more files generated using the default settings that aren't currently listed (not sure how important these are): accepted.txt, csdata.txt, csstepdata.json, midkrejected.txt, pcastate.pkl, rejected.txt,
