### ISSUE TITLE
Update output names to match BIDS derivatives RC2 conventions

### ISSUE THREAD

**Issue by emdupre** [ME-ICA/tedana#146]
Now that [BIDS Derivatives has released the RC2 status](https://docs.google.com/document/d/1Wwc4A6Mow4ZPPszDIWfCUCRNstn7d_zzaWPcfcHmgI4/edit), it's quite close to stable.

We should, therefore, update our naming conventions to match these so that we can more easily interoperate with the broader BIDS community.

**Comment by tsalo** [comment]
This is brought up in the Roadmap PR, but since this issue already exists I figured I'd ask about it there. 

I haven't read the full specification, but my understanding is that derivatives should follow the format `<pipeline_name>/sub-<participant_label>/func/<BIDSRawBase>[_keyword-<value>]_<suffix>.<ext>`. Unless we enforce BIDS-compatibility from the input data, how will we derive `BIDSRawBase`?

Also, since tedana operates _on_ derivatives, how should the filename from the input derived data be incorporated into the tedana output? For example, if we were using fMRIPrep output (I know that fMRIPrep will integrate tedana, but it's a good example with well-known outputs):

Inputs:
- sub-01_task-rest_run-01_echo-1_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz
- sub-01_task-rest_run-01_echo-2_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz
- sub-01_task-rest_run-01_echo-3_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz

Output possibilities:
- sub-01_task-rest_run-01_space-MNI152NLin2009cAsym_desc-preproc_desc-dntsoc_bold.nii.gz
    - Duplicate "desc" keyword.
- sub-01_task-rest_run-01_space-MNI152NLin2009cAsym_desc-dntsoc_bold.nii.gz
    - Removes original "desc" keyword. We won't know what the original derivative was from the filename.
- sub-01_task-rest_run-01_space-MNI152NLin2009cAsym_desc-preproc_desc2-dntsoc_bold.nii.gz
    - Uses new keyword in addition to input derivative's keyword. Doesn't have to be "desc2".

**Comment by tsalo** [comment]
Here is a list of tedana's outputs (copied from #17). I think it's comprehensive, but if not just let me know and I can add missing derivatives. This is just a first pass, and I have no clue how many of the derivatives should be named.

| Current name | Content | BIDS-compatible suffix |
| ------- | --------- | --- |
| t2sv.nii | Limited estimated T2* 3D map. | *_desc-t2s_bold.nii.gz |
| s0v.nii | Limited S0 3D map. | *_desc-s0_bold.nii.gz |
| ts_OC.nii | Optimally combined time series. | *_desc-optcom_bold.nii.gz |
| dn_ts_OC.nii | Denoised optimally combined time series. | *_desc-optcomDenoised_bold.nii.gz |
| lowk_ts_OC.nii | Combined time series from rejected components. | *_desc-optcomRejected_bold.nii.gz |
| midk_ts_OC.nii | Combined time series from "mid-kappa" rejected components. | *_desc-optcomRejectedMidK_bold.nii.gz |
| hik_ts_OC.nii | High-kappa time series. Combined time series from high-kappa accepted components. | *_desc-optcomAccepted_bold.nii.gz |
| t2ss.nii | Voxel-wise T2* estimates using ascending numbers of echoes, starting with 2. |  |
| s0vs.nii | Voxel-wise S0 estimates using ascending numbers of echoes, starting with 2. |
| t2svG.nii | Full T2* map/time series. |
| s0vG.nii | Full S0 map/time series. |
| comp_table_pca.txt | TEDPCA component table. |
| mepca_mix.1D | Mixing matrix (component time series) from PCA decomposition. |
| __meica_mix.1D | Mixing matrix (component time series) from ICA decomposition. |
| meica_mix.1D | Mixing matrix (component time series) from ICA decomposition. The only differences between this mixing matrix and the one above are that components may be sorted differently and signs of time series may be flipped. |
| betas_OC.nii | Full ICA coefficient feature set. |
| betas_hik_OC.nii | High-kappa ICA coefficient feature set |
| feats_OC2.nii | Z-normalized spatial component maps |
| comp_table_ica.txt | TEDICA component table. |
| veins_l0.nii | ??? |
| veins_l1.nii | ??? |
| T1gs.nii | Spatial global signal |
| glsig.1D | Time series of global signal from optimally combined data. |
| tsoc_orig.nii | Optimally combined time series with global signal retained. |
| tsoc_nogs.nii | Optimally combined time series with global signal removed. Same as ts_OC.nii when GSR is used. |
| sphis_hik.nii | T1-like effect |
| hik_ts_OC_T1c.nii | T1 corrected high-kappa time series by regression |
| dn_ts_OC_T1c.nii | T1 corrected denoised time series |
| betas_hik_OC_T1c.nii | T1-GS corrected high-kappa components |
| meica_mix_T1c.1D | T1-GS corrected mixing matrix |
| hik_ts_e[echo].nii | High-Kappa time series for echo number ``echo`` | *_echo-[echo]_desc-optcomAccepted_bold.nii.gz |
| midk_ts_e[echo].nii | Mid-Kappa time series for echo number ``echo`` | *_echo-[echo]_desc-optcomRejectedMidK_bold.nii.gz |
| lowk_ts_e[echo].nii | Low-Kappa time series for echo number ``echo`` | *_echo-[echo]_desc-optcomRejected_bold.nii.gz |
| dn_ts_e[echo].nii | Denoised time series for echo number ``echo`` | *_echo-[echo]_desc-optcomDenoised_bold.nii.gz |
| adaptive_mask.nii | Adaptive mask. Each voxel has value corresponding to number of echoes with good signal. | Needed to show adaptive mask. | *_desc-adaptiveMask_mask.nii.gz |
| mask.nii | Binary mask of voxels with good data. | Applied to all other images needed for walkthrough. | *_desc-meMask_mask.nii.gz |
| tsoc_whitened.nii | Optimally combined data after dimensionality reduction with PCA. | Needed to show time series plot of whitened vs. original OC data (i.e., to show impact of TEDPCA). | *_desc-optcomWhitened_bold.nii.gz |
| ica_model_betas_catd.nii | Echo-specific weight maps for each of the ICA components. | Needed to show how the component weights align with predicted weights from S0 and R2 models in line plots. |
| ica_model_F_R2.nii | R2 F-statistic maps for each of the ICA components. | Needed to calculate Kappa for each component. **Could be replaced with values from component table, I think.** |
| ica_model_F_S0.nii | S0 F-statistic maps for each of the ICA components. | Needed to calculate Rho for each component. **Could be replaced with values from component table, I think.** |
| ica_model_metric_weights.nii | Weight maps used to average metrics (R2 F, S0 F, predicted R2 model values, and predicted S0 model values) in the same manner as `fitmodels_direct`. | Needed to show how the component weights align with predicted weights from S0 and R2 models in line plots. |
| ica_model_R2_pred.nii | Echo-specific maps of predicted values for R2 model for each component.  | Needed to show how the component weights align with predicted weights from R2 models in line plots. |
| ica_model_S0_pred.nii | Echo-specific maps of predicted values for S0 model for each component.  | Needed to show how the component weights align with predicted weights from S0 models in line plots. |

**Comment by emdupre** [comment]
We should add comments to [the BEP012 draft](https://docs.google.com/document/d/16CvBwVMAs0IMhdoKmlmcm3W8254dQmNARo-7HhE-lJU/edit#) to make sure all of our derivatives are covered ! I'll go through these later this week, myself, with that in mind.

**Comment by jbteves** [comment]
@tsalo @emdupre How can I assist with this? I see that there's already an open PR. If I can help get this issue closed I'd like to do so, especially since it's mostly renaming (which is something that I think even my limited Python abilities can handle).

**Comment by tsalo** [comment]
As in #540, I think it makes sense to just not include naming information from the original files in the output files. So instead of `sub-X_ses-Y_task-Z_T2starmap.nii.gz`, we just have `T2starmap.nii.gz`. Since the outputs are in their own folder, any BIDS-compatible workflows that use tedana can rename those files according to the convention. The file names we use will still be a good start for those workflows though.

**Comment by Shotgunosine** [comment]
It might be nice to have a note in the documentation that the bids convention won't include the base filename. I've just stumbled on the fact that if you're not careful when running over multiple sessions or runs, outputs will get overwritten.

**Comment by tsalo** [comment]
I can incorporate that into #822. Thanks for bringing it up!

**Comment by tsalo** [comment]
@Shotgunosine WDYT of this?

![image](https://user-images.githubusercontent.com/8228902/144657971-c9d6a114-2314-4ae1-a6f7-0d9037e19051.png)

**Comment by Shotgunosine** [comment]
Looks great, thanks!
