### ISSUE TITLE
Improve enforcement description in the code of conduct

### ISSUE THREAD

**Issue by KirstieJane** [ME-ICA/tedana#148]
At the moment we only give [instructions on reporting a violation](https://github.com/ME-ICA/tedana/blob/master/Code_of_Conduct.md#enforcement), we don't give any information about what steps could be taken.

I'd like to propose - as a jumping off point:

> Elizabeth DuPre as BDFL can take any action she deems appropriate for the safety of the `tedana` community, including but not limited to:
> 
> * facilitating a conversation between the two parties involved in the violation of the code of conduct
> * requesting a contributor apologise for their behaviour
> * asking a contributor or multiple contributors to enter a cooling off period that puts a time limited pause on a particular discussion topic
> * asking a contributor to no longer participate in the development of `tedana`

Its just as starting point! Happy to iterate!

**Comment by emdupre** [comment]
I think we can close this with #151 ! We can (and should !) revisit this, though. Thanks so much for pointing this out, @KirstieJane !!
