### ISSUE TITLE
Add binder examples

### ISSUE THREAD

**Issue by KirstieJane** [ME-ICA/tedana#149]
In #133 @tsalo added some really lovely jupyter notebooks to explain some aspects of the `tedana`:tada: processing.

It would be really cool if these were accessible through [mybinder](https://mybinder.org).

I don't have time to work on this so any help would be greatly appreciated! ✨ 😻 👾 

I think this requires:

- [x] an update to the [`info.py`](https://github.com/ME-ICA/tedana/blob/master/tedana/info.py) file to include (for example) `matplotlib`,  `seaborn` and `nilearn`.
  * Side note, thank you to Minn in the binder team for helping understand where binder goes looking for its requirements 😸 
  * @emdupre would prefer this to be in the "DOCS REQUIRES" section so these packages aren't added when a regular user installs `tedana`.
  * An alternate idea is to make a `binder/requirements.txt` file that contains everything needed for the notebook. Note that this option won't run `setup.py` so *everything* needs to be added into that file, not just additional packages on top of those defined for `tedana`. 
- [x] moving the jupyter notebooks to somewhere more accessible, eg an `examples` folder
- [ ] uploading some data to OpenNeuro so it's easy to access
- [ ] creating the binder link
- [ ] updating the documentation to make it clear that this information exists!!

**Comment by souravsingh** [comment]
@tsalo @KirstieJane I would like to take a stab at the issue. Where do I start?

**Comment by emdupre** [comment]
Hi @souravsingh ! If you're not yet familiar with Binder, they have some really great resources to get started !  [These tutorials](https://mybinder.readthedocs.io/en/latest/) might be the best first place to look.

As @tsalo said, the notebooks and data are already hosted online, so the issue would be pulling them together in the right environment. Which Binder is perfect for ! Let us know if you have any specific questions about next steps :)

**Comment by jbteves** [comment]
I see that the original PRs were closed for this. @KirstieJane do you mind if I edit your comment so that your task list is at the bottom and we can track progress?

**Comment by jbteves** [comment]
Note: we already have data hosted on OSF for our CI. Relevant links:
- [five-echo task](https://osf.io/e3hsn/download)
- [three-echo rest](https://osf.io/e3hsn/download)

**Comment by KirstieJane** [comment]
Totally fine to edit!! Go for it 🚀🌟

**Comment by jbteves** [comment]
Thanks! Done, now we can track progress directly on the issue title/tracker

**Comment by jbteves** [comment]
@KirstieJane @emdupre @tsalo I have an example of it working for optimal combination [here](https://mybinder.org/v2/gh/jbteves/tedana/JT_add_mybinder)

**Comment by emdupre** [comment]
I'd like to suggest we use [Jupytext](https://github.com/mwouts/jupytext) for this, so that we're including .py rather than .ipynb files in our repository. It will keep the version history much more manageable !

_And_ if we add Jupytext to the dev-requirements and put the correct YAML front matter in the examples, Binder will open the python scripts as Jupyter Notebooks ! :sparkles:
