### ISSUE TITLE
Break `selcomps` into functions

### ISSUE THREAD

**Issue by emdupre** [ME-ICA/tedana#16]
_From @emdupre on November 15, 2017 16:31_

Currently, the function for selecting components contains (at least) 7 steps. It would be better to demarcate these into individual functions for interpretability / testing purposes. A good starting point for structuring these would be the code comments in `selcomps` itself.

_Copied from original issue: emdupre/tedana#4_

**Comment by handwerkerd** [comment]
I'll add that it looks like the current selcomps function is has two very distinct elements: (1) Calculations of cross-component metrics that are used for selection and (2) A decision tree that is where the actual component selection step happens. If everything can't be easily separated, this is the part that really  should be. There should be a function or functions that calculate the various measures used by the selection process and then as compact a section of code as possible that defines the actual criteria for categorizing components.

**Comment by handwerkerd** [comment]
While I'm making comments here, a headache that came up several times with older versions of this code is that, if a component is mid-Kappa rejected  or actually rejected, it's difficult to figure out which criteria was used for its categorization. Particularly if there are still multiple selection criteria, but they are better modularized, it could be very useful to record provenance information listing which criteria resulted in acceptance/rejection for each component.

**Comment by emdupre** [comment]
This was moved to the [`select`](https://github.com/ME-ICA/tedana/tree/master/tedana/select) module with #35 !

**Comment by tsalo** [comment]
I know that we want to further organize `selcomps`, and I noticed that the decision tree can broadly be divided into additional metric calculation and actual component classification. Some of the metrics depend on elbows or other values computed from only subsets of the components, which means that we can't move those out of `selcomps`, but a large number are calculated independently for each component.

I don't think that these metrics are substantial enough to merit their own functions (i.e., most would require more arguments than there would be lines of code), but we could move all of them into a _single_ function, or even into `fitmodels_direct`. Does anyone have a preference for where we should move these metrics and what we should call the resulting function? I think that we should have a new submodule in `model` (`tedana.model.metrics`) and we can name the function after the two decision trees that use these particular metrics (e.g., `kundu_metrics`). WDYT?
