### ISSUE TITLE
Change defaults for global signal regression and minimum image regression

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#161]
We have discussed changing the defaults for global signal regression and T1c-GSR [here](https://github.com/ME-ICA/tedana/pull/125#issuecomment-434400354), but I think it would be good to address this in its own new issue.

I propose that we do the following:
1. Change default for GSR from running it by default to not running it. We can do this by changing the argument `--no_gscontrol` to `--gscontrol`.
2. Add argument to select a global noise removal method. This is implemented in #120 as `--ws_denoise`, but that PR is not going to be merged any time soon, and I'd like to change these defaults sooner than later. Perhaps `--global_denoise` or `--postproc` would also be good names? Ultimately, we plan to support multiple options for this, including, at minimum, T1c-GSR and GODEC, so it would be better to plan for that now. The default for this argument would be `None`, and to turn T1c-GSR on we could use `t1c`, `mir`, or something else entirely.

Does anyone have any issues with turning off GSR and T1c-GSR (i.e., minimum image regression) by default?

**Comment by handwerkerd** [comment]
No issues with turning this off.

**Comment by emdupre** [comment]
To be clear, I think we are _not_ running gs control by default -- see https://github.com/ME-ICA/tedana/blob/63d643aa79e8b7c4a9865ec57c3263e93bfeb3cd/tedana/workflows/tedana.py#L122

Am I misunderstanding this ?

**Comment by tsalo** [comment]
Perhaps one argument against `--global_denoise` is that we don't want to have a submodule called `global` (for Python reasons) or `denoise` (tedana reasons). An argument against `--postproc` is that that doesn't include the standard GSR that is run on the input data rather than the denoised data, although maybe we don't want to roll GSR in with GODEC and T1c-GSR. Does anyone have any ideas for a better name?

**Comment by emdupre** [comment]
Ok, for some reason I remember us changing the default because we had turned it off, but I'm having trouble tracking down that history right now. I'm very pro removing it.

**Comment by tsalo** [comment]
Closed by #163.
