### ISSUE TITLE
Error in tedpca with minimally preprocessed data from ds001491

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#168]
I'm trying to run tedana on some minimally preprocessed (slice timing and motion correction only) data from [ds001491](https://openneuro.org/datasets/ds001491) (sub-01, images task). The preprocessing was somewhat hastily cobbled together, but I don't see any obvious problems in the [pipeline](https://github.com/tsalo/tedana-comparison/blob/aba5885df8208b689433ef398058db30ff88ccce/code/afni_preproc_step1.py) that could cause the following error.

Has anyone else come across this before?

```
tedana -d func/sub-01_task-images_echo-1_desc-realign_bold.nii.gz \
    func/sub-01_task-images_echo-2_desc-realign_bold.nii.gz \
    func/sub-01_task-images_echo-3_desc-realign_bold.nii.gz \
    -e 8.02 22.03 36.03 --out ds001491 --debug

INFO:tedana.workflows.tedana:Using output directory: /Users/tsalo/Documents/tsalo/tedana-comparison/sandbox/ds001491
INFO:tedana.workflows.tedana:Loading input data: ['func/sub-01_task-images_echo-1_desc-realign_bold.nii.gz', 'func/sub-01_task-images_echo-2_desc-realign_bold.nii.gz', 'func/sub-01_task-images_echo-3_desc-realign_bold.nii.gz']
DEBUG:tedana.workflows.tedana:Resulting data shape: (184320, 3, 493)
INFO:tedana.workflows.tedana:Computing adaptive mask
DEBUG:tedana.workflows.tedana:Retaining 134925/184320 samples
INFO:tedana.workflows.tedana:Computing T2* map
/Users/tsalo/anaconda/envs/python3/lib/python3.6/site-packages/scipy/stats/stats.py:1706: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return np.add.reduce(sorted[indexer] * weights, axis=axis) / sumval
DEBUG:tedana.workflows.tedana:Setting cap on T2* map at 3406.81902
INFO:tedana.combine:Optimally combining data with voxel-wise T2 estimates
INFO:tedana.decomposition.eigendecomp:Computing PCA of optimally combined multi-echo data
DEBUG:tedana.decomposition._utils:Creating eimask for echo 0
DEBUG:tedana.decomposition._utils:Eimask threshold boundaries: 1023.951 5119757.142

Traceback (most recent call last):
  File "/Users/tsalo/anaconda/envs/python3/bin/tedana", line 11, in <module>
    load_entry_point('tedana', 'console_scripts', 'tedana')()
  File "/Users/tsalo/Documents/tsalo/tedana/tedana/workflows/tedana.py", line 379, in _main
    tedana_workflow(**vars(options))
  File "/Users/tsalo/Documents/tsalo/tedana/tedana/workflows/tedana.py", line 318, in tedana_workflow
    ste=ste, wvpca=wvpca)
  File "/Users/tsalo/Documents/tsalo/tedana/tedana/decomposition/eigendecomp.py", line 200, in tedpca
    o[mask] = eimum
ValueError: NumPy boolean array indexing assignment cannot assign 111986 input values to the 134925 output values where the mask is true
```

**Comment by dowdlelt** [comment]
I encountered this error as well, but with much much closer values. Also fixed with explicit mask.  

I was attempting to test (new) tedana on data that was prepared by AFNI, and has been processed successfully through the 3.2 version of tedana. 
I am trying to test how the latest version of tedana, from github, performs relative to this older release.

This data is concatenated in the z direction, 3 echoes. I attempted a simple run of tedana:
`tedana -d tedprep_Zcat_all.nii.gz -e 15.4 33.66 51.92 --tedpca kundu-stabilize --out-dir kundu_stabilize`

and receive the following error: 
```
INFO:tedana.combine:Optimally combining data with voxel-wise T2 estimates
INFO:tedana.decomposition.eigendecomp:Computing PCA of optimally combined multi-echo data
Traceback (most recent call last):
  File "/home/dowdlelt/anaconda3/bin/tedana", line 11, in <module>
    sys.exit(_main())
  File "/home/dowdlelt/anaconda3/lib/python3.6/site-packages/tedana/workflows/tedana.py", line 394, in _main
    tedana_workflow(**vars(options))
  File "/home/dowdlelt/anaconda3/lib/python3.6/site-packages/tedana/workflows/tedana.py", line 311, in tedana_workflow
    verbose=verbose)
  File "/home/dowdlelt/anaconda3/lib/python3.6/site-packages/tedana/decomposition/eigendecomp.py", line 321, in tedpca
    o[mask] = eimum
ValueError: NumPy boolean array indexing assignment cannot assign 148631 input values to the 148663 output values where the mask is true

I have seen this with other data and for whatever reason the values are always quite close together, which I find curious. 

Has there been any progress here?

**Comment by jbteves** [comment]
This error occurred for 6 runs in one headcoil and 2 in another for me. I'm going to try masking now to see if that fixes it.

**Comment by tsalo** [comment]
@jbteves Your findings highlight something that has confused and concerned me about the `--sourceTEs` option for a while now. Namely, what is the difference in interpretation between findings using one option vs. another, and what should the default be? I'm going to open a separate issue where we can discuss `--sourceTEs` specifically. While the default can be determined based on the findings of the validation analysis, we should at least have a solid understanding of why one might do one vs. the other beforehand.

@dowdlelt My intuition is that this has something to do with the eimasking. Would you be willing to send me the failing data so I can dig into this myself? I am not very confident in the preprocessing pipeline I used for the current version of the reliability analysis, which is where my own failing data came from.

**Comment by jbteves** [comment]
@tsalo I can provide you the data

**Comment by tsalo** [comment]
Can you email it to me with a Drive upload?

**Comment by jbteves** [comment]
Sure. Do you want the raw data and intermediates, or just what got fed to tedana?

**Comment by tsalo** [comment]
I think just the inputs to tedana would be good. If you have the mask @dowdlelt used to fix the problem as well, that would be great.

**Comment by jbteves** [comment]
Oh sorry, I guess I wasn't clear. I don't have @dowdlelt's data, I do have the runs I had fed in for the above. Do you still want them?

**Comment by tsalo** [comment]
Those data should be good. I'll just need the echo times.

**Comment by tsalo** [comment]
It looks to me like the problem is our use of `make_min_mask` _only_ when the optimally combined data are used for `tedpca`. In all other cases, the mask that is fed into the function is the one used at this step. See below:

https://github.com/ME-ICA/tedana/blob/7d23934f172ab3d007a84905470633674656c1ae/tedana/decomposition/eigendecomp.py#L267-L275

When the min_mask contains zeros, we end up with a mismatch between the shape of the masked data and the nonzero values in `mask`.

I believe that the immediate solution is to stop using min_mask for performing PCA on optimally combined data. Long term, we should take a closer look at min_mask to see if that's what we should be using for all inputs and, if so, to determine how to fix this bug.

**Comment by jbteves** [comment]
Echo times are 
Resting: 15.40 33.66 51.92
TMS: 11 32.16 53.32

**Comment by dowdlelt** [comment]
Glad to see some work on this  - sounds like you are good with current data, but I am happy to share some if needed. I testing providing a mask and that worked as well. Let me know if I can help in any way - looks like I missed most of the action though.
