### ISSUE TITLE
Update tests to include --debug

### ISSUE THREAD

**Issue by emdupre** [ME-ICA/tedana#169]
In #167 we added log files that are written out if `--debug` is called; however, we are not yet testing that functionality since the exact log filename will depend on the time the job is executed. It would be great to update our test to call `--debug`, and to check for a logfile matching the general pattern !

**Comment by sushmaunnibhavi** [comment]
hello,I have found the --debug in 2 files,namely t2smap.py and tedana.py. Can u please tell me where I can find the functionality regarding --debug file.

**Comment by emdupre** [comment]
Hi @sushmaunnibhavi,

Thanks for checking on this ! The `--debug` flag writes out a log file (for both the tedana and t2smap workflows) with some additional details -- you can see where the logfile is created here https://github.com/ME-ICA/tedana/blob/e1bc0b6476c20b98db13c38c0455bb1e3f717afd/tedana/workflows/tedana.py#L265

In this issue what we'd like to do is update (at least one of) the tests to actually use this flag. The trick is that right now our tests check to see if files are created based on their filename, see 

https://github.com/ME-ICA/tedana/blob/e1bc0b6476c20b98db13c38c0455bb1e3f717afd/.circleci/config.yml#L147

Because the date and time is included in the logfile title with `--debug`, we would need to either:
1. Remove the date and time from the title. This information should be in the file already, so I'm not sure we need it, realistically.
2. Update the integration tests so that the fail on mismatched content, rather than just mismatched names.

Option 2 is a bigger update, and I'm not sure we're ready to move their just yet. So, personally I'd push for option 1. WDYT ?
