### ISSUE TITLE
Upload tedana OHBM abstract somewhere in the docs

### ISSUE THREAD

**Issue by KirstieJane** [ME-ICA/tedana#173]
I'm not 100% sure where exactly we should put it, but I like the idea of having the abstract up in our documentation somewhere!

Let me know if you have any concerns about adding it, and/or bandwidth to upload it otherwise I'll try to have a bash next week ✨

**Comment by tsalo** [comment]
Were you thinking more of including the info from the abstract in the [About section](https://tedana.readthedocs.io/en/latest/#about) or linking to the abstract page (and last year's) in the [resources page](https://tedana.readthedocs.io/en/latest/multi-echo.html#resources)?

**Comment by emdupre** [comment]
Do you think there's a reason to link in the abstract over the poster ? Or just until the poster becomes available ?

**Comment by jbteves** [comment]
@KirstieJane @emdupre @tsalo any further thoughts on this? OHBM is getting close, so I would think that at this point it makes more sense to link the poster (just my 2 cents).

**Comment by tsalo** [comment]
We can link the poster, but I doubt @emdupre has it done yet. I propose that we wait until that's finalized, and then we can link it.

**Comment by jbteves** [comment]
Sorry, that was ambiguous; I meant to wait until it’s finalized and then upload as you said. If others agree we should also Pause the issue.

**Comment by jbteves** [comment]
@emdupre now that the poster is done I've unpaused the issue; do you mind adding the abstract to the readthedocs? Otherwise you can paste it here and someone else can open an PR.

**Comment by emdupre** [comment]
Great timing ! I had just opened #340 before I saw this :+1:
