### ISSUE TITLE
Eliminate Mask Argument in fitmodels_direct

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#175]
### Summary
Per this [comment](https://github.com/ME-ICA/tedana/pull/119#discussion_r233692095) in #119, we are currently overriding the `mask` argument with nonzero voxels in the `t2s` array. This is because, in the "old" version of selcomps (v3.2), masking and unmasking were applied repeatedly to coerce arrays into the right shape, while in v2.5 we've taken a simpler approach wherein we expect the arrays to be the same shape to begin with.

For example, we have `F_R2_clmaps`, which is `n_data_voxels` (`t2s != 0`) x `n_components`, and `Br_R2_clmaps`, which is `n_voxels` (from `mask`) x `n_components`. However, in either version of the component selection function, `Br_R2_clmaps` is masked to match the shape of `F_R2_clmaps`, so I think it's fine to skip a step and just construct `Br_R2_clmaps` in the same shape as `F_R2_clmaps`.

### Next Steps
- [ ] Eliminate the `mask` argument entirely and switch to explicitly using `t2s != 0` in `fitmodels_direct`.

**Comment by jbteves** [comment]
@tsalo would you mind if I retitle this and convert your comment into a to-do item?

**Comment by tsalo** [comment]
Go for it!

**Comment by jbteves** [comment]
Done; let me know if I've flubbed it.
