### ISSUE TITLE
Output component tables as BIDS Derivatives-compatible jsons

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#180]
After a discussion with Chris M., we think we should use jsons to store the component tables. We'll need functions to load DataFrames from jsons and dump DataFrames to jsons as well, I think. We're pushing this out of #152 because it's a bit too much for the one PR.

**Comment by jbteves** [comment]
This will break some people's workflows, including I think @dowdlelt's if I'm not mistaken. We should probably add facilities for people to produce the old version of the tables if we do this; my guess is that some researchers will not be familiar with JSON format. 
WDYT @emdupre @tsalo ?

**Comment by jbteves** [comment]
Additionally, @tsalo, I'm not that familiar with BIDS derivatives, could you please link to the specification part you're talking about? I'm having a hard time finding it.

**Comment by tsalo** [comment]
#152 adds a function ([load_comptable](https://github.com/ME-ICA/tedana/blob/d3672809f0348a28e39c52ceff2d48c0db5b4f4d/tedana/io.py#L135)) that will read the json file into a DataFrame like the ones we use now.
As far as the BIDS derivatives specification, I don't believe that component tables with metrics (like we use) are discussed, but decompositions do require their own json files (see [here](https://github.com/bids-standard/bids-specification/pull/109/files#diff-03aac99b714e0e2b8cd023783cb55913R363)) that can also contain the metrics and classifications that we want to include.

**Comment by jbteves** [comment]
Great, thank you!
