### ISSUE TITLE
Create an issue template

### ISSUE THREAD

**Issue by KirstieJane** [ME-ICA/tedana#186]
In our meeting today @jbteves mentioned that our issues could be clearer for new folks coming along to the project.

Fortunately github gives us a nice way to do that!

The instructions for how to do it are [here](https://help.github.com/articles/creating-issue-templates-for-your-repository/) and I’d recommend putting the file in a `.github` folder so the root directory doesn’t get too messy.

Anyone welcome to open a PR with suggestions for templates :sparkles:

**Comment by emdupre** [comment]
One thing to think about here -- since we have a few different repositories, do we want each of them to have the same issue / PR templates ? Is there any way to link these across the repositories ?
