### ISSUE TITLE
Developer Tedana Config: import failure

### ISSUE THREAD

**Issue by jbteves** [ME-ICA/tedana#192]
When trying to run tedana without 
```pip install /path/to/tedana```
(which seems an inelegant solution), and instead using
```python tedana.py [opts]```
the following error message triggers
```python ./tedana/workflows/tedana.py
Traceback (most recent call last):
 File "./tedana/workflows/tedana.py", line 15, in <module>
   from tedana import decay, combine, decomposition, io, model, selection, utils
 File "/home/lod23/code/tedana/tedana/workflows/tedana.py", line 15, in <module>
   from tedana import decay, combine, decomposition, io, model, selection, utils
ImportError: cannot import name 'decay' from 'tedana' (/[tedana_path]/tedana/tedana/workflows/tedana.py)
```
I'm not sure if there's something I'm missing in the documentation or if the intended developer run method is to pip install. I think it would be good to be able to simply call python on the cloned version, though, if possible, and include documentation on how to do so correctly if that functionality exists.

**Comment by tsalo** [comment]
To install without pip you need to do "python setup.py [install|develop]", and then `tedana` and `t2smap` will become available as command-line scripts. The workflow itself won't work until the package is installed.

**Comment by jbteves** [comment]
Oh okay. Would it be appropriate to put that in the installation section of the docs, or under contributing guidelines? I took a quick look and I don't think it's stated there, although I will concede that ```setup.py``` does look an obvious starting place...

**Comment by emdupre** [comment]
Yes, exactly as @tsalo said ! Let's add this to the CONTRIBUTING so it's clear :)
