### ISSUE TITLE
Random Seed default does not match help text

### ISSUE THREAD

**Issue by jbteves** [ME-ICA/tedana#193]
Currently, we see from the [help text](https://github.com/ME-ICA/tedana/blob/0b4e0e3a13644a1fc14b26c2f72b8066cebb3e7f/tedana/workflows/tedana.py#L196-L199) that the default seed is -1, however it looks like the default value if none is passed is [actually 42](https://github.com/ME-ICA/tedana/blob/0b4e0e3a13644a1fc14b26c2f72b8066cebb3e7f/tedana/workflows/tedana.py#L126-L132).

**Comment by jbteves** [comment]
Oops, I realize I misunderstood the help text. Sorry about that. Instead, I think I'll suggest that we add some clarifying language about the default value.

**Comment by tsalo** [comment]
It would be great if you could add in `Default=42` to the seed documentation, as well as `Default='.'` for out_dir. I think that covers missing default values in the help.

**Comment by tsalo** [comment]
@jbteves This might actually be a good first issue for a new contributor, if you're okay waiting on it.

**Comment by jbteves** [comment]
I'm surprised I don't count as a new contributor since I've never edited source. I generally feel that documentation should be clarified ASAP, but if the project maintainers feel strongly that we should wait for someone new then I'll just make note of it.

**Comment by tsalo** [comment]
It's totally cool if you want to get it done sooner rather than later.

Related to this, the seed help is out of date since we moved from `mdp` to `sklearn`. I think that `Value passed to repr(mdp.numx_rand.seed())` should instead be `Random seed used for ICA.`

**Comment by emdupre** [comment]
We generally like to keep a few, small issues so someone new has a reasonable place to start -- it's easier to talk through GitHub, etc, on smaller issues than on larger ones. Of course it'd be great to get a fix in, and you can definitely send one, @jbteves ! But just to explain our thought process, sometimes we'll let issues like this (where the information isn't _wrong_, just unclear) sit open a little longer specifically to target new contributors who are looking to get started.

And re defining a when someone is a "contributor": all contributions count, from our perspective ! Even if you're not modifying the source code, we have a lot of other pieces of information which form an essential part of tedana development (such as CONTRIBUTING guides, etc).

Hopefully that clarifies things ! Of course, you're welcome to send a PR here, but I just wanted to explain our philosophy so you aren't surprised if you see that we let some smaller issues stay open for a little longer than you may be used to.

**Comment by jbteves** [comment]
That makes sense. I can wait a little bit but if nobody comes and changes it by, say, the end of February, I'd like to fix it. 
Additionally, I see some other documentation discrepancies. Should I add them here or open additional issues?
