### ISSUE TITLE
DueCredit not imported

### ISSUE THREAD

**Issue by jbteves** [ME-ICA/tedana#196]
When using a miniconda3 environment or pip install, the following import error occurs:
```
Failed to import duecredit due to No module named 'duecredit'
```
Unless we are avoiding acknowledging the devs and their hard work, we should probably fix that :-)

**Comment by jbteves** [comment]
I think it's just confusing for the user to receive the warning in a context where they're not looking for a citation, it makes it seem as if the setup has gone wrong. Would it be possible to not raise a warning at all under normal operations, but then raise an error if they're trying to get the duecredit message and it can't find the library?

**Comment by tsalo** [comment]
I think it's possible and a good idea, though that's something that should probably happen upstream in [duecredit](https://github.com/duecredit/duecredit).

**Comment by jbteves** [comment]
Taking a look, it seems like that may be a complicated approach. This may be inelegant, but can we just catch that warning and then ignore it? I see that [here](https://github.com/ME-ICA/tedana/blob/c821263a1ac639f5bd9731b2b3daf3ac64d835de/tedana/due.py#L52-L61) we catch the import exception, could we add a check for the name on the bottom of the stack, and discard the message entirely if it's not duecredit? 
Additionally, I think it may be ignored in documentation because it's below the citations. Docs state you can get citations "additionally" by running that, but most people won't run it if they think that the relevant ones are listed already and can just be pasted into the paper. Just a thought.

**Comment by emdupre** [comment]
I'm against hiding the warning, personally. I think the new message that @tsalo introduced should alleviate a lot of this confusion (and this conversation is a good reminder that we should think about cutting a release, soon !). 

Regarding the placement in the documentation: I completely hear your point, but I'm not sure where would be better to put it. Do you have a suggestion ?

**Comment by jbteves** [comment]
I'm afraid I don't have a good solution-- it's a classic question, right, how do you get users to read the full docs? (Obviously I'm guilty myself). The only other way I can think of is to add a reminder at runtime to please cite, but people may find that frustrating.

**Comment by jbteves** [comment]
@emdupre unfortunately with another user I've interacted with was still concerned that something is wrong with the setup, even with the new message. Nobody has filed or commented on a bug report except me, so I'm not sure how widespread this reading of the warning is.

**Comment by jbteves** [comment]
It's been a while since we discussed this and nobody else seems bothered by the warning, so I think we can close this.

**Comment by emdupre** [comment]
Sorry for never following up -- I was just concerned about hiding the warning for users who _do_ want to use duecredit ! I think closing for now is a good call, though, and we can always re-open with new reports :smile:

**Comment by jbteves** [comment]
@handwerkerd Here's the relevant issue thread.

**Comment by jbteves** [comment]
I would like to reopen this issue as a few more NIH users have reported concern over duecredit. It's a small dependency relative to our other dependencies and I feel that if we want to use it we should just require it.

**Comment by jbteves** [comment]
They just ask me if it's supposed to be there.
At this point I value a few megabytes of data and a line of requirements to be less important than having users ask me if it's okay, even though it says it's okay. I will concede that, to their credit, usually "not successfully"/"Failed to" juxtaposed with "functionality unaffected" is a little confusing.

**Comment by tsalo** [comment]
Fair enough. I agree that it's a very minor requirement, and it won't cost us anything to add it.

**Comment by tsalo** [comment]
#875 addressed this, so I'll close it now.

**Comment by mateuszpawlik** [comment]
When I install Tedana with pipx in a Docker image, I still get the less informative message:
```
root@6ccbea0e2c6a:/# tedana --version
Failed to import duecredit due to No module named 'duecredit'
tedana v23.0.1
```
