### ISSUE TITLE
Documentation does not reflect new 'mle' method

### ISSUE THREAD

**Issue by jbteves** [ME-ICA/tedana#201]
Currently, in the TEDICA step, [readthedocs](https://tedana.readthedocs.io/en/latest/approach.html#tedica) only describes the methods for kundu v2.5 and kundu 3.2. Documentation should be updated to describe the new mle method.

**Comment by tsalo** [comment]
MLE isn't actually used in TEDICA, just TEDPCA. The [TEDPCA section](https://tedana.readthedocs.io/en/latest/approach.html?highlight=mle#tedpca) has information about MLE.

**Comment by jbteves** [comment]
I see, my mistake... should we go ahead and close this?

**Comment by emdupre** [comment]
I'm going to close it ! One down :laughing:
