### ISSUE TITLE
Determine theoretical bases for different options for --sourceTEs

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#203]
We provide users with the option to perform `tedpca` and `tedica` on the optimally combined data (the default), the full z-concatenated data, or a subset of echoes from the full data. Unfortunately, while results may vary significantly based on which option is used, we don't currently have any solid theoretical or even empirical basis for choosing one option over another documented anywhere. This is something I would like to figure out _before_ we do the validation/comparison analysis, in which we will compare results across many different parameters, including different values for `--sourceTEs`.

Here is what I know so far about `sourceTEs`:
The first time it's used is in tedpca, so all echoes are used for T2* estimation and optimal combination, as well as to fit dependence models in component selection. When `--sourceTEs` is set to an index of echoes, `tedpca` is performed on the concatenated data for just the selected echoes, and returns a dimensionally reduced version of that concatenated data. Then, `tedica` seems to be performed on the dimensionally reduced concatenated data, rather than on a dimensionally reduced version of the optimally combined data (default) or of the full concatenated data (when --sourceTEs is set to -1). I believe that this means that both PCA and ICA will be performed treating the additional echo data as additional samples, rather than additional time points.

**Comment by dowdlelt** [comment]
Agreeing with you latter point based on limited testing - it appears to be performing PCA/ICA on the full stack, with the same number of timepoints. I am not sure which is preferable and haven't had a chance to perform extensive testing. Performing the PCA/ICA with 'more data' rather than a reduced (optimally combined) version is intuitively more appealing to me, but then again, each echo can be fairly noisy, which is reduced substantially by combination. Looking forward to empirical testing.

**Comment by jbteves** [comment]
Is this something explicitly mapped out in the reliability analysis @tsalo ?

**Comment by tsalo** [comment]
@jbteves I'm not planning to test out different sourceTEs options in the reliability analysis. I _am_ planning to do that in the validation analysis, but even then I'm not sure if we'll know what the theoretical basis for each option is based on those results (just what seems to give the best results).

**Comment by jbteves** [comment]
That's true; sorry for conflating the two. I think it would be great to get @handwerkerd's input on this, and I'm going to ask my PI when he gets back from vacation in a week-ish; I think he'd commented on it when we were talking about it with Peter Bandettini but my memory is very flawed.

**Comment by tsalo** [comment]
Would running PCA/ICA on the z-concatenated data bias toward identifying TE-independent signals over TE-dependent ones? Otherwise, it does seem like @dowdlelt's point about the tradeoff between quantity and quality of the data is the only impact `sourceTEs` would have.
