### ISSUE TITLE
TR isn't set correctly in output

### ISSUE THREAD

**Issue by dowdlelt** [ME-ICA/tedana#206]
When running the current version of tedana, it appears that the TR of the output data is set to 1.00. 

It looks like this occurs around line 638 in io.py, where the ref image is created. Specifically the variable img had a complete header, with the appropriate TR available via the get_zooms function (http://nipy.org/nibabel/nibabel_images.html):
```
good_header = img.header
good_header.get_zooms()[-1]
```
However, the TR information has been removed/replaced(?) with the ref image, such that get_zooms only has the voxel dimensions.

**Comment by emdupre** [comment]
Great catch, @dowdlelt ! Do you want to issue a PR for it ?

**Comment by dowdlelt** [comment]
I'll try and take a stab at it - if I can figure out what the line that creates the ref image is doing. The abundance of underscores in python remains a mystery to me...

**Comment by dowdlelt** [comment]
Either I am completely wrong, or that is a very simple fix.
