### ISSUE TITLE
Update comments and docstrings in PCA/ICA to clarify where whitening is performed

### ISSUE THREAD

**Issue by jbteves** [ME-ICA/tedana#209]
In #200, particularly [here](https://github.com/ME-ICA/tedana/issues/200#issuecomment-459520148) and [here](https://github.com/ME-ICA/tedana/issues/200#issuecomment-459542550), confusion was expressed about the data whitening required for ICA to be successful and where that step occurs. For clarity, the following should be updated:
1. The [tedpca docstring](https://github.com/ME-ICA/tedana/blob/101ad21ed1915e30b0e1afcfb992f3cb69abdf1e/tedana/decomposition/eigendecomp.py#L170-L262) should reflect the options chosen for PCA and their utility in preparing for ICA
1. The [tedica docstring](https://github.com/ME-ICA/tedana/blob/101ad21ed1915e30b0e1afcfb992f3cb69abdf1e/tedana/decomposition/eigendecomp.py#L396-L418) should reflect that the data is whitened as part of this ICA step, because it is required and impossible to override in scikit-learn
1. The [tedica step](https://github.com/ME-ICA/tedana/blob/101ad21ed1915e30b0e1afcfb992f3cb69abdf1e/tedana/decomposition/eigendecomp.py#L427) should be commented to indicate that data is whitened during this step

Contributors should comment below if they believe any additional documentation or comments should be added, or disagree with the above modifications. 

I will volunteer myself as the assignee for this issue.

**Comment by tsalo** [comment]
Additionally we want to clarify the distinction between whitening and dimensionality reduction throughout the repository (both in the code and in issues), since we have used the term "whitening" in reference to both in the past.
