### ISSUE TITLE
Improve documentation of PAID combination method

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#210]
### Summary
We support the parallel-acquired inhomogeneity desensitized (PAID) ME-fMRI combination method from [Poser et al. (2006)](https://onlinelibrary.wiley.com/doi/full/10.1002/mrm.20900) through `--combmode ste`. Per [Kundu et al. (2017)](https://www.sciencedirect.com/science/article/pii/S1053811917302410):
> The combination of TE signals in the manner of Eq. (3), referred to as parallel-acquired inhomogeneity desensitized (PAID) ME-fMRI, is comparable to that of Eq. (2) [`tedana`'s default combination method] **given noise is isotropic and homogeneous throughout the image**. However, given the high levels of artifact typical in most fMRI data, which adds to variance and thus reduces signal-to-noise ratio, the assumption of isotropic noise may not [be] suitable. In other words, depending on data quality and method of estimation, SNR may not reflect BOLD sensitivity and thus may not lead to optimal BOLD contrast. This condition makes the approach in Eq. (2) an appropriate choice if a T2* map is available. **Given the performance of modern computers and numerical computation software, computing per-voxel estimates of T2\* and T2\*-based weights is not prohibitive after acquiring ME-fMRI data.**

@emdupre and I discussed this a bit, and we interpret the above as indicating that one should only use the PAID method on smoothed data. Additionally, I believe that our choice of terminology (i.e., referring to PAID combination as `ste`, is somewhat confusing, especially since we often code the sourceTEs argument as `ste` as well.

### Next Steps
To resolve this, we should update the documentation in the following places to include the above caveats regarding combination method (i.e., not preferred and only on smoothed data):
- The argument documentation for the `tedana` and `t2smap` CLI.
- The docstrings for the `tedana` and `t2smap` workflow functions.
- The docstrings for any relevant functions in `combine.py`.

Pending #214, we should also add a note box to the [Processing pipeline details page](https://tedana.readthedocs.io/en/latest/approach.html#optimal-combination) to say that we support PAID in `t2smap` (a workflow for optimal combination), but not in `tedana` (i.e., denoising), and why that is (i.e., because PAID is only appropriate for smoothed data and denoising shouldn't be applied to smoothed data).

We should also change how we refer to the PAID combination method as `paid`, instead of `ste`, in order to reduce confusion.

**Comment by souravsingh** [comment]
@tsalo I am interested in working on the issue.

**Comment by tsalo** [comment]
@souravsingh That would be great, thank you! The good news is that I will be able to help more here than I can with the binder issues.
