### ISSUE TITLE
Incorporate features from MELODIC into PCA/ICA

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#218]
### Summary
While we may not want to use MELODIC for our dimensionality reduction (i.e., PCA) and decomposition (ICA) steps since it would require non-Python dependencies and because a lot of its options aren't necessary for `tedana`, there are several options that we may want to integrate into our workflow. Here is a list:
- `--dimest`: use specific dim. estimation technique: lap, bic, mdl, aic, mean (default: lap)
    - These options may be better able than our currently implemented MLE to dimensionally reduce the data prior to ICA. I would like to see how many components each method generally estimates compared to our method, and to see if we can implement them in Python.
- `--nl`: nonlinearity: gauss, tanh, pow3, pow4
    - I don't actually know what this refers to. The documentation isn't exactly helpful. Still, though, it might be worth figuring out and integrating into `tedana`.
- `--maxit`: maximum number of iterations before restart
    - We may want to provide users with the option to override our default of 5000 iterations.
- `--maxrestart`: maximum number of restarts
    - We only try running ICA once, and continue with a warning if there is convergence failure. I definitely think this is better than raising an error, but what if we allowed it to change the random seed and re-run a few times by default? Preliminary tests from the reliability analysis indicate that some data fails every time, but other data only fails sometimes (and some doesn't seem to fail ever). This could improve the quality of results for those data that fail sometimes.

**Comment by handwerkerd** [comment]
I think this is part of a bigger discussion on the correct way to do dimensionality reduction for multi-echo denoising and which options should be exposed to users. I agree that we don't want to use MELODIC itself because of unnecessary dependencies. Also I've experience some FSL functions being a bit brittle and having unknown consequences when using them in a way that differs from their originally intended purpose. Sticking with established general algorithms and figuring out which options to prioritize makes sense to me.

**Comment by tsalo** [comment]
It's good to know that MELODIC has some issues. I think, at minimum, we should implement `maxit` and `maxrestart` (as indirectly requested [here](https://neurostars.org/t/questions-about-the-fmri-denoising-algorithm-tedana-convergence-warnings-sensitivity-to-rounding-of-echo-times-and-differences-between-released-and-unreleased-versions/3458/3?u=tsalo)) and we should look into more aggressive dimensionality estimation methods when possible. I think I can pretty easily implement the former.

**Comment by tsalo** [comment]
Now that `--maxit` and `--maxrestart` are implemented, I think we can close this. We can discuss more aggressive dimensionality reduction methods in other issues (e.g., #101), and I don't think there are any other features from MELODIC that we would want to integrate into `tedana`.
