### ISSUE TITLE
Add information about draft PRs into contributing guidelines

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#221]
Original title: Remove WIP information from contributing guidelines
### Original Summary
Now that [GitHub supports draft pull requests](https://github.blog/2019-02-14-introducing-draft-pull-requests/), we can remove the WIP prefix from our contributing guidelines and replace that information with instructions for handling drafts.

### Original Next Steps
1. Remove WIP prefix from contributing guidelines
2. Add information about using GitHub's draft PR feature

### Update
As it turns out, Travis doesn't run on unmergeable PRs (like draft PRs) by design. As a result, linting and unit tests won't be run on draft PRs until they are opened for review _and_ a new, mergeable commit is made. As such, we *do not* want to remove WIP information from the contributing guidelines, and in fact we want to dissuade contributors from using the draft PRs feature, at least for now.

**Comment by jbteves** [comment]
I think the easiest solution to this is to change CONTRIBUTING so that these guidelines are reflected.
