### ISSUE TITLE
Extreme values in T2* maps

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#225]
### Summary
I noticed that there were some extreme values in the five-echo test dataset's T2* map (see figure below). In addition to extremely high values (~4000), there are also negative values. For the three-echo test dataset, we have values from -202 to 1104.

### Additional Detail
![t2s_dist](https://user-images.githubusercontent.com/8228902/53170183-7c262600-35ad-11e9-8894-4afb0c7c886e.png)

### Next Steps
We already cap extremely high T2* values [here](https://github.com/ME-ICA/tedana/blob/16cfa720f6202298d7587e72976c6e5e78eb904e/tedana/workflows/tedana.py#L292-L294), but I think we should move that step from the tedana workflow into the T2*/S0 estimation function _and_ we should be much more aggressive with how we restrict values. At minimum, we can replace negative values with zeros, NaNs, or some reasonable real value. We can almost cap high values at a reasonable maximum, although I know it will vary by magnet strength. We know it can't be at 4000, for example. 

We could also try replacing invalid values with values from valid neighboring voxels. I think that would work.

**Comment by tsalo** [comment]
Would it be reasonable to limit T2* values to the range of acquired echo times?

**Comment by dowdlelt** [comment]
Something about that feels wrong to me - though I agree completely with replacing negative values with zeros. I don't think I have a good enough understanding of the equation from which the T2* values are derived to understand how it is getting numbers that are lower or higher than the range of acquired echo times, but it seems possible that it could estimate (somewhat accurate) values outside of the echo time range. 

Perhaps there is something inherent in the estimation equation that would provide a reasonable cap based on the echo times provided - ie, for some given echo times, we would expect the equation to be 'accurate' out to Xms, so that is where the cap should be. Maybe that can be simulated? In that way it would depend on the data that was provided, so would change as needed from 1.5 to 7 T.

**Comment by cjl2007** [comment]
Hi - just wanted to add that I also have observed "extreme" negative T2* values in my own data (also a 5 echo dataset; 13.40 31.11 48.82 66.53 84.24 ms).

![extremet2](https://user-images.githubusercontent.com/46632198/53758588-2b0b1180-3e8c-11e9-9780-d9c1ce5b77af.jpg)

**Comment by tsalo** [comment]
One partial solution involving improving make_adaptive_mask is to combine the current method with a simple check of echo-wise means. Namely, if the mean value for a given voxel goes _up_ from one echo to the next, I think we can infer that that second echo is bad. Here's what I get when I combine the two methods:

![updated_t2s](https://user-images.githubusercontent.com/8228902/53886539-3c6c2f00-3fee-11e9-923f-9359b3b3a3ee.png)

As you can see, we lose the negative values and the extreme positive values >1000. We can probably fine-tune this idea, but it's a good starting point, I think.

**Comment by cjl2007** [comment]
Sorry to ask a likely obvious question - but what are the practical implications of having extreme values in the T2* maps? I consistently see a handful of these extreme values in my data, also in the ventricles.

**Comment by tsalo** [comment]
T2* is used to optimally combine the data and to make the model predictions used to calculate Kappa, so I think that the implications are 1) inaccurate values in the optimally combined data, leading to 2) PCA and ICA decompositions on optimally combined data with weird outliers, potentially altering the components, and 3) model fit metrics will be contaminated by invalid model predictions.

It's hard to say how large of an impact this will have though. I think I'll have to look into that.

**Comment by cjl2007** [comment]
Hmm okay, I am curious to see how this could be impacting how some components are classified in my data. As a temporary fix - do you think it makes sense for me to identify all the voxels that don't demonstrate the expected decay pattern (prior to submitting data to tedana) ... and setting them to zero?

<img width="1159" alt="Screen Shot 2019-03-08 at 4 42 45 PM" src="https://user-images.githubusercontent.com/46632198/54057773-da642300-41c1-11e9-9cfe-710c00d6fd6d.png"> 

Above is my brain mask (red) and the voxels that are not exhibiting the expected e1>e2>e3>e4>e5  signal intensity (averaged over time) pattern are shown in white. Many of these, I bet, are being flagged by tedana as "not having good signal" but I am pretty sure that subset of these (those in the ventricles) are the same ones that will later have "extreme" values in the T2* map. I need to check this though to be certain. 

But in general, does it make sense to zero these voxels prior to submitting the data to tedana?

**Comment by tsalo** [comment]
I spent some time looking at the data and I don't think this is a huge problem. I think it's definitely something we want to fix, but since the extreme values are primarily in CSF, the impact isn't very large. The good news is that, because of the way optimal combination is done, the adverse effects of T2* misestimation are limited. With an extremely high T2* value, the optimally combined data will just be dominated by the last echo's time series. Conversely, with an extremely low (e.g., negative) T2* value, that data will be dominated by the first echo. In most cases where there's no real signal (e.g., CSF), optimal combination shouldn't recover anything to begin with, and which echo it takes most of the signal from shouldn't matter.

I think the problem is that CSF seems to mix these extremely high and extremely low T2* estimates, leaving us with jumbled up optimally combined time series, but only in the CSF (as far as I can tell). When we get to decomposition, the signal in CSF isn't as cohesive (smooth) as it should be, and that could lead to more underlying signals/components. I mean, it's just a guess, but it makes sense to me.

**Comment by jbteves** [comment]
@allcontributors add @tsalo for bug reports

**Comment by jbteves** [comment]
@tsalo did we come to any recent conclusions on this one?

**Comment by tsalo** [comment]
Short of a two-compartment model that estimates parenchyma and CSF T2* values separately (which would require data with more echoes than is typical for tedana users), I don't think there's a good solution to the CSF T2*/S0 misestimation specifically.

In the current workflow, we could smooth these values or do a better job of cropping them to reasonable ranges. Negative values (which are set to 1 currently) could be set to a realistic CSF T2* value (e.g., 200) instead. Using better restrictions and initial values for the nonlinear estimation method could also help.

**Comment by emdupre** [comment]
Is it worth documenting this behavior, or now that we're no longer returning negative values should we just let it lie ?

**Comment by tsalo** [comment]
I don't think it's worth it to document this, but we can revisit if users report a problem. In the meantime, I'm comfortable closing this issue. Too bad we got rid of the `wontfix` issue tag...
