### ISSUE TITLE
Incorporate decay curve fit information into workflow

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#230]
### Summary
I believe that @handwerkerd mentioned this at some point, but I don't see anything in any of our issues. At minimum, we don't seem to have any discussions dedicated to this specifically.

### Additional Detail
We estimate T2* and S0 for each voxel using log-linear regression. We currently only use the parameter estimates for the intercept (S0) and slope (T2*), but we can incorporate fit quality information further down the workflow as well. Specifically, I think the fit quality would be useful in calculating metrics for component selection. We can somehow combine the fit quality maps with the component z-statistic maps, which are used as weights for the weighted averaging used to calculate Rho and Kappa.

Here are some ideas I've been thinking of:
- The residuals returned by [numpy.linalg.lstsq](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.lstsq.html).
- Root mean squared error, calculated from the log data and the predicted values.
- Something using the voxel- and _volume_-wise regressions. The reason I think this would be useful is that, assuming high-quality data, actual BOLD signal should increase the variability of the data within each echo, decreasing regression fit.

No matter what, I think we need to do two things. First, we need to invert the error values somehow, so that lower values indicate worse fit, in order to use the values in the weighted averaging for metric calculation. Second, we need to scale each voxel independently based on the voxel's overall signal, because many voxels with objectively poor fit will have lower residuals than voxels with better fit because they have overall lower signal.

**Comment by jbteves** [comment]
@tsalo would you mind turning this into a checklist? This issue has a few different pieces. If you don't have time, would you mind me editing it into one?

**Comment by jbteves** [comment]
@tsalo do we want to keep this open?

**Comment by tsalo** [comment]
I'm fine with closing it.
