### ISSUE TITLE
Add figure info to visual reports section on documentation site

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#237]
### Summary
Now that we have great static figures courtesy of @dowdlelt, we should add information about how to use them to the [visual reports section](https://tedana.readthedocs.io/en/latest/outputs.html#visual-reports) of the documentation site, along with the caveat that we don't have interactive or consolidated reports yet.

### Next Steps
1. Collect an example or two of each of the generated plots.
2. Add information about how to generate figures, how to interpret each figure, and how to manually select components to the Visual Reports section on the site.
3. Include information about interactive visual reports (namely that they're not set up yet, but that they're something we're working on).

**Comment by souravsingh** [comment]
@tsalo I am interested in working on the issue. How do I start?

**Comment by tsalo** [comment]
@souravsingh To start, you'll want to run the tedana workflow on some data in order to generate the figures. I would recommend using the five-echo dataset we use for testing, as it is a flashing checkerboard task and at least one component will be clearly signal (i.e., loading on visual cortex with a time series that reflects the block design of the task) and several will be clearly noise (e.g., the linear trend component that normally shows up around number 30). After that, it's a matter of including those figures in the documentation with information about how to interpret them, as described above. If you have trouble figuring out how each figure should be interpreted, I think @dowdlelt might be the best person to help there.

**Comment by emdupre** [comment]
Let us know if you have issues with getting any of this set up, @souravsingh ! You _should_ be able to use CircleCI and sphinx to help you, but I know there are a lot of moving pieces so happy to write down a few details as it's useful.

**Comment by jbteves** [comment]
We probably want this done before OHBM, WDYT @tsalo @emdupre @dowdlelt ?

**Comment by dowdlelt** [comment]
I agree completely - I should (or could) probably do this.. but not sure about my time between now and June 9th(!).

**Comment by jbteves** [comment]
Can you list what you think other people can do for you, and we'll try to get those handled and leave you to more of the documentation writing, since you created them? Alternatively, we can create something and you can just comment on it as a WIP PR. My time is more open than usual, so I'm happy to help with this.
