### ISSUE TITLE
Output summary file sometimes indexed by CircleCI

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#248]
### Summary
For some reason, sometimes the file listing the outputs for the three-echo and five-echo runs is indexed by CircleCI (see [here](https://circleci.com/gh/ME-ICA/tedana/2336?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification)). It seems to happen randomly (unless I'm missing some underlying pattern), and it causes the integration tests to fail when they shouldn't. If we could figure out why this happens and fix it (if it can be fixed), that would be great.

**Comment by jbteves** [comment]
I have added the "Help Wanted" flag in case we are so fortunate as to have someone very familiar with CircleCI come through. @tsalo @emdupre have either of you noticed this since its posting on April 3rd? We've merged a lot of PRs since then.

**Comment by jbteves** [comment]
This hasn't come up for almost 6 months; closing.
