### ISSUE TITLE
Move masking/unmasking functions into new masking module

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#250]
### Summary
We have a handful of masking/unmasking functions that I think should be moved out of `utils` and into their own module. While I would ultimately prefer to operate mostly on img-like objects (to make it easier for users to call each function in the package without knowing all of the details behind our data loading, masking, unmasking, and data saving procedures), we should move relevant functions out of `utils` (and potentially `io`) to reduce bloat in the meantime.

### Additional Detail
The functions `utils.load_image`, `utils.make_adaptive_mask`, `utils.unmask`, `decomposition._utils.eimask`, and potentially `io.new_nii_like` are all related to masking and/or converting between imgs and arrays. I think that these would be best organized in a `masking` module.

### Next Steps
1. Create masking file (`masking.py`).
2. Move functions from their current positions to new file.
3. Update imports throughout package.
4. Update tests.
5. Update API organization in docs.

**Comment by emdupre** [comment]
Sorry, is this instead of #251 ? I'm :+1: on just operating on imgs directly, if that helps in the discussion !

**Comment by tsalo** [comment]
I was thinking that this would be in addition to that. We’ll be able to eliminate most masking/loading functions but we may want one or two to gracefully apply the masks on the list of imgs. Plus we’ll still have eimask and make_adaptive_mask.
