### ISSUE TITLE
T2* maps should be outputted in seconds, not milliseconds

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#252]
### Summary
Per [BEP001](https://github.com/bids-standard/bep001/blob/e661031158c462c7c7ba9e11d42b99a67fca591e/src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md), T2* maps should be in units of seconds, not milliseconds.

### Additional Detail
BEP001 hasn't been merged yet, but it seems likely that the units for these kinds of maps will be set in stone. 

### Next Steps
1. Divide T2* estimates by 1000  when they're written out in the tedana and t2smap workflows.

**Comment by jbteves** [comment]
This should be a quick fix during the sprint.

**Comment by emdupre** [comment]
Should we coordinate with AFNI on this ? Not confident that it matters to them, but just to make sure !

**Comment by jbteves** [comment]
I think I will use this as an example for contributors.

**Comment by tsalo** [comment]
Just pinging this to remove the stale label until #525 is dealt with.
