### ISSUE TITLE
Add Pause tag to Issues

### ISSUE THREAD

**Issue by jbteves** [ME-ICA/tedana#257]
### Summary
Add a pause tag to some issues so that people don't work on them if there is a conflicting priority

### Additional Detail
The pause tag would be used in instances of refactoring or the necessity of diverting attention to a pressing issue. For example, if we're refactoring a section of code, it doesn't make sense for people to work on documentation in that section since it will likely change. The expectation would be that paused issues should NOT be worked on. For now, we will have to manually add/subtract the pause tag until workflows are more settled. 

### Next Steps
I would like to add the pause tag pending approval from @emdupre, @tsalo, @KirstieJane. If anybody is opposed to adding this tag, they should comment below outlining why they think it's a bad idea. 
- [x] Add the tag (Thanks @tsalo !)
- [ ] Add notes to CONTRIBUTING to indicate usage of the tag (PR #278 would complete this task)

**Comment by KirstieJane** [comment]
Sounds good to me! Maybe add a section in the CONTRIBUTING guidelines so people know what it means?

**Comment by jbteves** [comment]
I've updated the comment above with a checklist item so that we don't close the issue without opening a PR to fix that.

**Comment by tsalo** [comment]
I've added the [paused](https://github.com/ME-ICA/tedana/labels/paused) tag.

**Comment by jbteves** [comment]
Thanks @tsalo, @emdupre if you're happy with this then I'll draft a PR to add this tag description to CONTRIBUTING
