### ISSUE TITLE
Add Stale tag to Issues

### ISSUE THREAD

**Issue by jbteves** [ME-ICA/tedana#258]
### Summary
I'd like to propose adding a stale tag to an issue that meets certain criteria, with the intent of closing them if they remain stale over some time period.

### Additional Detail
I don't feel strongly about our criteria for a stale issue or how long it remains stale before closure, but I think it would be help keep the issue tracker from getting bloated. As an examples for issues that I think are stale:
1. #144 has little discussion since October of last year, and has never had a PR directly address. Discussion seemed to converge on adding documentation.
2. #50 has not been referenced since October as well, and is probably best broken into smaller issues like @tsalo has done in #249, #250 (Thanks @tsalo!)
The other advantage it has is that if we see that a conversation has stalled, we can think about why and decide if there is a way to either reignite discussion or resolve it. For example, it would be useful in my opinion to close #144 and replace it with some issues on documentation, as well as notes in the reliability analysis. Similarly, I think #50 could easily be replaced with @tsalo's new issues, and additional ones as we refactor more deeply. 

### Next Steps
- [x] I'd like to hear back from the maintainers about their thoughts on this, especially if there's already a policy in place that I'm just not aware of
- [x] I'd like to hear from contributors on whether they think this would make it easier to read through the issue tracker
- [x] If we decide to implement a stale tag, we should define a clear policy for what a stale issue would be
- [x] If we decide to implement a stale tag, we should define a policy for closing a stale issue if it remains stale for a certain period, including what closing comments should state about its closure (e.g., should they point to new issues that are spawned from that thread?)
- [x] If we decide to implement the tag, we should indicate policy on stale issues in CONTRIBUTING (Would be completed by #279)
- [ ] Add stale-bot to the repository

**Comment by jbteves** [comment]
My personal opinion is that an issue should be considered stale if it meets the following criteria:
1. There has been no discussion for at least 3 months
1. The discussion has not resulted in concrete action items
1. There have been no Pull Requests that address that conversation for at least 3 months
and that issues which remain stale for an additional 3 months are closed. To me, this seems okay because an issue can always be re-opened, and it's helpful to have the issue tracker have issues which are *targets for labor* only. Since it's a volunteer project, we want to try and make it as easy as possible for people to search through open pieces of work and take them on, so having discussions which reach no conclusions hinders rather than helps, even if good points are made (IMO). 

I would think that a closing comment should indicate that it's closed as stale, and reference any issues which represent actionable tasks that the discussion generated, or discussions spun off from that one.

**Comment by emdupre** [comment]
This all seems like a very reasonable course of action to me ! How long do you think an issue marked "stale" should be left open for, after the closing comment(s) are made ?

**Comment by jbteves** [comment]
I was envisioning more of leaving the comment and then closing immediately via “Close and comment”. That way there’s a record of why it’s marked stale and subsequently closed.

**Comment by emdupre** [comment]
It might be nice to give folks a chance to chime in... I think the Stale bot gives about a week: https://github.com/probot/stale

**Comment by emdupre** [comment]
One potential idea would be to use stale bot to flag issues as Stale, then write a closing comment and close within the week.

**Comment by jbteves** [comment]
Oh, true, that makes sense. That bot looks perfect! Thanks for digging that up, I always forget that on GitHub there’s probably a bot for it.

**Comment by KirstieJane** [comment]
Great idea @jbteves! 3 months is a sensible time for issues to be marked stale in my opinion.

Stalebot looks great. I think a week’s warning works 😸

**Comment by jbteves** [comment]
@KirstieJane @emdupre @tsalo it seems like we're converging on the idea to do three months gets marked stale by the bot, and is auto-closed after a week? Emoji vote below: 👍 or 👎

**Comment by jbteves** [comment]
Realized that my PR accidentally closed this; that wasn't intended because we would still like stale-bot; @emdupre maybe you could add this while adding the all-contributors bot?

**Comment by jbteves** [comment]
@emdupre can we add the bot?
