### ISSUE TITLE
Add all-contributors bot

### ISSUE THREAD

**Issue by jbteves** [ME-ICA/tedana#259]
### Summary
Add the all-contributors bot in #56 per @KirstieJane's suggestion.

### Additional Detail
This would enable us to easily acknowledge contributors through the README or a future CONTRIBUTORS file. A project maintainer will have to [add the bot to the repository](https://allcontributors.org/docs/en/bot/installation) in order for it to be active. For reference, bot usage may be found [here](https://allcontributors.org/docs/en/bot/usage). The bot will do basic natural language processing to use [emoji-key](https://allcontributors.org/docs/en/emoji-key) while active. 

### Next Steps
- [x] Install the bot
- [x] Update CONTRIBUTING or community guidelines (would be closed by #309)
- [x] Recognize previous contributors

**Comment by jbteves** [comment]
@emdupre WDYT?

**Comment by jbteves** [comment]
This may also fall under the "Healthy Community" milestone.

**Comment by emdupre** [comment]
This sounds great ! I don't know that we should have it in the CONTRIBUTING file itself... What about in a `people.md` or `contributors.md` ? Any experience with what other projects are doing, @KirstieJane ?

**Comment by jbteves** [comment]
There was some discussion about this in #56, see [here](https://github.com/ME-ICA/tedana/issues/56#issuecomment-484969312).

**Comment by emdupre** [comment]
Thanks for the pointer ! I'd say we should actually go ahead and create that `contributors.md`, then, since we have 12 people on the "contributors" tab but a few more that I think would be nice to include even though they don't have code contributions just yet. 

If there are strong preferences against this, though, happy to brainstorm how best to include it in CONTRIBUTING !

**Comment by jbteves** [comment]
I agree with @emdupre on splitting it out, just because I like ultra-modularity and it seems like they are distinct things-- one is how to become a contributor, and one is an acknowledgment to existing contributors. Also then the bot can't mess up our CONTRIBUTING file if it goes haywire for some bizarre reason, but that's more paranoia than sound reasoning.

**Comment by KirstieJane** [comment]
I have a preference for putting the table in the README - I don't think many people will see the table in `contributors.md` but I don't mind it going in there.

Agree that its best not in the `CONTRIBUTING.md` file - sorry if I accidentally recommended this at some point 😬

**Comment by jbteves** [comment]
Nope, I misread, you said README, sorry!

**Comment by emdupre** [comment]
@all-contributors please add @jbteves for project management, documentation, pull request review, maintenance ! I'm sure I'm missing other stuff, but as a start :smile_cat:

**Comment by emdupre** [comment]
@all-contributors please add @KirstieJane for documentation, finding funding, project management, pull request reviews, and giving talks on the project !

**Comment by emdupre** [comment]
@all-contributors please add @tsalo for code, ideas, documentation, tutorials, answering questions, and reviewing pull requests !

**Comment by emdupre** [comment]
@all-contributors please add @handwerkerd for design, documentation, a dataset for the examples, and pull request review !

**Comment by emdupre** [comment]
@all-contributors please add @dowdlelt for code, answering questions, designing the visual reports, and bug reports !

**Comment by emdupre** [comment]
@all-contributors please add @rmarkello for code, infrastructure, and answering questions !

**Comment by emdupre** [comment]
@all-contributors add @prantikk for code and ideas !

**Comment by emdupre** [comment]
@all-contributors add @javiergcas for ideas !

**Comment by emdupre** [comment]
@all-contributors please add @emdupre for code, documentation, ideas, infrastructure, pull request review, examples for testing, and answering questions.

**Comment by emdupre** [comment]
Trying advice from @KirstieJane in https://github.com/all-contributors/all-contributors/issues/225 ...

@all-contributors please add @jbteves for bug reports !

**Comment by emdupre** [comment]
Hmm. That didn't work. I might touch base with you Kirstie to see what your solution was ! For now I just manually updated it :sweat_smile: 

**Hi everyone !** Sorry for tagging you into this long thread. We've added the all-contributors bot to the project to recognize the many contributions folks have made -- so thank you ! 

I've done an initial pass, but I know there are contributions I left out ! Please feel free to add contributions from yourself or others following these [usage guidelines](https://allcontributors.org/docs/en/bot/usage). I'm also working to get this added to our Contributing guidelines :sparkles:

**Comment by jbteves** [comment]
I just saw this, I will add that to my documentation PR.

**Comment by jbteves** [comment]
@all-contributors please add @tsalo for bug reports

**Comment by jbteves** [comment]
@emdupre once you've approved the request from adding Monica I'll probably just close this unless you have any objections.
