### ISSUE TITLE
Contributor/Developer Documentation Overhaul

### ISSUE THREAD

**Issue by jbteves** [ME-ICA/tedana#268]
### Summary
We should add notes on how CircleCI works to CONTRIBUTING so that contributors understand what will be tested and how long it typically takes, as well as what a failure means. There should also be light details on how it works or a link to a brief explanation elsewhere. 

### Next Steps
- [ ] Outline what should be added to CONTRIBUTING
- [ ] Write additional documentation following the outline

**Comment by jbteves** [comment]
@emdupre @tsalo is there any existing documentation for this? Or maybe @KirstieJane has some documentation from other projects?

**Comment by jbteves** [comment]
I would outline the following to be done:
- [ ] Show how to use the unit tests
- [ ] Show how to run CircleCI tests
- [ ] Show how to run Travis tests

**Comment by jbteves** [comment]
Thoughts @tsalo @emdupre ?

**Comment by jbteves** [comment]
@emdupre, @rmarkello and I talked about just writing this up in `readthedocs`, any objections?

**Comment by emdupre** [comment]
Hmm. I'd like to hear about how you think it interacts with the CONTRIBUTING guide !

**Comment by jbteves** [comment]
CONTRIBUTING would have what it has now, but with a link to a "Developer Guide" tab or similar on RTD.

**Comment by tsalo** [comment]
Some sections I'd like:
- Code review guidelines (there's a scikit-learn section too)
- Basic git branching instructions
- Pull request checklist (there's a scikit-learn section too)
- Checking documentation on pull requests (there's a scikit-learn section too)
- Stalled pull requests (etiquette for taking over a pull request after it goes stale) (there's a scikit-learn section too)
- How to write good tests (there's a scikit-learn section too)
- More coding guidelines
- How to make a good bug report

**Comment by jbteves** [comment]
Add dev-requires `sphinx` for documentation creation.

**Comment by jbteves** [comment]
Switch WIP tag to Draft PR

**Comment by tsalo** [comment]
Add MAINT label. Remove STY (since we use REF generally).
