### ISSUE TITLE
Developer calls | Set dates and add to Contributing guidelines?

### ISSUE THREAD

**Issue by KirstieJane** [ME-ICA/tedana#270]
Heya! I'm having a calendar day and am just looking at the dev calls for tedana.

I can't make the next one (17 May) and as @emdupre and @handwerkerd weren't at the last one (19 April) I wonder if we could add one in on 3 May (I can't do 10 May either) to help get us alligned on the software demo and poster for OHBM?

What do you think @emdupre @tsalo @handwerkerd @jbteves @dowdlelt?

Added: EMOJI VOTE (use all that apply!)

| Emoji | Meaning |
| ------ | --------- |
|  ❤️  | May 3 regular time |
| 🚀 | May 3 30 min after |
| 🎉 | May 10 regular time |
| 👀 | May 17 regular time |
| 😕 | No times work |

---

Also, shall I add a sentence to the contributing guidelines about the dev calls and add the [calendar link](https://calendar.google.com/calendar/embed?src=pl6vb4t9fck3k6mdo2mok53iss%40group.calendar.google.com)?

**Comment by dowdlelt** [comment]
I would be ~30 minutes late for one on May 3rd, and cannot make it at all on the 17th. So 3rd is seeming more promising.

**Comment by KirstieJane** [comment]
I'd be fine with starting 30 mins late.

EMOJI VOTE:

| Emoji | Meaning |
| ------ | --------- |
|  ❤️  | May 3 regular time |
| 🚀 | May 3 30 min after |
| 🎉 | May 10 regular time |
| 👀 | May 17 regular time |

**Comment by jbteves** [comment]
I don't see a reason to not have the calendar link.

**Comment by KirstieJane** [comment]
Huh - I don't know why #271 didn't ping a link here. But that PR does the adding part if anyone wants to review 😸

**Comment by tsalo** [comment]
The link in 271 is to 254, not 270.

**Comment by KirstieJane** [comment]
Whooooops! Thank you @tsalo 😬

**Comment by KirstieJane** [comment]
Added a "No times work" option (😕) to the emoji vote too

**Comment by emdupre** [comment]
Looks like the option for May 3rd at 10:30a Eastern Time (3:30p London time) is currently in the lead !

**Comment by KirstieJane** [comment]
Lets call it - May 3 at 10:30am Eastern (3:30pm London). @emdupre would you mind updating the calendar please?

Thanks for all the votes! 😄

**Comment by emdupre** [comment]
Updated ! I think we can close this issue, now :sparkles: :rocket:
