### ISSUE TITLE
Remove Stale Labels: hacktoberfest and MozSprint

### ISSUE THREAD

**Issue by jbteves** [ME-ICA/tedana#272]
### Summary
We should probably get rid of these labels as neither event is happening anymore, and we should make sure that issues with that label are revisited with a plan to address them.

**Comment by tsalo** [comment]
I think that both events are annual, so I'd like to keep the labels around. It looks like the labels have been removed from all open issues, though, so I think that gets at what you're looking for. I'm not sure when that happened or who did it.

**Comment by jbteves** [comment]
Oh weird. Sorry I misunderstood, closing.
