### ISSUE TITLE
Revisit signal > noise t-value metric

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#274]
### Summary
The [signal-noise_t metric](https://github.com/ME-ICA/tedana/blob/1e148376634c426faf8c4223e5e1ddae71229b90/tedana/selection/select_comps.py#L150) is used to build the decision table score metric (i.e., the sum of several ranked metrics), which involves ranking t-values across components. The t-tests used to get these values are component-wise comparisons of the _unique_ F-statistics from "signal" (i.e., cluster) and "noise" (i.e., non-cluster) voxels, after log-transformation. There are a couple of elements to this metric that I think need to be rethought, including:
- [ ] T-values will be dependent on degrees of freedom (i.e., numbers of significant voxels for each component), so we should z-transform them before we use them as a metric.
- [ ] I don't think there's any reason to only use unique F-statistics in the t-test. We can just drop the `np.unique` call at that stage.
- [ ] I can't find any basis online for log-transforming F-statistics to make them normally distributed. It seems to generally work, but I think that the [Fisher's z-distribution](https://en.wikipedia.org/wiki/Fisher%27s_z-distribution) (i.e., `0.5 * np.log(f)` instead of `np.log10(f)`) makes more theoretical sense. The results are pretty similar, but at least there's a Wikipedia page for the z-distribution.

### Next Steps
1. [ ] Discuss my above suggestions and agree on which ones (if any) should be implemented.
2. [ ] Implement the chosen changes. This should be fairly easy, since all are done in just one or two lines.

**Comment by jbteves** [comment]
@tsalo in keeping with some of what we discussed on the call, would you mind if I convert your Next Steps to a checklist? Can you think of close-ended questions we could ask to guide the discussion?

**Comment by tsalo** [comment]
@jbteves Thanks for catching that. I've changed the list to a checklist.

I think that the three discussion points in the summary section are fairly close-ended already. We can discuss each one in detail, but they all ultimately boil down to yes/no decisions.

**Comment by handwerkerd** [comment]
I just noticed this and the related PR #360 
There are a lot of semi-arbitrary choices in this section of the code and I'd be hesitant to start changing them without having a more robust system to see how they affect results. This step is very ripe for re-thinking, but I'd push to do that rethinking within a more structured framework.
The "unique" step is the one that confuses me the most. I suspect it was done as a way to make the sample sizes more similar, but it's an odd way to do that. 
That said, I'm not sure how much this will change anything substantial. The number is essentially a ranking that is used in tandem with `countnoise` `countsigFR2` and 'dice_FR2`My sense is that, if you get more non-cluster significant voxels, it's going to give a slightly lower t value for `signalnoise_t` and all the other values will be ranked higher. Thus, it would be hard to say how much a non-stable sample size would affect the actual decision metric in this case.

Working on a framework for comparing decision tree changes wasn't directly mentioned for the hackathon #373 and could be useful to consider.

**Comment by tsalo** [comment]
In practice, the changes make almost no difference. The number of voxels for non-clusters and clusters both tend to be in the hundreds, so the z- and t-statistics are very close to one another. My concern was less about the impact of the changes and more about the logical basis for how the metric was calculated. That said, since the changes don't impact anything, I'm happy to postpone merging them until we have a framework for comparing decision tree results.

**Comment by handwerkerd** [comment]
Any chance you looked how much using only unique values changed anything?  My assumption is that, when dealing with floating point numbers, very few values will be unique so this won't change much. Perhaps this was a hack to remove 0's or other fixed values that might have ended up within these masks?

**Comment by tsalo** [comment]
I hadn't before, but I just ran a check on the five-echo and eight-echo test datasets. In all cases, the number of unique F-values was equal to the total number of F-values (i.e., zero duplicates), except when there were no selected voxels (e.g., when there were no clusters).

If `np.unique` _is_ used as a hack, I think it's for a currently unknown edge case. Unless, of course, all of our work to fix up masking throughout the library also addressed whatever the original issue was.

**Comment by handwerkerd** [comment]
I could see adding a message when ever this unique call removes values. The minus would be it's utterly meaningless to 99% of users, the plus is, if someone notices it, we might be able to figure out what edge case it was designed to address.

**Comment by emdupre** [comment]
Just going through the issues and wanted to note that this is something that might be useful in the `--debug` call !

**Comment by tsalo** [comment]
It looks like the same paper that describes the T-to-Z transform also describes an F-to-Z transform. We could probably use that to get the F-statistics into normal distributions prior to the t-tests. I might try to read that at some point.
