### ISSUE TITLE
Rename tedana.model to tedana.metrics

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#277]
### Summary
With #273 we'll be moving statistics-related functions out of `tedana.model.fit`, and so that module will become purely about metric calculation. This rename was proposed by @emdupre in her review of #266, but will be done separately to reduce PR bloat.

### Next Steps
1. Rename `tedana/model/` to `tedana/metrics/`. 
2. Update all imports throughout package, including tests. 
3. Update API documentation.

**Comment by jbteves** [comment]
@tsalo have you started on this already? If not I'll try to take a crack at it.

**Comment by tsalo** [comment]
I was planning to wait until after #266 was merged, and then never circled back to it after that happened. It would be awesome if you could do it.

**Comment by jbteves** [comment]
Cool, gave it a stab in #325 and requested your review.
