### ISSUE TITLE
Convert text dumps to json format

### ISSUE THREAD

**Issue by emdupre** [ME-ICA/tedana#28]
Comes from https://github.com/ME-ICA/tedana/pull/24#issuecomment-386768695

Right now, [`csstepdata`](https://github.com/tsalo/tedana/blob/11282c5f409fa44130917085aba5aebe3e3689a8/tedana/interfaces/tedana.py#L806-L811) is generated by evaluating variables and saving out the result to a text file. Something similar happens in [`seldict`](https://github.com/tsalo/tedana/blob/11282c5f409fa44130917085aba5aebe3e3689a8/tedana/interfaces/tedana.py#L546-L551), although there the result is returned as a dictionary. 

It would be great to instead `zip` together a list of the variables with descriptive identifiers. Then, if the dictionary is being saved out, we could use `json.dumps()` to write out a structured instead of plain text file.

**Comment by rmarkello** [comment]
This was partially resolved with #22!

**Comment by emdupre** [comment]
Yes, I realized in doing it that the issue with `seldict` is actually slightly different. I might be ok to close this for now and address `seldict` later as part of #16. WDYT ?

**Comment by rmarkello** [comment]
That seems fine with me! I would, however, potentially consider raising a separate issue for reorganizing the `comp_table.txt` file generated via `tedana.interfaces.tedana.writect()` to something a bit more JSON-like, too?

**Comment by emdupre** [comment]
Yes, I think that's fair. That might even be a more accurate description of this issue... `seldict` is coming up in #35 if I want to keep linting

**Comment by tsalo** [comment]
This was originally about the component table format, right? Given that we're now using a csv format for those tables, should we close this?

**Comment by emdupre** [comment]
Agreed ! Yes, this was still open if we wanted to use JSON instead, but that's overkill at this point I think. Closing :)
