### ISSUE TITLE
Next community call | 24 or 31 May?

### ISSUE THREAD

**Issue by KirstieJane** [ME-ICA/tedana#283]
We don't have a community call scheduled until after OHBM (according to the [calendar](https://calendar.google.com/calendar/embed?src=pl6vb4t9fck3k6mdo2mok53iss%40group.calendar.google.com)).

I'd like to propose that we do have one on either 24 or 31 May at the regular time of 3pm UK / 10am east coast.

Please emoji vote by reacting to this issue:

| Emoji | Meaning |
| ------ | --------- |
|  ❤️  | May 24 regular time |
| 🚀 | May 31 regular time |
| 😕 | No times work |

Comment if you'd like to ask for the times to be changed slightly....

**Comment by jbteves** [comment]
@KirstieJane looks like this Friday wins, should we schedule it on the tedana calendar?

**Comment by emdupre** [comment]
I don't think I'll be able to make this Friday _but_ I've started on the poster -- one thing that (I think) would be *amazing* is to have the all contributors bot added so that we can show folks on the poster. WDYT ?

**Comment by jbteves** [comment]
Whoops, I missed that you couldn't make this Friday.   
Yes, let's do it, plus we can close that issue! 🙌

**Comment by jbteves** [comment]
Closing since the meeting has passed
