### ISSUE TITLE
--manacc question 

### ISSUE THREAD

**Issue by cjl2007** [ME-ICA/tedana#287]
I recently updated my version of tedana to the update on this repo (0.7, I believe). 

When using the --ctab argument, Tedana seems to now require also inputting a comma separated list of manually accepted components (--manacc). Tedana is unhappy with the list I am providing it with, and I cant figure out why. Here is the error it generates. 

File "/home/cl968/miniconda3/envs/me/bin/tedana", line 11, in <module>
    sys.exit(_main())
  File "/home/cl968/miniconda3/envs/me/lib/python3.7/site-packages/tedana/workflows/tedana.py", line 475, in _main
    tedana_workflow(**vars(options))
  File "/home/cl968/miniconda3/envs/me/lib/python3.7/site-packages/tedana/workflows/tedana.py", line 320, in tedana_workflow
    manacc = [int(comp) for comp in manacc.split(',')]
  File "/home/cl968/miniconda3/envs/me/lib/python3.7/site-packages/tedana/workflows/tedana.py", line 320, in <listcomp>
    manacc = [int(comp) for comp in manacc.split(',')]
ValueError: invalid literal for int() with base 10:

Here are my questions 
1) I dont think I understand the differences between --manacc and --ctab and why they are required together. --ctab is a list of precomputed (manual or otherwise) classifications. So, isnt it redudant to also have --manacc? Maybe I am missing something. 

2) It is not clear to me if in --manacc the first component should be listed as 0 or 1. 

3) I have tried different versions of what I imagine a comma separated list of components should look like based off of the documentation (see attached) but i keep getting the error pasted above. Any ideas re: what I am missing?

Thank you 
[manacc_v1.txt](https://github.com/ME-ICA/tedana/files/3173672/manacc_v1.txt)
[manacc_v2.txt](https://github.com/ME-ICA/tedana/files/3173673/manacc_v2.txt)

**Comment by cjl2007** [comment]
It just occurred to me that I am assuming that --manacc is provided as a path to a .txt file containing a comma separated list ... I just tried again and it works if I provide the comma separated list as the input directly (like one specifies the echoes) ... sorry about that!

**Comment by emdupre** [comment]
Sorry about that, @cjl2007 ! This means we should definitely improve the documentation. It'd be great to get your insight on what we can improve, particularly here: 

https://github.com/ME-ICA/tedana/blob/624295f4055e1f6339a73086c5775569b2de305f/tedana/workflows/tedana.py#L87

We also might want to add a note about `manacc` in the Read the Docs (RTD) site; I'd think [somewhere around here](https://tedana.readthedocs.io/en/latest/approach.html#tedica). Curious what others (@tsalo, @dowdlelt) think !

Also, regarding your question of 0 vs 1 indexing -- we're expecting 0 indexing. This is something else that can clearly be improved in the docs :) For how it's implemented, see: 

https://github.com/ME-ICA/tedana/blob/624295f4055e1f6339a73086c5775569b2de305f/tedana/selection/select_comps.py#L69

**Comment by jbteves** [comment]
@emdupre I know this is closed but I don't think this is a useful error message; may I open an issue to have that message be more helpful?

**Comment by emdupre** [comment]
No need to ask me ! But that sounds great :+1: Thank you !

**Comment by cjl2007** [comment]
Just wanted to follow up this question with another question, and a potential suggestion, for what its worth. 

My understanding is that when specifying some manual classifications of ICA components, tedana requires both a --ctab (eg. "comp_table_ica.txt") and --manacc ("0,1,2,3...") argument. 

I initially thought that the list provided to --manacc was only for accepted components (as the name suggests). But it seems that these are literally the only components that will be retained.  In other words, the components classified as "ignored" in the --ctab file are now rejected. 

If this is all true, I would suggest changing "--manacc" to something like "--retained". To make it clear that  the user needs to provide a list of all components  that you do not want to reject/discard (both accepted and ignored).

If I am mistaken, please feel free to correct me!
