### ISSUE TITLE
Reorganize package

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#30]
Here is the proposed structure, from conversations on [gitter](https://gitter.im/ME-ICA/tedana):

- `tedana.workflows`: Common pipelines combining functions/classes for performing TE-dependent analysis
    - `tedana.workflows.t2smap`: Fit monoexponential decay curve to each voxel, estimating S0 and T2*, and then optimally combine echoes based on T2* estimate.
- `tedana.io`: File IO functions/classes
- `tedana.model`: Model fitting
    - `tedana.model.t2sadmap`
    - `tedana.model.fit`
    - `tedana.model.optcom`
- `tedana.decomposition`: Functions/classes for decomposing multi-echo data
    - `tedana.decomposition.tedica`
    - `tedana.decomposition.tedpca`
- `tedana.selection`: Component selection functions/classes
    - `tedana.selection.characterize`: Component characterization (in terms of TE-dependence and -independence)
    - `tedana.selection.select_components`
- `tedana.qc`: Quality control functions/classes
- `tedana.report`: Report generation
    - `tedana.report.static_report`
    - `tedana.report.interactive_report`
- `tedana.utils`: Miscellaneous utility functions

**Comment by emdupre** [comment]
Started in #35 ! I made two horrible typos and lost a few hours figuring that out, but I'm hoping to get this done tonight 🕵️‍♀️

**Comment by tsalo** [comment]
Is it considered awkward or bad form to include submodule-specific utils? E.g., not just `tedana.utils`, but also `tedana.model.utils`, `tedana.select.utils`, etc.?

**Comment by tsalo** [comment]
I think that, in its current form (i.e., 1-2 files per submodule), @rmarkello is probably right, but I also think it depends on how much `tedana` will grow. The submodules `decomp`, `model`, and `select` are going to include potentially many more methods in the future, so I think that the current organization is just preparing for that. Then again, if it turns out that not many new methods will be added, then this organization could be a bit much.

**Comment by rmarkello** [comment]
I agree that this is setting up the room for growth (which is definitely a good thing!), but I don't know if it needs to be quite so fragmented. 

Is it possible that `decomp`, `model`, and `select` could all go under one submodule: `modeling`? And it might be reasonable to move `io` to the `utils` submodule. I was thinking something like:

* `tedana.modeling`
    * `tedana.modeling.model`
    * `tedana.modeling.decomposition`
    * `tedana.modeling.select` -- this could potentially be a sub-module as well!
* `tedana.utils`
    * `tedana.utils.io`
    * `tedana.utils.utils`
* `tedana.workflows`
    * `tedana.workflows.tedana`
    * `tedana.workflows.t2smap`
* `tedana.cli`
    * `tedana.cli.run`

`tedana.modeling` could potentially get its own `utils.py`, if needed.

**Comment by tsalo** [comment]
@rmarkello Here's what I started playing with on my fork:
- `tedana.model`
    - `tedana.model.monoexponential`: contains `fit_decay` and `fit_decay_ts`
    - `tedana.model.fit`: contains `fitmodels_direct` and associated functions, minus the `getelbow` functions
    - `tedana.model.combine`: contains `make_optcom`
- `tedana.decomposition`
    - `tedana.decomposition.eigendecomp`: contains `tedpca` and `tedica`
    - `tedana.decomposition._utils`: contains `eimask`
- `tedana.selection`
    - `tedana.selection.select_comps`: contains `selcomps`, to be broken into separate functions
        - Also might need a better name, to distinguish it from other potential selection methods (if anyone has any they want to contribute)
    - `tedana.selection._utils`: contains the `getelbow` functions, because I think they belong here, rather than in `tedana.model`

My assumption was that `tedana.decomposition` would be getting new methods first, given the OHBM abstract @handwerkerd shared on Gitter, which could excuse its current anemic state.

I know that this makes it even more fragmented, although I think it would make it easier to add new methods to the package and also would prevent clutter in individual files.

I agree that `io` should definitely be in `utils`.

@emdupre @rmarkello Do you have any thoughts on preferred script size limits (in terms of lines) for the package? That could probably inform some of this, especially if we can get an idea of how many new functions will ultimately be added.

**Comment by emdupre** [comment]
I like this, @tsalo ! You're definitely right that modules should have full names, like `decomposition`, though it pains me to type that much 😆 

In terms of script size limits, I think `selcomps` is around 500 lines, so smaller than that is a good rule for me. Does anyone else have a preference ?

**Comment by rmarkello** [comment]
@tsalo I think that seems reasonable for now. Are you planning on making a PR to master with your organization schema? I'd love to start working with it!

@emdupre 500 lines seems a good heuristic, too, assuming we're excluding doc-strings!

**Comment by emdupre** [comment]
:+1: yes, extensive docstrings are encouraged ! No need to have them count against us in our "500 line limit."

**Comment by tsalo** [comment]
@rmarkello, I just opened #42 with the potential new organization schema. Hopefully it won't break everything.

**Comment by KirstieJane** [comment]
This conversations makes me SO HAPPY! Especially the long docstring part 😍😍😍

Is it useful to capture some of the philosophy in the CONTRUBUTING.md file so it’s remembered for the future?

**Comment by emdupre** [comment]
Closed with #42 ! The adding contributing documentation suggested by @KirstieJane has been started in #43 🎉
