### ISSUE TITLE
Use overall signal decay in adaptive mask creation

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#312]
### Summary
As discussed in #113, one possible improvement to the `make_adaptive_mask` function would be to flag echoes where the mean signal for that voxel fails to decrease from one echo to the next. This can be done in conjunction with the current method, rather than as a replacement.

### Additional Detail
There are probably a lot of ways in which we can improve this first pass (e.g., not using the mean, setting tolerances for the differences, etc.).

### Next Steps
- [ ] Discuss this method
- [ ] If we want to move forward with it, implement the method in `make_adaptive_mask`

**Comment by dowdlelt** [comment]
I like this idea - in addition, if we were to use more advanced methods (ie more computationally demanding methods) for fitting decay it would be important to remove these bad voxels from consideration as well (or at least know about them). 

Would this idea propose excluding those voxels entirely? Such that there are holes in the brain? That might could cause some issues..

**Comment by tsalo** [comment]
@dowdlelt Sorry, somehow I never saw your response. It does look like some voxels in CSF are flagged with only one good echo, but I think that's okay. I haven't seen any cases with holes in gray or even white matter.

**Comment by jbteves** [comment]
Hm, I'd be interested in doing this as it also incorporates some of @smoia's requests RE: echo order. If this metric tells us all voxels do that, it probably means that the wrong echo order was supplied.
