### ISSUE TITLE
Calculation of variance explained appears wrong

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#317]
### Summary
Variance explained and normalized variance explained are calculated within [dependence_metrics](https://github.com/me-ica/tedana/blob/65f89e1/tedana/model/fit.py#L21) for PCA and ICA components. However, variance explained is also directly returned by the PCA-fitting method, and the varex values from the original method are different from the ones calculated by our function.

### Additional Detail
Here is where we calculate variance explained and normalized variance explained in `dependence_metrics`:
https://github.com/ME-ICA/tedana/blob/65f89e1629bfddcf7f01a91ccb052440a6c22ea4/tedana/model/fit.py#L152-L154

The values are not very similar (for example, for PCA the "real" varex might be 37.8%, while the estimated varex is 57.6% and the estimated normalized varex is 53.8%), but they _are_ highly correlated across components.

**Comment by jbteves** [comment]
Thanks for bringing this up. When you say that the variance explained is highly correlated across components, do you mean that the variance explained appears to at least grow with the amount of variance that a component is purported to explain?

**Comment by tsalo** [comment]
I guess you could say that. The values differ by calculation method, but are correlated across methods.  I have high confidence in one method, but it only works for PCA, so I think we need to either come up with a more accurate method to implement in `dependence_metrics` or to figure out how to calculate variance explained for ICA specifically (i.e., in `tedica`) so we can use the "official" version for both decompositions.

**Comment by tsalo** [comment]
We can calculate voxel-wise variance explained and then average it across voxels to get an estimate of component-wise variance explained. These values are very similar to the PCA-based variance explained values, and can be calculated for both PCA and ICA.

Here's what the code could look like in `dependence_metrics`:
```python
tsoc_dm = tsoc - np.mean(tsoc, axis=-1, keepdims=True)
totvar = np.var(tsoc_dm, axis=1)
...
LGR.info('Fitting TE- and S0-dependent models to components')
for i_comp in range(n_components):
    comp_pred_data = np.dot(mmix[:, i_comp:i_comp+1], tsoc_B[:, i_comp:i_comp+1].T).T
    compvar = np.var(comp_pred_data, axis=1)
    comptable.loc[i_comp, 'variance explained'] = np.mean(compvar / totvar)
```

Otherwise, I can sort of see the logic behind using parameter estimates as a proxy for variance explained, since the IVs (mixing matrix) are all supposed to be z-scores, but I think it would only make sense if the data was also z-scores. I also don't know why we have separate "variance explained" and "normalized variance explained" values.

**Comment by tsalo** [comment]
Since "normalized variance explained" is only used within the PCA decision tree, and "variance explained" is only used within the ICA decision trees (both v2.5 and v3.2), I propose that we merge the two. As mentioned above, I don't know what the conceptual difference is between the two measures- they both sum to standardized values (100 or 1)- and they at least appear interchangeable.

**Comment by tsalo** [comment]
Okay, so it looks like squared parameter estimates do match up to variance explained, but only if both the DVs and the IVs have unit variance (which I believe means that the parameter estimates are actually beta values). If we z-score the mixing matrix and the optimally combined data within `kundu_fit`, and then square the resulting betas, we'll have voxel-wise estimates of variance explained. We can then just average them across voxels to get a variance explained value per component. I think this is a bit simpler than the method I described above.

**Comment by emdupre** [comment]
Do we have a PR open for this ?

**Comment by tsalo** [comment]
No PR. I don't know enough about variance explained in ICA to be sure about my conclusions. I was hoping that others could weigh in on it before trying to change it in tedana.

**Comment by emdupre** [comment]
I'd say we could roll this into #84 . Maybe once we document what we're doing it will be clearer if we need to change it ?
