### ISSUE TITLE
Add boilerplate generation to tedana workflow

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#330]
### Summary
It would be a great feature if we could output a citable boilerplate (a la fMRIPrep) when running tedana. This would be a full paragraph describing the inputs, steps taken, and including citations for relevant works.

### Additional Detail
I see a couple of ways forward on this. The harder (but potentially more extensible) approach would be to convert our functions to classes, as is done in fMRIPrep, and to incorporate some kind of attribute with the description of the step into each class. The paragraph can be built by compiling the classes' descriptions in sequence with the workflow. The other, definitely easier approach would be to have a long string that we can format based on inputs. If we want to incorporate run information (e.g., number of components), we can also include information from the run file. I don't think I'd recommend this, because it would mean having a different boilerplate for each run of data. That information can go in a table or something if people really want to report it.

### Next Steps
- [x] Write format-able workflow description string.
- [x] Format string with workflow inputs (after any conflicts are resolved).
- [x] Output formatted string to boilerplate file in tedana output directory.

**Comment by jbteves** [comment]
How does this interplay with `duecredit`? If we do this then having both seems redundant, unless I'm misunderstanding the above.

**Comment by tsalo** [comment]
It's an alternative to `duecredit` for those who don't want to use it. `duecredit` should generate BibTeX entries (from what I recall), so that's great to import into a manuscript if you want, but if you don't want to write up what tedana did and are fine importing the references yourself based on their citations, then you can use the boilerplate.

**Comment by jbteves** [comment]
I see, that makes sense, thanks for the clarification. Is it actually that much more work to generate a BibTeX reference and eschew the package and its warning entirely? Presumably we only have to add a new reference every time we add a citation, so if the overhead is high then presumably we've managed to worm into a great problem.

**Comment by tsalo** [comment]
It's definitely doable.

**Comment by jbteves** [comment]
Do you mind rewriting or letting me edit the above to make a task list? (Maybe I should change the template so that happens by default).

**Comment by tsalo** [comment]
Absolutely, feel free.

**Comment by emdupre** [comment]
I'm reticent to convert everything to classes -- they can be great, but inheritance can be an odd beast to work with particularly in learning a new codebase. I'd be happy to do it as things make sense, but I don't want this to be the motivating factor.

What would you think about moving forward with the second approach you outlined, at least for now ? I do think a boilerplate would be useful !

**Comment by tsalo** [comment]
Here's a first draft. Please let me know what you all think:

Input:
```
dset_dir=/Users/tsalo/Documents/tsalo/tedana-comparison/sandbox/e5_data

tedana -d ${dset_dir}/sub-01_ses-09_task-flashingcheckerboard_run-01_echo-1_desc-preproc_bold.nii.gz \
  ${dset_dir}/sub-01_ses-09_task-flashingcheckerboard_run-01_echo-2_desc-preproc_bold.nii.gz \
  ${dset_dir}/sub-01_ses-09_task-flashingcheckerboard_run-01_echo-3_desc-preproc_bold.nii.gz \
  ${dset_dir}/sub-01_ses-09_task-flashingcheckerboard_run-01_echo-4_desc-preproc_bold.nii.gz \
  ${dset_dir}/sub-01_ses-09_task-flashingcheckerboard_run-01_echo-5_desc-preproc_bold.nii.gz \
  -e 15.4 29.7 44.0 58.3 72.6 --debug --seed 8 \
  --out-dir /Users/tsalo/Documents/tsalo/tedana-comparison/sandbox/temp4
```

Boilerplate:

> TE-dependence analysis was performed on input data. An initial mask was generated from the first echo using nilearn's compute_epi_mask function. An adaptive mask was then generated, in which each voxel's value reflects the number of echoes with 'good' data. A monoexponential model was fit to the data at each voxel using log-linear regression in order to estimate T2* and S0 maps. For each voxel, the value from the adaptive mask was used to determine which echoes would be used to estimate T2* and S0. Multi-echo data were then optimally combined using the t2s combination method. Principal component analysis using MLE dimensionality estimation (Minka, 2001) was applied to the optimally combined data for dimensionality reduction. Independent component analysis was then used to decompose the dimensionally reduced dataset. A series of TE-dependence metrics were calculated for each ICA component, including Kappa, Rho, and variance explained. Next, component selection was performed to identify BOLD (TE-dependent), non-BOLD (TE-independent), and uncertain (low-variance) components using the Kundu decision tree (v2.5; Kundu CITATION).
> 
> References
> 
> Posse, S., Wiese, S., Gembris, D., Mathiak, K., Kessler, C., Grosse‐Ruyken, M. L., ... & Kiselev, V. G. (1999). Enhancement of BOLD‐contrast sensitivity by single‐shot multi‐echo functional MR imaging. Magnetic Resonance in Medicine: An Official Journal of the International Society for Magnetic Resonance in Medicine, 42(1), 87-97.
> 
> Minka, T. P. (2001). Automatic choice of dimensionality for PCA. In Advances in neural information processing systems (pp. 598-604).
> 
> Kundu CITATION

**Comment by jbteves** [comment]
I think this is a fantastic start, thanks @tsalo . What's missing for the Kundu Citation, or is that just a stand-in for the info already in `duecredit`?

**Comment by tsalo** [comment]
We didn't have a citation implemented for the component selection decision trees with duecredit. I've added the Kundu et al. (2013) citation (thanks @smoia) to the boilerplate.
