### ISSUE TITLE
Add ability to denoise data using existing component table

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#334]
### Summary
We currently support manual identification of accepted components (and could easily extend to rejected components) using comma-separated lists of components. However, additional decision trees (e.g., AROMA) could easily operate by overwriting the original component table with updated classifications. We should be able to simply run tedana with a component table (which may have updated classifications) without a separate list of classifications.

### Additional Detail
This will impact our internal logic regarding component tables, the mixing matrix, and `manacc` (and possibly a future `manrej`). It could also be a separate post-`tedana` workflow, if needed.

### Next Steps
- [ ] Vote on whether to implement this as a post-tedana workflow or within tedana.
- [ ] Add new workflow or adjust tedana workflow.

**Comment by jbteves** [comment]
My intuition is that you would want it to be a post-tedana operation since I would assume you at least want the PCA denoising and optimal combination before you run AROMA. That could be wrong, though, since I don't work with other ICA routines.

**Comment by dowdlelt** [comment]
I imagine a post-tedana workflow where you provide it with the table and tedana output directory, and it creates a new output directory, applying the new classifications, regenerating the denoised data, noise component timeseries for inspection, etc.

**Comment by emdupre** [comment]
I like the idea of incorporating it into tedana in that it'd be great to be able to just update the classification table instead of providing a list to `manacc`. I personally find using manual classification really clunky right now, and I'd prefer to let users supply a new table. 

Not a strong preference, since there are other ways we could update `manacc`, but just my 2c !

**Comment by emdupre** [comment]
Is this related to #407 or #344 ?

**Comment by tsalo** [comment]
More #407 than #344. #407 should make it possible to denoise data the _exact_ same way as the original denoising using the existing workflow. In its current form, even with a mixing matrix and component table provided, T2* estimation and optimal combination will still be performed from scratch. Both are deterministic, so in practice this isn't a problem, but still...

**Comment by tsalo** [comment]
I think this should have been closed by #508 🤦‍♂
