### ISSUE TITLE
Add documentation page with info linking to other multi-echo denoising software

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#336]
At the OHBM 2019 Meeting, we received feedback that tedana's readthedocs info might be useful to all multi-echo users, but not all efforts to do multi-echo denoising will end up in tedana in the near future or ever. The suggest was to make a page our documentation where summaries of other available options and links to those options can be shared.

### Next Steps
1. Make a page where this info can be added.
2. Make stub paragraphs for currently available options
3. Invite others to contribute more information.

**Comment by tsalo** [comment]
A partial list from the [meeting notes](https://docs.google.com/document/d/1wtOBKmKjQzmFpyo5V2a9n9ejtl2nCeHt3cQ63SdTHXc/edit):
- [3dMEPFM](https://afni.nimh.nih.gov/pub/dist/doc/program_help/3dMEPFM.html) (with multivariate version coming out next year)
- Bayesian approach uses the noise structure across time take advantage of priors and not use ICA. [OHBM 2019 poster M868](https://ww5.aievolution.com/hbm1901/index.cfm?do=abs.viewAbs&abs=5026)
- Group ICA applied to multi-echo data. [OHBM 2019 poster W337](https://ww5.aievolution.com/hbm1901/index.cfm?do=abs.viewAbs&abs=1286)
- Dual echo imaging by Molly Bright
- Beamforming by Pieter Buur: [paper](https://ieeexplore.ieee.org/document/4740318) and [thesis](https://repository.ubn.ru.nl/bitstream/handle/2066/91291/91291.pdf)
- MATLAB tool by Rasim Boyacioglu when at Donders
- Rasmus working with rapid imaging people to create a 3d radial acquisition to potentially create multiple echoes from parts of the k space that was acquired
- Martin Havlicek biexponential model taking information in the data to model the curves directly

**Comment by jbteves** [comment]
Do we have contacts for these people? If so, how would you feel about asking them to just contribute a sentence for use on the page? That way each group gets to choose how it's represented on it.

**Comment by emdupre** [comment]
That sounds like a great idea. If we have a stub of a page to point them to, I think that would help !

**Comment by jbteves** [comment]
Please chime in on #343 if you have opinions about how we should request these contributions and how we should manage them.

**Comment by emdupre** [comment]
Is this addressed in #419 ?

**Comment by emdupre** [comment]
Pinging @dowdlelt @mvaziri !

**Comment by emdupre** [comment]
Closed via #419.
