### ISSUE TITLE
Stop writing __meica_mix.1D

### ISSUE THREAD

**Issue by jbteves** [ME-ICA/tedana#339]
### Summary
Per discussion in #338 there is no reason to continue writing __meica_mix.1D, and it is confusing to keep since there is a similarly named output. We should deprecate writing this file. 

### Next Steps
- [x] Stop writing the file
- [x] Remove file reference from readthedocs "Outputs of tedana"

**Comment by tsalo** [comment]
Could you add "remove file description from **Outputs of tedana** page" to the Next Steps? I think that those two things are all we need to do.
