### ISSUE TITLE
Spatial info for surface data

### ISSUE THREAD

**Issue by rmarkello** [ME-ICA/tedana#34]
There are a few points throughout `tedana.py` where spatial information is required. Namely:

1. `tedana.interfaces.tedana.fitmodels_direct()`
2. `tedana.interfaces.tedana.spatclust()`
2. `tedana.interfaces.tedana.selcomps()`

The function `fitmodels_direct()` calls `spatclust()` to do spatial clustering on the independent components generated from ICA. While spatial clustering is possible with surface data, it would require information about the location of the vertices in 3D space; this info is generally kept in a separate datafile. We could maybe ask users to provide that file if they want spatial clustering to occur?

On the other hand, the function `selcomps()` makes a call to `np.fft.rfftn()`, which operates over the 3D volumetric data to detect high-spatial frequency artifacts. Figuring out how to get this working with surface-based data (or indeed, if it is even reasonable to do so) is up for debate.

Relatedly, there are a few other steps in `selcomps()` where surface data may run into issues (e.g., with generating the vein masks) that will require some thought.

**Comment by emdupre** [comment]
I think the only path forward for this is to either ask users to provide their surface information, or to ship `tedana` with the most common surface templates, or both.

Is there a preference on which surfaces we could ship with ? I'd say `fsaverage`, `fsaverage5`, and `fsaverage6`, but would love to hear other opinions !
