### ISSUE TITLE
Change Issue Template to encourage keeping up-to-date summaries

### ISSUE THREAD

**Issue by jbteves** [ME-ICA/tedana#357]
We should change the issue template to reflect that we'd like to keep top comments up-to-date. 

### Additional Detail
I would propose that we keep the 1-2 sentence summary unheadered, keep additional detail, and then make "Summary" a heading underneath that which appends notes as the issue is discussed further. 

### Next Steps
- [ ] Draft issue template

**Comment by jbteves** [comment]
Above is a rendering of what the new template would look like, before appending new info.

**Comment by tsalo** [comment]
I've been thinking about this a bit. I think I'd like to see the overall summary at either the top or the bottom, to make it easier to find. Also, what if we had "Issue Summary" or "Description" for the initial description and "Thread Summary" for the final summary?

**Comment by emdupre** [comment]
:+1: to having the summary at the top ! I think updating the issue template is a great idea -- thanks, @jbteves !

**Comment by jbteves** [comment]
WDYT about the format above?

**Comment by emdupre** [comment]
I think this can be closed ! We've updated the issue template to follow this format :rocket:
