### ISSUE TITLE
Next call: 24th of July, noon EST, 17h BST, 18h CEST

### ISSUE THREAD

**Issue by smoia** [ME-ICA/tedana#359]
Let's build the agenda for the next call, on the 24th of July 2019!
Meeting at 12h00 EST, 17h00 BST, 18h00 CEST (anyone else?).

From gitter, the main points are:
 - How testing should be written for new PRs (issue number?)
 - How to edit the docs for the API, and how the API docs should be structured (#343 ?)
 - Some confusion about how some of the math works in various signal estimations (#352 )
 - Dimensionality Reduction (#356 )

Is it ok? Would you rather talk about something specific/else?

**Comment by jbteves** [comment]
Thanks for bringing this up and writing the agenda, @smoia! Now that the call has happened let's go ahead and close this.
