### ISSUE TITLE
Tip in the doc to write the logs in a file

### ISSUE THREAD

**Issue by benoitberanger** [ME-ICA/tedana#361]
### Summary

To save the logs (outputs in the terminal), I use the same strategy described in `afni_proc.py` : 

`tedana [...] 2>&1 | tee $outdir/tedana.log` (if you use bash)

What do you think if this tip could be written in the *readthedocs* & the *README.md* ?

### Additional Detail

I'm trying `tedana` with different datasets based on different sequences, populations of subjects, activation tasks & resting-state. 

The complete log is written into this `tedana.log` file, and I can parse it latter to check, depending on the *tedpca* strategy chosen, the number of components selected (even if I can have it with `comp_table_pca.txt`), and more importantly if the ICA failed to converged after reaching the maximum iterations attempts.
Parsing `comp_table_ica.txt` gives me the number of accepted/ingored/rejected components.

On our computing cluster which uses *slurm* so it's possible to use an option to redirect stdout and stderr into a files for diagnostic. However I found it's more convenient to have a log of `tedana` in the $outdir.

**Comment by tsalo** [comment]
You should be able to use `--debug` to get the log in a text file.

**Comment by benoitberanger** [comment]
Oh I see ! And the option also write the timestamp, that's wonderful.
I didn't see the option, its not on the docs, the readme.md, and does not appear when you just check the help printed when you write `tedana` <enter>.

Is there a reason this option is a bit "hidden" ?

**Comment by tsalo** [comment]
You're right. For some reason we're suppressing the help message for that option at the moment. I'm not sure why, but that's something we will definitely fix. @emdupre @jbteves do you have a preference for how we should change this? Should be just make `--debug` visible or should we separate log file generation from the logging level (DEBUG) set by `-debug`?

**Comment by jbteves** [comment]
We should probably have a log file made by default and a verbose flag instead. Sorry I never followed up on this.

**Comment by emdupre** [comment]
Commented in #385 -- and now I see where the discussion (that I said I missed) happened ! Too many GitHub notifications :sweat_smile:

**Comment by jbteves** [comment]
Okay, I have a proposal that I think will address everybody's concerns surrounding the logfile:
1. We make a logfile appear on every run
1. We make a logfile, perhaps `tedana_YYYY-MM-DDTHH:MM:SS.log` (the ISO datetime format)
1. We IGNORE the logfile in circleci harvesting BUT
1. We create a testing module which verifies that running `tedana` generates the appropriate log information.
This way we will have a logfile which is always tested AND which is easy to extract in slurm. We could also add further clarifying details at the top of the file in the case of massively parallel jobs.
@benoitberanger @emdupre @tsalo WDYT?

**Comment by jbteves** [comment]
Update: this won't work because you still have to specify a file. I'll update #391 to just use the right `grep` and regexp to check that the file is in the right format.
