### ISSUE TITLE
Add information about duecredit to contributing guidelines

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#362]
### Summary
It can be difficult to remember to update duecredit citations when making changes to the code. We should add information about duecredit to the contributing guidelines so people won't forget.

### Next Steps
- [ ] Describe duecredit citation procedure in contributing guidelines.
- [ ] Add reminder in contributing guidelines to check duecredit citations when making changes to the code.

**Comment by emdupre** [comment]
Looks like we need a general update of the contributing guidelines with this and #372 !
