### ISSUE TITLE
Wrong estimation of S0 & T2* maps

### ISSUE THREAD

**Issue by benoitberanger** [ME-ICA/tedana#370]
### Summary

_tedana version == 0.0.7_

Here is, in my mind, a **good** estimation of S0 & T2* maps.
Pic 1 : volume shortest echo
Pic 2 : S0
Pic 3 : T2*

![good](https://user-images.githubusercontent.com/16976839/61710455-04be1380-ad52-11e9-83e7-5273b3fc0e51.gif)

We can notice the negative T2* values in the ventricles, but **it does not matter** as it was noticed in #225 

And here, is a **bad** estimation of S0 & T2* maps.
Pic 1 : volume shortest echo
Pic 2 : S0
Pic 3 : T2*

![bad](https://user-images.githubusercontent.com/16976839/61710469-0982c780-ad52-11e9-8670-0d9ce67ad6d0.gif)

We can notice that the S0 volumes is exactly the first echo masked.

I'm sure the problem comes from the estimation, but I don't know why : 

```
/network/lustre/iss01/cenir/software/irm/python36_anaconda/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/network/lustre/iss01/cenir/software/irm/python36_anaconda/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
INFO:tedana.workflows.tedana:Using output directory: /network/lustre/iss01/cenir/analyse/irm/users/benoit.beranger/eval_tedana/nifti/SUPERMAN/2018_07_20_SUPERMAN_006/S29_Run_5/tedana_afni_kundu-stabilize
INFO:tedana.workflows.tedana:Loading input data: ['/network/lustre/iss01/cenir/analyse/irm/users/benoit.beranger/eval_tedana/nifti/SUPERMAN/2018_07_20_SUPERMAN_006/S29_Run_5/_vte1.nii', '/network/lustre/iss01/cenir/analyse/irm/users/benoit.beranger/eval_tedana/nifti/SUPERMAN/2018_07_20_SUPERMAN_006/S29_Run_5/_vte2.nii', '/network/lustre/iss01/cenir/analyse/irm/users/benoit.beranger/eval_tedana/nifti/SUPERMAN/2018_07_20_SUPERMAN_006/S29_Run_5/_vte3.nii']
INFO:tedana.workflows.tedana:Using user-defined mask
INFO:tedana.workflows.tedana:Computing T2* map

Intel MKL ERROR: Parameter 6 was incorrect on entry to DGELSD.

Intel MKL ERROR: Parameter 6 was incorrect on entry to DGELSD.
/network/lustre/iss01/cenir/software/irm/python36_anaconda/lib/python3.6/site-packages/tedana-0.0.6+13.ge1bc0b6.dirty-py3.6.egg/tedana/decay.py:85: RuntimeWarning: invalid value encountered in log
  log_data = np.log((np.abs(data[:, :echo + 1, :]) + 1).reshape(len(data), -1).T)
/network/lustre/iss01/cenir/software/irm/python36_anaconda/lib/python3.6/site-packages/tedana-0.0.6+13.ge1bc0b6.dirty-py3.6.egg/tedana/decay.py:91: RuntimeWarning: divide by zero encountered in true_divide
  t2s = 1. / betas[1, :].T
INFO:tedana.combine:Optimally combining data with voxel-wise T2 estimates
INFO:tedana.decomposition.eigendecomp:Computing PCA of optimally combined multi-echo data
INFO:tedana.decomposition.eigendecomp:Making initial component selection guess from PCA results
INFO:tedana.model.fit:Fitting TE- and S0-dependent models to components
/network/lustre/iss01/cenir/software/irm/python36_anaconda/lib/python3.6/site-packages/tedana-0.0.6+13.ge1bc0b6.dirty-py3.6.egg/tedana/model/fit.py:173: RuntimeWarning: divide by zero encountered in true_divide
  F_S0 = (alpha - SSE_S0) * (n_echos - 1) / (SSE_S0)
INFO:tedana.decomposition.eigendecomp:Saving PCA results to: /network/lustre/iss01/cenir/analyse/irm/users/benoit.beranger/eval_tedana/nifti/SUPERMAN/2018_07_20_SUPERMAN_006/S29_Run_5/tedana_afni_kundu-stabilize/pcastate.pkl
INFO:tedana.decomposition.eigendecomp:Selected 22 components with Kappa threshold: 8.10, Rho threshold: 21.34
INFO:tedana.decomposition.eigendecomp:ICA attempt 1 converged in 56 iterations
INFO:tedana.workflows.tedana:Making second component selection guess from ICA results
INFO:tedana.model.fit:Fitting TE- and S0-dependent models to components
INFO:tedana.model.fit:Performing spatial clustering of components
Traceback (most recent call last):
  File "/network/lustre/iss01/cenir/software/irm/python36_anaconda/bin/tedana", line 11, in <module>
    load_entry_point('tedana==0.0.6+13.ge1bc0b6.dirty', 'console_scripts', 'tedana')()
  File "/network/lustre/iss01/cenir/software/irm/python36_anaconda/lib/python3.6/site-packages/tedana-0.0.6+13.ge1bc0b6.dirty-py3.6.egg/tedana/workflows/tedana.py", line 460, in _main
    tedana_workflow(**vars(options))
  File "/network/lustre/iss01/cenir/software/irm/python36_anaconda/lib/python3.6/site-packages/tedana-0.0.6+13.ge1bc0b6.dirty-py3.6.egg/tedana/workflows/tedana.py", line 378, in tedana_workflow
    n_echos)
  File "/network/lustre/iss01/cenir/software/irm/python36_anaconda/lib/python3.6/site-packages/tedana-0.0.6+13.ge1bc0b6.dirty-py3.6.egg/tedana/selection/select_comps.py", line 249, in selcomps
    rho_elbow = np.mean((getelbow(comptable.loc[ncls, 'rho'], return_val=True),
  File "/network/lustre/iss01/cenir/software/irm/python36_anaconda/lib/python3.6/site-packages/tedana-0.0.6+13.ge1bc0b6.dirty-py3.6.egg/tedana/selection/_utils.py", line 71, in getelbow
    p = coords - coords[:, 0].reshape(2, 1)
IndexError: index 0 is out of bounds for axis 1 with size 0

```

### Additional Detail

`Intel MKL ERROR: Parameter 6 was incorrect on entry to DGELSD.` seems to come from the cluster execution, I'm waiting for an answer from my colleague who manage the cluster

tedana is installed from a cloned git repo and added to a conda env, this is why the path says 'site-packages/tedana-0.0.6+13.ge1bc0b6.dirty-py3.6.egg/tedana/selection/_utils.py' but it's checkout @ **tag==0.0.7**

I had a problem with the automatic masking embedded in tedana, especially when no bias correction filter was applied (Siemens : Filter > Prescan normalize).
The signal bias was "not taken into account" in the automatic masking of tedana, and tehre was a big hole in the middle of the brain, where the raw signal has lower intensities, due to the distance from the coil elements and the g-factor.
Now I have a robust masking strategy : after minimal preprocessing (tshift + volreg), do a temporal mean of the first echo and apply FSL BET : `bet <in> <out> -R -m -f 0.3`.
It works better than all tests I've made with AFNI's 3dAutomask

Best,
Benoît

**Comment by benoitberanger** [comment]
Correction, it might be tedana version == 0.0.6+13.
Ok sorry guys, I messed up the tedana version, I thought the one on the cluster was the last release -> 0.0.7, exactly the same as I have on local rig. But ot's not the case.

I will re-process the data with last release version 0.0.7 and come back, if the bug persists.

**Comment by emdupre** [comment]
Please do let us know if you see that issue -- I agree, it looks very wrong !

**Comment by benoitberanger** [comment]
Hello again,

I reprocessed the data with the *real* 0.0.7 version (last release at the moment), and things became more interesting.

The same problem of wrong estimation appeared, but only on the computation cluster.
This is the source of the `Intel MKL ERROR`. And when I perform the same computation (same data, same scripts, same version)  I have still the same warning `RuntimeWarning: divide by zero encountered in true_divide F_S0 = (alpha - SSE_S0) * (n_echos - 1) / (SSE_S0)` but the S0 and T2* estimations are good.

I put aside the *Why* this problem happens and tried *How to solve it*.
I noticed the runs where this estimation problems occurred are mostly the ones with the biggest movements, especially spikes of movement.
So I tried to add the **despike** block in afni_proc, because it was performed in the older meica.py wrapper. And this despiking step seems to work ! The components founds, reviewed with the PNG files, seem normal and with a normal balance between accepted, ignored, rejected.

Next step : re-pre-process more datasets by add the despike block, and watch how tedana pipeline behaves.

If anyone else has in idea about where this estimation problem comes from and how it could be solved, that would be wonderful.
But for the moment, I will try this despike solution.

Best,
Benoît

**Comment by jbteves** [comment]
@tsalo @emdupre any thoughts on the above?

**Comment by tsalo** [comment]
Despiking might serve as a good pre-tedana preprocessing step, but I think that it's something we should look into in the planned validation analysis. It would be awesome if we could definitively recommend that as a preprocessing step in our documentation.

**Comment by benoitberanger** [comment]
Hey,

**Despiking** is now activated by default in my pre-processing in _afni_proc.py_.
Here is what I commented in the code, that serves as rule of thumb :

```
TEDANA recomandations :          tshift,        volreg
MEICA pipeline        : despike, tshift, align, volreg
robust for TEDANA     : despike, tshift,        volreg <== default
```
Benoît

**Comment by benoitberanger** [comment]
Hello,

It's been a while !
I never encountered this problem in ~3 years of usage of TEDANA. And v0.0.7 is very old comapred to the cycle of development and release.
Since the problem never occurred, I'm closing the issue.

Best,
Benoît
