### ISSUE TITLE
Add smoke tests for helper files

### ISSUE THREAD

**Issue by monicayao** [ME-ICA/tedana#376]
### Summary
Continuing from issue #335, this issue addresses the smoke tests for files that mainly "help" other files, and less directly involved in the workflow.

### Additional Detail
By smoke tests, there will be a test function that simply asserts that the function, when called on randomly generated inputs in the correct format, will output a non null value. It will be similar to the kundu test.

The files this issue addresses include `stats.py`, `io.py`, and `viz.py` for the functions that have an output. Functions which only generate a file or image are not tested. 

### Next Steps

- [x]  Add smoke test to `stats.py`
- [x]  Add smoke test to `io.py`
- [x] Add smoke test to `viz.py`

**Comment by emdupre** [comment]
Amazing, thanks @monicayao !! So excited to see #377 #378 and #380 opened ! :sparkles: :rocket:
