### ISSUE TITLE
Consider updating repo name

### ISSUE THREAD

**Issue by emdupre** [ME-ICA/tedana#38]
As brought up by @handwerkerd in #12, we've embraced the repo name "tedana" without any real discussion.

I'm fine to keep "tedana" as the the name&mdash; I think expanding beyond ICA is on the horizon, so sticking with ME-ICA (outside of legacy reasons, as captured in the org name), makes less sense. @prantikk, do you have a preference ?

Any other suggestions are welcome !

**Comment by handwerkerd** [comment]
I agree that Prantik's "tedana" name (TE Dependent Analysis) is more generalized that ME-ICA and might make this package more welcoming to a range of analysis methodology directions in the future that are united by asking what we can do with multi-echo acquisitions. For example, some of the stuff @CesarCaballeroGaudes is working on would fit, though I don't know if he wants implement them here in addition to in AFNI. (He's working on a multi-echo version of https://afni.nimh.nih.gov/pub/dist/doc/program_help/3dPFM.html which seems to work a lot better than the single echo version)

I'm open to other name ideas, but "tedana" is a passable name.

**Comment by CesarCaballeroGaudes** [comment]
I agree with Tedana (TE Dependent Analysis). I am planning to integrate 3dMEPFM into AFNI since I'm implementing these algorithms in R and using the AFNIio.R functions. In addition, I am investigating other algorithms that make use of these TE-dependence. If I implemented them in Python, they could be perfectly incorporate it here.

**Comment by emdupre** [comment]
I've assigned this to our 0.0.1 milestone, aka our first release ! 🎉 

Given we'll try to maintain the name we release with (unless exceptional circumstances arise), if anyone has concerns with the current `tedana` name please do share ! I'm hoping we'll release this week 😄

**Comment by KirstieJane** [comment]
I'll just jump in with a :+1: for *tedana* 🎉 I like it!

**Comment by emdupre** [comment]
I think I'm going to go ahead and close this&mdash; it sounds like the consensus is to move forward with _tedana_. Looking forward to our first release ! 🎉 🎉
