### ISSUE TITLE
Nipype-ify workflow and functions

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#394]
### Summary
We have touched on the idea of converting tedana toward an object-oriented approach (e.g., [here](https://github.com/ME-ICA/tedana/issues/330#issuecomment-503653831)), but I wanted to consolidate discussion somewhere.

### Additional Detail
I'd like to discuss the idea of converting functions to interfaces (or of building interfaces for functions while retaining the original functions) and converting the workflows to niworkflows LiterateWorkflows.

### Pros
- Using LiterateWorkflows will make building boilerplates and workflow figures easier and cleaner. I have been working on implementing boilerplates in [NiBetaSeries](https://github.com/HBClab/NiBetaSeries), so I have some fresh experience with this.
- We would move from working on arrays (or images, per #251) to working on files. This could help with memory costs.
- Integration with fMRIPrep and other BIDS Apps would be easier.
- Workflows make resource management easier.
- It should be easier to configure workflows by swapping nodes in and out.

### Cons
- Working on files would possibly slow things down. I really don't know.
- There is a bit of a learning curve when it comes to working with Nipype.
    - We can offset this to some extent by keeping our functions and just adding interfaces instead of replacing the functions with interfaces.
- Debugging workflows can be difficult.

**Comment by jbteves** [comment]
I don't feel great about adding to our learning curve (which is basically a vertical climb already), but I don't think we would see much of a memory impact on a modern SSD machine, so I don't think that's a concern with this approach. I would be concerned about adding complexity or tying ourselves to a particular workflow.   
I would agree that configuring workflows would be dramatically simplified by mostly operating on files, and this is the approach I've selected for an unrelated project. This also means that you could allow people to resume workflows partway through (maybe they want to manually inspect their T2* map before running PCA/ICA, for example).

**Comment by eurunuela** [comment]
Creating interfaces will definitely make tedana more user-friendly. However, I would not replace functions with interfaces, as more pro users will want to have more control over what they're doing.

Regarding the idea of working with files, it will definitely make a positive impact on memory management. Will it make tedana slower? It will depend on how often we want to read and write entire files. I'd go for it but we should be smart about it and optimize the code, e.g. maybe not all calculations need an entire file to be loaded but just a column of the matrix.

I have never read about Workflows in Python, could you please tell us more about it? A website we can read to have an idea maybe?

However, I would focus on solving the main bugs and modularizing tedana before working on anything else.

**Comment by emdupre** [comment]
> There is a bit of a learning curve when it comes to working with Nipype.

The original intention of tedana was to adopt Nipype, but there was no need once we converted everything to pure python. I'm hesitant to give up that gain, and I'd encourage us to avoid bringing in external packages for as long as possible.

As is, I don't see the need for a true Nipype workflow with only python nodes. I think we're likely to see performance take a hit, and you've already (very successfully, I think !) started on a boilerplate in #330.

**Comment by tsalo** [comment]
Okay, sounds good. Closing now.
