### ISSUE TITLE
Set numpy minimum version to 1.14

### ISSUE THREAD

**Issue by effigies** [ME-ICA/tedana#395]
### Summary

Looks in #141 it was established (https://github.com/ME-ICA/tedana/issues/141#issuecomment-430445785) that tedana requires a minimum numpy of 1.14, but this isn't specified in the requirements:

https://github.com/ME-ICA/tedana/blob/94b9275e6707641a0d97f4463fc13901dfe73c9f/tedana/info.py#L30-L39

This leads to situations like poldracklab/fmriprep#1782, where old numpy versions are not being upgraded because there is no metadata setting this requirement.

### Next Steps

If 1.14 is still considered the appropriate minimum version, I can open a PR setting the constraint.

It's also a good idea to run tests on your stated minimum versions to make sure that there aren't bugs hiding on the low range. If you like, I can help set up Travis or Azure, which are better suited to a parametric build matrix. This one might take a little more time, though.

**Comment by emdupre** [comment]
That (and #396) would be great, thank you ! :sparkling_heart: 

We had a build-matrix in Travis (that @tsalo converted to CircleCI), but it was systematically testing python rather than package versions. That's definitely something we should be doing, but we can open a separate issue for that.
