### ISSUE TITLE
Brainstorming: "I want to learn" Hackathon 2019

### ISSUE THREAD

**Issue by jbteves** [ME-ICA/tedana#399]
### Summary
All developers attending the hackathon, please comment with things you would like to learn more about at `tedana`'s 2019 hackathon.

**Comment by jbteves** [comment]
I would like to learn more about:
- the metrics for which ICA components should be kept  
- how the testing environment is configured and how we can edit it
- how the different t2* fitting methods work

**Comment by dowdlelt** [comment]
For me, as a start. 

* 2nding metrics about ICA component selection
* adding new metrics, methods
* what is all this talk about modularization and how does that interact with the point above
* why is some code in folders, others not
* Conceptual and practical understanding of testing/code coverage?
* what is a workflow, why so many '__' everywhere

**Comment by smoia** [comment]
- 2nding @dowdlelt in understanding the organisation of the code
- Where does this version of the code diverge from the last paper containing tedana's workflow (I guess Kundu et al. 2013), and why
- What is this CircleCI thing and testing.

**Comment by tsalo** [comment]
Should we close this now that the hackathon is over?

**Comment by dowdlelt** [comment]
I feel like the hackathon did a pretty good job at answering a lot of my questions, and when it didn't, it gave me enough information to figure things out. I vote close!
