### ISSUE TITLE
Brainstorming: specific testing questions

### ISSUE THREAD

**Issue by jbteves** [ME-ICA/tedana#400]
### Summary
For the 2019 hackathon, please comment on testing questions you have so that we can attempt to address them ahead of the hackathon.

**Comment by jbteves** [comment]
- How do you adjust CircleCI configs for entirely new tests?
- How do you examine CircleCI artifacts?
- How do you get CircleCI to allow logging? (it appears to be disabled by default)
- What types of synthetic data should we be generating for testing?

**Comment by handwerkerd** [comment]
At the hackathon, we're going potentially have multiple people working on larger-than-usual portions of the code at the same time and submitting PRs. How should we keep track of everything both with regard to GitHub and adding tests?

**Comment by jbteves** [comment]
@handwerkerd we should probably bring that up on the next call. My intuition is that we'll just have people also write tests for any code they submit.

**Comment by handwerkerd** [comment]
Just to be clear, there's a logistical part to this, but also an educational part. I think we need to decide the logistical part at the next call, but whatever we decide, we'll want a guide or an explanation for the less advanced git and CI users. I suspect this will be more than just following our standard contributors' guide.

**Comment by jbteves** [comment]
I see, that makes sense.

**Comment by emdupre** [comment]
I'm going to close this as it seems to duplicate #268, at this point. 

Please re-open if you disagree !
