### ISSUE TITLE
Tedana multi echo data processing : fMRIprep outputs

### ISSUE THREAD

**Issue by sameera2004** [ME-ICA/tedana#404]
Hi @tsalo and @dowdlelt,

I have a question regarding the TEDANA output from fMRIprep pre-processed data on Neurostars. 

Here I am attaching the TEDANA output.

![dn_ts_OC](https://user-images.githubusercontent.com/5701652/65796799-8ad44d00-e13b-11e9-9340-f4509a586c63.png)

https://neurostars.org/t/tedana-multi-echo-data-processing-fmriprep-outputs/5133/2
 Why do some parts of the brain are missing in TEDANA output?

I have attached inputs I used and TEDANA output and the command I used on Neurostars.

Thank you
Sameera

**Comment by emdupre** [comment]
Thanks, @sameera2004 ! I followed up on NeuroStars and will close here, so as not to duplicate conversations.
