### ISSUE TITLE
Add Test to Check .BRIK/.HEAD compatibility

### ISSUE THREAD

**Issue by jbteves** [ME-ICA/tedana#412]
Add a test to check BRIK/HEAD compatibility.

**Comment by emdupre** [comment]
Is this related to adding AFNI data to OSF ? cc @afni-rickr

**Comment by jbteves** [comment]
@afni-rickr has confirmed that .BRIK.gz and .BRIK provide identical results. Still need to add tests.

**Comment by jbteves** [comment]
@emdupre yes

**Comment by afni-rickr** [comment]
Just to add details, that uploaded dataset is identical to the NIFTI version, but in AFNI format and no longer stacked.  So I gave it (the 3 AFNI datasets) to afni_proc.py to run tedana on.  gzip'ing the BRIKs and re-running tedana produced identical (no diff) NIFTI results.  Thanks!
