### ISSUE TITLE
Add third integration test using four-echo event-related dataset

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#444]
### Summary
We can increase coverage some more with a third integration test.

### Additional Detail
Per an idea by @jbteves, we can cover BRIK/HEAD support with a new test, plus this will give us resting state, block design, and event-related design tests, if we use the FIU four-echo event-related dataset [here](https://osf.io/c4awb/). The dataset is also BIDS-compatible.

### Next Steps
1. Truncate dataset to 75 volumes.
2. Convert to BRIK/HEAD.
3. Upload to relevant folder on OSF.
4. Write integration test that uses the dataset.
    - What parameters do we want?
    - kundu-stabilize PCA (at least until GIFT is merged)
    - curvefit
    - lowmem
    - tedort
    - Include a second tedana call with manacc and other relevant inputs.

**Comment by jbteves** [comment]
In fairness, it was actually @dowdlelt's idea to test BRIK/HEAD data, and @afni-rickr upped it to BRIK.gz as an idea.

**Comment by tsalo** [comment]
Per in-person discussion with @jbteves, the results from the truncated event-related dataset do not look good. He is still planning to add an integration test using the four-echo data, but using the block-design run instead of the event-related one.

**Comment by emdupre** [comment]
Can you explain a little what "look good" means here ?

**Comment by tsalo** [comment]
I don't know the details but I assume that there didn't end up being any components that looked like the events.

**Comment by jbteves** [comment]
No, it was just selecting way too many components in PCA even with the `kundu` option, it was taking N-1 TRs for it. I suppose if there are event-looking components it might still be okay. I have the data on standby.

**Comment by emdupre** [comment]
Can we try it with #435 and see if it's still selecting too many components ? Curious if this is dataset specific.

**Comment by tsalo** [comment]
Closed by #482.
