### ISSUE TITLE
Rename common variables and functions

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#448]
### Summary
There are a number of variables and functions that should be renamed across the package, in my mind, because they are confusing or uninformative.

### A partial list
- catd --> data_cat
- tsoc --> data_optcom
- masksum --> adaptive_mask
- t2s --> t2s_limited
- s0 --> s0_limited
- t2ss --> t2s_ascending
- s0s --> s0_ascending
- t2sG --> t2s_full
- s0G --> s0_full
- dd --> data_dimred
- mmix --> mixing (sklearn convention)
- betas --> betas_optcom
- tedana.decomposition._utils.eimask() --> outlier_mask()
- tedana.stats.computefeats2() --> z_comp_maps()
- tedana.io.writeresults() --> tedana.io.write_results()
- tedana.io.writefeats() --> tedana.io.write_feats()
- tedana.io.load_data() --> tedana.io.reshape_data()  (since it just reshaped input 4D data to 2D/3D)
- tedana.gscontrol.gscontrol_mmix() --> tedana.gscontrol.minimum_image_regression()
- tedana.gscontrol.gscontrol_raw() --> tedana.gscontrol.gscontrol()
- Finally, how do we feel generally about `betas` vs. parameter estimates vs. regression parameter, etc? I personally had enough classes with SPSS that I automatically interpret "beta" as "standardized parameter estimate", which is not how we use it throughout the package.

### Next Steps
1. Discussion.
2. Large-scale renaming.

**Comment by dowdlelt** [comment]
I'm fine with betas as the label and it is nice and short.  do we think it should include that these are ICA betas? As in, betas_ica_optcom? If the optcom was not used to generate the betas, would it be betas_sepechoes? or something like that?

Overall I am very much pro renaming to names that kind of mean something. Just reading this has helped me make sense of it.

**Comment by emdupre** [comment]
What do you think of `ctab` to `comp_table` ?

**Comment by rmarkello** [comment]
@emdupre: I think @handwerkerd had updated `ctab` to just `comptable` in his branch of the code, which would also work!

**Comment by tsalo** [comment]
`ctab` refers to the comptable file provided by the user though, while `comptable` is the DataFrame. I think there are times when we need separate variables. Same for the mixing matrix and T2* map (pending #408).

**Comment by tsalo** [comment]
I'd like this to be the final thing we address for 0.0.9.

**Comment by tsalo** [comment]
Not stale.

**Comment by tsalo** [comment]
I propose we push this to 0.0.10.

**Comment by tsalo** [comment]
I'd like to start working on this in conjunction with #146 soon, given that there are relatively few active open PRs with major changes to the code. (My assumption is that the reports PR doesn't have much overlap with the files that need to be changed).

However, these changes will lead to _major_ merge conflicts for any open pull requests, as well as conflicts for the proposed changes if new PRs are opened while this one is still unmerged, so I want to see what people think. I'd prefer to fast-track review of the proposed PR so that it doesn't get stuck and have conflicts accumulate.

Alternatively, I could break the changes into a bunch of separate PRs to keep the diffs manageable. What are folks' thoughts?

**Comment by jbteves** [comment]
My 2 cents:
I think we'll want to do one major PR and get it merged quickly. Every time we merge it'll make a downstream series of merge conflicts, so we want to minimize the number of merges. So we should do one merge and plan that after merge, we should coordinate to help people resolve conflicts on their forks.

**Comment by tsalo** [comment]
Happy to close this in favor of #919.
