### ISSUE TITLE
Coveralls

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#45]
Does anyone have any thoughts on adding Coveralls for the repository? Now that @rmarkello is writing unit tests for the util functions in #41, I think it would be good to get an idea about the coverage of the tests. Some minimum level of coverage would also be good for the 0.0.1 milestone.

**Comment by emdupre** [comment]
I honestly held off on coveralls because the numbers were so low it just made me sad 😅 But you're right, now that we're adding tests it would be great to keep track of our progress !

**Comment by emdupre** [comment]
Do you have a preference on [coveralls](https://coveralls.io/) vs [codecov](https://codecov.io/gh) ? I usually use codecov, but no strong preference !

**Comment by tsalo** [comment]
I don't have a personal preference. From what I recall, they're both great.

**Comment by tsalo** [comment]
@emdupre @rmarkello Any thoughts on a coverage threshold for release? 80-90% seems good to me, but depending on the current level of coverage, that might be unrealistic. Also, the current milestone is 0.0.1, so near-complete coverage might not be necessary.

**Comment by rmarkello** [comment]
I'm working on getting testing and coverage set up on Travis right now, so we'll be able to see what the current coverage is! It seems *woefully* low right now (testing on my computer says we're at ~19%), but @emdupre just got me some down-sampled data that I'll be able to use to add a bunch of tests. I'm going to work on my PR some tonight and we can see what we're dealing with. I think 80-90% might be a bit optimistic for the v0.0.1 release. Maybe that can be for v0.1!

The plan is to use Circle just for integration testing (i.e., the tests in `tedana/tests/test_tedana.py`, which will grow as we add new datatypes and options), and everything else will (hopefully) be relegated to Travis. If that becomes unreasonable we can update accordingly!

**Comment by emdupre** [comment]
Closed with #41, I think !
