### ISSUE TITLE
Generate html or dynamic reports

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#450]
### Summary
We would like reports that render and link to figures.

### Additional Detail
Per discussion, main page should have:
- Command used
- tedana version
- Grey/carpet plots for raw, combined, and denoised data (plus any additional denoising steps, like T1c or GODEC)
    - Should use standardized grey plot method being worked on at Code Convergence
- QC metrics pre and post denoising
- T2* map and histogram
- TSNR maps for raw and denoised data
- Histogram of TSNR pre and post
- Motion parameters and other nuisance regressors (on grey plots)
- Report and reference at the bottom

Then a decomposition page for TEDICA:
- Kappa/Rho scatterplot
- Kappa/Rho lineplot
    - Additional denoising/orthogonalization should result in multiple lines here (e.g., orig + tedort)
- Links to component pages
- Rendered log file (has more specific info about numbers of components and warnings through run)

Component-specific pages:
- Metrics
- Our current component time series, Fourier transform, and component map figure

Wishlist:
- Ability to update classifications with buttons in the report

**Comment by emdupre** [comment]
Still working on this with #457 !
