### ISSUE TITLE
Finish adding math to function docstrings

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#47]
We started adding in relevant math and detailed descriptions to the Notes sections of several function docstrings in #43, but it's far from done.

**Comment by emdupre** [comment]
It sounds like @handwerkerd and Jen Evans would be great people to help with this !

**Comment by jbteves** [comment]
I'm interested in helping with this, it would be a good exercise to familiarize myself with the codebase.

**Comment by jbteves** [comment]
Due to @tsalo's large PR #247 and issues #214, #249, #250 I think this issue should be paused.

**Comment by jbteves** [comment]
We have numerous refactors and documentation discussions that have happened in the past month; I think that we should discuss unpausing this and converting it to a larger documentation project on the call, WDYT @handwerkerd @emdupre @tsalo ?

**Comment by jbteves** [comment]
I think this has sat open long enough. As part of the sprint we should look for individual gaps in documentation and fill them as needed; closing.
