### ISSUE TITLE
Update number of required reviews from one to two

### ISSUE THREAD

**Issue by emdupre** [ME-ICA/tedana#479]
### Summary

Now that we have a larger number of contributors actively working on tedana, I think we should update our number of required reviews from one to two. The reasons for this are two-fold:

1. It helps to make sure that experience with how to properly review a PR is distributed throughout the team, as more team members will be reviewing.
2. It helps to protect against code that is not ready for merging into master being merged. 

### Additional Detail

I have already updated this requirement in the tedana settings. @tsalo and I will retain the ability to merge without the two required reviews, although we'll try to minimize using this power as much as possible.

### Next Steps

We might want to update the contributing guide to note that all PRs require two approving reviews before merging.

**Comment by jbteves** [comment]
Do you want me to integrate this into #446 ?

**Comment by emdupre** [comment]
> Do you want me to integrate this into #446 ?

I think that would be great, @jbteves !

**Comment by tsalo** [comment]
This was resolved by #446, so I'm going to close it now.
