### ISSUE TITLE
Enable text wrapping in RTD tables

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#48]
Currently, long lines in tables on the RTD site require horizontal scrolling, but we want to just have them wrap around to new lines. The most obvious way to do this is to override the theme by uncommenting [these lines](https://github.com/ME-ICA/tedana/blob/d7807548871348993d7daf849e7499bbdb64cd88/docs/conf.py#L121-L125), but this also removes the RTD theme. The solution appears to be described [here](https://github.com/rtfd/readthedocs.org/issues/2116). It just needs to be implemented in the tedana documentation code.

**Comment by emdupre** [comment]
Closed with #55
