### ISSUE TITLE
Submissions to OHBM 2020

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#483]
### Summary
The Organization for Human Brain Mapping submission deadline is December 19, 2019. This is an issue to coordinate submissions related to tedana.

### Additional Detail
- tedana poster. I (Dan) am willing to take the lead on this as the writer & submitter. If someone else wants to take the lead, please speak up ASAP. Like last year, the plan is to have "Tedana Community" as the first author & others alphabetized?
  * Submitted: https://docs.google.com/document/d/1XpeIC88-4FjW5xCHLyHTAdHIfJUPYm9Y96tjAg2gqao/edit?usp=sharing
- Other tedana or multi-echo posters. I think we can link posters at OHBM? If others are submitting posters on multi-echo methods or validations of algorithms, list them if you want to attempt to group them. It would also be useful to get a sense of what else might be submitted that directly overlaps with tedana.
- multi-echo focused symposium. Dan & @smoia are working on putting together a proposal. If you want more details or have suggestions, contact them.
  * Submitted: https://docs.google.com/document/d/1BhDRP1cEBG_Re5O6gyl7ttbeTq5sS6nzp55xOkQ5ah4/edit?usp=sharing
- Open science room presentation. I think we want to do this again, but that's a later deadline
- Software demonstration. I think the decision was not to do a demo this year, but if you want a demo & are willing to lead it, please speak up!

### Next Steps
- Anything big missing?
- Share abstracts that might get linked together
- Share opinions on what to put in the abstract for a tedana-specific poster.

**Comment by KirstieJane** [comment]
Thanks @handwerkerd for getting this issue up! I'm looking forward to some multi-echo fun at OHBM this year!

Re: authorship - yep - I have a strong preference to continue last year's author ordering as Tedana Community as first, and then alphabetical by last name. I'd also like us to be quite inclusive of those additional names - it doesn't cost us anything to include folks and its a nice way to appreciate all the folks in our community.

What's the goal for the symposium? (is that worth a separate issue?) Is it to build the community? To bring in more users? More developers? (What's the difference?) Or to highlight lots of different tools?

**Comment by handwerkerd** [comment]
@KirstieJane I just shared the link to the draft symposium proposal with you. If anyone else wants to see the draft proposal, give a 👍 to this comment.

**Comment by tsalo** [comment]
@handwerkerd Have you started on the abstract already or would you mind if I took the lead? Sorry for taking so long to ask.

**Comment by KirstieJane** [comment]
Hi @handwerkerd - please can you add the link to the poster submission here?

I don't quite understand why the symposium submission is private but it feels like the poster at least should be transparently developed?

**Comment by handwerkerd** [comment]
Here is the poster draft. It will hopefully be in better shape in the next couple of hours. Until then, general feedback and alerts regarding unintentionally excluded authors are welcome:
https://docs.google.com/document/d/1XpeIC88-4FjW5xCHLyHTAdHIfJUPYm9Y96tjAg2gqao/edit?usp=sharing

Here is the symposium draft:
https://docs.google.com/document/d/1BhDRP1cEBG_Re5O6gyl7ttbeTq5sS6nzp55xOkQ5ah4/edit?usp=sharing

**Comment by handwerkerd** [comment]
For the tedana poster, I was hoping to include some of the nice visualizations that were recently added to the code, but the best ones are still in a PR and I've had a bit of trouble getting that PR running & generating figures. I could just use the figure from: https://github.com/nih-fmrif/codeconvergence/issues/16 It would be static, but is a nice demo of what the reports will very soon look like. Thoughts? Any other better visualization.

Also it seems like the current master is generating all the png files, but it's no longer automatically creating an html page which organizes those images in a coherent manner. Am I missing something?

**Comment by emdupre** [comment]
> Also it seems like the current master is generating all the png files, but it's no longer automatically creating an html page which organizes those images in a coherent manner. Am I missing something?

The HTML page hasn't yet been merged into master -- it's part of #467. I might look at #465 for the prettier pictures ! Specifically the [generated RTD build](https://external-builds.readthedocs.io/html/tedana/465/index.html).

**Comment by KirstieJane** [comment]
This is fun everyone! Congratulations on getting the symposium and poster submitted!! 🚀 🌟 🙌 
I've opened #509 to collect OHBM related details! If you submitted an abstract using multi-echo please add a link there!
