### ISSUE TITLE
reason for mmix = mmix.copy() in kundu_fit.py

### ISSUE THREAD

**Issue by CesarCaballeroGaudes** [ME-ICA/tedana#484]
@smoia @eurunuela and myself are wondering the reason of this copy of the mixing matrix mmix in kundu_fit.py (https://github.com/ME-ICA/tedana/blob/9912c092dd12891aeb4609a2112ce0a8f349d2d2/tedana/metrics/kundu_fit.py#L119)

**Comment by tsalo** [comment]
I believe that the goal is to ensure that `mmix_orig` that's fed into that function below isn't changed in place:

https://github.com/ME-ICA/tedana/blob/9912c092dd12891aeb4609a2112ce0a8f349d2d2/tedana/workflows/tedana.py#L493-L496

**Comment by smoia** [comment]
@tsalo , thank you, but could you explain a bit more? It's still quite unclear to me.

**Comment by tsalo** [comment]
The first step applied to `mmix` in the function is `mmix *= signs`, so the following code might be helpful:

```python

import numpy as np


def func(x):
    x *= 5
    return x

arr = np.arange(10)
print('orig: {}'.format(arr))
arr2 = func(arr)
print('new: {}'.format(arr2))
print('orig?: {}'.format(arr))
```
You'd expect  it to be

```
orig: [0 1 2 3 4 5 6 7 8 9]
new: [ 0  5 10 15 20 25 30 35 40 45]
orig?: [0 1 2 3 4 5 6 7 8 9]
```

but it's
```
orig: [0 1 2 3 4 5 6 7 8 9]
new: [ 0  5 10 15 20 25 30 35 40 45]
orig?: [ 0  5 10 15 20 25 30 35 40 45]
```

I can't remember the proper CS terminology, but it's like a shallow vs. deep copy thing.

**Comment by tsalo** [comment]
Changing  `mmix *= signs` to `mmix = mmix * signs` would work just as well as having the copy line.

**Comment by smoia** [comment]
I see now, it's very clear! Thank you!
(Now I need to check all of my functions)
If your last option is as good as, I would propose to use that instead: I think the code would be more clear.

**Comment by tsalo** [comment]
The only problem is that `x += 1` is a common refactor to `x = x + 1`, so it would be easy for someone to accidentally introduce a bug at a later date if they aren't aware of the issue.

**Comment by smoia** [comment]
I see. Then maybe commenting it would be a better option.

**Comment by CesarCaballeroGaudes** [comment]
Sorry, but does the mmix variable that use used in the subsequent call to [get_coeffs] (https://github.com/ME-ICA/tedana/blob/9912c092dd12891aeb4609a2112ce0a8f349d2d2/tedana/metrics/kundu_fit.py#L127-L129) need to be multiplied by the signs? If it does, I think it would be clearer that we create a new variable, i.e. mmix_signed = mmix * signs, and use it in the rest of this function.
