### ISSUE TITLE
Remove sourceTEs option

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#485]
### Summary
In a discussion that I am unable to locate, I recall someone saying that maPCA would be incompatible with running PCA on z-concatenated data (i.e., using anything other than optimally combined data with the `sourceTEs` option). Given that we were never able to find a satisfactory rationale or use-case for the argument (see #203), I think that we should remove it.

### Next Steps
1. Remove `--sourceTEs` from tedana CLI, workflow function, and PCA functions.

**Comment by eurunuela** [comment]
As far as I can tell, maPCA is not compatible with `—sourceTEs`. I guess it could be implemented in the feature but I personally do not know how atm.

**Comment by tsalo** [comment]
@eurunuela Thanks! It's good to have that on record from someone more familiar with that code than me. I don't think there's much benefit (if any) to supporting `sourceTEs`, even if maPCA was compatible with it already.

**Comment by eurunuela** [comment]
Totally agree on that @tsalo. I don't see any benefits to supporting `sourceTEs` either but I'm not very familiar with the rest of the code anyway.
