### ISSUE TITLE
Remove MLE tedpca option

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#486]
### Summary
Per https://github.com/ME-ICA/tedana/issues/356#issuecomment-560134982, our current plan is to remove MLE as an option, since it just doesn't work for fMRI data.

### Additional Detail
We may wish to replace MLE with a basic variance explained-based threshold, which may be worth discussing in this issue.

### Next Steps
1. Remove MLE option from CLI, workflow function, PCA functions, tests, and documentation.
2. ~~Possibly add simple threshold-based PCA option, though retaining maPCA as the default.~~ See #492.

**Comment by tsalo** [comment]
Should we discuss the threshold-based option here or should we have a separate issue for that.

**Comment by jbteves** [comment]
Let's do a new issue for the threshold-based.

**Comment by eurunuela** [comment]
Should we wait for #492 to be done before we remove the MLE option?

**Comment by jbteves** [comment]
IMO there's no reason to. My impression is that everyone who tried the MLE option didn't like it, and with a reasonable new alternative I think it's safe to remove it.
@emdupre @tsalo any objections?

**Comment by tsalo** [comment]
Agreed. MLE isn't the default anymore and the threshold-based option won't be the default when it's added, so most users won't even notice the difference. Plus the two changes will probably end up in the same release, even if they're not bundled into the same PR.

**Comment by jbteves** [comment]
Same release, different PRs sounds good to me.

**Comment by eurunuela** [comment]
Sounds good to me! Just wanted to check whether it was best not to tackle both issues together.

**Comment by jbteves** [comment]
Let's keep separate to make it easier to review.
