### ISSUE TITLE
Secondary masking in decomposition.tedpca crashes program

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#490]
### Summary
decomposition.tedpca takes a mask as input. The following lines of code call _utils.eimask to apply an additional mask that seems to remove voxels with outlier magnitudes.
https://github.com/ME-ICA/tedana/blob/9912c092dd12891aeb4609a2112ce0a8f349d2d2/tedana/decomposition/pca.py#L258-L259
The additional voxels masked in this step are not recorded anywhere and the program later crashes because the masked data volume now has fewer voxels than the mask defined in `mask`

### Additional Detail

I came across this bug while processing a new data set. I suspect that most data haven't actually caused _utils.eimask to remove voxels so this bug never appeared. In my case, the original mask included 60455 voxels and eimask removed a single voxel so that the new data included 60454 voxels. The program continued to run without problem until the following write call where `dd` contained one fewer voxel than `mask`
https://github.com/ME-ICA/tedana/blob/9912c092dd12891aeb4609a2112ce0a8f349d2d2/tedana/workflows/tedana.py#L486-L487

When I change the above code so that `eim` is True for all values (i.e. no additional masking) the full program runs without problems.

This function has existed for a while so I don't know when this problem arose. I think @tsalo worked on in this area of the code 8 months ago and @eurunuela had the most recent PR. Either no one has tested data that has caused additional masking or the recent merges have altered how the additional masking was handled.

### Next Steps

- Decide if this additional outlier masking is necessary.
- If the masking isn't necessary, then remove this function and the few uses of `eim` from the code
- If the masking is necessary, then
    - Option 1: Outlier masking should be moved to the section of the code where the mask is originally calculated. Outlier masking isn't specific to the PCA step and this masking will remove voxels from every resulting image. Thus this should be documented in the mask file.
    - Option 2: Think more about how user provided masks should be handled. If a user provides a mask that includes outliers, there are and should be checks to exclude those voxels, but that might necessitate logging and creating a more restricted mask than was provided by the user.
    - Option 1 makes sense for this specific scenario, but https://github.com/tsalo/tedana/pull/8 points another situation where the user provided mask might need to be additionally restricted in the code. Thinking about how to do that in a consistent way is probably useful.

**Comment by handwerkerd** [comment]
As an aside to the main issue, in trying to figure out what was going on, I ended up seeing how often utils.unmask is called. It was called 400 times with 352 of those calls following the logged line:
"INFO:tedana.metrics.kundu_fit:Performing spatial clustering of components" My data has 323 volumes.

This inefficiency relates to my general concern about always moving files around in an img format and specifically suggests there's room for an efficiency increase in the spatial clustering step. (If I get a chance to dig more, this might become another issue).

**Comment by tsalo** [comment]
> Option 1: Outlier masking should be moved to the section of the code where the mask is originally calculated. Outlier masking isn't specific to the PCA step and this masking will remove voxels from every resulting image. Thus this should be documented in the mask file.

Agreed. I think we should move the outlier masking into `make_adaptive_mask` for now. We can revisit our masking procedure separately, but this will at least fix the bug.

> If a user provides a mask that includes outliers, there are and should be checks to exclude those voxels, but that might necessitate logging and creating a more restricted mask than was provided by the user.

This is already done. See here:
https://github.com/ME-ICA/tedana/blob/2e6e3cbe4fda553a0cfbb122e404c7bc0fc4e8cb/tedana/utils.py#L96-L105

> It was called 400 times with 352 of those calls following the logged line:
"INFO:tedana.metrics.kundu_fit:Performing spatial clustering of components" My data has 323 volumes.

We could definitely generate 4D imgs below, and then index them in the for-loop instead of making a 3D img for each component within the loop. We'd probably want to profile both to see which is faster/less memory intensive. We could also support volume-wise thresholding of 4D imgs in the threshold_map function, although there would end up being a for loop in there somewhere, I think.

I believe that merits a separate issue though.
https://github.com/ME-ICA/tedana/blob/2e6e3cbe4fda553a0cfbb122e404c7bc0fc4e8cb/tedana/metrics/kundu_fit.py#L252-L255

**Comment by handwerkerd** [comment]
I agree with your suggestions, but I'm realizing there is a non-trivial bug in _utils.eimask. https://github.com/ME-ICA/tedana/blob/2e6e3cbe4fda553a0cfbb122e404c7bc0fc4e8cb/tedana/decomposition/_utils.py#L14
That function assumed the data is multi-echo data with (S x E x T) dimensions. It then explicitly processes the data based on those dimensions. Thus, if one passes it optimally combined data, instead of operating on each echo separately, it's operating on each timepoint separately and I'd have to think more what this does in reality. It shouldn't be too hard to move yet another arbitrary threshold into make_adaptive_mask, but I wanted to document that the current version is has this problem as well.

**Comment by tsalo** [comment]
The `tedpca` function adds a singleton dimension in lieu of echoes to the optimally combined data, so it should be fine.

https://github.com/ME-ICA/tedana/blob/2e6e3cbe4fda553a0cfbb122e404c7bc0fc4e8cb/tedana/decomposition/pca.py#L248-L250
