### ISSUE TITLE
Add threshold-based PCA option

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#492]
### Summary
Continuing from #486, we want to add in a simple variance explained threshold-based PCA option.

### Next Steps
1. Decide what threshold we want to use.
2. Add new option to CLI, tedana workflow, PCA function(s), and tests.

**Comment by jbteves** [comment]
Thanks for opening @tsalo !

**Comment by tsalo** [comment]
I'll propose a threshold that keeps components explaining the top 95% of the variance.

**Comment by eurunuela** [comment]
Sounds good to me, although I’d also give the user the option to set this threshold.

**Comment by tsalo** [comment]
Allowing users to provide a float for `--tedpca` seems doable, but I don't think there's an elegant way to combine that with a default variance threshold, since `'mdl'` is our default PCA method.

**Comment by tsalo** [comment]
I haven't circled back to work on this lately, and given the difficulties in supporting floats, I propose we push this to 0.0.10.
