### ISSUE TITLE
Multi-echo at OHBM | collect posters/talks/demos & plan other engagements

### ISSUE THREAD

**Issue by KirstieJane** [ME-ICA/tedana#509]
### Summary

The `tedana` :tada: community submitted a [poster abstract](https://docs.google.com/document/d/1XpeIC88-4FjW5xCHLyHTAdHIfJUPYm9Y96tjAg2gqao/edit?usp=sharing) and a [symposium application](https://docs.google.com/document/d/1BhDRP1cEBG_Re5O6gyl7ttbeTq5sS6nzp55xOkQ5ah4/edit?usp=sharing) on 19 December 2019. WOOOO 🚀 🌟 

The point of this issue is to keep track of other abstracts that were submitted/accepted on ME-ICA and to brainstorm other engagements such as presenting at the Open Science room or hosting a project at the hackathon. Please comment with any ideas!

**Comment by jbteves** [comment]
@KirstieJane could you head your comment with two additional sections, "Abstracts" and "Hackathon Ideas"?
I'd like to throw 90% coverage into the ring for hack ideas.

**Comment by handwerkerd** [comment]
The symposium was accepted. Looking forward to collaborating on "Two is better than one (and many are better): Multi-echo fMRI methods and applications" with @smoia, @emdupre, @CesarCaballeroGaudes, Angela Laird, and everyone else working to make tedana awesome.

**Comment by jsheunis** [comment]
Congrats! I'm really looking forward to this!

**Comment by handwerkerd** [comment]
Multi-echo Symposium: 
"Two is better than one (and many are better): Multi-echo fMRI methods and applications"
https://www.humanbrainmapping.org/files/2020/OHBM_Two.pdf

Symposium "Discerning Signal From Artifact: Current Issues in resting-state fMRI quality control" includes "Multi-echo acquisition for fMRI sensitivity enhancement and data quality control - Benedikt Poser" https://www.humanbrainmapping.org/files/2020/OHBM_Discerning.pdf

I will try to start adding posters once the full program is posted online.

**Comment by emdupre** [comment]
I just wanted to share [the draft for my talk on tedana](https://docs.google.com/presentation/d/1PowXJGj2DP0vU-62-rgZfatACE5UOel8tH8Z9whNiIc/edit?usp=sharing) in the ME symposium:

Any feedback is appreciated ! I have to record tomorrow at noon EDT, but I'll be tweaking it before then, and I'll do my best to implement any / all suggestions :smile_cat:

**Comment by jbteves** [comment]
Your 9th slide gave me a good chuckle.

Do we happen to have `pip install` statistics? It would be nice if we could include those.

Great job, thanks @emdupre !

**Comment by CesarCaballeroGaudes** [comment]
@emdupre The content and the message looks great!!
Perhaps you can add a last slide with the references that you don't need to go through as viewers can stop the video.
Some diagram or picture in some slide to reinforce the text? For instance, slide 3 with the main procedures implemented in the pipeline could include the flowchart in https://tedana.readthedocs.io/en/latest/approach.html

**Comment by emdupre** [comment]
Thanks @CesarCaballeroGaudes ! I couldn't quite fit the picture on the slide but I've now explicitly linked to the pipeline. Good call on the references -- I added all of the journal names so viewers can more easily access them without clicking through !

**Comment by handwerkerd** [comment]
I assume a few others have gotten the email from OHBM "reminding" us that posters need to be uploaded by June 12th. Given this deadline wasn't previously mentioned, I'm not taking it too seriously, but I really should start to put together the tedana community poster. If people have images or suggestions on what to include, please contact me directly or in this issue.

**Comment by handwerkerd** [comment]
We are going to compile multi-echo related events at OHBM 2020 in the README.md of https://github.com/ME-ICA/tedana-ohbm-2020 Please add suggest or directly add content there.

**Comment by emdupre** [comment]
Also, we've created a website (linked from that same repository) to demo
the added tedana reports. If there's any other content that would make
sense to highlight on the website, we can mirror it in both the markdown
and HTML !

Le ven. 19 juin 2020 11 h 16, handwerkerd <notifications@github.com> a
écrit :

**Comment by tsalo** [comment]
We can close this now, right?

**Comment by jbteves** [comment]
I agree, we can close this.
