### ISSUE TITLE
Update installation documentation

### ISSUE THREAD

**Issue by rmarkello** [ME-ICA/tedana#51]
The [installation docs](https://tedana.readthedocs.io/en/latest/installation.html) currently list AFNI as a requirement, which is no longer true as as of #40. It would be great to update that!

Moreover, I think that suggesting docker for use/development might be a bit overkill, since `tedana` is now a pure-Python package. Perhaps it would be better to suggest simply installing via `pip install https://github.com/ME-ICA/tedana/archive/master.tar.gz` as suggested in the README? I'm also game to proselytize `conda` (as is currently being done), but regardless I think making it as simple as possible to use `tedana` would probably be best!

**Comment by emdupre** [comment]
I'm actually going to get rid of the installation documentation all together, I think. It will be something we can add back in if needed, but for now I think the information in the README is detailed enough ! 📖 
Please LMK if you disagree, @rmarkello !
