### ISSUE TITLE
Webinar/zoom call on testing

### ISSUE THREAD

**Issue by KirstieJane** [ME-ICA/tedana#510]
### Summary

Knowing when to add tests, why to add tests and what a _good_ test looks like is a key skill for building an extendable open source software library.

One idea we had in the December community call is to host a webinar to capture that conversation around a specific example. We could also co-host this with [_The Turing Way_](https://github.com/alan-turing-institute/the-turing-way) community if that sounds good.

### Next Steps

- [ ] Get @handwerkerd's PR in a place that it can be discussed 
- [ ] Plan a date that has a couple of folks (who are confident on testing) available to participate in the conversation
- [ ] Promote and tell folks about what's going on
- [ ] Zoom away! 🚀

**Comment by jbteves** [comment]
If I'm going to participate I would preferably like to schedule it before January 11th, even though that's short notice. I don't think my attendance is necessary though, especially if @rmarkello is willing to step in.

**Comment by handwerkerd** [comment]
If the goal is to get #476 to a place where it can be a use example case, that would probably be late January or early February.

**Comment by jbteves** [comment]
That's fine, if I can't make it to the actual call I'm happy to help prep on off-time.

**Comment by tsalo** [comment]
I think we can close this.
