### ISSUE TITLE
Next tedana newsletter

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#512]
### Summary

We are hoping to release a [newsletter](https://tinyletter.com/tedana-devs ) soon. A central part of that will be a summary of the hackathon. I've written that summary at: https://docs.google.com/document/d/1hn8Mx8fZoVx2g5Kd1wQNk8Xc1aSwAdlr_3l_8CY5GVM/edit?usp=sharing 

### Next Steps
- Particularly for those who went to the hackathon, read the text & make suggestions or edits.
- Too much detail anywhere? Anything key I'm missing?
- Thoughts on if/how to acknowledge contributions of individuals?

- Anything else to include in the newsletter?

- Once things are stable, @jbteves will put everything in a newsletter & send it out.

**Comment by jbteves** [comment]
Thanks for this, @handwerkerd. One of the things is that this for NIH to determine if the funding was worth it, essentially, so what are key things that NIH wants to see as successes? For example, is engaging the community a priority? Is expanding internal and external knowledge of a subject matter a priority? This helps us tailor some of the points to them so that they're happy with their purchase.

**Comment by handwerkerd** [comment]
I wrote this for the newsletter. If others like it, it won't be hard to slightly restructure for a more formal summary report.

**Comment by emdupre** [comment]
Thanks so much for drafting this, @handwerkerd ! :sparkles: 

I (lightly) worry it might be a little too much detail for the newsletter, but it feels like a great blogpost to me (that we could pull pieces of for the newsletter). I'll let those with more experience on newsletters (thinking of @jbteves , @KirstieJane in particular) weigh in there, though.

Re listing everyone: I love the current "film credits" style acknowledgements ! To echo @eurunuela 's response out-of-band, the one thing I'd ask we add for the newsletter is to point out that all of these folks are resources for questions anyone might have. And it'd be great to remind everyone that we'd love to have new contributors (and always new contributions from existing contributors), too !

Re anything else to add: I think it'd be great to also list in the newsletter the OHBM submissions, and briefly highlight our 2019 (thinking of OHBM 2019, etc).

**Comment by jbteves** [comment]
Thanks for the ping @emdupre, this had unfortunately slipped me in the holiday confusion. I agree that this is longer than a desired newsletter. I target but rarely hit a <1 minute read time. We could probably trim it by about half IMO. Our last newsletter was ~750 words and this version (excluding the struck out bits) is ~1300 words. The simplest way to do this is to list out the accomplishments, without so much of the rationale and discussion surrounding them, and complete by noting that contributions are welcome and appreciated. I admit it's been a while but I think small things are more likely to be read with how busy people are, particularly in January. I'm happy to help with this if others agree. 

I think I agree with the idea of a blog post. It does raise the point of maybe having a larger social media or website presence; for example, almost all of us are active on twitter and could share it. But for a series of posts or one large one, this is a great start. 

I also agree with credits-style acknowledgments. Previously I would list all of the merged PR titles and their primary authors, but that would scale hysterically poorly with the frenzy of the hack activity we're reporting on. 

Thanks again @handwerkerd !

**Comment by handwerkerd** [comment]
I decided to make a new abridged doc since we might want the longer version as a record. The abridged version is here: https://docs.google.com/document/d/1XYjDrfq0KidNBuJjbggAaukiGhXUQyVC-lscr0OrOSI/edit?usp=sharing

The report is 786 words and the credits are an additional 186 words. This seems reasonable to me, but others are welcome to trim more. I asked @jbteves to trim the testing section a bit more.

As for a blog post, I don't see any of us maintaining a tedana-specific social media presence in the near future. I think the lower hanging fruit is making a place to archive project documentation that should be accessible. To date, this would include reports like this one and tedana-specific posters (our messy dev call notes are probably fine in their current google drive folder, but we could link to that folder). Two posters are currently sitting on the front page of tedana's readthedocs. I assume we'll swap those out with OHBM 2020 posters, but it would be good to have a natural place (on readthedocs?) to place the older posters & things like the hackathon report. If others agree, I can open an issue to remind me or someone else to eventually set that up.

**Comment by handwerkerd** [comment]
If possible, I'll also suggest we don't send a newsletter out until #517 is resolved. If the newsletter drives a bunch of people to peek at the project, it would be nice not to have a potentially non-trivial bug at the top of the issues.

**Comment by jbteves** [comment]
I agree there's not much to trim. I think that the abridged version is more appropriate, and I'm happy with it pending a few suggestions. Thanks @handwerkerd !
I also agree with waiting until CI is passing again to send a newsletter. 
Let's discuss archiving documents on the next call if we have time, maybe?

**Comment by jbteves** [comment]
@handwerkerd I'm supposed to send the version in the google doc, correct? Sorry this fell through the cracks.

**Comment by handwerkerd** [comment]
Correct. It's the abridged doc at: https://docs.google.com/document/d/1XYjDrfq0KidNBuJjbggAaukiGhXUQyVC-lscr0OrOSI/edit?usp=sharing

**Comment by emdupre** [comment]
So happy to see this went out ! Thank you all.

I'm going to mark this issue as closed, and we can open up another one for the next newsletter ? :smile_cat:
