### ISSUE TITLE
zenodo has only 0.0.6 (no 0.0.8)

### ISSUE THREAD

**Issue by yarikoptic** [ME-ICA/tedana#516]
e.g. on https://zenodo.org/record/2558498#.Xg9wkHVOmk8 
I wondered if that was intended

**Comment by tsalo** [comment]
@emdupre should 4a56876c64a5a187209550857da9ba9b3e3020a6 fix that for future releases?

**Comment by tsalo** [comment]
New versions are now pushing to Zenodo, so the bug appears to be fixed.
