### ISSUE TITLE
Current Master Failing CI

### ISSUE THREAD

**Issue by jbteves** [ME-ICA/tedana#517]
### Summary
For some reason in 4a56876 we're failing CI, which is bizarre since it only changed the license type. According to the failed report [view here](https://circleci.com/gh/ME-ICA/tedana/8600?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification) the 4-echo test generated mismatched outputs, where we expect `s0v.nii` and two other files to be generated; however, they are not.

### Next Steps
@tsalo @emdupre @rmarkello any thoughts on what's happening?

**Comment by tsalo** [comment]
The error message is misleading. `s0v.nii` is not missing- it's just that no BOLD components are being detected so none of the denoised files are written out. I don't know what's causing the issue, however something similar is also impacting #358.

**Comment by dowdlelt** [comment]
Looking through the artifacts, its finding plenty of components, its just ignoring almost all of them:
![image](https://user-images.githubusercontent.com/15126366/71924317-5ddd0080-3154-11ea-9381-50993a4ddb9c.png)

Its odd that the the kappa values are are not that much higher than the rho values, for sure. 

![image](https://user-images.githubusercontent.com/15126366/71924421-954bad00-3154-11ea-9e49-82575e5061d0.png)

Not sure how this could be related to the license change at all. Really doesn't seem like it could be. The mask and components all still look 'good'.
