### ISSUE TITLE
Topics for January 2020 Developers' call

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#521]
### Summary
Our next developers' call is scheduled for Friday, January 17 at 10:00EST ( [Click for other time zones](https://arewemeetingyet.com/New%20York/2020-01-17/10:00/Tedana%20Developers%20Call) )
Use this thread to bring up potential topics to discuss. Next week I'll reorganize the topics into a meeting agenda/minutes Google Doc.

### Action items or updates from the [December call](https://docs.google.com/document/d/1Ky1F1rZnrqMs777Bo5XL7glp8iRYywJAXDxQd18NUN4/edit?usp=sharing)
- Send out tedana newsletter (#512 @handwerkerd & @jbteves )
- Open an issue on how to track & credit author contributions & update Zenodo  ( @emdupre )
- Update on potential 2020 tedana hackathon (@handwerkerd )
- Google Summer of code or other summer students (@KirstieJane )
- Finding a resolution to #401 & #473 (@emdupre & @rmarkello )
- With the new PCA code is #255 now resolved? (@tsalo & @eurunuela )
- Open issue/PR to create unit tests for sub functions in the PCA method
- Open issue/PR to expand testing code for PCA to show impacts of alterations beyond just testing that it's doing what it's supposed to do
- Make a documentation section on use cases and multi-echo benefits (Now: #520 )
- Finalize & merge reports into master #457 & #465
- Figure out how dynamic reports & static reports run in the code by default ( @dowdlelt & others ). Any open issue specifically on this? 
- Open a GitHub issue with mockups of options on how the reports could look (@emdupre )
- Updates on modularization #475, #476, #491, & #490 (@handwerkerd @tsalo)
- Pull requests that might be mergeable after review: #458, #496, #508, #408 (pending 508?), #500 
- Possibly start governance discussion

### New topics for January call
- Resolving CI failing on master #517 
- Discussing where to host archival documents like tedana posters from multiple conferences and the post hackathon report.

### Topics to cover in a future call
- tedana at OHBM planning #509
- Webinar on testing #510

**Comment by handwerkerd** [comment]
Confirming the following developers' calls are at reasonable times:
Friday, Feb 21
Friday, March 20
Friday, April 17
All at 10:00EST
Subscribe to the full calendar at: https://calendar.google.com/calendar/embed?src=pl6vb4t9fck3k6mdo2mok53iss%40group.calendar.google.com&ctz=America%2FNew_York

We should briefly discuss at the meeting, but also follow up with those who couldn't attend the Friday meeting.

**Comment by KirstieJane** [comment]
Hi @handwerkerd! Thank you for coordinating! My zoom room is available - please use it if it’s useful - but *i* am only available at 3:30pm.....and even then only maybe. There’s a bit external advisory board meeting that finishes at 3:30 but I’m not confident that it won’t run long 😭 I can add notes to the agenda in advance. Sorry that I can’t make the start of the call (or any of it confidently 😕)

**Comment by KirstieJane** [comment]
I’m a no for Feb 21 but good for the other two.

**Comment by emdupre** [comment]
Thanks so much for coordinating this ! Unfortunately I had a meeting come up that I can't move for Friday at 10a so I won't be able to make this Friday :disappointed:  I'll add my updates tonight -- so sorry !

The other dates generally work well for me, though if Fridays are no longer as convenient I wonder if we shouldn't send a poll for general times that work, just to see if there are any other better times ? WDYT ?

**Comment by eurunuela** [comment]
A poll sounds good to me!

**Comment by handwerkerd** [comment]
The editable agenda where we can type notes tomorrow is at: https://docs.google.com/document/d/1Z2w7cHxPcGmfQYzYHaH2p-6Y8CNQ52pXegZeRyAMnPw/edit?usp=sharing 
I'm trying out a different ordering that I hope is closer to how we've actually ended up ordering discussions during the calls. The last few calls have had a lot of bouncing around to different parts of the agenda.

For those who can attend, please check if you agree with the topic orders & priorities. For those who can't attend, advance updates on things where you have info to contribute would be greatly appreciated.

There is an item on future meeting times with a few questions that will help focus a poll. If you can't attend, but have opinions, please try to give your opinions before the meeting.

**Comment by dowdlelt** [comment]
Looks good to me and I've added a bit to the agenda about validation data. Dates work for me, but I can be flexible. Trying to increase involvement again, but only time will tell if that is successful.
