### ISSUE TITLE
Integrate denoising into fMRIPrep

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#524]
### Summary
We want to integrate multi-echo denoising into fMRIPrep eventually, but have been postponing this until the component classification is solid. However, given that fMRIPrep users have asked about multi-echo denoising on Neurostars and that we are now outputting BIDS Derivatives-compatible component tables and ICA time series, I think we're ready to run the denoising pipeline in fMRIPrep. Specifically, I think we should run tedana within fMRIPrep and then retain the optimally combined data (as we do now) along with the component table json and the component time series tsv, so that users may use those to denoise the data themselves. As long as fMRIPrep retains the component table with its metrics and classification rationales, users can choose which criteria they want to use to denoise their own data and they won't be beholden to our initial (and currently imperfect) classifications.

EDIT: This issue is related to https://github.com/poldracklab/fmriprep/issues/1010.

### Next Steps
1. Vote
2. If yes, move discussion of actual implementation to fMRIPrep repository. If no, close this issue.

**Comment by emdupre** [comment]
I'd suggest that the one additional consideration will be that fMRIPrep is starting to worry about feature-creep, so I think we'll additionally need to make an argument for why they should support adding in tedana denoising as an additional step.

**Comment by jbteves** [comment]
It looks like fMRIPrep only offers optimal combination now, though, no sort of denoising. Or am I misreading the docs?

**Comment by emdupre** [comment]
> It looks like fMRIPrep only offers optimal combination now, though, no sort of denoising. Or am I misreading the docs?

Yes, that's right ! Sorry, not sure if I said something misleading. I think the question is if we'd additionally add in denoising there (since it's not currently supported).

**Comment by jbteves** [comment]
Sorry, I think I was being unclear. I meant, they don't offer any sort of denoising, so I don't understand why they would not want it offered for multi-echo.

**Comment by tsalo** [comment]
@emdupre Since fMRIPrep has a still-open issue, I feel like it wouldn't be too presumptuous to comment on the issue as if that was still the plan, iff we're ready/willing to move forward with this approach.

>Sorry, I think I was being unclear. I meant, they don't offer any sort of denoising, so I don't understand why they would not want it offered for multi-echo.

They offer AROMA, both by actual denoising and by returning the time series necessary to perform that denoising after the fact. I think tedana would be in a very similar situation.

**Comment by jbteves** [comment]
> They offer AROMA
Oops, sorry, I missed that. Sorry, I don't use fMRIPrep so I'm not as familiar with all of the options. Thanks for the correction @tsalo.

**Comment by emdupre** [comment]
> They offer AROMA, both by actual denoising and by returning the time series necessary to perform that denoising after the fact. I think tedana would be in a very similar situation

Ah, I see the confusion. Thanks for clarifying ! Yes, they offer AROMA. I think the difference is that we had to re-configure quite a few of the internals to support multi-echo, and I worry about adding in denoising as increasing the maintainability burden since we'll have to move a few more (only really harping on this since this is a conversation that just came up). But my concerns aren't strong enough that I think we _shouldn't_ broach the issue. Just something to keep in mind.

**Comment by tsalo** [comment]
@emdupre Sounds good.

On an unrelated note, I'm not 100% sure how to work with these voting-based issues. How long should I give it before closing the polls?

**Comment by tsalo** [comment]
I've commented in the associated fMRIPrep issue, so it's now up to the fMRIPrep devs to decide whether to move forward with it or not. As such, I'm going to close this issue.
