### ISSUE TITLE
Reduce stale-bot aggression

### ISSUE THREAD

**Issue by jbteves** [ME-ICA/tedana#528]
### Summary
It seems like stale-bot may be overly aggressive by removing posts after 60 days of inactivity + comment + 7 additional days of inactivity. We should discuss a more reasonable removal period.

### Next Steps
1. Pick a less aggressive removal window.

**Comment by tsalo** [comment]
Initial proposal by @handwerkerd on Gitter is 60 days + comment + 600 days.

**Comment by handwerkerd** [comment]
An additional proposal is, once people post updating comments on a stale issue, it would be considered ok to manually remove the "stale" label (I don't think it automatically gets removed?). That means, if the issue remains stale for another 60-days, it would be again get auto-labeled stale, which would remind people to check in on it again.

Also reconsider the 'exemptLabels' in https://github.com/ME-ICA/tedana/blob/master/.github/stale.yml
The only current exempt label is 'community' . Should 'discussion' also be exempt?

**Comment by jbteves** [comment]
That seems fine to me. I'm kind of iffy on discussion, on the grounds that I would hope that discussion gets rekindled by the bot.

**Comment by emdupre** [comment]
> it would be considered ok to manually remove the "stale" label (I don't think it automatically gets removed?).

It _should_ automatically be removed if someone comments on it ! 

> Should 'discussion' also be exempt?

Also no strong feelings -- I share @jbteves hope that discussion would be advanced by the bot-related ping. But as in https://github.com/ME-ICA/tedana/issues/403 it seems that it's just pinging someone (@jbteves , mostly :smile_cat: ) to remove the stale label. So maybe we should just exempt it and devise another method to check-in on those discussions ?

**Comment by tsalo** [comment]
> Should 'discussion' also be exempt?

I think `bug`, `paused`, and `good-first-issue` should be exempt, but not necessarily `discussion`. Bugs remain problems even if they're minor and no one has addressed them. Paused issues are already on a specific timeline, so they shouldn't be subject to an arbitrary time limit. Good first issues are there for any interested newbies, and we don't really control when those new folks will develop an interest in contributing to tedana. I think discussions should close if there's no interest, and I agree with the others that hopefully stalebot notifications will get us invested in those discussions again.

**Comment by tsalo** [comment]
It looks like our current setting is 90 days before flagging, rather than 60 days.
