### ISSUE TITLE
Add buttons from "Is it maintained?"

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#533]
### Summary
I noticed on the [datalad-extensions repository](https://github.com/datalad/datalad-extensions) that they have buttons for percentage of open issues and average time to issue resolution from [Is it maintained](https://isitmaintained.com/project/ME-ICA/tedana). I thought the buttons might be nice for us to use as well.

### Additional Detail
[![Average time to resolve an issue](http://isitmaintained.com/badge/resolution/ME-ICA/tedana.svg)](http://isitmaintained.com/project/ME-ICA/tedana "Average time to resolve an issue") [![Percentage of issues still open](http://isitmaintained.com/badge/open/ME-ICA/tedana.svg)](http://isitmaintained.com/project/ME-ICA/tedana "Percentage of issues still open")

### Next Steps
1. Vote
2. Add buttons (or don't) to README.
3. Add buttons (or don't) to RTD index page.

**Comment by emdupre** [comment]
Can I vote with the :heart: emoji ? :wink:
