### ISSUE TITLE
More documentation for --tedpca

### ISSUE THREAD

**Issue by benoitberanger** [ME-ICA/tedana#547]
### Summary

Between version **0.0.7** and **0.0.8**, the `--tedpca` parameter changed.
Is it planned to enhance the documentation explaining which _tedpca_ does what ?

### Additional Detail

The "decision tree" part in the code is proably the most difficult part 

Help in **0.0.7** :
```
Possible choices: mle, kundu, kundu-stabilize
Method with which to select components in TEDPCA
Default: “mle”
```

Help in **0.0.8** :
```
Possible choices: kundu, kundu-stabilize, mdl, aic, kic
Method with which to select components in TEDPCA. PCA decomposition with the mdl, kic and aic options is based on a Moving Average (stationary Gaussian) process and are ordered from most to least aggresive. Default=’mdl’.
Default: “mdl”
```

### Next Steps

Explain a bit more what does each decision tree ?
In particular, why "mdl" is choose to be the default one ?

**Comment by tsalo** [comment]
@eurunuela You know the PCA methods best at this point. Would you be willing to take this on?

**Comment by eurunuela** [comment]
Sure, I can tackle this!

**Comment by eurunuela** [comment]
#551 should take care of this.

**Comment by benoitberanger** [comment]
Thanks you @eurunuela and @tsalo !

**Comment by eurunuela** [comment]
I'm going to reopen this as some people still feel like this section of the docs is not very clear.
