### ISSUE TITLE
Topics for March 2020 Developers’ call: Pandemic Edition

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#550]
Use this thread to bring up potential topics to discuss. Next week I'll reorganize the topics into a meeting agenda/minutes Google Doc.

### Scheduling question
The developers’ call is scheduled for Friday, March 20, at 10:00AM EST ( [Click for other time zones](https://arewemeetingyet.com/New%20York/2020-03-20/10:00/Tedana%20March%20Dev%20Call) ). 

The first major question is should we move the time? The pandemic has mixed up my whole schedule, but I think the standard time for this call should still be fine for me. How about others?  I’m realizing that we’re cross scheduled with the https://ohbmx.org twitter conference. Are people planning to spend that whole work-day focused on that conference? If so, I can open a poll to identify an alternate meeting time for this month.

### Action items or updates from the [February Call](https://docs.google.com/document/d/1ckABlMg4t1KAPCIBTRzCMErADTehokNUry24ym-3mlg/edit?usp=sharing)
- Update on getting some some of the new reporting code into master ( a combination of #457, #465, #467 ) @emdupre
- Updates on modularization & masking issues #475, #476, (@handwerkerd @tsalo)
- Decision making and possibly a broader governance discussion. Everyone should look at #526 in advance. At the last meeting, we planned to give people a deadline to provide feedback, I don’t think we every announced a deadline. We should do that soonish and set a realistic deadline.
- Open an issue on how to track & credit author contributions & update Zenodo ( @emdupre )
- Update on AFNI Code Convergence + tedana code sprint
- Update of GSOC student (@KirstieJane )
- There is now an open issue (  #520 ) for making a documentation section on use cases and multi-echo benefits. Contribute!
- Update on responders regarding our regular dev call times (@handwerkerd & @emdupre)
- Look into testing coverage, particularly with regards to PCA/ICA to see if any key areas aren’t yet covered ( @jbteves @eurunuela )

### Check issues marked as stale
- Add binder examples #149 (closed. Should it be re-opened?)
- Add information about duecredit to contributing guidelines #362 (closed. Should it be re-opened?)
- Calculation of variance explained appears wrong #317 (closed. Should it be re-opened?)
- Outline memory required for tedana to run#267 (closed. Should it be re-opened?)
- Reduce memory usage for metric calculations #269 (closed. Should it be re-opened?)
- Revisit signal > noise t-value metric #274 (closed. Should it be re-opened?)
- get_coeffs run on mean-centered data for no reason #179 (closed. Should it be re-opened?)
- Consider updating required status checks #506 (marked stale)

### New topics for the March Call
- Worth discussing the OHBM symposium & tedana presence at OHBM before knowing if OHBM will happen on schedule? #509
- @handwerkerd plans to go through the new open issues & PRs and add them here.

### Topics to cover in a future call
-	Webinar on testing #510

**Comment by eurunuela** [comment]
I can do Friday at 10 AM EST.

Regarding the testing coverage of `ma_pca.py`, I opened #549. I’ll look at the coverage of the other decomposition functions tomorrow and potentially write a couple of unit tests.

**Comment by KirstieJane** [comment]
Hey folks! Unfortunately I can't make the 3pm time on Friday this week - I'm looking after my niece (the schools aren't closed here yet, but my sister needs to be at work). I'm happy for the call to go ahead without me - and for you to use my zoom room (I'm so sorry again for February's mixup!)

I didn't have capacity to mentor GSOC students this year, so no GSOC students for us.

**Comment by handwerkerd** [comment]
Given the state of the world and not many comments here, I wanted to make sure at least a few people are interested in having the call this Friday. Even if there isn't immense progress to share, it would be good to check in. If people are interested, but the time no longer works, we can try another time. Hope everyone is ok.
@emdupre @tsalo @smoia @jbteves @javiergcas @dowdlelt @benoitberanger

[Not fully serious: @KirstieJane Since I'm working at home, we can both have kids join the call and start training the next generation.  :smile: :fist: ]

**Comment by jbteves** [comment]
I'm interested but unfortunately cannot make that time.

**Comment by emdupre** [comment]
I have the time blocked off, but it's a small group I'm happy to just say hello and do a little video co-working on tedana, if folks would be interested in that !

**Comment by dowdlelt** [comment]
I'm available at that time. Co-working/brief meeting/updates/seeing more humans/etc all sound good by me.

**Comment by handwerkerd** [comment]
OK. Let's still with the currently scheduled time. I will try to clean up/prioritize agenda for tomorrow. Besides governance/decision making, most of the stuff on the agenda really is just checking in anyway. It will be good to catch up.

**Comment by benoitberanger** [comment]
Hello everyone,
I'll be available at that time (10AM EST == 4PM CET).
Cheers,
Benoît

**Comment by eurunuela** [comment]
Hi @benoitberanger , I believe it's at 3 PM CET 😉 You can check it [here](https://arewemeetingyet.com/New%20York/2020-03-20/10:00/Tedana%20March%20Dev%20Call).

**Comment by KirstieJane** [comment]
Hi everyone! Due to covid19 I'm _not_ babysitting my niece today (my sister works in the NHS and wants to keep the edges that she creates in the network as small as possible) so I can join the call!

See you at 2pm my time - but as @eurunuela says - please [check the link](https://arewemeetingyet.com/New%20York/2020-03-20/10:00/Tedana%20March%20Dev%20Call) because some places haven't changed to daylight savings and some have and so the time difference is harder to calculate! 

A quick heads up - my lab has a standing remote coffee chat at 3pm so they'll appear on the call at the end of our meeting! Probably not a problem, but just a heads up to keep us to time! You're all very welcome to say hello if you'd like a coffee and hangout too ☕️ 👋

**Comment by handwerkerd** [comment]
The link for the minutes for this meeting is at: https://docs.google.com/document/d/16Vmyb9m4KoRoFAkpq4DJMOWbyXMTJlhojsyY1h3MByg/edit?usp=sharing Hope to see some of you soon.
