### ISSUE TITLE
Shape mismatch , during unmasking

### ISSUE THREAD

**Issue by giorgos4** [ME-ICA/tedana#553]
Hi everyone,
I encountered a shape mismatch error while running tedana on 3 functional files with different echo times. 

Traceback (most recent call last):
  File "/home/giorgos/.local/bin/tedana", line 11, in <module>
    load_entry_point('tedana', 'console_scripts', 'tedana')()
  File "/home/giorgos/tedana/tedana/workflows/tedana.py", line 672, in _main
    tedana_workflow(**vars(options))
  File "/home/giorgos/tedana/tedana/workflows/tedana.py", line 504, in tedana_workflow
    io.filewrite(utils.unmask(dd, mask),
  File "/home/giorgos/tedana/tedana/utils.py", line 132, in unmask
    out[mask] = data
ValueError: shape mismatch: value array of shape (32264,300) could not be broadcast to indexing result of shape (32268,300)

PCA found 51 components using mdl and ICA converged. No explicit mask was provided so tedana created an adaptive mask. I tried using explicit mask but I got the same error. 

Dimensions of the functional files were the same.

Has anybody encountered the same problem and knows how to solve it ?

Thanks in advance !

**Comment by tsalo** [comment]
Hi @giorgos4. Thank you for opening this. This bug is actually already logged in #490, so I'm going to close this issue, but just know that we're aware of the issue but haven't fixed it yet. Please feel free to follow up in the thread in #490 though.
