### ISSUE TITLE
Resolving summation/averaging ambiguity in multi-echo combination methods

### ISSUE THREAD

**Issue by jsheunis** [ME-ICA/tedana#556]
### Summary

Hi folks. I am currently working on comparing outcomes of various real-time multi-echo combination methods. I have read the methods in the [Posse (1999)](https://www.ncbi.nlm.nih.gov/pubmed/10398954), [Poser (2006)](https://www.ncbi.nlm.nih.gov/pubmed/16680688) and the [Kundu (2012)](https://www.ncbi.nlm.nih.gov/pubmed/22209809) papers, have looked at the `tedana` code for T2*-weighted ("optimal") combination and have coded my own scripts as well. I am a bit confused by how Posse (1999) define their combination methods vs how most other sources refer to them, and I'm hoping you can help me interpret it correctly.

### Additional Detail
I think the ambiguity I'm experiencing results from the definitions of weighted _summation_ vs weighted _averaging_ and how different sources understand and use this terminology. Posse (1999) is the main source of the T2*-weighted combination method, cited by Poser (2006), Kundu (2012) and `tedana`. This is a snapshot of the equations given in Posse (1999):

![image](https://user-images.githubusercontent.com/10141237/77860448-a36b1000-720f-11ea-8629-d75f77ea7da9.png)

Neither in the text above nor anywhere else in the paper do the authors refer to a weighted average. I should add that a weighted _summation_ is equal to a weighted _average_ if the weights add to 1, i.e. if the weights are normalised. But this is not mentioned in the Posse (1999) paper. It could, however, be the case that that is what they meant (i.e. weighted _average_), and that their methods actually implement a weighted average. But from my reading of the paper I couldn't deduce that.

**However**, in all the subsequent papers and in `tedana`, the weights (in Eq.7 above) are either normalised (as given in Poser and Kundu papers) or explicit mention is made of a weighted _average_, or both.

So, could someone give me a sanity check on this please? Am I misunderstanding some fundamentals of these definitions, or the way in which the combinations are calculated? Or is it a terminology issue?

### Specific questions

1. Do you agree with my understanding of summation vs averaging?
2. Did Posse (1999) actually use weighted summation (with non-normalised weights)? Or did they do weighted averaging (as all other sources seem to suggest) while using (IMO) ambiguous terminology?
3. A bit unrelated (please tell me if I should split this off as a separate issue), I looked at the [`tedana` code](https://github.com/ME-ICA/tedana/blob/master/tedana/combine.py#L94) for the PAID combination method. If I'm reading the code and the PAID method correctly, it seems that there should be a tSNR calculation in that line, i.e. it needs to be divided by the standard deviation of the data as well. Currently it's the mean of the data multiplied by the TEs. Am I missing something?

Thanks!

**Comment by tsalo** [comment]
> 1. Do you agree with my understanding of summation vs averaging?

I can't speak to what Posse originally did, but I agree that the equation 7 above doesn't lead to normalized weights, which, with weighted summation, would lead to different scales for different T2* values (see curve below from [this notebook](https://github.com/tsalo/misc-notebooks/blob/master/tedana_summation_vs_averaging.ipynb)):

![image](https://user-images.githubusercontent.com/8228902/78255388-3e404480-74c5-11ea-8084-f3bf85a406b9.png)

I have noticed in the past that our weighted averaging can lead to predicted values _not_ on the decay curve, as in https://github.com/ME-ICA/tedana/issues/93#issuecomment-437687531. I looked into linear interpolation as a solution, but that would lead to bad results in cases with bad T2* estimation. However, this original formula _does_ make me wonder if unnormalized weighted summation would produce combined values along the decay curve better than weighted averaging. It's something I will have to look into.

> 3. A bit unrelated (please tell me if I should split this off as a separate issue), I looked at the tedana code for the PAID combination method. If I'm reading the code and the PAID method correctly, it seems that there should be a tSNR calculation in that line, i.e. it needs to be divided by the standard deviation of the data as well. Currently it's the mean of the data multiplied by the TEs. Am I missing something?

Just based on a quick glance, I think you're right, but it would probably be good to open a separate issue about PAID.

**Comment by jsheunis** [comment]
Thanks, @tsalo. I'll look into your notebook and the linked issue a bit over the weekend. Will open a new issue for the PAID method.

**Comment by jsheunis** [comment]
@tsalo is the 8-echo dataset that you used for the documentation and [here](https://github.com/ME-ICA/tedana/blob/master/examples/plot_approach_figures.ipynb) available online somewhere? I would like to compare different echo-combination methods and put it all in a notebook. I have my own 3-echo set, and I think a 4-echo dataset is on OpenNeuro, but 8 echos would be great as well :)

**Comment by tsalo** [comment]
@jsheunis The 8-echo dataset was acquired by @dowdlelt and he shared it with the tedana devs for debugging/testing, so it's not available publicly.

**Comment by dowdlelt** [comment]
I'll look into some things. I think this latest, floc dataset is good to share, would OpenNeuro be a valid target (@tsalo you probably know more about this...)?

**Comment by tsalo** [comment]
@dowdlelt I think that would be great! OpenNeuro will require some additional files for BIDS-compatibility, but I think it's worth the effort to add more multi-echo datasets to a popular database.

**Comment by dowdlelt** [comment]
I actually just helped with BIDSyfying a dataset for OpenNeuro and it went live today, so all the details are fresh for me. I'll clean it up a bit and see what I can do.

**Comment by dowdlelt** [comment]
May be wrong about permissions, looking into it (for this data and other). In any case, there will be data sharing in the future. Once scanning can happen again.

**Comment by jsheunis** [comment]
@tsalo @dowdlelt thanks for looking into it, no rush. But would it be useful in future, agreed.

**Comment by tsalo** [comment]
I've updated my original notebook with a very quick check comparing weighted summation vs. averaging (see [here](https://github.com/tsalo/misc-notebooks/blob/f1a5dc6d7b080170ca6636013b9509b7e3bb9475/tedana_summation_vs_averaging.ipynb)).

I basically just took some values guesstimated from https://github.com/ME-ICA/tedana/issues/93#issuecomment-437687531 and plotted the weighted average and the weighted sum in a scatter plot.

First we have the weighted average (red dot) along with the data points (green dots), with echo times and T2* in the X-axis and the values on the Y-axis:

![image](https://user-images.githubusercontent.com/8228902/102642120-309e1e00-412b-11eb-86a0-340dfb9ffe09.png)

As you can see, the weighted average is clearly not on the curve, but it's not terrible.

Here I've added the weighted sum (blue dot) onto the previous plot:

![image](https://user-images.githubusercontent.com/8228902/102642183-4a3f6580-412b-11eb-9822-05c6f49eedd0.png)

Clearly the weighted sum is _terrible_. Assuming my approach isn't completely wrong (I don't think it is), I think we can conclude that weighted average >> weighted sum. IMHO, the original Posse paper must have either had weirdly scaled results or there was something lost in translation from the code to the paper.

**Comment by tsalo** [comment]
@jsheunis do you think my simulations are sufficient to answer the question (i.e., should we close this issue)?
