### ISSUE TITLE
Confirm if PAID echo combination method is implemented correctly

### ISSUE THREAD

**Issue by jsheunis** [ME-ICA/tedana#558]
### Summary

I'm working on a variety of echo combination methods and was investigating the PAID method by [Poser et al. (2006)](https://doi.org/10.1002/mrm.20900). I looked into the `tedana` code for this method and noticed that [this line](https://github.com/ME-ICA/tedana/blob/master/tedana/combine.py#L94) (the second line in the code block below) only contains the data mean and not tSNR, i.e. the mean divided by standard deviation. Here are the main lines of code from the PAID method in `tedana`:
```
n_vols = data.shape[-1]
alpha = data.mean(axis=-1) * tes
alpha = np.tile(alpha[:, :, np.newaxis], (1, 1, n_vols))
combined = np.average(data, axis=1, weights=alpha)
```
### Additional Detail
Here's a screenshot of where the method is described in Poser et al. (2006):

<img width="339" alt="Screen Shot 2020-04-03 at 15 37 46" src="https://user-images.githubusercontent.com/10141237/78367733-dc660480-75c2-11ea-93fa-30e51ec3ad4d.png">

I also noticed that [the description](https://github.com/ME-ICA/tedana/blob/master/tedana/combine.py#L67) for the PAID method in `tedana` mentions *"Combine data across echoes using SNR/signal and TE via the..."*. Does this mean it uses SNR ***or*** signal? This might clarify the absence of standard deviation in the equation, but in that case some more clarification of the reasoning behind that decision could be useful.

### Next Steps
Is the absence of the division by standard deviation an oversight or intentional? If intentional, is there some documentation available as to why?

**Comment by tsalo** [comment]
My assumption up to this point has been that the results would end up being identical (or at least very close), but I haven't thought about it really. That isn't the case, based on some tests I've run locally.

It does look like the current PAID implementation has been around since the original meica.py code (see [here](https://github.com/ME-ICA/me-ica/blob/53191a7e8838788acf837fdf7cb3026efadf49ac/meica.libs/t2smap.py#L290-L293)):

```python
if options.combmode == 'ste':
    alpha = fdat.mean(-1)*tes
else: 
    alpha = tes * np.exp(-tes /ft2s)
```

I think the correct implementation would be the following, and would be happy to open a PR if others agree:

```python
snr = data.mean(axis=-1) / data.std(axis=-1)
alpha = snr * tes
alpha = np.tile(alpha[:, :, np.newaxis], (1, 1, n_vols))
combined = np.average(data, axis=1, weights=alpha)
```

**Comment by emdupre** [comment]
Just wanted to tag in @handwerkerd and @javiergcas , as they might have some insight into why the code was originally written that way..

But your proposal makes sense to me, @tsalo !

**Comment by jsheunis** [comment]
I don't have any history with the original code, but from my understanding of the PAID equation this looks right.
