### ISSUE TITLE
Acknowledge contributors to tedana

### ISSUE THREAD

**Issue by KirstieJane** [ME-ICA/tedana#56]
We're currently acknowledging the "tedana developers" in the docs, which is great - I think that's a really nice catch all for all the different ways that people can contribute.

However, I think it would make sense to also list their names and the types of contributions they have made. I really like the [emoji key](https://github.com/kentcdodds/all-contributors#emoji-key) as proposed by [Kent Dodds](https://github.com/kentcdodds) in the [All Contributors](https://github.com/kentcdodds/all-contributors) project.

Here's [an example](https://github.com/softwaresaved/code-cite#contributors) from a little hack project I ran.

![image](https://user-images.githubusercontent.com/3626306/40063252-d1784412-5854-11e8-9213-54f6ba1bdc5c.png)

You can also look at a bunch of the different contributions via [Let's All Build a Hat Rack](https://labhr.github.io/hatrack/#repo=ME-ICA/tedana). (You might have to sign in with your github ID to reload the page.)

I propose adding an emoji key to the README file and populating it with the people listed at the LABHR page.

What do you think?

**Comment by emdupre** [comment]
Thanks for bringing this up, @KirstieJane ! Acknowledging contributions is definitely something we should be doing more.

Although this is still a far off worry, since we're actively soliciting contributors I'm somewhat concerned that eventually the list will overwhelm the README. What do you think of either linking out to the [Let's All Build a Hat Rack](https://labhr.github.io/hatrack/#repo=ME-ICA/tedana) page or creating a new `contributors.md` file ?

**Comment by jbteves** [comment]
@emdupre and @KirstieJane do you have any additional thoughts on this? For my 2 cents, I think it would be good to create a contributors.md file. I have no strong feelings about emoji, both here and generally, as long as there is some indication of what the contributions are for each contributor.

**Comment by KirstieJane** [comment]
Heya! I LOVE the new @all-contributors bot: https://allcontributors.org/docs/en/bot/overview

Basically you add it to the repo and then when you want to acknowledge a contributor you just ask the bot to open a pull request to add that person to the table in the README file.

It uses the [emoji key](https://allcontributors.org/docs/en/emoji-key) so it's super easy to acknowledge lots of different types of work for the project 😄

**Comment by jbteves** [comment]
I'm going to operate under the assumption that nobody will be opposed to this and open #259 to have that done. If anybody does disagree, then we can close that.

**Comment by jbteves** [comment]
As an update; @emdupre seems to be on board with using all-contributors bot, and I think most discussion related to closing this has been migrated to #259 or Gitter at this point. In light of that, I'm closing this issue as redundant to the more focused #259.
