### ISSUE TITLE
Topics for April 2020 Developers’ call

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#561]
The developers’ call is scheduled for Friday, April 17, at 10:00AM EST ( [Click for other time zones](https://arewemeetingyet.com/New%20York/2020-04-17/10:00/Tedana%20April%202020%20Dev%20Cal) ).

Use this thread to bring up potential topics to discuss.  

The current agenda is at: [tedana Minutes 2020-04-17](https://docs.google.com/document/d/16nQImUpEzCLhzrPYpxysgT_JMSlNb2lp9tr2Ti67h1Q/edit?usp=sharing)

**Comment by tsalo** [comment]
Some topics I think we should cover:
- Details of the decision-making document (#539).
    - What constitutes a voteable issue/PR?
    - When does the BDFL have to weigh in? Hopefully very rarely.
- Releasing 0.0.9 sooner rather than later (#487 and #540).
- Plans for 0.0.10.

**Comment by emdupre** [comment]
I won't be able to join until 10:30a, sorry about that ! I'd also like to quickly check in on #558 and #457 if there's time to discuss them then ! :smile_cat:
