### ISSUE TITLE
Replace comma-separation in --manacc with space-separation

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#563]
### Summary
In most cases where we allow multiple inputs for a given argument (e.g., `-d`, `-e`, and `--gscontrol`), `tedana` accepts a space-separated list at the command line. This should simplify how `manacc` is handled internally, since the tools already exist to parse `nargs='+'`, and I feel like space-separated parameters are more intuitive at the command line. 

### Next Steps
1. Set `nargs` for  `--manacc` to `'+'`.
2. Set `type` for `--manacc` to `int`.
3. Remove string parsing for `manacc` within `tedana_workflow`.
4. Update documentation.
5. Update any tests that use `manacc`.

### Discussion
Emoji vote below: 👍 for yes and 👎 for no.

**Comment by emdupre** [comment]
When do you want to close the voting on this, @tsalo  ? :smile_cat:

**Comment by tsalo** [comment]
Next Friday maybe? August 14.
