### ISSUE TITLE
Zenodo DOI for tedana

### ISSUE THREAD

**Issue by KirstieJane** [ME-ICA/tedana#57]
It's important that people are able to cite *tedana* and (very importantly) the version of the code that they've used. At the moment we only ask people to cite [Kundu et al, 2012](https://www.ncbi.nlm.nih.gov/pubmed/22209809) and we should absolutely still require that citation, but we should also add in a citation to the code and acknowledge the people who have done so much work refactoring and testing the code.

[Zenodo]() allow us to archive a release into their repository. What's great is that they give us a "concept DOI" and a "version DOI" so you can refer to the python module (this repo, the concept) or the specific release that was used for their analyses. (See their blog on [DOI versioning](http://blog.zenodo.org/2017/05/30/doi-versioning-launched/) for more information).

Here's [an example](https://github.com/softwaresaved/code-cite) from a hack project that I ran.

![image](https://user-images.githubusercontent.com/3626306/40063617-a8651a90-5855-11e8-9b18-ab38e99f50d7.png)

The logistics of adding the appropriate files/metadata aren't too hard, but there's a bit of a **challenging discussion point** to be had by the *tedana* community about what constitutes authorship.

My proposal is that in the first instance @emdupre decides who has contributed sufficiently to being an author. I think these discussions do not need to be open, but I think we could commit to building up guidelines for future releases.

(@emdupre - if you'd like to also form a mini committee to reign in your powers I think that's also a very sensible position to hold. But to be clear - I think you've lead the development of this python module and therefore you should have the final say on how we assign authorship.)

The overall goal is to allow new contributors to *know before they start* what they should expect from their contributions. If you come along and say something useful on an issue - does that count as authorship? My gut instinct would be to say no, but I think that regular comments that are helpful would push someone up to author status. I don't think lines of code are a sensible metric either as someone who mentors others or who reviews PRs is a very valuable member of the community and should be acknowledged.

I know authorship is basically the worst part of academic publishing, and I personally would love it if we could just stick with the emoji key I've suggested in #56, but that isn't the world in which we live and I also want to make sure that people get fair acknowledgment for all their work.

**Comment by emdupre** [comment]
Thanks so much for sharing your thoughts, @KirstieJane ! Yes, I agree that authorship in general is a tough question. At this point, the pool of contributors for both [code](https://github.com/ME-ICA/tedana/graphs/contributors) and mentorship is rather small, so it's easier to weigh contributions. But it will certainly get more complicated as time goes on (and we get more people contributing, I hope !).

For at least this first release, to make things easier, I might make the judgement calls. But as we build towards a major release, I'd love to think more about how we could form a "steering committee."

**Comment by tsalo** [comment]
I think this is ready to close, but I noticed that we haven't updated the RTD site or the init file with a citation for the Zenodo release. I've opened #66 to address that.

**Comment by tsalo** [comment]
Related to this issue, is there a reliable way to track citations of Zenodo DOIs? Support on Google Scholar seems spotty at best.

**Comment by KirstieJane** [comment]
Great question @tsalo - I can tweet this at a few people and see if they have any answers! I do have a [separate project](https://github.com/softwaresaved/code-cite) that's trying to mine the literature to find these DOIs.....but it would be better if we could track *a specific* DOI more easily!

**Comment by tsalo** [comment]
That would be great @KirstieJane! Thanks!

**Comment by emdupre** [comment]
Bumping this, it looks like we can circulate one DOI that will resolve to the latest version release -- fMRIPrep is doing that [here](https://github.com/poldracklab/fmriprep/pull/1024#discussion_r205959935).

It would certainly be easier to track _one_ DOI rather than one for each version !

**Comment by KirstieJane** [comment]
@emdupre - you get the two DOIs for free - a specific doi for the release and a concept doi. Happy to focus on sharing the concept doi if that makes the most sense.

I'm getting a bit jetlagged today and running out of steam - but I can work on this issue tomorrow (Tuesday) if that's useful?

**Comment by KirstieJane** [comment]
Gotcha - yes - I think the "concept" language I got from zenodo - I agree that it isn't the most intuitive wording.

Lets see if I'm feeling motivated tomorrow to integrate some (more) of this information into the docs (I know #66 is already merged) ✨ 

Might ping you in gitter if I'm hitting points for discussion 😸

**Comment by tsalo** [comment]
In the documentation, I think it makes sense to reference the concept DOI, but duecredit should use the version-specific DOI so that papers actually cite the relevant version and we can track version-specific usage. If that's possible, then it will make it all the easier to identify which papers are affected by any bugs we might identify, or larger changes we might make, associated with a given version.

**Comment by emdupre** [comment]
I think this might be closed with #109. Now, our RTD site is building with the DOI for the most recent release, which is great !

@KirstieJane @tsalo, please let me know there's anything else you think we should address in this issue !
