### ISSUE TITLE
Pre-release naming convention

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#570]
### Summary
Continues from https://github.com/ME-ICA/tedana/pull/568#discussion_r425811608, but separated into its own issue for posterity. We have two competing naming conventions for unstable/pre-releases: alpha (`X.X.Xa[0-9+]`) and release candidate (`X.X.Xrc[0-9+]`). In our release history, we have two cases of each: 0.0.5rc1 and 0.0.5rc2 for release candidate and 0.0.9a0 and 0.0.9a1 for alpha. 

### Next Steps
Please vote :tada: for the release candidate system and :rocket: for the alpha system.

**Comment by jbteves** [comment]
We can't react with those emojis, unfortunately on a few are supported. I'll put two comments below and people can thumbs-up for them.

**Comment by jbteves** [comment]
🕯 a[0-9]

**Comment by jbteves** [comment]
🔤 rc[1+]

**Comment by tsalo** [comment]
Ugh so frustrating!!!! I'll change the vote-mojis then.

**Comment by emdupre** [comment]
It seems that they can coexist according to semvar:

> 1.0.0-alpha < 1.0.0-alpha.1 < 1.0.0-alpha.beta < 1.0.0-beta < 1.0.0-beta.2 < 1.0.0-beta.11 < 1.0.0-rc.1 < 1.0.0.

Still, to reflect common usage I'd agree to adopt one or the other. My vote is for `rc`, but it's not a strong opinion.

**Comment by jbteves** [comment]
Oops, sorry, I missed that @tsalo 

I'm fine with either, but do think we need to pick one.

**Comment by tsalo** [comment]
@emdupre, whoa.... yeah let's not have that intense a development cycle. Agreed about adopting one or the other. How about we close the polls on this (since it's not that big of a deal) on Friday?

**Comment by emdupre** [comment]
> How about we close the polls on Friday

Sounds reasonable to me !

**Comment by tsalo** [comment]
Okay, the polls have officially closed as of 10:31 pm EDT on July 13. Yes, this is 52 days _after_ when we said the poll would close, but, in fairness, I forgot.

Anywayyy... we have a majority vote for the RC system, and we shall adopt it henceforth.
