### ISSUE TITLE
Consolidate codecov files

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#573]
### Summary
If possible, I'd like to consolidate `codecov.yml` and `.codecov.yml` to reduce the number of files we have to maintain.

### Additional Detail
Both files should refer to the same thing, so hopefully we can move the contents of one into the other.

**Comment by tsalo** [comment]
I wonder if we can do the same thing to our requirements files? Can we just rely on tags in our installation (e.g., `pip install .[all]`) for everything, including docs building?

**Comment by emdupre** [comment]
Is this already taken care of, @tsalo  ?

**Comment by tsalo** [comment]
#575 deals with it.
