### ISSUE TITLE
Error at reshaping step in t2smap

### ISSUE THREAD

**Issue by bmdeen** [ME-ICA/tedana#578]
Hi all,

I'm getting an error running t2smap. The following command:

`t2smap -d fMRI_2p4mm_MB3_TR3-1.nii.gz -e 14.4 33.89 53.38 72.87 92.36`z

yields the error:

INFO:tedana.workflows.t2smap:Using output directory: /Users/ben/NeuroscienceResearch/SEQTEST_HUM/WAF_seqtest_01/func/tmp_t2s
INFO:tedana.workflows.t2smap:Loading input data: ['fMRI_2p4mm_MB3_TR3-1.nii.gz']
Traceback (most recent call last):
  File "/opt/anaconda3/bin/t2smap", line 8, in <module>
    sys.exit(_main())
  File "/opt/anaconda3/lib/python3.7/site-packages/tedana/workflows/t2smap.py", line 256, in _main
    t2smap_workflow(**kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/tedana/workflows/t2smap.py", line 200, in t2smap_workflow
    catd, ref_img = io.load_data(data, n_echos=n_echos)
  File "/opt/anaconda3/lib/python3.7/site-packages/tedana/io.py", line 411, in load_data
    fdata = utils.load_image(img.get_data().reshape(nx, ny, nz, n_echos, -1, order='F'))
ValueError: cannot reshape array of size 508032000 into shape (84,84,14,5,newaxis)

Looking at this output, it looks like the script thinks my data have 14 slices, when in fact the data have 72 slices, leading to a reshaping error. Any idea what might be going wrong here?

Data can be found at: https://www.dropbox.com/sh/xhxv8rbdzkscn8x/AAA-jRJIf08SHfptcTlGpVlza?dl=0

I'm running this on a macbook pro, OS 10.14.5, with Python 3.7.6, and I cloned the tedana repository a few days ago. This is my first time running the scripts, but I believe all of the dependencies are installed.

Thanks!

Ben

**Comment by tsalo** [comment]
Hi Ben. It looks like your file has the shape `(84, 84, 72, 1000)`. Are the five echoes concatenated in the fourth dimension?

When one file is provided, `t2smap` (and `tedana`) assumes that the data are z-concatenated- i.e., that the echoes are stacked on top of each other along the z axis. This is how the original ME-ICA pipeline operated on data. Generally, we recommend providing one file per echo, as that matches the BIDS standard. You may need to reshape or split your data before feeding it into `t2smap`.

**Comment by bmdeen** [comment]
Ah ok, yes, my data were concatenated across time. Got this to work with separate files for each echo. Thanks!
