### ISSUE TITLE
Add y = x line to Kappa/Rho scatterplot

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#582]
### Summary
We should add a line to the Kappa/Rho scatterplot to make it easier to see when Rho > Kappa and vice versa. The line should be muted and not too obtrusive.

~~We should give the Kappa and Rho axes in the Kappa/Rho scatterplot the same scale, so that it's easier to tell when Rho > Kappa and vice versa.~~ Given that the scatterplot is now dynamic, giving the axes the same scale isn't a great solution.

### Next Steps
1. Discuss
2. Add the line to the bokeh figure.

**Comment by tsalo** [comment]
Given that the figure is now dynamic, a line at y = x might be better.

**Comment by emdupre** [comment]
I think [right here](https://github.com/ME-ICA/tedana/blob/d933592befa2260b599d76921ee956c9b7f7bef2/tedana/reporting/dynamic_figures.py#L154) we'd need to insert an additional line with a `fig.line` call. What I'm not immediately sure of is how to access the x- and y-lims in bokeh. 

[Here's the docs for the bokeh line glyph](https://docs.bokeh.org/en/latest/docs/user_guide/plotting.html#single-lines), btw !

**Comment by tsalo** [comment]
Adding a line seems pretty straightforward, so I'm putting GFI label on this.
