### ISSUE TITLE
Manual component classification in reports

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#583]
### Summary
We've discussed this on calls before, but I'd like to open an issue about it. Now that we have lovely reports, we should be able to update our component classifications _within_ the report.

### Additional Detail
This would take a lot of effort and is more of a long-term goal, but I think it's worth doing.

**Comment by tsalo** [comment]
Does anyone have any ideas about what this might look like within the reports?

I'm thinking that the component-wise mini-report could have a radio button multiple-choice at the bottom:
```
Manually classify component:
[] Accept component    [] Reject component    [] Ignore component    [] Retain classification
```
The last one is just to clear a manual classification in case someone accidentally hits the button.

**Comment by handwerkerd** [comment]
This will be a lot easier when the decision tree modularization with the function for manual selection is merged. That would also be able to add a node to component classification for a component so that there would be a record of it being classified as X & then manually reclassified to Y. As far as how to do this in the reports interface, I'm not sure what we'd want to do. 

The tricky part is, when would it effectively recalculate the denoised time series? After every time a component is reclassified? It seems like we would want a two step process where one can make a list of components to reclassify in the reports GUI, but then need to press a separate button or run a separate script to actually run the reclassification and denoising step.

**Comment by tsalo** [comment]
>The tricky part is, when would it effectively recalculate the denoised time series? After every time a component is reclassified? It seems like we would want a two step process where one can make a list of components to reclassify in the reports GUI, but then need to press a separate button or run a separate script to actually run the reclassification and denoising step.

I think a separate function/script is the way to go. I also think, as we move toward integrating with fMRIPrep more, folks will end up using bad components in other GLMs more than the denoised data.

**Comment by eurunuela** [comment]
I would be willing to take on this issue. I would love to learn some `React` (a JavaScript library to build complex UIs) and this issue feels like the perfect project to learn with.

**Comment by eurunuela** [comment]
I wanted to report back that I am close to replicating our current reports. I want to make sure the data structure makes sense for the JS charts before I import the data from tedana.

My idea is to have a 3-option button right next to the component ID that will let the users change the status of the components (accepted, rejected, ignored). This change will update the colors in the graph too.

Of course, there are still some styling changes to be made, but I'll address those once the core of the reports is functional.

![report_demo](https://user-images.githubusercontent.com/13706448/127737039-bf9d3323-5421-449f-8b61-a3d051201087.gif)

P.S.: Sorry if the GIF is too small. I recorded it on a big screen.

**Comment by eurunuela** [comment]
Update: I managed to come up with a simple data structure and replicate our current reports.

![tedana_reports_demo](https://user-images.githubusercontent.com/13706448/127750376-f80640e0-f15e-43c5-88d3-8859fdcf9cf9.gif)

**Comment by tsalo** [comment]
Based on @eurunuela's work, it doesn't look like manual classification will work with bokeh, so we're pivoting to creating a Javascript package for generic ICA reports with manual classification, which will go in [ME-ICA/ica-reports](https://github.com/ME-ICA/ica-reports). Hopefully, this package will eventually also be linked to a web service so folks can view reports online.

**Comment by eurunuela** [comment]
I had completely forgotten about this issue. Thank you @tsalo !
