### ISSUE TITLE
Topics for the July 2020 Developers Call

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#584]
### Summary
The tedana developer's call is scheduled for this Friday, July 17th, at 10:00 EST, 14:00 UTC.
[Check your local time here](https://arewemeetingyet.com/New%20York/2020-07-17/10:00/tedana%20dev%20call)
[The current agenda](https://docs.google.com/document/d/1YOc0PdSHdBUaknSVtFuHoCMF1LmPIyOYws0XBqjLVuE/edit?usp=sharing) 
[Zoom link](https://us02web.zoom.us/j/87523039100?pwd=aVRIZ25JbTQ0VGxnVGx0b29sTUhQZz09)

Please comment below or in the agenda to indicate items you'd like to see added or reprioritized in the agenda.

**Comment by emdupre** [comment]
Closing since the call has passed. For anyone looking to catch-up on the minutes, please check the agenda link !
