### ISSUE TITLE
Add count of floored T2* values in logging

### ISSUE THREAD

**Issue by dowdlelt** [ME-ICA/tedana#589]
### Summary
Related to #585 
We now have `_apply_t2s_floor`, which fixes divide by zero issues related to very low t2* estimates. It may be useful to have the option to record the number of voxels corrected with this, perhaps when asking for verbosity. I don't see any obvious dangers of the correction, but currently it is invisible.

### Next Steps
- [ ] count the number of voxels that have "bad" values
- [ ] report this value if verbosity is requested.

**Comment by jbteves** [comment]
Thanks for opening this issue @dowdlelt ! 
I agree that this would be good because if it happens a *lot*, it could be an early warning that something has gone wrong.
