### ISSUE TITLE
Topics for the August 2020 Developers Call

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#594]
### Summary
The tedana developer's call is scheduled for this Friday, August 21st, at 14:00 UTC, 10:00 EST.
[Check your local time here](https://arewemeetingyet.com/New%20York/2020-08-21/10:00/tedana%20August%202020%20Developers%20call)
[The current agenda](https://docs.google.com/document/d/15LVJCt6dmmV2HjmgMw2xM-JCNccpP9rY8kY5a96c7II/edit?usp=sharing) 
[Zoom link](https://us02web.zoom.us/j/87860021610)

Please comment below or in the agenda to indicate items you'd like to see added or reprioritized in the agenda.

**Comment by jbteves** [comment]
Meeting has passed; closing.
