### ISSUE TITLE
Test auto-deployment

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#596]
### Summary
The open question regarding the changes in #568 is whether the person making the release on GitHub has to be the same person whose PyPi credentials are stored in CircleCI (namely, me).

### Additional Detail
None.

### Next Steps
1. Next time we make a release, someone else should actually make the release. **This cannot be release drafter though**. I know that release drafter-generated releases do not work, so we need to copy the contents of our release drafter-generated draft into a new release draft before making the release.
2. Check that the release is deployed to PyPi.
3. If it fails:
    - Delete the tag and the release on GitHub.
    - I will make the release _or_ we can change the environment variables to someone else's credentials so that someone else can be the releaser.
4. If it succeeds:
    - Celebrate.

**Comment by tsalo** [comment]
Now that #635 has been merged, I think we're ready to make the next release, but I'd love to hold off until #663 is merged if that's cool. @emdupre will you do the first release test? Would Friday work?

**Comment by emdupre** [comment]
It wouldn't bother me at all to cut it, but did we want to solicit user feedback first ?

**Comment by tsalo** [comment]
I just didn't think we were going to get any.

**Comment by emdupre** [comment]
It's a fair concern 😅 I just seem to remember in the last dev call we talked about reaching out specifically on the thresholding issue ?

**Comment by jbteves** [comment]
@tsalo I think #663 is ready to merge, you have all tests passing and several approvals. Let's merge it and release.

**Comment by jbteves** [comment]
@emdupre per the minutes, we agreed to wait for a week of feedback on #635. So we could go ahead and merge #663 and then release next Friday?

**Comment by emdupre** [comment]
Sorry @jbteves, I think I'm a little confused by what you're proposing ? I'm fine to wait until next Friday. We should probably directly follow-up on #/617 to ask for user feedback, if we want the chance of having any !!

**Comment by jbteves** [comment]
Sorry, that's my fault for responding to one comment at a time. I originally thought, "Yeah, release! Let's go for it!" but then I saw that you were right about us agreeing to wait a week, and we haven't specifically sought out feedback, so I figured we should do that today and then wait until next Friday to actually cut it as a consequence.
Relevant excerpts from notes:
> Plan is get 635 in, give a week for feedback, then cut a release before next dev call.

> Merging 635 is the last thing to consider before cutting a release (if they’re prompt, maybe also wait for Chuck & Mateo to test it on their data)

**Comment by tsalo** [comment]
Continuing from https://github.com/ME-ICA/tedana/issues/617#issuecomment-774109855

@jbteves, I believe that @emdupre is going to attempt to make the release. At minimum, the first person to try has to be someone other than me, since it's _my_ credentials that we'll be using. If it fails, then I'll do the release and we can revisit how we want to handle the credentials.

**Comment by jbteves** [comment]
Alright, that makes sense. Would it be possible for me to tag along via Zoom to see how it's done?

> we can/should also consider using the "Publish Python Package" GitHub Action
Do you mind opening an issue to discuss, @tsalo ?

**Comment by tsalo** [comment]
> Do you mind opening an issue to discuss, @tsalo ?

Can do, but I'll wait until _after_ we successfully make this release. If it fails, then the GitHub Action probably won't work either.

**Comment by emdupre** [comment]
> EDIT: Regarding Zoom, I can't speak for Elizabeth, but if it doesn't work for her we could try it. Although, at that point it will be clear that knowing how to make the release this way won't work for you either...

I'm on a coding sprint right now, but after 2p-ish I should be free. I hope it will be as simple as a button click but I can set up a quick jitsi to debrief after as you prefer @jbteves

**Comment by jbteves** [comment]
> Although, at that point it will be clear that knowing how to make the release this way won't work for you either...
Good point.

Let's only jitsi if it doesn't work with the button press, I'm free this afternoon so it's at your convenience.

**Comment by emdupre** [comment]
On here to debug :  https://meet.jit.si/tedana-009-release

**Comment by tsalo** [comment]
We jumped ship on the CircleCI-based approach, and moved to GitHub Actions. It worked (after like 4 tries)!
