### ISSUE TITLE
Bokeh Not Found with latest version

### ISSUE THREAD

**Issue by jbteves** [ME-ICA/tedana#601]
### Summary
When installing the latest version of `tedana`, `ModuleNotFoundError: No module named 'bokeh'`.

### Additional Detail
It seems that despite having a `requirements.txt` and a `dev_requirements.txt` file, we're actually using `tedana/info.py`, which does not have the latest changes including a more up-to-date bokeh. I'm actually slightly confused that our automated testing didn't fail on the integration tests.

### Next Steps
- [x] Open a PR to add bokeh to `info.py`

**Comment by tsalo** [comment]
The reason CI passes is that `dev_requirements` are installed:

https://github.com/ME-ICA/tedana/blob/150b5c0dd4e452ed00861e7e8d4347f1583599c5/.circleci/config.yml#L24

`dev_requirements.txt` in turn grabs all of the requirements in `requirements.txt`, which is where bokeh is listed.

**Comment by tsalo** [comment]
This should be good now that #575 has been merged, so I'm going to close it.
