### ISSUE TITLE
requirements and dev_requirements are misleading

### ISSUE THREAD

**Issue by jbteves** [ME-ICA/tedana#603]
### Summary
Related to #601, it seems that we have requirements and dev_requirements files which aren't actually used. We should either reconfigure `tedana` to use those files or delete them to avoid confusion. If you feel strongly about it, state your case below.

### Next Steps
- [ ] Figure out if we should incorporate the files or delete them

**Comment by tsalo** [comment]
This is part of https://github.com/ME-ICA/tedana/pull/575.

**Comment by jbteves** [comment]
Oh shoot, sorry I missed that.

**Comment by tsalo** [comment]
Closed by #575.
