### ISSUE TITLE
Topics for the September 2020 Developers Call

### ISSUE THREAD

**Issue by jbteves** [ME-ICA/tedana#604]
### Summary
The tedana developer's call is scheduled for this Friday, September 18th, at 14:00 UTC, 10:00 EST.
[Check your local time here](https://arewemeetingyet.com/New%20York/2020-09-18/10:00/tedana%20Developer%20Call%20September%202020)
[The current agenda](https://docs.google.com/document/d/1OXpml-qanhzaIRie4tOOJ71DFbp0lcZdu2nRATeJHHA/edit?usp=sharing) 
[Zoom link](https://us02web.zoom.us/j/87860021610)

Please comment below or in the agenda to indicate items you'd like to see added or reprioritized in the agenda.

NOTE: the currently linked agenda has not actually been modified for September 2020 yet.

**Comment by emdupre** [comment]
>  tedana developer's call is scheduled for this Friday, August 21st, at 14:00 UTC, 10:00 EST.

Should this be Friday, 18 September ?

**Comment by jbteves** [comment]
I'd like to highlight #575 and #592 + Pydra as discussion points, personally, as well as hopefully talk about governance.

**Comment by jbteves** [comment]
@emdupre it should be, whoops, edited.

**Comment by tsalo** [comment]
https://us02web.zoom.us/j/83238912315

**Comment by roboneuro** [comment]
> Hey guys, what's the new link?
We're on the one in the agenda !
