### ISSUE TITLE
Rename T1c to "minimum image regression"

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#605]
### Summary
In a manuscript that I'm working on, I describe, in detail, the method implemented in [`tedana.gscontrol.gscontrol_mmix()`](https://github.com/ME-ICA/tedana/blob/150b5c0dd4e452ed00861e7e8d4347f1583599c5/tedana/gscontrol.py#L111).
We generally refer to this method as either `gscontrol_mmix` (based on the array it works on), `T1c` (because it references a T1-like effect that it removes as "T1-correction"), or `MIR` (aka minimum image regression).  I don't recall the origin of the term "minimum image regression", beyond that regressing out a minimum image from a time series is very much a step in the function. I think it might have come from the original MEICA code, but please correct me if I'm wrong on that.

In any case, the method, while recommended in MEICA, is not actually documented in a publication AFAIK. This means that, unfortunately, the manuscript I'm working on might end up being the first detailed description of the method. To make things as clear as possible, I'd like to standardize how we talk about it, both in the documentation and in the code itself.

### Next Steps
1. Rename `gscontrol_mmix` to `gscontrol_mir`.
1. Incorporate detailed steps from my manuscript (still in-prep, sorry) into the docstring to make the procedure clearer.
1. Rename outputs to include `MIR` or `mir` instead of `T1c` (except for the map of the T1-like effect, of course).

**Comment by dowdlelt** [comment]
This may be useful: From previous conversations  Prantik indicated (https://github.com/ME-ICA/me-ica/issues/4#issuecomment-369058536) that minimum image regression was similar to GODEC, the method in "Ridding fMRI data of motion-related influences: removal of signals with distinct spatial and physical bases in multi-echo data" (Jonathan Power, Mark Plitt, Stephen Gotts, Prantik Kundu, Valerie Voon, Peter Bandettini, Alex Martin), here: https://www.pnas.org/content/115/9/E2105 and more here https://www.pnas.org/content/115/9/E2105.

**Comment by tsalo** [comment]
I recall you mentioning that the results were the same, although based on my (limited) knowledge of the GODEC code and the MIR code, the actual method is _very_ different. I vaguely remember GODEC not even successfully fitting to some test data, which isn't a possibility for MIR.

Since my manuscript is actually a replication of that Power paper (:laughing:), it might be a good idea for me to explicitly mention that in the manuscript. For the code, though, I think mentioning that similarity in the Notes section of the docstring is sufficient- I don't think we should name MIR GODEC or anything similar. Not sure if you were recommending that though.

**Comment by dowdlelt** [comment]
No, not suggesting that - and I was trying to retrace my steps to sort out why my brain was linking MIR and GODEC. 

I like the ideas for changes, because the mixture of all the names and acronyms has always confused me.

**Comment by tsalo** [comment]
I can open a PR for this fairly quickly, beforehand I'd like to reach consensus. It looks like we have 3 :+1:s (Elizabeth, Logan, and me). Anyone have any issues with the proposed change?
