### ISSUE TITLE
Roles in tedana: Call for nominations and discussion

### ISSUE THREAD

**Issue by jbteves** [ME-ICA/tedana#607]
### Summary
Per our developer call this morning, we will be asking people to nominate and self-nominate for the various roles that we foresee a community need for. These roles may be adjusted as we discuss them in more detail. Please see the current [decision making document](https://docs.google.com/document/d/1213KX0Jsr-I0aVHIF3Xdp3EZhORMWEoSDR7rT948K8U/edit?usp=sharing) for the overall context as currently proposed. We will also be soliciting nominations for steering committee members (self-nomination is acceptable).

#### Task manager & record keeper
- Helps write & keep track of notes from meetings
- Keeps track of issues or items that should be addressed
- Follows up with people who volunteered to address an item or alerts the broader community of known tasks that could use a volunteer
#### MR physics leader
- Someone who can make sure calculations fit within our understand of MR physics
- Someone who can either answer MRI physics questions related to multi-echo or direct people to where they can find answers
#### Processing algorithms leader 
- Someone who can make sure algorithms are appropriately implemented (or knows enough to delegate to someone who can make sure implementation is good)
- Someone who can either answer processing algorithm questions or direct people to where they can find answers
#### Collaborative programming leader
- Helps make sure tedana is following best practices for Python code design, testing, and communication for issues/pull requests etc.
#### Communications leader
- Mailing list manager & other outward-facing communication about the project
#### New contributors leader
- Leads efforts to make contributor documentation more welcoming
- Is a point of contact for potential contributors to make them feel welcome and direct them to relevant resources or issues
#### Multi-echo fMRI support leader
- Monitors places where people may ask questions about tedana or multi-echo fMRI and tried to find someone to answer those questions
#### Enforcer(s) of the Code of Conduct
- A person or people someone can go to if they want to report a code of conduct violation
- If this is one person, that person should NOT be on the steering committee
- If this is more than one person, at least one should not be on the steering committee
- Ideal is someone who cares about tedana but DOESN’T know contributors well enough to say, ”Person X would never do that”

### Next Steps
Please state nominations and discussions below.

**Comment by jbteves** [comment]
@eurunuela I believe you nominated @CesarCaballeroGaudes for MR Physics leader on the call. Would you mind confirming?

**Comment by eurunuela** [comment]
I did nomitate @CesarCaballeroGaudes for the MR physics leader role. I think he'd be happy to take the role to occasionally make sure the calculations make sense.

**Comment by CesarCaballeroGaudes** [comment]
Hi, I would be happy to take that role if nobody wants to (for example, I think @javiergcas or @handwerkerd could also take it), I would also feel comfortable with the role of processing algorithms leader (although other are more aware of the entire tedana workflow).

**Comment by handwerkerd** [comment]
As I have been doing this work, I am willing to be the task manager & record keeper. @jbteves is doing more for this work recently as well.

I could also be the Processing algorithms leader.

**Comment by dowdlelt** [comment]
I'll volunteer as Multi-echo fMRI support leader - seems like something I can do. 

Also meshes well with the multiecho detail spreadsheet, which is currently neglected...so I can revisit that.

**Comment by jbteves** [comment]
@handwerkerd nominates me for Collaborative Programming Leader, Communications Leader.

**Comment by tsalo** [comment]
I'll nominate myself for New Contributors Leader.

**Comment by eurunuela** [comment]
I'll nominate myself for Processing Algorithms co-leader

**Comment by emdupre** [comment]
I'll self-nominate for collaborative-programming co-lead and co-enforcer of the code of conduct.
