### ISSUE TITLE
Topics for the October 2020 Dev Call

### ISSUE THREAD

**Issue by jbteves** [ME-ICA/tedana#611]
The October 2020 Developers Call is this coming Friday, October 16 at 10:00 AM EST.
- [agenda](https://docs.google.com/document/d/109uUuLpXNmw0lG8Vqf_qOv1q__euxNVxEn2G6A_3Z3U/edit?usp=sharing)
- [zoom link](https://us02web.zoom.us/j/86084694394?pwd=NkRzeFlPazhwSzNOYyt3enhxazNNUT09)

Please note any topics you'd like to see discussed Friday below.

**Comment by jbteves** [comment]
I've already added this to the agenda, but I'd like to consider using an object-oriented approach to the metric modularization in order to simplify maintaining metric calculations. Typically this would be a larger burden on developers, but in this case I actually think it would alleviate some of the complications of maintenance.

**Comment by emdupre** [comment]
That sounds great, @jbteves ! At some point we had proposed a class-based approach, but the conversation evolved and I never followed-up. So it would be great to check-in and see what the stumbling blocks were / are.

Otherwise, I know there are two PRs that I'd like to work through before the next release, so I'd add cutting that to the agenda ! Or at least, asking if anyone knows of any other blockers.

**Comment by jbteves** [comment]
Which two PRs would you like to work through?

**Comment by emdupre** [comment]
#609 (it's so close !) and #465 (also so close ! and it'd be a shame to have a stable release with a major feature left undocumented).

**Comment by jbteves** [comment]
Alright, I'll add to the agenda. Are we going for 1.0?

**Comment by emdupre** [comment]
No, I think we still need to cut 0.0.9 (the stable version) !

**Comment by jbteves** [comment]
Oh, oh, oh, sorry, I forgot the last one was an rc! My mistake.

**Comment by handwerkerd** [comment]
Note: The correct Zoom link is:
https://us02web.zoom.us/j/86084694394?pwd=NkRzeFlPazhwSzNOYyt3enhxazNNUT09
Meeting ID: 860 8469 4394
Passcode: tedana

**Comment by eurunuela** [comment]
> #609 (it's so close !) and #465 (also so close ! and it'd be a shame to have a stable release with a major feature left undocumented).

I'm sorry, I think #465 is on me. I've just pushed some changes that hopefully make it ready to be merged.

We can talk about it tomorrow :)
