### ISSUE TITLE
Add all contributors to Zenodo file

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#612]
### Summary
In preparation for 0.0.9, we want to update our Zenodo file to include _all_ contributors, in alphabetical order.

### Additional Detail
I will start pinging contributors in this thread, asking for ORCIDs and institution information.

**Comment by tsalo** [comment]
I'm pinging everyone who I'd like to add to the Zenodo file. Attribution is opt-in, so please respond with your full name, affiliation, and ORCID if you'd like to be added. If you don't want to be added, that's okay too. You can react to this comment with a :-1:, add a new comment saying as much, or just not respond. If you don't respond, though, I may follow up with you directly just to make sure you didn't miss this message.

I will close this issue in two weeks, on October 30th. Thank you all for contributing to `tedana`.

@eurunuela @smoia @jbteves @dowdlelt @CesarCaballeroGaudes @monicayao @frodeaa @jsheunis @effigies @RupeshGoud @mjversluis @katrinleinweber @benoitberanger @aykhojandi @TomMaullin @javiergcas @mvaziri @Islast

**Comment by eurunuela** [comment]
Thank you @tsalo ! Here's me:

Eneko Uruñuela - Basque Center on Cognition, Brain and Language - https://orcid.org/0000-0001-6849-9088

**Comment by jbteves** [comment]
Thanks! Here's me
Joshua Teves - National Institutes of Mental Health, Section on Functional Imaging Methods - https://orcid.org/0000-0002-7767-0067

**Comment by effigies** [comment]
Thanks! Here's my snippet: https://github.com/effigies/meta/blob/master/zenodo.json

**Comment by dowdlelt** [comment]
Thanks for putting this together. 

Logan T. Dowdle, Center for Magnetic Resonance Research, University of Minnesota https://orcid.org/0000-0002-1879-705X

**Comment by mvaziri** [comment]
Thank you. Here is my information:
Maryam Vaziri-Pashkam, Laboratory of Brain and Cognition, National Institute of Mental Health, Orchid: https://orcid.org/0000-0003-1830-2501

**Comment by jsheunis** [comment]
Thanks @tsalo. This is me:

Stephan Heunis, Eindhoven University of Technology, Orcid: [https://orcid.org/0000-0003-3503-9872](https://orcid.org/0000-0003-3503-9872)

**Comment by smoia** [comment]
Hi @tsalo , thank you for taking care of this!
Here's my snippet:
```
        {
            "orcid": "0000-0002-2553-3327", 
            "affiliation": "BCBL - Basque Center on Cognition, Brain and Language", 
            "name": "Stefano Moia"
        }, 
```

**Comment by CesarCaballeroGaudes** [comment]
Here is mine:

**Comment by TomMaullin** [comment]
Here is mine:

Thomas Maullin-Sapey, Big Data Institue, University of Oxford, Orcid: https://orcid.org/0000-0002-4516-5103

**Comment by Islast** [comment]
Isla Staden, Orcid: https://orcid.org/0000-0002-0795-1154
