### ISSUE TITLE
Add descriptive information for each contributors' contributions to tedana

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#618]
### Summary
At the last Developers' call we talked about allowing contributors to add descriptive text to explain their involvement with tedana.

### Next Steps

1. Decide where on the site this information will be presented
2. Decide the mechanism through which contributors will add or edit their descriptive texts

**Comment by tsalo** [comment]
What about using the wiki before releases and then consolidating the changes in the documentation in a single PR right before each release? BIDS uses the wiki for more changeable information, like [recent contributions](https://github.com/bids-standard/bids-specification/wiki/Recent-Contributors), and then those _recent_ contributions get moved into [the documentation](https://github.com/bids-standard/bids-specification/blob/master/src/99-appendices/01-contributors.md) later.

**Comment by jbteves** [comment]
Do we use the wiki for anything else though? I'm a little concerned about information sprawl.

**Comment by tsalo** [comment]
No we don't, but I think it could be used as a staging area when we don't want to inundate ourselves with minor PRs. To be fair, though, BIDS is obviously a much bigger repository, so they have stronger motivation to reduce the number of small PRs like "Add `documentation` emoji to Taylor Salo's list of contributions."

**Comment by jbteves** [comment]
If we run into a problem where we have too many contributors adding PRs to reflect their new contributions, I will be ecstatic and more than happy to address it then. In the mean time I think it hasn't really been much of a burden. We could do a batch to get everything up to date before the release, and then smaller PRs to keep things up to date. That's just my opinion though.

**Comment by handwerkerd** [comment]
Thoughts on where to add the descriptive text? Since the current contributor grid in README.md is auto-generated will we need to make a separate file to host these descriptions?

**Comment by jbteves** [comment]
I'd say we should just add it under the existing table in README.md

**Comment by eurunuela** [comment]
> I'd say we should just add it under the existing table in README.md

I like the idea. We could actually update it every time we use the bot too.

**Comment by jbteves** [comment]
That's true, we could push a commit to the bot's branch.

**Comment by emdupre** [comment]
> I'd say we should just add it under the existing table in README.md

I think this will somewhat depend on how much information we ask from folks. If we'd like longer descriptions, [the Turing Way's model](https://the-turing-way.netlify.app/afterword/contributors-record.html#personal-highlights-from-the-turing-way-contributors) of having a separate page in the docs would give us more room. And then I'd think we should link it from the README !

**Comment by handwerkerd** [comment]
We have a few good options, but it would now help to get a sense of the amount of text we're talking about. I suspect a stand-alone page may be necessary.
I think it's time to gather the information we want to add. We can either invite contributors to insert their blurbs as comments to this issue or I can create a google doc to gather blurbs in a slightly more structured manner. Preferences?

**Comment by jbteves** [comment]
We do not. My proposed prompt:
> Please write a sentence or short paragraph concisely describing your contributions to tedana.
Example: I help manage issues and pull requests for a variety of both administrative and code-specific tasks. In the past, my largest contributions have included helping to overhaul `tedana`'s testing suite and reviewing our PCA implementation at the November 2019 hackathon.

**Comment by handwerkerd** [comment]
I think the plan will be to add these blurbs through PRs, but the question is how to create the initial list.  Given the comments so far, how does it sound to open a draft PR that:
1. Creates a new file called contributor_contributions.MD and links it to the README.md
2. Keep it open for a couple of weeks to give people time to make edits to add their blurbs
3. Merge & then future additions will be stand alone PRs.

**Comment by jbteves** [comment]
Maybe call it contributions.md ?

**Comment by jbteves** [comment]
I opened #624 to try and address this. Right now we just have my sentence. The Turing Way gives people more room, which is a model I'm happy to follow, but I thought this would be a simple way to start and get everyone to make short contributions. I can add peoples' sentences if they ping me here or on the PR.
