### ISSUE TITLE
Topics for November 2020 Dev Call

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#620]
The November 2020 Developers Call is this coming Friday, November 20 at 15:00 UTC & 10:00 AM EST

[agenda](https://docs.google.com/document/d/1JWMq5-It5pkWakqbd1HXkx7LL0lwaazmbTAvKPhfR_c/edit?usp=sharing) (Still needs updating)
[Teams link](https://teams.microsoft.com/l/meetup-join/19%3a2e309071ace3480ea7909a8d0b527a56%40thread.skype/1605710238598?context=%7b%22Tid%22%3a%2214b77578-9773-42d5-8507-251ca2dc2b06%22%2c%22Oid%22%3a%22d0454ceb-fd20-4027-9d7b-1c7806332d29%22%7d) (My access to a Zoom pro account is currently down. I've had good success with Teams meetings. We can change this to Zoom, if someone else can set up an hour long meeting. I can also test a Teams call with anyone in advance of the meeting.)

Discussion will likely include governance, modularization, & finally sending out a newsletter. 

Please note any topics you'd like to see discussed Friday below.

**Comment by jbteves** [comment]
The only major downside of Teams (aside from having to use yet another videoconferencing software) is that if you don't actually have a Teams account, you can't view or respond in chat. So if we do Teams, we'll have to do something other than the call's chat to share links, etc.

**Comment by emdupre** [comment]
I now have access to a pro Zoom account. I can add a link to the agenda day-of.

**Comment by emdupre** [comment]
@handwerkerd would you have time to do a quick 30 minute "agenda sweep" meeting before the call ? Just to try and consolidate / restructure some of the (fantastic) information in there !

**Comment by jbteves** [comment]
I think for consistency of platform it would make sense to use Zoom. WDYT @handwerkerd ?

**Comment by handwerkerd** [comment]
Fine switching to Zoom. @emdupre, put a link here and I'll make sure to update it elsewhere.
Also happy to talk over the agenda in advance, but let me update the agenda first. Today is 5h of zoom meetings for me. DM me about your Thursday availability.

**Comment by handwerkerd** [comment]
@emdupre & I just talked.
I just trimmed a lot of standing issues from the agenda to help keep us more focused. If I removed an issue that you do want to discuss, please mention it here or add it to the agenda!

Also, for various reasons, we'll plan to use Teams, with the link above, for the November meeting. If we have any issues, we'll try to transition to Zoom.

**Comment by eurunuela** [comment]
Another option would be to use [Around](https://around.co/). I have a spare invitation code that I could give to @handwerkerd for instance, or whoever will be present at every meeting. Folks can join via browser or the app just by clicking the meeting link.

It's a pretty cool app, to be honest. It actually sends you an email of the meeting notes automatically once the meeting is over.

**Comment by handwerkerd** [comment]
Meeting moved to https://umn-private.zoom.us/j/9201158646
