### ISSUE TITLE
Next tedana newsletter

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#621]
A draft of the tedana newsletter is at: https://docs.google.com/document/d/1s3WATkOAOJKesWYHaCUH_bgbPT1Y01JsfcaYFWrgDI8/edit?usp=sharing

This will be discussed the Nov 2020 dev call, #620. Comments are welcome.

**Comment by handwerkerd** [comment]
I just added a paragraph regarding governance. Take a look and, unless there are issues worth more discussion, let's plan to send this out early in the week of Dec 14.
@jbteves @emdupre @tsalo @eurunuela @dowdlelt

**Comment by emdupre** [comment]
Closing with the [Dec 15 newsletter](https://tinyletter.com/tedana-devs/letters/tedana-winter-2020-newsletter) !
