### ISSUE TITLE
Harmonize other docs with the new governance rules

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#631]
### Summary

We should go through the documentation to make sure there aren't any conflicts with the new governance guidelines and to see if there are more places we should be linking to the governance guidelines

### Additional Detail
[CODE_OF_CONDUCT.md](https://github.com/ME-ICA/tedana/blob/master/CODE_OF_CONDUCT.md) contains references to @emdupre as the BDFL. We should make sure the text instead refers to the CoC enforcement group.

### Next Steps

- [ ] Fix CODE_OF_CONDUCT.md
- [ ] Multiple people should look around documentation for additional things to adjust & comment below

**Comment by emdupre** [comment]
One thing I just hit -- we should specifically link to contributions.md from CONTRIBUTING.md in the "Acknowledging Contributions" section !
