### ISSUE TITLE
December 2020 developers' call?

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#632]
### Summary
We have a developers' call scheduled for Friday, December 18. Given people's schedules, there was some discussion on cancelling this dev call. Please comment or :thumbsup: :thumbsdown: if you would or would not attend. We should make a decision by Monday or sooner.

**Comment by handwerkerd** [comment]
Given 3 of the 7-or-so regular attendees say "no" I'll call this as a cancelled meeting. Sometime in the next week, I'll try to go through the November minutes to make sure nothing of note slips an extra month with no follow-up.

**Comment by emdupre** [comment]
Closing as we're coming up on the January call this **Friday, 15 Jan**.

We can roll over the agenda notes that @handwerkerd prepared for our December (non-)meeting, though. Thanks, Dan !
