### ISSUE TITLE
Add real-time multi-echo fMRI dataset to documentation

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#633]
### Summary
Now that @jsheunis has released his super-cool [real-time multi-echo dataset on Dataverse](https://dataverse.nl/dataset.xhtml?persistentId=doi:10.34894/R1TNL8), we should add it to our list of public multi-echo datasets [here](https://tedana.readthedocs.io/en/latest/resources.html#datasets)!

### Additional Detail
None

### Next Steps
1. Add name of dataset with link to [resources.rst](https://github.com/ME-ICA/tedana/blob/master/docs/resources.rst).
1. Maybe reorganize the list of datasets into a table?

**Comment by jbteves** [comment]
So I'd like to wait on this until we resolve a bug where dataverse doesn't actually let you download the whole dataset.

**Comment by jsheunis** [comment]
Good point @jbteves. I'll post updates on the issue [here](https://github.com/jsheunis/rt-me-fMRI/issues/1).

**Comment by tsalo** [comment]
The bug might still exist, but there are detailed access instructions on the Dataverse page that can be followed, so I think we can add the dataset to our documentation.

**Comment by jbteves** [comment]
That seems fair. I'm fine with adding it. I've been playing around with it and it's pretty neat/useful!
