### ISSUE TITLE
Role of ignored components is ambiguous in docs 

### ISSUE THREAD

**Issue by notZaki** [ME-ICA/tedana#634]
### Summary

The [component table](https://tedana.readthedocs.io/en/latest/outputs.html#component-tables) in the docs (reproduced below) does a good job of describing the role of the `accepted` and `rejected` components in the outputs, but the role of `ignored` component is ambiguous. 

Based on the table, I expected the denoised timeseries to only contain `accepted` components and the high-Kappa data to contain the `accepted` and `ignored` components. But looking at the code (referenced below), it's the other way round.

### Additional Detail

**Table**

| Classification | Description                                                           |
|----------------|-----------------------------------------------------------------------|
| accepted       | BOLD-like components retained in denoised and high-Kappa data         |
| rejected       | Non-BOLD components removed from denoised and high-Kappa data         |
| ignored        | Low-variance components ignored in denoised, but not high-Kappa, data |

**Code**

https://github.com/ME-ICA/tedana/blob/45e5ad7ab23f89dad091c3f0b6c7cc61062a0acc/tedana/io.py#L115-L117

### Suggestions

- Change the description for the `ignored` component to make it less ambiguous, e.g.
 ```diff
- Low-variance components ignored in denoised, but not high-Kappa, data
+ Low-variance components retained in denoised, but not high-Kappa, data
```

**Comment by jbteves** [comment]
Thanks for the suggestion @notZaki! You are welcome to open a Pull Request to adjust the documentation for clarity, or one of us can adjust it and we may invite you to review it. I can see why the current description can be confusing for a newcomer; I believe I had a similar confusion when I started with `tedana`.

How would you feel about wording like:
> Low-variance components are retained in denoised, but omitted from high-Kappa, data.
?

**Comment by notZaki** [comment]
> How would you feel about wording like:
> 
> > Low-variance components are retained in denoised, but omitted from high-Kappa, data.
> 
> ?

I like that version---'omitted' makes it clearer that the ignored components were not included at all in the high-Kappa data.
 
Perhaps then the description for the rejected component could also be changed to:
```diff
- Non-BOLD components removed from denoised and high-Kappa data
+ Non-BOLD components removed from denoised and omitted from high-Kappa data
```

**Comment by tsalo** [comment]
```diff
- Non-BOLD components removed from denoised and high-Kappa data
+ Non-BOLD components removed from denoised and omitted from high-Kappa data
```

I agree that your proposed wording is technically more accurate (since the denoised data are created by regressing the non-BOLD components from the OC data and the high-Kappa data are created by combining just the BOLD components), but I think that it will confuse most folks.

Perhaps instead we could use language that is more vague, but equally applicable to both approaches:

```diff
- Non-BOLD components removed from denoised and high-Kappa data
+ Non-BOLD components not included in either denoised or high-Kappa data
```

**Comment by notZaki** [comment]
The simplified description for the rejected component is ok with me.

Would it make sense to use the same terms for all descriptions? The following example uses included/excluded for all components:

```diff
- accepted: BOLD-like components retained in denoised and high-Kappa data
+ accepted: BOLD-like components included in denoised and high-Kappa data

- rejected: Non-BOLD components removed from denoised and high-Kappa data
+ rejected: Non-BOLD components excluded from denoised and high-Kappa data

- ignored: Low-variance components ignored in denoised, but not high-Kappa, data
+ ignored: Low-variance components included in denoised but excluded from high-Kappa data
```
