### ISSUE TITLE
Duplicated text in reports

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#638]
### Summary
At minimum, the optimal combination step is duplicated in our report text and visual reports. We should review the logging code to ensure that report text is only logged once, as appropriate.

In the five-echo test's current report (emphasis mine):

> TE-dependence analysis was performed on input data. An adaptive mask was then generated, in which each voxel's value reflects the number of echoes with 'good' data. **Multi-echo data were then optimally combined using the T2\* combination method (Posse et al., 1999). Multi-echo data were then optimally combined using the T2\* combination method (Posse et al., 1999). Multi-echo data were then optimally combined using the T2\* combination method (Posse et al., 1999).** Next, components were manually classified as BOLD (TE-dependent), non-BOLD (TE-independent), or uncertain (low-variance). This workflow used numpy (Van Der Walt, Colbert, & Varoquaux, 2011), scipy (Jones et al., 2001), pandas (McKinney, 2010), scikit-learn (Pedregosa et al., 2011), nilearn, and nibabel (Brett et al., 2019). This workflow also used the Dice similarity index (Dice, 1945; Sørensen, 1948).

### Next Steps
1. Review logging code
2. Eliminate duplicated text by adding a `report` argument to the relevant functions and setting to `False` when called 2+ times. See `fit_loglinear` for an example:
https://github.com/ME-ICA/tedana/blob/45e5ad7ab23f89dad091c3f0b6c7cc61062a0acc/tedana/decay.py#L158

**Comment by notZaki** [comment]
As a starting point for that specific case, the duplicate messages are from multiple calls to `tedana.combine._combine_t2s` in the following loop:
https://github.com/ME-ICA/tedana/blob/45e5ad7ab23f89dad091c3f0b6c7cc61062a0acc/tedana/combine.py#L218-L228
