### ISSUE TITLE
Remove stale-bot, issue-resolution badge

### ISSUE THREAD

**Issue by emdupre** [ME-ICA/tedana#642]
Currently, we use our issue tracker largely as a way to discuss potential new features or extensions for tedana. However, we have two pieces of infrastructure (stale-bot, the [issue-resolution badge in the README](https://isitmaintained.com/project/ME-ICA/tedana)) that assume we are using our issue tracker largely for bug reports.

I'd like to suggest that we remove both of these. Although this could conceivably increase the amount of manual work to close issues, I think this is something we could assign as a quarterly (-ish) task.

Actions:

- [ ] Vote on removing stale-bot, issue resolution badge
- [ ] Update as appropriate

**Comment by jbteves** [comment]
I think this is a valid point. The original rationale for stale-bot was to foster discussion, and I do not think it achieves this purpose. I would be in favor of removing both and doing quarterly reviews of open issues.

**Comment by tsalo** [comment]
+1 for removing stalebot.

-1 for the issue trackers. `IsItMaintained` ignores issues with certain labels (particularly feature request-related ones), so it shouldn't be an issue as long as we label our issues appropriately. According to [the code](https://github.com/mnapoli/IsItMaintained/blob/cb451435e5232496600a9747722db4942fd88041/src/Maintained/Statistics/StatisticsComputer.php#L27-L43), the ignored labels are `enhancement`, `feature`, `task`, `refactoring`, `duplicate`, `tests`, `refactoring`, `suggestion`, `wip`, `rfc`, `wishlist`, `question`, `cleanup`, `discussion`, and `meta`. For the most part, I think that should leave us with `bug` issues, in which case our typical timeline for resolving them is something I think we should keep an eye on.

**Comment by eurunuela** [comment]
+1 for removing stalebot.

= no opinion on the issue trackers.

**Comment by emdupre** [comment]
> -1 for the issue trackers. IsItMaintained ignores issues with certain labels (particularly feature request-related ones), so it shouldn't be a problem as long as we label our issues appropriately.

I think that last part is my concern (I just closed one without any labels, and I see another one or two open from a quick skim). But maybe if we're committing to scan for staleness, we can also scan for labels !

**Comment by jbteves** [comment]
This seems like a good approach to have.
I'm in favor of:
- Removing stalebot
- Quarterly issue checks
- Making sure all issues have labels
- Retaining `IsItMaintained`

**Comment by emdupre** [comment]
Should we consider the vote closed on this, and implement the following ?

>  - Removing stalebot
>  - Quarterly issue checks
>  - Making sure all issues have labels
>  - Retaining IsItMaintained

I can do that on Friday if I don't hear any objections before Friday EOD !

**Comment by jbteves** [comment]
I think 4 of 5 steering committee members are in favor, so I would consider this vote closed. If it's possible I'd rather see if someone aside from you can do those things, as we try to migrate some of your BDFL responsibilities to be shared ones, similar to checking PyPI deployments with other credentials. Would that be okay?

**Comment by emdupre** [comment]
> Would that be okay?

Of course ! I'll leave this open, then. Please feel free to implement, @jbteves (or anyone else!)

**Comment by jbteves** [comment]
Alright. I'll plan on removing the bot on Friday provided there are no objections, doing issue checks this week, and then another check on the week of March 29.

**Comment by emdupre** [comment]
Closing with the removal of stale-bot ! :robot:
