### ISSUE TITLE
January 2021 developer's call

### ISSUE THREAD

**Issue by emdupre** [ME-ICA/tedana#643]
This Friday at 10a Eastern Time (find [your local time here](https://www.timeanddate.com/worldclock/converter.html?iso=20210115T150000&p1=165)) we'll hold our first tedana developer's call of the year !

As always, we welcome any community members who are interested in tedana to attend.

[Draft agenda here](https://docs.google.com/document/d/1uTSIiUGasxaTi_aFW63A5OXLc9DwnO6g3-zna-BLPnE/edit?usp=sharing)
[Zoom link](https://nih.zoomgov.com/j/1603314994)

Please note any topics below that you'd like to see included in the agenda !

**Comment by tsalo** [comment]
There's a [new NeuroStars post](https://neurostars.org/t/zerodivisionerror-with-combine-py-for-multi-echo-fmri/17928) that reports #513 within an fMRIPrep run, and the only way to fix that would be to make a release ASAP and update fMRIPrep's requirements.

Given how important the masking procedure is for a number of fMRIPrep users, I also think we should consider #635 high priority.

**Comment by emdupre** [comment]
+1 on all of the above.

So I'll put the release blockers as a high-priority discussion point, then the release schedule.

@jbteves is it ok with you if I just edit the last call agenda, or had you started a new one ?

**Comment by jbteves** [comment]
You can edit the last call agenda, I haven't started a new one.

**Comment by handwerkerd** [comment]
I just created a zoom link: https://nih.zoomgov.com/j/1603314994

**Comment by jbteves** [comment]
@emdupre edited your comment to link to Zoom up top, hope that's okay.

**Comment by emdupre** [comment]
I'm closing this EOD as the meeting has passed. The meeting minutes are available in the project Google Drive, but to broadly summarize next steps:

- we're going to review and merge #635
- we'll solicit feedback on the current codebase to see if it addresses the use cases outlined in #617
- we'll cut a stable release (0.0.9) using the release process outlined in #596
