### ISSUE TITLE
Add NeuroStars link to issue template selection page

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#647]
### Summary
I think we could benefit from having specific bug report and feature request issue templates, along with links for usage questions to NeuroStars. 

### Additional Detail
GitHub lets you link to external sites from your issue template selection page. We recently adopted this in `nilearn` and `NiMARE` (see `nilearn`'s page below):

![image](https://user-images.githubusercontent.com/8228902/104750388-089ddc80-5722-11eb-89e3-94eac4618dff.png)

We can have the NeuroStars link point directly to `tedana`-labeled topics, and when you create a new topic from that page, it automatically adds a `tedana` label.

### Next Steps
1. Add goal-specific issue templates (with autolabeling!)
2. Add link to NeuroStars `tedana` label page.

**Comment by jbteves** [comment]
We had that at one point, except for the external link. I believe that's a new feature since we revisited the templates. We first discussed something like this in #189, and condensed the two templates into one. You can check out the templates with these commits:
Bug: 11ca2fe2fde3b11832bb23739ba8d0c45515af26
Issue: d8c3611eb70ad19466300aa5d7c9ccb362792a9f

**Comment by tsalo** [comment]
Wow... I totally forgot about that! Thank you for linking. So, the consensus two years ago was that we didn't need differentiated issue templates, which I guess is probably still the case since we don't have _that_ many new issues from folks who aren't devs. I can streamline this issue to reflect that, unless you (or anyone else) would like to revisit that proposal (probably with your original templates).

That said, I think having a NeuroStars link would still be great, since it's much easier to come across than the information we have about NeuroStars in our documentation.

**Comment by jbteves** [comment]
No problem! Yeah, I personally don't see a need for splitting the template, but I'm open to hearing counterpoints. I think adding a NeuroStars link would be fantastic, though. I don't think that was an option when I opened that PR, it's pretty nifty.
