### ISSUE TITLE
Add system info to report outputs

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#650]
### Summary
From today's dev call, we want to collect and save system/environment info among out report outputs, in order to improve reproducibility.

### Additional Detail
I thought we could take something from `rapidtide` for this, but it turns out they just output the parameters used in the run (which is still useful information that we could output) in a json. I _know_ there are some packages that output system information, but for some reason I can't find any right now. Will need to revisit later.

### Next Steps
1. Find a Python library that outputs system information and adopt their approach.
2. Write out a file with system info at the beginning of each workflow run.

**Comment by jbteves** [comment]
For a start, here's [platform](https://docs.python.org/3/library/platform.html)
