### ISSUE TITLE
OHBM 2021 abstract submissions

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#657]
The OHBM 2021 abstract submission deadline is Feb 1, 2021
https://ww4.aievolution.com/hbm2101/
Please give a thumbs up if you agree there should be a tedana abstract submitted this year. Comment if you are willing to lead the abstract writing & poster creation (I am willing, but also fine if someone else wants to do it instead).

Also comment to add other tedana/multi-echo focused abstracts you're submitting that you want to alter others to at this point.

### Next Steps

- Decide who is taking the lead by Monday, 1/25 so that there's a week to write the abstract and get feedback

**Comment by handwerkerd** [comment]
No one else stepped up so I guess I'll take the lead? 
Just like last year, for the abstract, I'll be first author & everyone else is alphabetical. For the poster, "Tedana community" will be the first author and everyone is alphabetical.

Topics to cover in the abstract:
- Governance
- Modularization (I'll word it slightly aspirationaly with the goal/motive to use OHBM has a realistic target for getting all the modularization merged.
- Highlight generally stuff that isn't completely novel since OHBM 2020, but has seen activity (suggestions?)

Give a thumbs up or comment, if this is ok with you. Comments on ideas for stuff to include are particularly appreciated. If you're a maintainer/steerer and don't give some sort of reply, I'll plan on reaching out directly.

**Comment by tsalo** [comment]
I think the biggest novel thing is the reports, right?

**Comment by handwerkerd** [comment]
The draft abstract is at https://docs.google.com/document/d/1txsqxo5iBdhUG7qI81r70Wof2LvB94AypR5ycSsbM6A/edit?usp=sharing
There's still work to do & more than enough space to add so, please comment. I also will need confirmations of who is or is not ok being an author. I think I've included all tedana contributors from the past 18 months.

There are currently no figures. I can take some screen shots, but ideas for what to include are also welcome.

Anyone can comment and a few of you can edit. If you cannot currently edit, but want to, contact me directly.

**Comment by tsalo** [comment]
Thanks for writing the abstract! Not sure where you want folks to confirm, but I am okay (and happy) with being an author.

**Comment by jbteves** [comment]
Thanks @handwerkerd. I think this looks good. I would vote against a software demo at this point, between unknowns about how it will go and the fact that we can always add demos to the documentation.

**Comment by handwerkerd** [comment]
tedana abstract submitted. The submitted text is available here: https://docs.google.com/document/d/1txsqxo5iBdhUG7qI81r70Wof2LvB94AypR5ycSsbM6A/edit?usp=sharing
