### ISSUE TITLE
Tedana doesn’t find any BOLD components in the data

### ISSUE THREAD

**Issue by arielle68** [ME-ICA/tedana#659]
I have a set of multi-echo data which have been motion-corrected and slice timing corrected using fMRIprep. For some of the data, tedana fails at the spatial clustering of components, giving the following errors message. I’m wondering what I can do to fix this issue? I'm also uploading the figures and report.txt here as was requested by tsalo in response to [my Neurostars post](https://neurostars.org/t/tedana-doesnt-find-any-bold-components-in-the-data/18045). 
[figures.zip](https://github.com/ME-ICA/tedana/files/5868766/figures.zip)
[report.txt](https://github.com/ME-ICA/tedana/files/5868769/report.txt)

INFO:tedana.decomposition.pca:Computing PCA of optimally combined multi-echo data
INFO:tedana.decomposition.ma_pca:Performing SVD on original OC data…
INFO:tedana.decomposition.ma_pca:SVD done on original OC data
INFO:tedana.decomposition.ma_pca:Estimating the subsampling depth for effective i.i.d samples…
INFO:tedana.decomposition.ma_pca:Generating subsampled i.i.d. OC data…
INFO:tedana.decomposition.ma_pca:Performing SVD on subsampled i.i.d. OC data…
INFO:tedana.decomposition.ma_pca:SVD done on subsampled i.i.d. OC data
INFO:tedana.decomposition.ma_pca:Effective number of i.i.d. samples 5272
INFO:tedana.decomposition.ma_pca:Perform eigen spectrum adjustment …
INFO:tedana.decomposition.ma_pca:Estimating the dimension …
INFO:tedana.decomposition.ma_pca:Estimated components is found out to be 45
INFO:tedana.metrics.kundu_fit:Fitting TE- and S0-dependent models to components
INFO:tedana.decomposition.pca:Selected 45 components with mdl dimensionality detection
INFO:tedana.decomposition.ica:ICA attempt 1 converged in 84 iterations
INFO:tedana.workflows.tedana:Making second component selection guess from ICA results
INFO:tedana.metrics.kundu_fit:Fitting TE- and S0-dependent models to components
INFO:tedana.metrics.kundu_fit:Performing spatial clustering of components
INFO:tedana.selection.tedica:Performing ICA component selection with Kundu decision tree v2.5
WARNING:tedana.selection.tedica:Too few BOLD-like components detected. Ignoring all remaining.
WARNING:tedana.workflows.tedana:No BOLD components detected! Please check data and results!
INFO:tedana.io:Writing optimally combined time series: C:\test\out\ts_OC.nii.gz
INFO:tedana.io:Variance explained by ICA decomposition: 97.34%
INFO:tedana.io:Writing low-Kappa time series: C:\test\out\lowk_ts_OC.nii.gz
INFO:tedana.io:Writing denoised time series: C:\test\out\dn_ts_OC.nii.gz
INFO:tedana.io:Writing full ICA coefficient feature set: C:\test\out\betas_OC.nii.gz
INFO:tedana.workflows.tedana:Making figures folder with static component maps and timecourse plots.

**Comment by tsalo** [comment]
Is there a task associated with these data? Having task regressors would make it easier to figure out if any obviously important components are being missed.

**Comment by jbteves** [comment]
How long is this data set? The last time I saw a kappa vs. rho plot that looked like that, it was because there weren't very many TRs.
@tsalo or @arielle68 would you mind linking the neurostars post?

**Comment by tsalo** [comment]
I've added the link to the issue summary.

**Comment by jbteves** [comment]
Taking a look at the components, it looks like a lot of them have a strange banding about the z-axis. Is there any way you could share the data you fed into `tedana` for us to take a look?

**Comment by CesarCaballeroGaudes** [comment]
Hi, is this resting state data? I also noticed the banding artifact in the z-axis that @jbteves indicates, but I found the data very noisy in general. Also the small number of TRs does not help the classification. By looking at the time series and spectra, I only found 1 or 2 components (comp 4 and comp 11) that could be potentially labeled as BOLD-related, whereas I would classify the rest of them as noise related. Can you please indicate the previous preprocessing in fMRIprep?

**Comment by arielle68** [comment]
Thank you all for your replies. 
> Is there a task associated with these data? Having task regressors would make it easier to figure out if any obviously important components are being missed.
No there is no task associated with this data. This is a resting-state fMRI dataset. 

> Taking a look at the components, it looks like a lot of them have a strange banding about the z-axis. Is there any way you could share the data you fed into `tedana` for us to take a look?

Sure. I uploaded the data from two participants' data that had this issue in this link (one data that changing the random seed solved the issue and one that changing the seed didn't solve the issue) . The full output is also available within each subjects' results folder. https://drive.google.com/drive/folders/16t-Fck4Et9k0WzjKgG2wOBqLBKTG88Y4?usp=sharing



> Hi, is this resting state data? I also noticed the banding artifact in the z-axis that @jbteves indicates, but I found the data very noisy in general. Also the small number of TRs does not help the classification. By looking at the time series and spectra, I only found 1 or 2 components (comp 4 and comp 11) that could be potentially labeled as BOLD-related, whereas I would classify the rest of them as noise related. Can you please indicate the previous preprocessing in fMRIprep?

Yes. It's a resting state data. The data is motion corrected and slice timing corrected in fMRIprep.

**Comment by tsalo** [comment]
Given how effective changing the random seed has been, it may be worth looking into adding a feature to feed the classification results back toward the decomposition. I imagine it would require a substantial refactor, but it could perhaps be very helpful. I will open an issue about it.

**Comment by tsalo** [comment]
@arielle68 now that #662 has been merged, would you be willing to try running our current main branch to see if the new approach works for you?

**Comment by emdupre** [comment]
This should be addressed with the most recent stable release (0.0.9). I'll close this, but please re-open if you encounter any difficulties !
