### ISSUE TITLE
Review and check packaging before 0.0.9 release

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#668]
### Summary
This stems from [this NeuroStars comment](https://neurostars.org/t/number-of-components-in-tedana-pca-is-equal-to-the-number-of-epi-volumes/18126/6), in which a user was unable to install `tedana` directly from GitHub. In #595, we started using the README as the source of `long_desc` (long description) in `info.py`, which means that we need to bundle the README in with our package data in order for `tedana` to install correctly. It does not appear to be bundled in just yet, and I'd like to make sure we fix/check this before our release on Friday.

### Additional Detail
I tried to test this by adding the README to `MANIFEST.in` in the [`package-readme`](https://github.com/ME-ICA/tedana/tree/package-readme) branch, but directly installing from GitHub (i.e., `pip install git+https://github.com/ME-ICA/tedana.git@package-readme`) failed for the same reasons described in the NeuroStars post. I don't know if this is unique to installing directly from GitHub or if it will impact our PyPi releases.

### Next Steps
1. Investigate.
2. Fix.
3. Release!

**Comment by tsalo** [comment]
My understanding of the MANIFEST.in file is that it should be used to identify files _outside of the package subfolder_ that you want to bundle with the package in your distribution. On the other hand, `package_data` should be used to identify non-code files _inside_ the package subfolder that you want to bundle with the package.

If anyone knows why adding the README to MANIFEST.in doesn't solve the issue, please respond to this issue.

**Comment by jbteves** [comment]
Interestingly, we shouldn't even need to include it per my read of [this page](https://packaging.python.org/guides/using-manifest-in/), where it states that a README.md should get included by `setuptools`.

**Comment by tsalo** [comment]
Hm, so maybe installing directly from GitHub doesn't use `sdist`?

**Comment by notZaki** [comment]
I think the issue is that the parent folder of the github repository doesn't get copied. Even if it did get copied, the path of the readme file would have to be in the site-packages folder, which is an odd place.

In other words
```
# Folder where tedana gets installed
$SOME_PATH/lib/python3.8/site-packages/tedana’
# Folder where tedana expects the readme to be
$SOME_PATH/lib/python3.8/site-packages/README.md
```

One workaround is to load the readme inside `setup.py` instead of placing that code in the module itself, i.e. don't use `info.py`.
I followed [these instructions](https://packaging.python.org/guides/making-a-pypi-friendly-readme/#including-your-readme-in-your-package-s-metadata) and made the changes [in this commit](https://github.com/notZaki/tedana/commit/2303c8da18ec59a22c5ecd51d1fde9558f447000), and it looks like it no longer gives an error.

**Comment by jbteves** [comment]
@emdupre and @tsalo what do you think of the approach provided by @notZaki ? While I assume the rationale behind much of the other info living in `info.py` is to make it accessible to users using our API, I'm not sure that it's quite helpful for them to have the entire README in the API; they should probably be looking at RTD by that point anyway.

**Comment by tsalo** [comment]
Thanks @notZaki. That solution seems to work. Do you want to open a PR?

**Comment by notZaki** [comment]
Yup. I'll remove the commented code and then open a PR.

**Comment by tsalo** [comment]
This should be good with #670 merged, so I'm going to close. If we come across any problems, we can reopen.
