### ISSUE TITLE
Add "What's New" page to docs

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#676]
### Summary
This is an idea that @emdupre has brought up in a couple of different locations. Essentially, we should try to document our changes (currently placed just in the release notes) in a changelog document on the RTD site. Many users are not going to be familiar enough with Python packaging to know to check the release notes, and the newsletter doesn't have a large enough audience for us to trust that it reaches all relevant users.

### Additional Detail
Unfortunately, this adds one more thing we have to keep track of. Still, I think it's worth it for our users.

I think our focus should be on (1) identified major bugs and the package versions impacted by those bugs, (2) backwards-incompatible changes, and (3) major improvements. We can always have a link to the full changelog in the documentation, where the other changes would be documented (e.g., documentation, maintenance, minor bug-fix, refactor, and minor enhancement PRs).

**Comment by tsalo** [comment]
From today's meeting- big red admonition boxes with breaking changes highlighted in #622.

**Comment by tsalo** [comment]
I think we should use a hybrid automated/manual approach. Specifically, we could use a GitHub Action, like [Next Change](https://github.com/marketplace/actions/next-change), to create and update a CHANGELOG as PRs are merged in, as we do with release-drafter. Then, before each release, we could reorganize and prettify the CHANGELOG with admonition boxes and the like, just as we do with our release notes. The only open issue I can foresee related to this idea is that `Next Change` seems to be Markdown-specific, while I think restructuredText would look better.

What does everyone think of this plan?

**Comment by tsalo** [comment]
Here's a list of the Actions I've found. It's not a comprehensive list, so please add to it if you find any others.

- [next-change](https://github.com/marketplace/actions/next-change)
- [release-changelog-builder](https://github.com/marketplace/actions/release-changelog-builder)
- [generate-changelog-action](https://github.com/marketplace/actions/generate-changelog-action)
- [auto-generate-changelog](https://github.com/marketplace/actions/auto-generate-changelog)

**Comment by eurunuela** [comment]
I like the second one to be honest.

I'm curious to know though, what did you miss from all these options? At the meeting, you mentioned these weren't quite what you were looking for.

**Comment by tsalo** [comment]
The main thing that I was looking for, but didn't find, was the ability to generate restructuredText, rather than Markdown, files. I _really_ want to use admonition boxes in the **What's New** file, to highlight bug-fixes, deviations from ME-ICA, output/input changes, and important enhancements.

**Comment by handwerkerd** [comment]
I'm not sure I want to deal with an automated updater just to replicate information from the release notes. I could see adding an RTD page that includes the info for #699 and other major changes and then has a link to the release notes on github. That way, anyone who is looking for detailed version change info would be clearly directed to the release notes & we wouldn't need to replicate the same info in two places.

**Comment by tsalo** [comment]
One cool idea I just saw on the physiopy website is they included the link to the GitHub releases page as the "Changelog". So we wouldn't need to actually manage a changelog, and could just link out to our release notes, which should at least increase visibility of those release notes for users who aren't experienced with GitHub.
