### ISSUE TITLE
Add references to HTML reports

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#686]
### Summary
Currently, our HTML reports have the descriptive report text, with citations, but the reference list is missing. We should add it to the end of the report.

### Additional Detail
The code to do this should be roughly the same as the code to load and add the report text.

**Comment by handwerkerd** [comment]
This PR looks good to me. That said, it looks like the report figures are not generating for me either in this PR or in Main. I've tried on Mac in Firefox, Safari, & Chrome & the same issue is in all (see screenshot). I'm fine approving this PR and opening a new issue, given I don't think this PR is the root of the problem. Still, I wanted to do a sanity check with others first. Anyone else having this issue now?
<img width="567" alt="image" src="https://user-images.githubusercontent.com/7406227/112041045-4b15d800-8b1c-11eb-8650-ee9ea23d6dd9.png">

**Comment by tsalo** [comment]
@notZaki fixed that problem with #703. A number of older PRs should have the same issue if they haven't updated from `main`.
