### ISSUE TITLE
Add carpet plots to HTML reports

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#688]
### Summary
It would be great to include carpet plots in the HTML reports. In a perfect world, those plots would be broken down by tissue type and would also have line plots attached with regressors of no interest, but those elements would require additional inputs, which we may not want to support.

### Additional Detail
I have been working on carpet plots in `nilearn`, so we could use their functions.

This stems from #450.

**Comment by tsalo** [comment]
A first draft:

![Screen Shot 2021-03-01 at 4 33 43 PM](https://user-images.githubusercontent.com/8228902/109562170-0c0bde00-7aac-11eb-8ac8-51258f267498.png)
![Screen Shot 2021-03-01 at 4 33 52 PM](https://user-images.githubusercontent.com/8228902/109562174-0ca47480-7aac-11eb-92c7-289cf2768519.png)
![Screen Shot 2021-03-01 at 4 34 02 PM](https://user-images.githubusercontent.com/8228902/109562175-0d3d0b00-7aac-11eb-9995-d9fac89cbbd1.png)
![Screen Shot 2021-03-01 at 4 34 10 PM](https://user-images.githubusercontent.com/8228902/109562177-0d3d0b00-7aac-11eb-8684-c76d0098aa19.png)

**Comment by tsalo** [comment]
Do we want to support atlases at all? I'm leaning toward "no" (at least for the core workflows), but we could consider a reporting workflow that could take in an output directory, optionally an atlas, and optionally a set of nuisance regressors to plot against, much like @smoia's idea for post-tedana workflows.

**Comment by dowdlelt** [comment]
I think this is all fantastic (my mantra "look at your data as much as possible, then look at it more"). Atlases would be nice - but as you say, thats requires more input, and careful thought, they need to be aligned, on the right grid, etc. 

What of sorting/reordering - such as proximity, correlation, etc I'm thinking of https://www.sciencedirect.com/science/article/pii/S1053811920301014 specifically - maybe allowing for struture would give even more insight. Not a demand, mind you, just don't know what capabilities we have here.

**Comment by tsalo** [comment]
I actually have an open PR to implement that sorting (https://github.com/nilearn/nilearn/pull/2718). At least with the few files I've tested on, it hasn't made much of a difference, and it takes ~4.5 minutes. Still, I'm happy to support it in `tedana` if that will help. Ultimately it should just be a parameter to `nilearn`'s carpet plot function.

**Comment by notZaki** [comment]
Is the carpet plot function in `nilearn` similar to the one in `niworkflows`? I've used the latter with an atlas and don't remember it being that slow.

**Comment by dowdlelt** [comment]
I see, thats not a small timing difference, so perhaps best to revisit later.

**Comment by tsalo** [comment]
@notZaki I don't think the `niworkflows` version doesn't include hierarchical clustering. Other than that, the approaches are pretty much the same.
