### ISSUE TITLE
Reach 90% test coverage

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#69]
The general consensus is that we want at least 90% coverage before `1.0.0`.

**Comment by jbteves** [comment]
@emdupre @tsalo How would you feel about opening some smaller issues indicating sections of code to add tests for? For example, maybe we could open one for workflows and a separate one for the math/stats packages that are being broken out?

**Comment by emdupre** [comment]
That seems like the right call -- this was my first attempt at a milestone, but we have a much better system in place now ! Thanks for checking on this, @jbteves :smile_cat:

**Comment by jbteves** [comment]
No problem. How would you feel about creating one issue each for each [API header](https://tedana.readthedocs.io/en/latest/api.html)? It's a lot of issues, but then each one is much smaller and manageable.

**Comment by jbteves** [comment]
@emdupre any thoughts on the above?

**Comment by tsalo** [comment]
I refuse to allow the stalebot to take this away from me.

**Comment by tsalo** [comment]
We're over 90% as of #496! Thanks to @jbteves for pushing us over the edge! :tada::tada::tada:

This would have been way more fun if I hadn't had to reopen the issue in order to properly close it, but I'll take any victory I can get.
