### ISSUE TITLE
Update contributing guidelines with style suggestions for pull requests

### ISSUE THREAD

**Issue by KirstieJane** [ME-ICA/tedana#7]
I've noticed that the PRs for tedana often have labels like `[WIP]`, `[TST]`, `[ENH]` associated with them.

I think it makes sense to explain in the contributing guidelines what they mean and how to use them for new pull requests.

You could also consider a pull request template. @islast has a [really lovely one](https://github.com/WhitakerLab/BrainNetworksInPython/blob/master/PULL_REQUEST_TEMPLATE.md) for [Brain Networks in Python](https://github.com/WhitakerLab/BrainNetworksInPython/).

Here's a github help article about [pull request templates](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/).

**Comment by emdupre** [comment]
Yes, PR label conventions would be something to include in more general style guidelines ! I'm planning to add those&mdash; maybe in the documentation itself, with a link out from the Contributing file. Something like [these suggested tags](http://nipy.org/nibabel/devel/devguide.html#commits) from [Nibabel](http://nipy.org/nibabel/index.html).

I love the idea of a pull request template too, though ! Would be great to have help in creating one for this repo.

**Comment by KirstieJane** [comment]
My favourite thing about @islast's template is the checkbox that tells me whether it's ready for review. I get the notifications when she pushes commits but I know not to go and check it out until that checkbox is ✅!

Isla's on holiday at the moment but I'm sure she'd be delighted to help out when she's back in about 1 week (or other folks could share their experiences too) ✨

**Comment by Islast** [comment]
Hi, just saw this in my notifications and I thought I'd say hi! I think pull request templates are great. One tip I have if you decide to do one is that if you look at the [raw file](https://github.com/WhitakerLab/BrainNetworksInPython/edit/master/PULL_REQUEST_TEMPLATE.md) of ours you'll see a section in a ! html tag: 
```
<!---
This is a suggested pull request template for the BrainNetworksInPython. 
We don't mind whether or not you use it. It's just a list of useful 
questions to answer. :)
-->
``` 
Github markdown doesn't render anything enclosed in this tag so it's useful for leaving an explanatory message to your pull-requester :dizzy:
