### ISSUE TITLE
End Python 3.5 compatibility

### ISSUE THREAD

**Issue by jbteves** [ME-ICA/tedana#706]
### Summary
Python 3.5 reached end of life in September 2020, however we still unit test for it. I believe we should discuss ending Python 3.5 support as it is now affecting testing in #692. Please 👍🏼 or 👎🏼 this issue to indicate if you support removing 3.5 support in the next release. If not, please indicate your reasoning.

### Next Steps
- [ ] Decide if it is time to end support for 3.5 at the next release
- [ ] Document the drop in support in documentation and release notes
- [ ] Update PYTHON_REQUIRES to 3.6 and above

**Comment by notZaki** [comment]
One benefit of dropping 3.5 support: We can finally use f-strings.

**Comment by tsalo** [comment]
I think this is a good opportunity to formalize a deprecation procedure. In `nilearn`, I believe they have a timeline of adding a FutureWarning about the version, making two major releases, and then dropping support for that version. I understand if we want to forgo that in this particular case, given that it directly impacts one of our PRs, but long-term I think we should plot this kind of thing out a few versions ahead of time.

**Comment by jbteves** [comment]
That makes sense to me. I would be fine with tentatively ending support for 3.5 (particularly since I think it's less impactful than changing the filenames anyway) in the next release, but in the future having a FutureWarning for two consecutive major versions.
