### ISSUE TITLE
Support Python 3.8 and 3.9

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#707]
### Summary
Currently we test 3.5-3.7, and our setup files specify 3.5-3.7. We can easily add jobs for testing 3.8 and 3.9, and can 

### Additional Detail
This should be pretty straightforward. I don't anticipate any issues with version compatibility.

### Next Steps
1. Add CircleCI workflows for 3.8 and 3.9
2. Add 3.8 and 3.9 to setup files

**Comment by jbteves** [comment]
We should probably open one PR to close this and #706 at the same time for simplicity, pending consensus in that issue.

**Comment by tsalo** [comment]
Forgot to properly link this issue from #721. Closing now.
