### ISSUE TITLE
F maps are truncated after they are written but before kappa/rho calculation

### ISSUE THREAD

**Issue by jbteves** [ME-ICA/tedana#710]
### Summary
F-maps are truncated to F_MAX for kappa and rho but not for T2/S0 maps and their derived metrics.

### Additional Detail
In this code block [here](https://github.com/ME-ICA/tedana/blob/0f4d54c375ffd2a4b96ebd6a662269ea3b92d691/tedana/metrics/kundu_fit.py#L185-L200) we see that f > F_MAX is truncated to just F_MAX *after* the f maps are written, but *just before* we calculate kappa and rho. As a consequence, kappa and rho are calculated with one version of the f-map while f-map metrics and their derivatives are calculated with the un-truncated version. I don't believe that we should be doing this since that means that f-map might mean different things at different times, and it seems reasonable to threshold as early as possible. While the difference is typically small, in my metric modularization testing (where this bug is not present) some components will flip, sometimes shifting total variance explained in each category by several percent. It seems that some components have very large f-statistic outliers that can drive classification disproportionately. 

### Next Steps
- [x] Decide if this is actually a bug.
- [ ] Merging metric modularization will fix this bug OR
- [ ] We can issue a hotfix by threshold the f-maps sooner; I can issue a PR if everyone agrees this is a bug OR
- [ ] This is not a bug and we should close the issue.

**Comment by tsalo** [comment]
I'm not sure whether calculating kappa and rho on thresholded maps, but using unthresholded maps for other metrics, is a problem, but looking at these lines did make one related issue clear:

`F_R2` and `F_S0` should only have non-zero values in voxels where `adaptive_mask == j_echo`, while `F_R2_maps` and `F_S0_maps` should be filled in with values at all voxels where `adaptive_mask >= 3` over the `j_echo` loop:
https://github.com/ME-ICA/tedana/blob/0f4d54c375ffd2a4b96ebd6a662269ea3b92d691/tedana/metrics/kundu_fit.py#L185-L186

However, we _calculate_ kappa and rho from `F_R2`, not `F_R2_maps[:, i_comp]`, which means that kappa and rho are probably only calculated from the F-statistics for voxels with good data in all echoes, along with a bunch of zeros:
https://github.com/ME-ICA/tedana/blob/0f4d54c375ffd2a4b96ebd6a662269ea3b92d691/tedana/metrics/kundu_fit.py#L202

**Comment by jbteves** [comment]
To clarify: the bug that I reported isn't present, or the bug I reported and the related ones you mentioned aren't present?

**Comment by tsalo** [comment]
The way I interpreted your initial post is that you found a bug in `main` that isn't present in #591. The related bug I noted is _also_ present in `main` but not #591.

**Comment by handwerkerd** [comment]
Going back to @jbteves original question, do we want to fix these bugS in `main` or just wait until we merge #591.
I'd lean towards fixing them in `main` because this is a breaking change that will non-trivially alter results. It may be useful to be able to point to a clean PR that marks this breaking change. If that happens, then the eventual merging of metric modularizaiton in #591 can be considered a major change under-the-hood with only rounding-error level changes to the outputs.

**Comment by jbteves** [comment]
If we want to do that we'd basically need two discrete PRs:
1. Get rid of the f_max bug, which contributed to a larger amount of varex discrepancies than clustering differences in my testing but is super easy to patch.
1. Match the clustering method in the modularized branch, which is slightly more complicated but not too bad.

I can open both in the next day or two if that's what people want to see happen. If we want them that way, I'll also open up a new issue to change the cluster thresholding method as an enhancement.
