### ISSUE TITLE
April 2021 developers' call

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#715]
### Summary

Our next tedana developers' call is this Friday, April 16, at 10a Eastern Time ([find your local time here](https://www.timeanddate.com/worldclock/fixedtime.html?msg=tedana+April+2021+Dev+call&iso=20210416T10&p1=263&ah=1))

As always, we welcome any community members who are interested in tedana to attend.

[Draft agenda](https://docs.google.com/document/d/1rqQi9JFc5oZqM5U7LVF8WYrkHhvZ-a1L9Z4LkbMnHcs/edit?usp=sharing)
[Zoom Link](https://nih.zoomgov.com/j/1610138973)

### Additional Detail

I trimmed and prioritized the agenda based on what he's aware of, but I didn't go through all open PRs & issues to see if there's something else missing. Take a look in advance to see if there are additional things we should discuss.

At the last meeting we asked more people to look at the fMRI walkthrough #690, and a series of discussions on handling of adaptive masking ( #685, #680, #697 )to give feedback. Not many (I'm also guilty) have done this yet. If you have a chance, try to take a look before the dev call.

**Comment by emdupre** [comment]
Unfortunately I won't be able to make it today 😔

But I will go through the issues you've highlighted @handwerkerd and plan to catch up from the minutes ! Hope everyone is hanging in 💛
