### ISSUE TITLE
Move logger management into new functions

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#719]
### Summary

We can move the logger management for the general, report, and reference loggers into new utility functions. Perhaps something like `tedana.io.setup_loggers` and `tedana.io.teardown_loggers`.

### Additional Detail

Two benefits are (1) less duplicated code between the two workflows and (2) the workflow functions will be more focused on the actual workflows.

### Next Steps

1. Move logger creation-related code into a new function.
2. Move logger deconstruction-related code into a new function.
3. Use both functions in both `tedana.workflows.tedana_workflow` and `tedana.workflows.t2smap_workflow`.

**Comment by jbteves** [comment]
Do we want to include the loggers in the OutputGenerator class?

**Comment by tsalo** [comment]
I don't think it's necessary. We can close all of the loggers' handlers just using the loggers themselves. Plus I don't think we want to pass our `OutputGenerator` to every function that involves logging.

The part I'm currently stuck on is ensuring that the general logger (`LGR`) is in fact the same across modules. As it stands, it's almost like we have a completely different `LGR` for each module, and the only way to operate on all of those at once is through `logging.root`, which may not be optimal. I'm looking into using `LGR = logging.getLogger("GENERAL")` instead, while still retaining the logging format we like.
