### ISSUE TITLE
release-drafter not updating

### ISSUE THREAD

**Issue by jbteves** [ME-ICA/tedana#724]
### Summary
Release-drafter has not actually updated since our last release on February 26, see [here](https://github.com/ME-ICA/tedana/releases).

### Next Steps
- [ ] Figure out why
- [ ] Apply fixes

**Comment by jbteves** [comment]
Pinging @emdupre and @tsalo on this, since I don't remember this coming up before.

**Comment by tsalo** [comment]
It looks fine to me? The most recent PRs are listed in the Changes section.

**Comment by jbteves** [comment]
No, actually I made a mistake and didn't see that despite being marked February 26, it contains changes that are up to date. My mistake, closing.
