### ISSUE TITLE
May 2021 developers' call

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#728]
## Summary

Our next tedana developers' call is this Friday, May 21, at 10a Eastern Time ([find your local time here](https://www.timeanddate.com/worldclock/fixedtime.html?msg=tedana+May+2021+Dev+Call&iso=20210521T10&p1=263&ah=1))

As always, we welcome any community members who are interested in tedana to attend.

[Draft agenda](https://docs.google.com/document/d/1ogfJ60u1ZE9MD-Qt0eCpMVBBM9ex-j5nNnFHrRv8qGk/edit?usp=sharing)
[Zoom Link](https://nih.zoomgov.com/j/1606210233)

## Additional Detail

Please look over the agenda to re-prioritize or remove your PRs/issues not worth discussion & add anything I missed.

One main non-code thing for discussion is that the OHBM tedana poster is supposed to be submitted next Tuesday, May 25th. :anguished: @handwerkerd will try to have a very rough draft worth discuss by the meeting, but ideas before & after the dev call would be welcome.

Modularization #591 is ready for review. In addition to reviewing code, more people running & comparing `Main` & this branch on their data & confirming nearly identical results would be VERY helpful.

**Comment by handwerkerd** [comment]
We had a bit of a low attendance meeting today. It's almost as if 3/4 of our dev team is trying to finish their PhDs. 😄 
You can read the minutes, but quick things to highlight are:
OHBM poster upload deadline is now 6/14 so we now have breathing room. We're going to try to get metric modularization merged before then & try to see what else we can merge as well. I'll try to get a draft poster to share by the end of next week.

For metric modularization, looking at the code is useful, but for our standard test data the difference in component table metric values is rounding errors (i.e. <10^-14). It would be useful if others like @emdupre @tsalo @dowdlelt and @notZaki could compare the results of `Main` and #591 on their own data sets to make sure this really is stable.

@tsalo we noticed the walkthrough branch ( https://github.com/ME-ICA/tedana/tree/improved-walkthrough ) is no longer linked to an open PR. Is it worth opening one we we can keep track of it. It would be nice to get some version of this merged to highlight on the OHBM poster, but I wouldn't place this as a particularly high priority.

We talked about pushing a new release before OHBM with the goal of having metric modularization & the two subsequent PRs that will changes results in it. Anything else to prioritize?

**Comment by emdupre** [comment]
> We talked about pushing a new release before OHBM with the goal of having metric modularization & the two subsequent PRs that will changes results in it. Anything else to prioritize?

I think if OHBM is still the desired deadline, really focussing on the modularization is a good (realistic) plan !
