### ISSUE TITLE
June 2021 dev call canceled

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#729]
### Summary
Our next dev call was scheduled for Friday, June 18th. This is during the OHBM hackathon and the week before OHBM. Several regulars suggested we skip and no one advocated for keeping the meeting as scheduled, so we'll skip. I'm keeping this issue open through the scheduled meeting time. If you have opinions about this, speak up soon.

**Comment by emdupre** [comment]
I'll remove this event on the shared calendar now to avoid confusion !
