### ISSUE TITLE
Error when re-running workflow

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#730]
### Summary

In setting up the interactive report to use for the OHBM poster I noticed a bug. If you run the workflow with an existing output directory with existing files, the program crashes. I suspect it sees an existing file, which will leads to running different clauses in the workflow, and that's causing the crash. I can probe this a bit more, but I wanted to get an issue up while it's on my mind.

### Additional Detail
I am running: https://github.com/ME-ICA/ohbm-2021-multiecho/blob/master/process_three_and_five_echo_datasets.ipynb
If you run the code once, everything executes without problem. The crash arises when you try to run it again without deleting the files from the first run. For the 3 echo data, I get the following error:
```
Loading input data: ['three-echo-dataset/S0map.nii.gz', 'three-echo-dataset/T2starmap.nii.gz', 'three-echo-dataset/desc-ICAAccepted_components.nii.gz', 'three-echo-dataset/desc-ICAAccepted_stat-z_components.nii.gz', 'three-echo-dataset/desc-ICA_components.nii.gz', 'three-echo-dataset/desc-ICA_stat-z_components.nii.gz', 'three-echo-dataset/desc-PCA_stat-z_components.nii.gz', 'three-echo-dataset/desc-adaptiveGoodSignal_mask.nii.gz', 'three-echo-dataset/desc-optcomAccepted_bold.nii.gz', 'three-echo-dataset/desc-optcomDenoised_bold.nii.gz', 'three-echo-dataset/desc-optcomRejected_bold.nii.gz', 'three-echo-dataset/desc-optcom_bold.nii.gz', 'three-echo-dataset/three_echo_Cornell_zcat.nii.gz']
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<timed exec> in <module>

~/code/tedana_community/master/tedana/tedana/workflows/tedana.py in tedana_workflow(data, tes, out_dir, mask, convention, prefix, fittype, combmode, tedpca, fixed_seed, maxit, maxrestart, tedort, gscontrol, no_reports, png_cmap, verbose, low_mem, debug, quiet, t2smap, mixm, ctab, manacc)
    412 
    413     LGR.info('Loading input data: {}'.format([f for f in data]))
--> 414     catd, ref_img = io.load_data(data, n_echos=n_echos)
    415     io_generator = io.OutputGenerator(
    416         ref_img,

~/code/tedana_community/master/tedana/tedana/io.py in load_data(data, n_echos)
    577                              '{}'.format(data))
    578         else:  # individual echo files were provided (surface or volumetric)
--> 579             fdata = np.stack([utils.load_image(f) for f in data], axis=1)
    580             ref_img = check_niimg(data[0])
    581             ref_img.header.extensions = []

<__array_function__ internals> in stack(*args, **kwargs)

/opt/anaconda3/lib/python3.8/site-packages/numpy/core/shape_base.py in stack(arrays, axis, out)
    425     shapes = {arr.shape for arr in arrays}
    426     if len(shapes) != 1:
--> 427         raise ValueError('all input arrays must have the same shape')
    428 
    429     result_ndim = arrays[0].ndim + 1

ValueError: all input arrays must have the same shape
```

### Next Steps

- Figure out why this is happening and solve it! 😀 
- I think, in the current code, if certain files exist in the output directory, it will use those files rather than re-generating them. Do we want an option where it will always overwrite any existing files rather than re-using? (I thought there was an option, but don't see it right now)

**Comment by tsalo** [comment]
It looks like the script is globbing _all_ nifti files in the folder, and writing the outputs to the same folder as the inputs. So the second time you run it, there are a bunch of other nifti files in the folder that are being treated as inputs. I'd either (1) hardcode the input filenames or (2) write the outputs to a different folder.

**Comment by handwerkerd** [comment]
I just checked and you're right. It's the call to tedana & not tedana. Yay!
I'll close the issue & hopefully get some more sleep.
