### ISSUE TITLE
ZeroDivisionError with tedana

### ISSUE THREAD

**Issue by Zhihao-Li18** [ME-ICA/tedana#744]
### Summary
Hi tedana experts,

I was running tedana with me-rfMRI (5 echoes, TE(ms)=15.0 30.93 46.86 62.79 78.72) from a group of subjects. Most of the subjects went well, but an error message of "ZeroDivisionError" raised from a few subjects (see screen outputs below). Could you please help me to figure out the cause of this error message? Thank you so much for the help!

### Additional Detail
INFO:tedana.workflows.tedana:Using user-defined mask
INFO:tedana.workflows.tedana:Computing T2* map
INFO:tedana.combine:Optimally combining data with voxel-wise T2 estimates
INFO:tedana.decomposition.pca:Computing PCA of optimally combined multi-echo data
INFO:tedana.metrics.kundu_fit:Fitting TE- and S0-dependent models to components
INFO:tedana.decomposition.pca:Selected 297 components with MLE dimensionality detection
INFO:tedana.decomposition.ica:ICA attempt 1 converged in 131 iterations
INFO:tedana.workflows.tedana:Making second component selection guess from ICA results
INFO:tedana.metrics.kundu_fit:Fitting TE- and S0-dependent models to components
INFO:tedana.metrics.kundu_fit:Performing spatial clustering of components
INFO:tedana.selection.tedica:Performing ICA component selection with Kundu decision tree v2.5
INFO:numexpr.utils:Note: NumExpr detected 32 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/tedana", line 8, in <module>
    sys.exit(_main())
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/tedana/workflows/tedana.py", line 669, in _main
    tedana_workflow(**vars(options))
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/tedana/workflows/tedana.py", line 530, in tedana_workflow
    comptable = selection.kundu_selection_v2(comptable, n_echos, n_vols)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/tedana/selection/tedica.py", line 244, in kundu_selection_v2
    np.min(comptable.loc[acc_prov, 'variance explained'])))
ZeroDivisionError: float division by zero

**Comment by tsalo** [comment]
What version of tedana are you using? We had someone report a similar error (#402), and it should be fixed in 0.0.9.

**Comment by Zhihao-Li18** [comment]
Thank you for this prompt response! But how can I check the version? I don't see an option for version check in the help menu.

**Comment by tsalo** [comment]
`tedana --version` should print that out.

**Comment by Zhihao-Li18** [comment]
I don't see this option available.

tedana --version
usage: tedana [-h] -d FILE [FILE ...] -e TE [TE ...] [--mask FILE]
              [--mix FILE] [--ctab FILE] [--manacc MANACC]
              [--sourceTEs SOURCE_TES] [--combmode {t2s}] [--verbose]
              [--tedort] [--gscontrol {t1c,gsr} [{t1c,gsr} ...]]
              [--tedpca {mle,kundu,kundu-stabilize}] [--out-dir OUT_DIR]
              [--seed FIXED_SEED] [--png] [--png-cmap PNG_CMAP]
              [--maxit MAXIT] [--maxrestart MAXRESTART] [--lowmem]
              [--fittype {loglin,curvefit}] [--debug]
tedana: error: the following arguments are required: -d, -e

**Comment by tsalo** [comment]
Interesting... it must be an older version then. I would recommend just updating the version to 0.0.10 then.

If you really want to determine the version, you could do the following in Python:

```python
import tedana
print(tedana.__version__)
```

**Comment by Zhihao-Li18** [comment]
Thanks a lot again. So mine is 0.0.8, I will ask my root for an update!

**Comment by notZaki** [comment]
In case a system administration isn't around to run the update, an alternative that might work is to run:
```
pip3 install -I --user tedana=0.0.10
```

**Comment by tsalo** [comment]
Hi @Zhihao-Li18. I just wanted to follow up. Did updating `tedana` solve your problem?

**Comment by Zhihao-Li18** [comment]
> Hi @Zhihao-Li18. I just wanted to follow up. Did updating `tedana` solve your problem?

Yes @tsalo, it worked like a charm! Thank you again for your kindly help!

**Comment by tsalo** [comment]
Glad to help! I'll close this now then.
