### ISSUE TITLE
Updating minimum required python package versions (nilearn)

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#761]
### Summary

I just found out that nilearn added carpet plots in version 0.7 (I was still on 0.6). We currently don't have any minimum version requirement for nilearn, so we should add 0.7. 

### Additional Detail

Checking into this, I also noticed nilearn is soon phasing out nibabel 2.0 support. I don't know if we should already restrict the minimum version, but we should probably keep track of this. nilearn also lists it's minimum reqs at numpy 1.16, SciPy 1.2, scikit-learn 0.21, nibabel 2.5, & pandas 0.24. Since we are using a bunch of these through nilearn, we might want to consider changing some of those versions to our new minimums.

### Next Steps

- Use this as an excuse to check if there are any other version minimums that are also out-of-date. Decide which version minimums to change now.

Change the versions listed in:
- README.md
- docs/installation.rst
- tedana/info.py
- Anywhere else?

**Comment by tsalo** [comment]
Agreed. I should have updated the minimum version in #696. However, I don't think there's any benefit to listing required versions outside of `info.py` (or even, really, the requirements themselves), since the installation will manage those dependency versions automatically based on the contents of `info.py`.

**Comment by handwerkerd** [comment]
Based on the above comment, the plan is to remove the existing version numbers (except for the python version number) from README.md and installation.rst and then update info.py to match the minimum requirements from nilearn.
