### ISSUE TITLE
August Developers' call THURSDAY, 8/19

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#771]
[Update]
Our next dev call is now scheduled for THURSDAY, August 19th at 4:00 PM CET / 10:00 AM EDT / 2:00PM UTC / 7:00 AM PST
[Check your time here](https://www.timeanddate.com/worldclock/fixedtime.html?msg=tedana+Augut+2021+dev+call&iso=20210819T10&p1=263&ah=1)
[https://nih.zoomgov.com/j/1608885123?pwd=ZTBobm96NDl0Nmw5Tkh3cGd6TWtTdz09](https://nih.zoomgov.com/j/1608885123?pwd=ZTBobm96NDl0Nmw5Tkh3cGd6TWtTdz09)
Meeting ID: 160 888 5123
Passcode: 651229

Here's the meeting [
Meeting Agenda](https://docs.google.com/document/d/18_tTJgkUGK9fovJslWL7FqQ8qU6JSmqqQAHq8MTo8Hs/edit?usp=sharing). There' a lot to discuss. I tried to prioritize as best as I understood, but please re-prioritize or add as appropriate.

[Original Message]
Our next dev call is scheduled for August 20th. I am traveling that day (though I am available on the 19th). I don't need to attend every dev call, but I wanted to confirm enough other people could attend that date.

There has been a nice amount of work in the last month from @tsalo, @eurunuela, @tsalo, and me that may benefit from discussion. Do people want to:
1. Meet as scheduled?
2. Attempt to reschedule?
3. Skip the August dev call?

**Comment by eurunuela** [comment]
I can meet between the 18th and the 29th.

**Comment by tsalo** [comment]
I'd prefer to meet, and am happy to reschedule. 18th-29th looks good for me too.

**Comment by handwerkerd** [comment]
Making sure the other @ME-ICA/tedana-devs see this issue.

**Comment by dowdlelt** [comment]
I could meet on the 19th certainly, and other mornings other than Wednesdays

**Comment by handwerkerd** [comment]
I'm tentatively going to say we should meet on Thursday, 10/19, at 10:00 EST (Same time, one day earlier). If I don't here any concerns by Friday, I'll make this official.

**Comment by handwerkerd** [comment]
@ME-ICA/tedana-devs I just updated the initial comment with info for our meeting this Thurday. Please check the agenda and re-prioritize as appropriate.

**Comment by emdupre** [comment]
I hoped to make this one, but it looks like I'll have to miss it. I'll also need to skip next month's call, unfortunately, but I'll catch up from the minutes / issues ! Hope everyone is well 🌻
