### ISSUE TITLE
Add minimally-preprocessed EuskalIBUR dataset to datasets module

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#778]
### Summary

One dataset we may want to include in the new `datasets` module is [EuskalIBUR](https://openneuro.org/datasets/ds003192).

### Additional Detail

We'll need to run fMRIPrep on this dataset and then upload it to the OSF (or wherever).

### Next Steps

1. Determine preferred location for data.
2. Add data to location.
3. Build manifest (not sure how this is done).
4. Add new dataset to `datasets` module.

**Comment by tsalo** [comment]
@smoia I've seen you making releases of `EuskalIBUR_preproc`. Is the preprocessed data (preferably echo-wise) going to be uploaded to OpenNeuro as well?

**Comment by tsalo** [comment]
Sorry for the delay in responding. Given that all of the data aren't available yet, I'm leaning toward providing fMRIPrep/Freesurfer derivatives of each version of the dataset as it is updated (or at least at major releases). Running fMRIPrep on my school's HPC shouldn't be a problem for the first release, and we can always revisit our process for future releases.

Would it be possible to upload the preprocessed physio data to the OpenNeuro repo as derivatives? Just for the breath-hold data that have already been shared. If you're willing to share the manual annotations, that would be amazing too, but I think just the filtered and cleaned physio data would be sufficient for the CVR example we want to include in the multi-echo-data-analysis book.

**Comment by smoia** [comment]
Hey @tsalo ! I'll try to get this done by Christmas.

**Comment by tsalo** [comment]
That would be amazing, thank you!

**Comment by smoia** [comment]
@tsalo, would it be ok if instead of bids derivatives I put everything in OSF? I did not prepare them for BIDS, and I don't have the time to do so before loosing access to the resources (I'm transferring).

**Comment by tsalo** [comment]
I think OSF would be a great place to put the files. It would be nice to organize/name the files on the OSF according to BIDS, but as long as all of the necessary files and metadata are available, we could always do that at a later date.
