### ISSUE TITLE
New Python and Numpy versions cause all components to be accepted or ignored

### ISSUE THREAD

**Issue by jbteves** [ME-ICA/tedana#781]
### Summary
With new versions of python and numpy, for some reason all components get classified as "accepted" or "ignored," failing the integration tests for 4-echo data since no "rejected" timeseries gets written on the current `main` branch.

### Additional Detail
MacOS 10.15.7 ("Catalina")
Python 3.9.6
Numpy 1.21.2
To reproduce:
Build fresh environment, install the current main branch with `pip install -e .` at the top level of the repository, run the four-echo integration test via `pytest -k four test_integration` in the `tests/` subdirectory.

### Next Steps
- [ ] Identify source of bug
- [ ] Patch the bug

**Comment by jbteves** [comment]
Anyone have any idea how to get the pinned version that CircleCI is using for `numpy`? That would help track down what version introduced whatever changes are causing this.

**Comment by tsalo** [comment]
I generally look through the environment creation step in the CI logs, but you end up having to work backwards through jobs to find when the cache was updated.

**Comment by tsalo** [comment]
Unfortunately, I wasn't able to replicate locally. Here's what I did:

```bash
conda update conda
conda create --name py39 python=3.9
conda activate py39
cd Documents/tsalo/tedana/
pip install -e .
cd tedana/tests/
pip install pytest
pytest -k four test_integration.py
```

MacOS 11.4 ("Big Sur")
Python 3.9.6
Numpy 1.21.2

I've attached the log (renamed to `txt` because GitHub won't load a `tsv`).

[tedana_2021-08-21T103758.txt](https://github.com/ME-ICA/tedana/files/7025673/tedana_2021-08-21T103758.txt)

**Comment by jbteves** [comment]
Well this is embarassing, but apparently I just hadn't updated my fork's `main`. Thanks for letting me know about the replication failure @tsalo
