### ISSUE TITLE
Numpy Deprecating `int` and `float` aliases

### ISSUE THREAD

**Issue by jbteves** [ME-ICA/tedana#782]
### Summary
As of Numpy 1.20.0, the aliases `np.int` and `np.float` are deprecated. We have an instance of this in the codebase which we should patch. The overwhelming majority are outside of our control as they originate from third-party packages such as `sklearn`, specifically in the `linear_model` sub-package.

### Additional Detail
Read more [here](https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations).
Instance occurs [here](https://github.com/ME-ICA/tedana/blob/e8a43ebe1ac896a7c4cd69bc7ba473c28775ecc6/tedana/selection/_utils.py#L59)

### Next Steps
- [ ] Revise to specify precision of cast
- [ ] Consider suppressing third-party warnings

**Comment by tsalo** [comment]
I like the idea of suppressing the warnings. I assume we'll need to bump our minimum versions for several packages once numpy removes these aliases?

**Comment by jbteves** [comment]
I don't believe we will need to. I'm much more concerned about the versioning that's causing #781. For this one we should be able to filter out the specific warning from numpy about `np.int` and `np.float`.

**Comment by tsalo** [comment]
I think we're in good shape at this point. Going to close this.
