### ISSUE TITLE
Add minimally-processed "Multi-echo masking test dataset" to datasets module

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#783]
### Summary

A dataset we may want to include in the new `datasets` module is [Multi-echo masking test dataset](https://openneuro.org/datasets/ds002156).

### Additional Detail

We will need to process this dataset with fMRIPrep.

### Next Steps

1. Determine preferred location for data.
2. Add data to location.
3. Build manifest (not sure how this is done).
4. Add new dataset to `datasets` module.

**Comment by tsalo** [comment]
@Shotgunosine the README for this OpenNeuro dataset said that it would be released in 2020. Is what's on OpenNeuro the full dataset, or will more be published at a later date?

**Comment by Shotgunosine** [comment]
There's more, but it may be a few months yet before I can release it. I'll let you know when I do.

**Comment by tsalo** [comment]
Sounds good. Thanks @Shotgunosine!
