### ISSUE TITLE
Add GODEC to package

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#79]
This was initially brought up in the me-ica repository ([here](https://github.com/ME-ICA/me-ica/issues/4)), but after discussing it with @emdupre we figured it would be good to open here as well. This is a low-priority enhancement, but is probably worth incorporating in the long term.

**Comment by dowdlelt** [comment]
Can't hurt - though I will note that the T1c data produced by MEICA does appear to have the global nuisance signal removed. I've been fiddling with the rapid tide toolbox recently and today I discovered that T1c_medn data has nearly the exact same time course as the MEDN data after passing it rhough rapidtide. As a brief overview, rapidtide takes the global signal, filters to low frequency bands and performs lagged correlations on a voxel wise basis, shifting the regressor forward and backward in time. This leads to maps that seem to reflect the transit time of blood, and perhaps the effects of CO2. The lagged correlations can be filtered out of the data.  

I found it fascinating that the two timecourses were virtually identical, both appearing to capture and remove global fluctuations. 

Thus, I think the T1c data, as @prantikk mentioned, is nearly equivalent to GODEC and appears to remove similar global fluctuations as other toolboxes. Hopefully I can produce some examples of this tomorrow. 

Never going to complain about more features though ;)

**Comment by jbteves** [comment]
It seems like the only thing left for your PR is to add unit tests and perform review, @tsalo. Would you mind sketching out some general thoughts for what unit tests should be done? Then perhaps @monicayao and I can work on finishing this up!

**Comment by tsalo** [comment]
I don't think any of the current tedana developers (including me) has the necessary knowledge to review the GODEC code, unfortunately, which is why I've been comfortable putting it on the back burner for the foreseeable future. I basically just copied everything over line by line, but I have no clue if it's any good.

**Comment by jbteves** [comment]
Ah, I see, I misunderstood, sorry.

**Comment by tsalo** [comment]
Since GODEC does not leverage any multi-echo information (and could be performed on any decomposition-based denoising results, AFAIK), I think it would be preferable to just move the GODEC code into a separate repository (nidecomp, maybe?). If we get it working there, we could make it a dependency for tedana.

**Comment by tsalo** [comment]
Opened https://github.com/tsalo/nidecomp/issues/2.

**Comment by tsalo** [comment]
New repo for the original GODEC code (with some Python version-related updates, refactoring, and bug-fixing): https://github.com/ME-ICA/godec
