### ISSUE TITLE
September Developers' call

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#794]
Our next dev call is scheduled for Friday, September 17th. However, we are planning to meet with the fMRIPrep team about tedana-fMRIPrep integration on Wednesday, September 15th (see https://github.com/nipreps/fmriprep/issues/1010). In the interest of reducing our meeting count, would anyone be opposed to either skipping our developers call this month or tacking it on to right after the fMRIPrep call?

EDIT: Here is the [tedana + fMRIPrep meeting agenda](https://docs.google.com/document/d/1uDGtv9VLGGg60LVG55FaiSivVx9PJT5UMG0UVPVuKvE/edit).
EDIT 2: Also, I've added the meeting (with Zoom link) to the tedana GCal.

**Comment by tsalo** [comment]
Okay, we're looking at 4 :+1:s and no :-1:s, so I guess we can cancel the Friday meeting? The next question is whether we want to try to have a dev meeting after the fMRIPrep call or not. Thumbs up for continuing the call (probably in a separate Zoom room) and thumbs down for just cancelling?

**Comment by handwerkerd** [comment]
The one thing that I think is worth discussion before our October meeting is cutting a new release. Our last full release was late April and we have a release candidate from a month ago and includes a massive amount of new stuff.

We were talking about trying to resolve #762 first, but that's been around for a while & it might not be worth waiting for a resolution. Is there anything else needing broad discussion this month? 

If you think we should cut a release now 👍 and if you think we should wait or discuss more 👎

**Comment by eurunuela** [comment]
I'd like to get #793 merged before the release. I feel like quite a few people have complained about the reports not rendering and I think the fix can be quickly merged.

**Comment by tsalo** [comment]
I agree that #793 should be merged first (though it's just waiting on CI, so that'll happen very soon). After that I think a release is a good idea. @jbteves would you be willing to start working on the release notes in the current release draft?

**Comment by tsalo** [comment]
I do think we'll want to make another release after addressing JOSS review comments, but I don't think that should stop us from releasing 0.0.11 soon.

**Comment by jbteves** [comment]
I can work on it later this week, sure. CI is apparently having issues with the three-echo test but it's not clear to me why, it's hanging without further info.
