### ISSUE TITLE
[JOSS review] developer's guide link broken

### ISSUE THREAD

**Issue by martinagvilas** [ME-ICA/tedana#796]
### Summary

Hey! I noticed the developer's guideline link in the readme [here](https://github.com/ME-ICA/tedana#getting-involved) seems to be broken. Perhaps you were trying to point to this url: https://tedana.readthedocs.io/en/stable/developing.html?
<!--
If needed, add additional detail for:
1. Recreating a bug/problem
2. Any additional context necessary to understand the issue

**Comment by eurunuela** [comment]
Hi @martinagvilas ! Good catch! Actually, the next release should update the docs. The link for the stable release should be the one you shared. To have a look at the "latest" version of the guidelines see [here](https://tedana.readthedocs.io/en/latest/contributing.html#developer-guidelines).

**Comment by martinagvilas** [comment]
@eurunuela great! Thanks for the link to the latest version.

**Comment by tsalo** [comment]
The link should be good now that #797 has been merged.
