### ISSUE TITLE
[JOSS review] Documentation suggestions

### ISSUE THREAD

**Issue by martinagvilas** [ME-ICA/tedana#798]
I found the documentation super complete and easy to follow. I really don't have more than a few minor suggestions following the JOSS reviewing guidelines:

- [ ] In the [installation instructions](https://github.com/ME-ICA/tedana/blob/bb573840da9176374ee8f4e9cb50e15ff7f097e1/CONTRIBUTING.md#3-run-the-developer-setup) for the developer version, I think it should say `pip install -e .'[all]'` (with quotes surrounding `[all]`), at least for my operating system (MacOS).

- [ ] Maybe some interactive demos might be useful? I see some example notebooks [here](https://github.com/ME-ICA/tedana/tree/8477aabc2081c1b97ad646b203516ccea9ad75d8/examples) that are not linked in the online documentation (but maybe I missed them). I see they are basically showing the same steps as outlined [here](https://tedana.readthedocs.io/en/latest/approach.html) but I still think it would be useful for users to be able to interact with that walkthrough and for you to also provide (or point to) a downloadable dataset that can be used for the demo, if possible.

- [ ] Feel free to disregard if you don't agree, but I think it would be clearer for new users (at least in terms of functionality) if the about section in the readme and online documentation first highlights the purpose of the toolbox, and then the context and prospective user case. Something like this rearrangement seems clearer to me:

    > `TE`-`de`pendent `ana`lysis (`tedana`) is a Python module for denoising multi-echo functional magnetic resonance imaging (fMRI) data. The `tedana` package is part of the ME-ICA pipeline, performing TE-dependent analysis of multi-echo functional magnetic resonance imaging (fMRI) data. The ME-ICA pipeline originally performed both pre-processing and TE-dependent analysis of multi-echo fMRI data; however, `tedana` currently assumes that you’re working with data which has been previously preprocessed.

- [ ] Maybe it would be nice to explicitly tell users how to check if their installation is correct. I find the example recommendation of [nilearn](https://nilearn.github.io/introduction.html) very user-friendly, but of course you are probably aware of it :) 

https://github.com/openjournals/joss-reviews/issues/3669

**Comment by emdupre** [comment]
Thanks for your review, @martinagvilas ! We've pushed changes to the `JOSS` branch in https://github.com/ME-ICA/tedana/commit/3ef3ccfaed49eed879a279c5ca95502b702a5f1b which I believe address your comments  :smile_cat:  

The one point I want to explicitly follow-up on is the idea for interactive demos. We definitely agree that these would be useful ! We're actually working on making datasets easily available within `tedana` (see #720), which will help with this goal. However, this work is still ongoing -- and using these datasets in the walk-through will require a larger update of the documentation. Specifically, we'll need to move away from the current 8-echo demonstration dataset (which is not openly available) to another publicly available dataset with a large number of echos.

That said, we have renamed the previous `Examples` folder to `Notebooks` to make it clearer to users that these -- at present -- are not intended to be runnable examples. We've also moved the folder from the top-level directory into the documentation, which should hopefully better situate it in its appropriate context !

Please let me know if this (and the linked commit !) addresses your concerns, here !

**Comment by martinagvilas** [comment]
Hi @emdupre, thanks for addressing these points.

I see how creating the demos takes a lot of time, and I think the publication of your package in JOSS shouldn't be halted for that reason if it is a work in progress. 

So I considered this issue resolved 👍
