### ISSUE TITLE
Three-echo integration test frequently fails due to exceeded context deadline

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#800]
### Summary

The three-echo test is failing regularly (see #793) due to the following:

```
make: *** [Makefile:21: three-echo] Hangup

Too long with no output (exceeded 40m0s): context deadline exceeded
```

In the above PR, it looks like the failure was after PCA, but before ICA.

**Comment by tsalo** [comment]
It's currently failing in `main`.

**Comment by emdupre** [comment]
Should we try sub-sampling or down-sampling the data to avoid this ?

**Comment by eurunuela** [comment]
Is this issue still a thing?

**Comment by tsalo** [comment]
I believe so.

**Comment by eurunuela** [comment]
Can we close this?
