### ISSUE TITLE
Remove accepted and rejected time series from the standard file outputs

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#819]
### Summary

The terminology for the 'denoised' vs 'accepted' time series is confusing to end users and saving both of these files is a waste of space most of the time. The proposal is to stop saving these time series and making the documentation a bit more explicit on how an end user can generate these files as needed.

This is based on a comment by @emdupre in the [Oct 2021 dev call.](https://docs.google.com/document/d/1IYthF4JxKhWxrxpV8C61SGdjNbIYnRI8L294eP9D6cg/edit?usp=sharing)

### Next Steps

- Decide if others agree to move forward on this
- Decide if there's anything we can do to make it easier for an end user to generate and save these files or, if it's already easy enough, clearly document how to do it.

**Comment by tsalo** [comment]
👍 to remove `optcomAccepted` and `optcomeRejected`, but I don't want to remove `optcomDenoised` (though renaming it to just `denoised` might be nice). Based on the issue name I assume that's what you're proposing, but in the summary you mention "denoised" specifically, so I wasn't sure.

**Comment by tsalo** [comment]
Love it! If we're focusing on the denoised data, then we can even document it like AROMA. For example, we could distinguish between aggressive and non-aggressive denoising, and show how to do both in our documentation.

**Comment by jbteves** [comment]
I am admittedly not an fMRIPrep user and therefore a smidge biased, but I really don't want to explain the logic behind `desc-TEDANAnonaggr` to new users when `desc-denoised` is much more clear.
