### ISSUE TITLE
Change number of volumes when saving images

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#82]
The function, filewrite, uses a ref_img to get all the parameters for the output image. Looking through the code, it seems like the same ref_img is used for almost all outputs. I think this is causing some problems because, the ref_image has the same number of volumes as the time series, but some of the outputs have a different number of volumes, yet are still coded having more.
https://github.com/ME-ICA/tedana/blob/2fa0136605f52a54fc11f361cd883af0e6a6fb8f/tedana/utils/utils.py#L241

The quick solution is to add lines into https://github.com/ME-ICA/tedana/blob/2fa0136605f52a54fc11f361cd883af0e6a6fb8f/tedana/utils/utils.py#L302 and https://github.com/ME-ICA/tedana/blob/2fa0136605f52a54fc11f361cd883af0e6a6fb8f/tedana/utils/utils.py#L333 that will adjust the number of volumes in the image to match the number of volumes in the new data set.

I'm not sure if there's an easier way to do this within the nilearn I/O framework or if there are other data-specific parameters we should also be examining and changing as well.

Also, related to this, any reason why the volume I/O functions are in utils.py rather than io.py?

**Comment by handwerkerd** [comment]
Looking into this issue a bit more, it seems like ref_img is a critical variable, but, in the current code. I think it's originally assigned at: https://github.com/ME-ICA/tedana/blob/2fa0136605f52a54fc11f361cd883af0e6a6fb8f/tedana/workflows/tedana.py#L94
where the data variable is either a filename as a string or a list of file names.
In that case, the load_data function returns a single variable at: https://github.com/ME-ICA/tedana/blob/2fa0136605f52a54fc11f361cd883af0e6a6fb8f/tedana/utils/utils.py#L148 without ever assigning ref_img since that variable's assignment is below the return statement https://github.com/ME-ICA/tedana/blob/2fa0136605f52a54fc11f361cd883af0e6a6fb8f/tedana/utils/utils.py#L155

I'm confused enough about what's going on here that I don't want to mess with this too much unless I hear from someone who has a better idea of how this function was set up. Also, the pull request #70 seems unfinished and overlaps with this section of code a good bit. @tsalo Do you think it's worth trying to address this one issue as a stand-alone or wait until that I/O PR is complete and then work on that version?

**Comment by rmarkello** [comment]
Hey Dan! I do apologize for the code being a bit obtuse here; this got hacked together when I was adding alpha-level gifti support back when we thought that was going to be an integrated feature. Thankfully, in speaking with @emdupre it sounds as though gifti support might be dropped altogether, and this should get severely cleaned up by @tsalo's PR!

Nonetheless, to address your current problem: hypothetically, a differing number of volumes between `ref_img` and any given functional data to be written out _shouldn't_ be throwing any errors. The `new_nii_like` function you referenced currently pulls the number of volumes from the new data set:

https://github.com/ME-ICA/tedana/blob/2fa0136605f52a54fc11f361cd883af0e6a6fb8f/tedana/utils/utils.py#L324-L327

That second line (L325) reshapes `data`, which is a 2D `(voxels x volumes)` array, into a 4D image `(X x Y x Z x volumes)`, where `(X x Y x Z)` is based on `ref_img` and the `(volumes)` dimension comes from the `data` object itself. But if this is causing you issues somewhere let me know where and I can try and figure out why!

**Comment by handwerkerd** [comment]
I've been trying to figure this out a bit more. I think this might be an issue with how AFNI interacts with the reading & writing functions in nilearn. Here's what I've been doing. I run the command:
```
tedana -d S06_Task01_e1.in.nii.gz \
                 S06_Task01_e2.in.nii.gz \
                S06_Task01_e3.in.nii.gz \
            -e 15.4 29.7 44.0 \
           --fout --filecsdata --seed 123425
```

When I go into the resulting TED directory, and run afni, I get a bunch of warnings like: 
** WARNING: NIfTI file S06/Task01/TED/T1gs.nii dimensions altered since AFNI extension was added

AFNI lists all the files as having 160 volumes (the same as the time series), but correctly displays them with fewer volumes.

When I run a command like `nifti_tool -disp_hdr -infiles s0v.nii ` I get the correct number of volumes in the "dim" field of the NIFTI header so this probably has to do with copying something in the AFNI extension header that shouldn't have been copied.

I haven't had this issue with reading and writing files directly with nibabel functions and nilearn's `new_img_like` seems under-documented without digging into the code more than I should right now. Thoughts where this issue might arise? @afni-rickr 

More generally, the nilearn input/output functions seem nice, but it seems they add unnecessary opacity & rigidity over more directly calling nibabel functions as in the original meica code. I haven't used the nilearn I/O functions directly before so perhaps I'm missing some benefits?

Also, if I'm reading the code correctly, the default is to pass a string to the reference file name and every time a few volume is written, the ref_img file's header or the entire ref_img volume (unclear) needs to be read into memory. I would probably be better to pass around the pre-loaded header information rather than the string.

**Comment by rmarkello** [comment]
Got it! Thank you so much for digging into this&mdash;this is absolutely an unintentional bug. 

What's happening is that the AFNI extension from the `ref_img` isn't being stripped out when the header is copied to the `tedana`-generated output files in `filewrite()`. When the `ref_img` object is _created_ (in the case of a provided zcat image) the header extensions are explicitly removed (L157, below):

https://github.com/ME-ICA/tedana/blob/2fa0136605f52a54fc11f361cd883af0e6a6fb8f/tedana/utils/utils.py#L154-L158

However, as you noted, when individual echos are provided the `ref_img` file is just a pointer to one of those files:

https://github.com/ME-ICA/tedana/blob/2fa0136605f52a54fc11f361cd883af0e6a6fb8f/tedana/utils/utils.py#L147-L148

We should be able to mirror the creation of a `ref_img` object, with header extensions removed, for the latter case which should resolve the tedana output / AFNI input compatibility issues!
