### ISSUE TITLE
November Developers' call. THURSDAY, 11/18

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#826]
In #821 we proposed moving our regular developers' call to Thursdays rather than Fridays. I'm not sure we're ready to make this a standing change yet, but maybe we can take this month-by-month for a little bit. This means our next dev call would be on
THURSDAY, 11/18 at 4:00 PM CET / 10:00 AM EDT / 2:00PM UTC / 7:00 AM PST
[Check your time here](https://www.timeanddate.com/worldclock/fixedtime.html?msg=tedana+November+Developers%27+Call&iso=20211118T10&p1=263&ah=1)

@ME-ICA/tedana-devs Please either confirm this time works for you or let me know that you wouldn't have planned to attend on Thursday or Friday.

[https://nih.zoomgov.com/j/1610947409?pwd=SW00T3BaVkJWYml5SXY5YlZOUXVsQT09
](https://nih.zoomgov.com/j/1610947409?pwd=SW00T3BaVkJWYml5SXY5YlZOUXVsQT09
) Meeting ID: 161 094 7409
Passcode: 715158
[
Meeting agenda](https://docs.google.com/document/d/1O_Z8P3_ct2Bu2I7BZxjLtayjihcNktjGKN52hAgeY9M/edit?usp=sharing)

**Comment by emdupre** [comment]
I'll be there on Thursday :)

**Comment by handwerkerd** [comment]
I just added a link to the meeting agenda. Please take a look and add stuff or re-prioritize.
