### ISSUE TITLE
Add acquisition documentation

### ISSUE THREAD

**Issue by emdupre** [ME-ICA/tedana#83]
~.@dowdlelt had compiled [a google spreadsheet](https://docs.google.com/spreadsheets/d/1WERojJyxFoqcg_tndUm5Kj0H1UfUc9Ban0jFGGfPaBk/edit?usp=sharing) of published multi-echo scanning parameters. It would be great to include this in a more general, motivating section of the [readthedocs](tedana.readthedocs.io) on what mutli-echo EPI acquisition entails, such as echo times, effective echo spacing, in-plane acceleration, etc.~

~I _think_ that @dowdlelt is getting started on this ! If there's anything else that could / should be added, it'd be great to keep track of it here.~ 

This is done, now ! :tada: :sparkles: 

Following our May tedana developers calls, @jbteves came up with the following actionables:
- [x] link datasets and their sequence parameters (fixed by #284)
- [ ] add parameter adjustment locations for various scanner manufacturers
- [ ] link to CMRR for guidance on getting sequences at institutions

I think @handwerkerd @dowdlelt and @tsalo (currently) have the most expertise on this, but it would of course be great to get feedback from anyone interested in acquiring multi-echo data !

**Comment by dowdlelt** [comment]
Strong motivation to make some progress here - I've nearly finished adding details to what is on the spreadsheet - but I'm quite certain I am still missing some papers. I'm not strong with the idea of adding to the documentation, but I'm still motivated to figure it out. I'll keep chipping away at it - for delays, please blame the world cup. Thanks for the shout out

**Comment by tsalo** [comment]
To consolidate discussion from Gitter, here are some recommendations for doing multi-echo with the [CMRR MB sequence](https://www.cmrr.umn.edu/multiband/). They are Siemens-specific (and maybe even 3T-specific as well), but may be useful generally:
- Number and timing of echoes can be set in "Contrasts" in Sequence, Part 1 tab.
- If you want short TEs and are using GRAPPA acceleration, use an excitation pulse of 4000-4200 and enable LeakBlock (per @handwerkerd).
    - LeakBlock is set in the Sequence, Special tab.
    - If banding occurs with the above settings or you don't care about short TEs, consider extending the excitation pulse to 8180 (per @dowdlelt) 
- If using GRAPPA acceleration, use GRE with default FA=12 (good performance per @handwerkerd) or use FLEET with FA=15 and 5 dummy scans (MGH multi-echo recommendations and used by @dowdlelt), but do not use single-shot EPI.
    - Papers use FLEET with a variety of flip angles from 5, 10 and 20, so it's hard to have a specific recommendation (they all seem to work...). This may be a good reason to use GRE, which has a strong default.
    - This is set in the Sequence, Special tab.
- If processing echoes individually, consider acquiring a single-band reference image. These are useful as volume registration targets (per @dowdlelt). They can also be used in conjunction with an SBRef image with the opposite phase encoding direction for blip-up/blip-down distortion correction (also per @dowdlelt).
    - This is set in the Sequence, Special tab.

**Comment by jbteves** [comment]
This is something that has come up on numerous calls and that there is still frequent Gitter discussion about. Personally I feel strongly that there should be a deadline of having something up before OHBM starts on June 9 since it will be confusing if people see the software demo there, come to our documentation, and realize they have no idea how to acquire the data to put through `tedana`. It's true that we link to scientific papers but I don't believe all of the above recommendations are published anywhere. Furthermore, that's not really the focus in most papers, so it would be hard to dig out and figure out practically what to do at the console. 
@emdupre @KirstieJane @tsalo @handwerkerd @dowdlelt any thoughts? Please tag anyone I missed that should be part of that discussion.

**Comment by jbteves** [comment]
Note that #282 offers some practical information on acquiring multi-echo data; thanks, @handwerkerd !

**Comment by jbteves** [comment]
@emdupre per today's call I think it may be good to add the following checklist:
- [ ] link datasets and their sequence parameters
- [ ] add parameter adjustment locations for various scanner manufacturers
- [ ] link to CMRR for guidance on getting sequences at institutions

**Comment by jbteves** [comment]
@emdupre I think it's only fair that if the plan is to ask new contributors to make task-lists out of their comments, I should request the same of you 😄
If you don't want to do that, may I edit your top comment?

**Comment by emdupre** [comment]
Thanks for pinging again !! Sorry for dropping the ball. Updating the top comment now :rocket:
