### ISSUE TITLE
OHBM 2022 Abstract(s)

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#833]
### Summary

I wrote a draft of the tedana abstract for OHBM 2022. [Here it is.](https://docs.google.com/document/d/1AnLP_dX59fNHkrL6ks1VGiI6FmoIt3C6FlEA9KZAmuE/edit?usp=sharing)

### Additional Detail

If people want to share other tedana connected abstracts in the comments, please do so.

### Next Steps
 
- @ME-ICA/tedana-devs and others are welcome to take a look and make comments & additions. Anything I missed? I don't think we need a figure, but anything people want to highlight with a figure?
- I'd like feedback at least from the core devs by Friday so that I can then share with all authors.
- Authorship: In the past I've suggested that we list anyone who has made contributions (code/ideas/comments/feedback) in the 18 months preceding abstract submission. This is the first time that idea might bump a couple of people. I'm leaning towards still inviting all contributors, but only including them if they positively affirm that they want to be included. Thoughts? Anyone currently not listed who I should invite?

**Comment by handwerkerd** [comment]
@manfredg Because of your PR, I've listed you as a potential author for the tedana OHBM abstract this year. I'm realizing I don't have an email address for you. Could you please confirm whether or not you want to be an author and provide the relevant info? Also, thank you for your contribution and welcome to the community!

**Comment by 62442katieb** [comment]
Hi @handwerkerd sorry for the delay in responding. Yes, I would like to be an author, thanks for reaching out!

**Comment by jsheunis** [comment]
@handwerkerd sorry for my absence in this thread. I'm very happy to be included. I've worked through the abstract and it looks good to me (great to see all the updates listed!). I've also included my details in the author table.
