### ISSUE TITLE
Make MA-PCA criteria curves more accessible to users

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#834]
### Summary

The number of PCA components is defined using one of several methods. [A recent neurostars question](https://neurostars.org/t/tedana-mask-and-components/21117/10) and an issue I've been examining would have been easier to answer if the criteria curves used to calculate the number of components were more accessible. I propose outputting these curves either by default or when the --verbose option is used.

### Next Steps

- @eurunuela has already made these values slightly more accessible in this PR: https://github.com/ME-ICA/mapca/pull/43 
- Have that PR also return either the full PCA object or the three criteria curves so that tedana can access that information
- Add code [after this line](https://github.com/ME-ICA/tedana/blob/64fa9d0b96df949a8ef38d450c37ca528f40f283/tedana/decomposition/pca.py#L236) to save the numbers in the criteria curves for aic, kic, and mdl.

**Comment by eurunuela** [comment]
> Have that PR also return either the full PCA object or the three criteria curves so that tedana can access that information

Do you think adding a "selection" array or dictionary would be enough? It could be something like `mapca.selection_ = {"aic": 67, "kic": 56, "mdl": 36}`.

> Add code after this line to save the numbers in the criteria curves for aic, kic, and mdl.

I personally think we should save the plot and log the selection numbers.

**Comment by tsalo** [comment]
I think we should leverage the "classification" and "rationale" columns of the PCA component table, and retain the full PCA mixing matrix. When we shift from "rationale" to "tags", we can also add "aic_accepted", "kic_accepted", and "mdl_accepted" tags, right?

**Comment by handwerkerd** [comment]
There are a bunch of single values that should be saved in a clear location. I'd add % variance explained by the PCA to the three selection criteria.
FWIW, the decistion tree modularization has a dictionary & saved file called `cross_component_metrics` I could see making a new file called `PCA_cross_component_metrics` now and then the decision tree's file would become `ICA_cross_component_metrics`

I also think we should be saving the curves and not just the aic/kic/mdl thresholds. Those curves were important for diagnosing issues, so if we're saving something, they should be accessible.

The full PCA mixing matrix would be a fairly large file. If we're saying it, it should definitely only be saved with the --verbose option.
