### ISSUE TITLE
Switch from gitter to mattermost

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#836]
### Summary

At the January Dev call (#835) we agreed to switch from gitter to mattermost.

### Next Steps

- [x] Share the link to the correct mattermost channel with the current developers
- [ ] Change all references in the documention to gitter to mattermost, including the badge on readthedocs
- [x] Post a message on the gitter channel noting it's deprication & pointing to the mattermost channel.

**Comment by tsalo** [comment]
Here's the Mattermost channel link: https://mattermost.brainhack.org/brainhack/channels/tedana
