### ISSUE TITLE
Fix the rendering for citations on readthedocs

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#838]
### Summary

I just noticed that the JOSS paper isn't listed in the citations on https://tedana.readthedocs.io/en/stable/ I was just going to add it, but I looked at index.rst and the reference is there, but it's not rendering. For some reason all the references are indexed as "1."  I don't see anything obviously wrong in the html, but I'm obviously missing something.

### Additional Detail

The text is rendering correctly on github at: https://github.com/ME-ICA/tedana/blob/main/docs/index.rst 

This is what I see at: https://tedana.readthedocs.io/en/stable/
<img width="712" alt="image" src="https://user-images.githubusercontent.com/7406227/153039117-6be19ef8-484e-4934-94b3-714a918858ee.png">

### Next Steps

- Someone who understands RTD more than me should figure out why the references are mis-rendering
- Minor: For both RTD and the README.md, we're asking people to cite both the zenodo & the JOSS paper. I think the indented message is that people should use the zenodo reference to identify the version of tedana they used to process their data. If this might not be obvious to users, should we clarify the text?

**Comment by notZaki** [comment]
Does this page look better? https://tedana.readthedocs.io/en/latest/

My guess is that the `stable` page is pointing to the latest release (Sep. 30) and it didn't include the JOSS paper, so it's rendering [[this version of index.rst]](https://github.com/ME-ICA/tedana/blob/4d5c6456d66c6badea7aa3730130756db286a52d/docs/index.rst)

**Comment by handwerkerd** [comment]
That looks like the issue. This is good motivation to push another release soonish.

FWIW, I'm seeing another rendering issue that's both in the stable and latest releases:
<img width="307" alt="image" src="https://user-images.githubusercontent.com/7406227/153075471-67616d50-958f-4abf-963c-68592865d033.png">
I've played around a bit and rst doesn't seem to like the slanted quotes with letters on both sides. It should be something like `TE de`pendant `ana` lysis. I think this used to look ok so maybe there was a rendering change??? I tried a few different formatting options and nothing seems to be working. I'm probably missing something obvious.

**Comment by tsalo** [comment]
I tried to fix that a while ago, but couldn't find a great solution. I think the easiest move is to have spaces separating the "code" and "non-code" portions of the words.

**Comment by handwerkerd** [comment]
I'm mildly happy there isn't an obvious solution to the rendering quirk. It's not a pretty, but
TE DEpendant ANAlysis (`tedana`)
is a simple replacement that properly renders.

**Comment by notZaki** [comment]
If the goal is to get something that looks like this:  
``TE``-``de``pendent ``ana``lysis (``tedana``)
then try:
```
``TE``\ -``de``\ pendent ``ana``\ lysis (``tedana``\ )
```

**Comment by handwerkerd** [comment]
Great. I just pushed the formatting option to #840
