### ISSUE TITLE
Add component selection documentation

### ISSUE THREAD

**Issue by emdupre** [ME-ICA/tedana#84]
It would be great to have more documentation on what component selection entails. This is only covered in a very general way at this point and could be enormously expanded.

As @jbpoline had suggested, it would be great at some point to have automatically generated jupyter notebooks (using [sphinx-gallery](https://sphinx-gallery.readthedocs.io/en/latest/syntax.html#notebook-styled-examples-syntax)), but to start with I'd love to have a break down of the kappa, rho calculations and how various points in the decision tree impact those metrics. 

One other piece: I know @handwerkerd has some examples from his `meica-reports` -- this section could be a great place to include those, until we generate some of our own !

**Comment by emdupre** [comment]
@jwe080, it'd be great to have your expertise here, too !

**Comment by jbteves** [comment]
Since the reorganization happening in #247 I think this issue should be paused.

**Comment by jbteves** [comment]
With #262 merged I am unpausing this issue.

**Comment by jbteves** [comment]
In line with many of the other issues I've commented on, I think that we should come up with a discrete set of tasks to close this issue. From the above, I could envision something like the following:
- [ ] Add kappa, rho calculations and decisions to readthedocs
- [ ] (Optional) Generate jupyter notebooks

**Comment by jbteves** [comment]
Given the interest in rewriting the decision tree, it seems that this issue is likely going to be solved as new code is written and documented. I think this issue is on probation.
