### ISSUE TITLE
Installation instructions do not work for Windows machines

### ISSUE THREAD

**Issue by aryangupta701** [ME-ICA/tedana#844]
Hello, 

I am getting errors while using the command "pip install -e .'[all]'" 
Can anyone help me to fix this please, I want to contribute to this project.

Thankyou

**Comment by tsalo** [comment]
Can you post the traceback?

**Comment by aryangupta701** [comment]
ERROR: Invalid requirement: '[all]' 
I get this error

**Comment by tsalo** [comment]
I can't reproduce locally, so maybe it's a version or path issue. Let's see if we can diagnose the problem.

- Where are you running this command from? Is it from the tedana directory?
- Is your local copy of tedana up-to-date with `main`?
- What version of PyPi are you using?
- What version of Python are you using?

**Comment by tsalo** [comment]
>I have copied this command from CONTRIBUTING.md file present in the project

Yes, but in what location on your filesystem did you run the command?

Maybe it's an OS issue. What operating system are you using?

Lastly, can you try `pip install -e .[all]` (no single quotes around `[all]`).

**Comment by aryangupta701** [comment]
yes this worked thanks a lot.

**Comment by tsalo** [comment]
Are you using a Windows machine by any chance? I'd like to make sure our installation instructions work for all operating systems, so we may need to update them if they don't work for Windows machines.

**Comment by aryangupta701** [comment]
Yes I am using a windows 11 machine

**Comment by tsalo** [comment]
Thank you.

@ME-ICA/tedana-devs do any of you use a Windows machine? Can you reproduce the behavior @aryangupta701 reported with `pip install -e .'[all]'`?

**Comment by handwerkerd** [comment]
Welcome @aryangupta701 ! I don't have easy access to a Windows computer right now so I can't help directly. This sounds like a really important issue to resolve.

**Comment by eurunuela** [comment]
My colleague @vinferrer has a Windows I believe. We could have a look on Monday.

**Comment by Cristina-Tobias** [comment]
I have tried installing tedana both ways in my Windows laptop. It has only worked without the single quotes

**Comment by tsalo** [comment]
What about `pip install -e '.[all]'`?

**Comment by Cristina-Tobias** [comment]
It showed this error message : `ERROR: .'[all]' is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with svn+, git+, hg+, or bzr+)`

**Comment by eurunuela** [comment]
> What about `pip install -e '.[all]'`?

That didn't work. We're gonna have to update our docs.

**Comment by tsalo** [comment]
No, not `.'[all]'`. `'.[all]'`.

**Comment by Cristina-Tobias** [comment]
Sorry. I have tried it again with `'.[all]'` and it shows the same error message

**Comment by tsalo** [comment]
Thank you @Cristina-Tobias, that's really helpful for nilearn too.

@aryangupta701 we can follow up in #846 about how specifically we should update the installation instructions.
