### ISSUE TITLE
Update Contributing.md file

### ISSUE THREAD

**Issue by aryangupta701** [ME-ICA/tedana#845]
hello,
In contributing.md file at the place where " pip install -e .'[all]'' is written there should be one more line written , if it did not work try using "pip install -e .[all]"

**Comment by tsalo** [comment]
Rather than opening a separate issue, I would recommend just adding a comment with "next steps" to the original issue (#844) in the future.

**Comment by eurunuela** [comment]
I believe we can close this issue. It seems to be resolved in #844.
