### ISSUE TITLE
Create a `multi-echo` tag on neurostars

### ISSUE THREAD

**Issue by emdupre** [ME-ICA/tedana#85]
Although we're not yet able to support a `tedana` user group (we'll need to be a few more releases along for that), it would be great to have a place to point people for general multi-echo questions. Right now questions seem to be scattered across [bitbucket](https://bitbucket.org/prantikk/me-ica/branch/v3), [github](https://github.com/me-ica/me-ica), emails, and [the AFNI mailing list](https://afni.nimh.nih.gov/afni/community/board/read.php?1,145704,145719). After discussion with @tsalo, @handwerkerd, it seems that there's interest in trying to funnel these to [neurostars](https://neurostars.org) as a central platform. 

@chrisfilo might be able to help us with getting a multi-echo tag on neurostars, which will help when sorting questions and answers on the platform.

**Comment by chrisfilo** [comment]
Done! https://neurostars.org/tags/multi-echo

**Comment by emdupre** [comment]
:raised_hands: Great ! thanks, @chrisfilo !
