### ISSUE TITLE
Revisiting #230 - incorporate decay curve fit information into workflow

### ISSUE THREAD

**Issue by madisoth** [ME-ICA/tedana#861]
### Summary
We're interested in how decay curve fits compare across subject age groups, from human neonates through adults. It would be great to output decay curve fit information including some or all of the measures proposed by @tsalo in the (now-closed) #230:

> - The residuals returned by [numpy.linalg.lstsq](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.lstsq.html).
> - Root mean squared error, calculated from the log data and the predicted values.
> - Something using the voxel- and volume-wise regressions. The reason I think this would be useful is that, assuming high-quality data, actual BOLD signal should increase the variability of the data within each echo, decreasing regression fit.

**Comment by tsalo** [comment]
I'm sorry for not following up sooner. I agree that having some measure of fit would be great. I tried to implement R-squared maps as part of the adaptive masking procedure in #548, but the results always seemed wrong. Do any of those measures seem particularly useful to you, and would you be willing/able to implement them?
