### ISSUE TITLE
Add minimally-processed Spreng dataset to datasets module

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#865]
### Summary

A dataset we may want to include in the new datasets module is [Neurocognitive aging data release with behavioral, structural, and multi-echo functional MRI measures](https://openneuro.org/datasets/ds003592).

### Additional Detail

We will need to process this dataset with fMRIPrep.

This dataset also has cardiac and respiratory data, which could be useful.

### Next Steps

1. Determine preferred location for data.
2. Add data to location.
3. Build manifest (not sure how this is done).
4. Add new dataset to `datasets` module.

**Comment by emdupre** [comment]
cc @rsetton and @lmwilambwe, in case they happen to have a preprocessed version of this dataset available that could be added to OpenNeuro ! :smile_cat:
