### ISSUE TITLE
Orthogonalizing rejected components permanently alters the ICA mixing matrix

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#868]
### Summary

As @jbteves and I work on the decision tree modularization, I noticed a problematic design choice. The `--tedort` option orthogonalizes the rejected components, which is a conservative way to remove rejected signal. The way it is done is by altering time series for the rejected ICA components in the mixing matrix `mmix` That means, if we look at reports, we can no longer see the component time series as they were created through ICA. This also makes it impossible to later manually change the accept/reject status of components, since the original, non-orthogonalized components are lost.

As the code was originally written, this wouldn't have been a bug, but given how the reports are currently used and the plans for better ways to manually accept and reject components, I'd say this is now a bug.

### Additional Detail
Here's the relevant code.
https://github.com/ME-ICA/tedana/blob/f42ba63829e1aa060b2be9bf2f9d72903c4714a6/tedana/workflows/tedana.py#L776-L784

### Next Steps

- We will fix this as part of #756. Should this be independently fixed any sooner?
- The solution will be to never change the mixing matrix based on component status. Orthogonalization should be a parameter that's passed to the fMRI data writing step and only applied then.
- Is there any reason to also save the Orthogonalized mixing matrix?
- Given issues like this, should be be adding information into a file's nii or json header noting which components were removed and whether they were orthogonalized?

**Comment by tsalo** [comment]
>This also makes it impossible to later manually change the accept/reject status of components, since the original, non-orthogonalized components are lost.

Isn't the orthogonalized mixing matrix written out after the original one is? And to a different file (i.e., `desc-ICAOrth_mixing.tsv` instead of `desc-ICA_mixing.tsv`)?

**Comment by handwerkerd** [comment]
I just looked at this more carefully and checked the outputs. Your correct. I wanted to open this issue while it was on my mind, but I should have checked a bit more first. This aspect of the code is confusing and it might be worth cleaning up, but that's more of a refactor than a bug. I'll close this issue for now.
