### ISSUE TITLE
seed for ICA is never random

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#87]
I noticed that the seed for the ICA step is always defined
Default set in 2 ways:
https://github.com/ME-ICA/tedana/blob/2fa0136605f52a54fc11f361cd883af0e6a6fb8f/tedana/cli/run_tedana.py#L154
https://github.com/ME-ICA/tedana/blob/2fa0136605f52a54fc11f361cd883af0e6a6fb8f/tedana/workflows/tedana.py#L32

The random number generator is seeded based on the default or a user defined seed:
https://github.com/ME-ICA/tedana/blob/2fa0136605f52a54fc11f361cd883af0e6a6fb8f/tedana/decomposition/eigendecomp.py#L262

There's actually no way to run the code with a randomly assigned seed. I'm not sure this is a good or bad design choice, but it's not clearly documented that the seed is always fixed. (I had assumed it would be random unless I set the variable). I think it does make sense to set the default to a fixed seed, but I could imagine situations where someone might want a random seed. Whether or not an unseeded option is added, the fact that the code defaults to a fixed seed should be better noted.

I can take care of this, but I wanted to make sure I wasn't missing something first & get feedback on whether it's worth added a non-fixed seed option.

**Comment by emdupre** [comment]
Thanks for bringing this up, @handwerkerd !

Yes, my thinking is that the default should be to run with a set seed to encourage reproducible results (which I think most users will expect, particularly new users). What we could do is allow people to explicitly pass `None` for the `fixed_seed` argument, and then treat that as unseeded. Right now this argument documented in the [usage section](http://tedana.readthedocs.io/en/latest/usage.html#run-tedana)&mdash; do you mean that we should expand on the docstring for that argument, or note it somewhere else, additionally ?

**Comment by handwerkerd** [comment]
The language could probably be tweaked a bit there & in the output to "tedana --help" to make clear that it is always fixed. For example, "Initial rand num generator is always fixed so ICA results are reproducible."

Adding an option to explicitly pass None might be nice, but isn't essential.

**Comment by emdupre** [comment]
That sounds great ! I'd be happy to see an explicit `None` option, too&mdash; PR welcome :smile:

**Comment by emdupre** [comment]
Ok, I went and looked through this and I think the current implementation actually _does_ support passing `None` if results should be allowed to vary between runs.

The default is `mdp.numx_rand.seed(42)`, but that's just a wrapper for `scipy.random.seed` which does allow for passing `None`. So the only change we'd need to make is to document that `None` can be passed -- maybe in the argument description ? Where do you think would be best, @handwerkerd ?

**Comment by handwerkerd** [comment]
Thank you for looking into this. That makes this a really easy fix.
It probably just needs an added comment like, 'Set to None to use a random seed' here:
https://github.com/ME-ICA/tedana/blob/2fa0136605f52a54fc11f361cd883af0e6a6fb8f/tedana/decomposition/eigendecomp.py#L241
Here:
https://github.com/ME-ICA/tedana/blob/2fa0136605f52a54fc11f361cd883af0e6a6fb8f/tedana/workflows/tedana.py#L85
and here:
https://github.com/ME-ICA/tedana/blob/2fa0136605f52a54fc11f361cd883af0e6a6fb8f/tedana/cli/run_tedana.py#L153

I don't think this needs to be mentioned anywhere else.

**Comment by emdupre** [comment]
Just opened #104 to close this. It'd be great to get your review there, @handwerkerd, to make sure it's in line with what you were looking for !
