### ISSUE TITLE
Add Rica documentation

### ISSUE THREAD

**Issue by n-reddy** [ME-ICA/tedana#883]
### Summary
Rica is not mentioned in the documentation as a tool to help with manual classification of ICA components.

### Additional Detail
Somewhat related to / precedes #851 regarding Rica documentation.

### Next Steps

- Add Rica to the documentation, potentially under [TEDICA](https://tedana.readthedocs.io/en/stable/approach.html#tedica) and/or [this FAQ section](https://tedana.readthedocs.io/en/stable/faq.html#tedana-i-think-that-some-bold-ica-components-have-been-misclassified-as-noise).
- Consider adding a mention of Rica to the tedana Terminal output.

**Comment by handwerkerd** [comment]
Closed with #756
