### ISSUE TITLE
inconsistent version numbers

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#887]
### Summary

@jbteves @n-reddy and I are working on comparing results between branches. When we type `tedana --version` on the same branch we all get the same hash but different version numbers. 

### Additional Detail

For example, the three of us are all looking at https://github.com/jbteves/tedana/tree/JT_DTM/ which is #756. Our outputs for `tedana --version` are:
Josh: `tedana v0.0.11+44.ge60f87a`
Dan: `tedana v0.0.11rc1+53.ge60f87`
Neha: `tedana v0.0.12+34.ge60f87a`

Assuming we are all looking at the same code, my best guess is that the hash is correct, but _version.py is somehow holding onto the version number from when the repo was last cloned. For both Josh & me our Main is synced with Main well after the v0.0.12 release.

### Next Steps

- @emdupre @tsalo know this part of the code best. Does one of you have the time to try to figure out why this might be happening?

**Comment by notZaki** [comment]
Maybe try updating the tags
```
git fetch --all --tags
```
and then seeing how the version updates

**Comment by handwerkerd** [comment]
That updated the version number for me. Thank you!
Is there a way to update the tags when people pull or is this just inherent to the way github/git is set up?
