### ISSUE TITLE
fproj_arr is never used

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#89]
In the selcomps function, a variable fproj_arr is created, which is a ranked list of value of a max projection of the FFT of each component. I don't think this variable is ever used again. The following line contains the creation of fproj_arr_val, which is used later in the code in an SVM classifier of rejected components to identify some additional components as midk. I don't completely get this part of the code, but it seems like fproj_arr_val might have been intended to contain the ranked list of values in fproj_arr and not the unranked values from fproj_z
https://github.com/ME-ICA/tedana/blob/2fa0136605f52a54fc11f361cd883af0e6a6fb8f/tedana/selection/select_comps.py#L178-L179

**Comment by emdupre** [comment]
I'm marking this as low priority since we're updating the selection criteria, and it's unclear if this will still be a concern in the "new" pipeline. I'll leave it open, though, so we can re-visit !

**Comment by emdupre** [comment]
Let's close it once we merge that one in ! Want to edit the issue
description to say it closes this issue ?

**Comment by tsalo** [comment]
Whoops, sorry about that. Didn't mean to close this.
