### ISSUE TITLE
October 2022 developers call

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#890]
Our next dev call is Thursday, 10/20 at 5:00 PM CET / 11:00 AM EDT / 3:00PM UTC / 8:00 AM PST [Check your time here](https://www.timeanddate.com/worldclock/fixedtime.html?msg=tedana+dev+call+October+2022&iso=20221019T11&p1=263&ah=1).

I'll try to put together an agenda later today. I don't think there was a huge amount of work done in the past month so this could be a shorter meeting. If you have topics to discuss, please comment. One topic potentially worth discussion is that the OHBM submission deadline is 12/20. We can discuss plans/goals for things to complete before submission (tedana & tedana-adjacent)

Agenda: https://docs.google.com/document/d/1dyuUarQNwsZ6DeZWIOMzUtWw3zMlXiUNJlQa_lp5xbw/edit?usp=sharing

https://nih.zoomgov.com/j/1610302358?pwd=VlRMbXpBNmg4bjJIS1B1cjlMSGVyZz09

Meeting ID: 161 030 2358
Passcode: 047525

**Comment by tsalo** [comment]
Unfortunately, I failed to synchronize my two calendars, so I accidentally booked a meeting at this time. It's a one-off, so at least I'll be able to make future meetings at the same time. It should hopefully be a short meeting, so I'll try to join once it finishes.

**Comment by dowdlelt** [comment]
Was going to add this to the agenda https://neurostars.org/t/tedana-v0-0-12-cant-read-metrics-tsv-file/23810

Some tool (like, software tool) doesn't like the rationale being `""` for accepted components. Would be an easy fix, of course, but didn't look past the current code.

**Comment by tsalo** [comment]
It's BIDS-y to fill empty cells in TSVs with `n/a` anyway, so changing it absolutely for the best.
