### ISSUE TITLE
Add "n/a" to accepted components rationale

### ISSUE THREAD

**Issue by eurunuela** [ME-ICA/tedana#892]
### Summary

This issue stems from the following neurostars post: https://neurostars.org/t/tedana-v0-0-12-cant-read-metrics-tsv-file/23810

### Next Steps

- Add na_rep='n/a' to to_csv calls.

**Comment by tsalo** [comment]
It looks like we already do this, actually:

https://github.com/ME-ICA/tedana/blob/4b44d55cf80f9658174b8724a4c4f86eaa75d150/tedana/io.py#L256-L269

**Comment by tsalo** [comment]
I wonder if it's instead related to non-tab delimited within the cells, like the semicolons separating rationales.

**Comment by tsalo** [comment]
If it _is_ related to the semicolons, and the user was running the current version of tedana, then it sounds like bids-matlab isn't reading in delimited files correctly. If you specify that a tab-delimited file is tab-delimited, then you should be able to have other common delimiters (e.g., commas, semicolons) without issue.

**Comment by tsalo** [comment]
Just to follow up from this week's meeting, the problem appears to be cells containing empty strings (`""`), rather than empty cells. @eurunuela asked us to hold off on addressing this, since it would be a very good GFI for someone at BrainHack Donostia.
