### ISSUE TITLE
Mention dropping non-steady-state volumes in documentation

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#900]
Our documentation doesn't cover dropping dummy scans before running tedana. The gists we include for running fMRIPrepped data through tedana, for example, don't mention that users should probably identify the non-steady-state volumes from the fMRIPrep confounds file and drop those volumes from the echo-wise data before denoising.

> The highest variance components have a very large spike at the beginning of the scans. That is usually a sign that the non-steady state volumes weren't removed. Siemens removes those by default, but GE keeps them. Looking at the openneuro description of these data, some participants were acquired on a Siemens scanner and others on a GE scanner. Any chance this run was GE scanner without steady state volumes removed?

_Originally posted by @handwerkerd in https://github.com/ME-ICA/tedana/discussions/899#discussioncomment-4171093_

**Comment by tsalo** [comment]
I also noticed that the non-steady-state volumes didn't cover all of the major spikes. This may be an issue for fMRIPrep, but it's worth noting on our side.

**Comment by emdupre** [comment]
@jmumford had also seen a case where not all non-steady-state volumes were flagged by fMRIPrep (or, rather, that it flagged a variable number across participants), so I'd say that the latter point is definitely on the fMRIPrep side. 

I'd suggest that the tedana docs recommend that folks identify and drop non-steady-state volumes before running, but I don't think we should do any additional checks, etc. _Caveat emptor_ and all that 🙂
