### ISSUE TITLE
Include prefix in report, log, and figures

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#901]
### Summary
I've noticed that our current output structure doesn't work well if you want to run multiple tasks/runs from the same subject/session in the same output directory (i..e, a BIDS derivatives-like structure). If we ensure that the files _without_ prefixes have them, then  it should work fine.

**Comment by handwerkerd** [comment]
Would the idea be to add a prefix to every single png file or just to the figure's directory and everything in the tedana output directory?

Also, you marked this as a breaking change. If the default option is no prefix, then I don't think this would be a breaking change.

**Comment by tsalo** [comment]
>Would the idea be to add a prefix to every single png file or just to the figure's directory and everything in the tedana output directory?

I planned to add the prefix to each figure, like how fMRIPrep does it.

>Also, you marked this as a breaking change. If the default option is no prefix, then I don't think this would be a breaking change.

That's a good point. In that case, it's just a typical enhancement.
