### ISSUE TITLE
Add information about Nashiro dataset to documentation

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#902]
### Summary

The [Heart rate variability biofeedback training and emotion regulation](https://openneuro.org/datasets/ds003823) has 3-echo fMRI, physio, ASL, MRS.... all sorts of cool stuff, basically.

### Next Steps

1. Add link to Nashiro dataset to tedana's multi-echo datasets section.

**Comment by Kasambx** [comment]
Hey can I work on this.

**Comment by tsalo** [comment]
@Kasambx absolutely. Check out #780 and #895 to get an idea of what we're looking for. Thanks!
