### ISSUE TITLE
Module is named after Python Built-In Module

### ISSUE THREAD

**Issue by awstanton** [ME-ICA/tedana#905]
The "io.py" module is named after a Python built-in module.

This manifested as an issue when I tried running a custom workflow since it was trying to use the tedana io module in place of the Python io module.

I suggest renaming "io.py" to "imageio.py" (which I ended up doing) or something similar.

**Comment by effigies** [comment]
I'm curious how this happened. `<package>.io` is not an uncommon pattern and generally doesn't cause problems.

(Not a tedana developer, just looking through the issues and this caught my eye.)

**Comment by jbteves** [comment]
Thanks for the ping @effigies. I agree, that's a bit weird...
@awstanton sorry for the delay in response, I've been a bit scattered. Could you explain how you used the package? The main way I could think of for this to happen is running `from tedana import io`, which would then place `tedana.io` into the namespace as `io`. However, `from tedana import *` should not result in this, because `io` is not included in the list of modules to be loaded in this case.

**Comment by awstanton** [comment]
Thanks for the responses @jbteves and @effigies. After taking a look again, it looks like it's my bad.

I encountered the "issue" with the following command (excluding all the file names and echo times and associated flags): `PYTHONPATH=<roothPath>/tedana/tedana python3 <rootPath>/tedana/tedana/workflows/t2star.py`. This resulted in the following error:

`Fatal Python error: init_sys_streams: can't initialize sys standard streams
Python runtime state: core initialized
Traceback (most recent call last):
  File "<rootPath>/tedana/tedana/io.py", line 10, in <module>
  File "/usr/lib/python3.10/logging/__init__.py", line 26, in <module>
  File "/usr/lib/python3.10/traceback.py", line 5, in <module>
  File "/usr/lib/python3.10/linecache.py", line 11, in <module>
  File "/usr/lib/python3.10/tokenize.py", line 27, in <module>
ImportError: cannot import name 'open' from 'builtins' (unknown location)`

However, when I ran the command with `PYTHONPATH=<roothPath>/tedana` (notice it now refers to the directory containing the package rather than the package directory itself), it worked fine.

It appears with the first command, Python found the io.py file directly in the directory I specified in the PYTHONPATH. But it seems this should not be a problem since io.py is **inside** the tedana package. I made the mistake of adding the wrong path.

My rationale for adding the PYTHONPATH setting was because it could not find the tedana package the way I was running tedana. I was running the workflow with my current directory as the "workflows" directory. When the workflow tried to find the "tedana" package from an import statement in t2star.py, it failed. So I added the PYTHONPATH setting to modify the sys.path variable so it could find the tedana package from the workflow I was in (since as far as I know we can only specify one level out - not two - in import statements by using prepending .. to the name).

**Comment by effigies** [comment]
This is not my project to give advice from, but I would advise against using PYTHONPATH for libraries. I would encourage you to find ways to avoid using it at all, if you can.

**Comment by jbteves** [comment]
This is not a recommended configuration from our point of view.
We recommend using a pip installation, ideally in a virtual environment manager such as virtualenv or conda, as described [here](https://github.com/ME-ICA/tedana/blob/main/CONTRIBUTING.md#3-run-the-developer-setup). You can pip install from a local copy of the repository per our instructions [here](https://github.com/ME-ICA/tedana/blob/main/CONTRIBUTING.md#3-run-the-developer-setup).

**Comment by awstanton** [comment]
Closing since the source of the issue has been explained and it is working fine. I have been using pip and venv fine, but I was just being stubborn about running the code from the workflows directory. No issue anymore.
