### ISSUE TITLE
Check metrics exist before running tree. Possibly calculate metrics from tree

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#921]
### Summary

In Decision Tree Modularization (#756), the functions in [`selection_nodes.py`](https://github.com/jbteves/tedana/blob/JT_DTM/tedana/selection/selection_nodes.py) were written so that it's possible to dry-run a tree and collect all metrics that would be needed to run the tree. This check is not currently being done. Once the metrics are gathered, it would  then be possible to have tedana load a decision tree and only calculate the metrics that are requested by the tree.

### Additional Detail

Every `selection_node` function has a ` only_used_metrics` parameter. If that's true, it will output the metrics it will use (i.e. kappa, rho, etc) but not actually run anything. This dry run would be added to the initialization of the component_selector object.

### Next Steps

- Figure out where this fits in relation to other priorities.

**Comment by tsalo** [comment]
What about `necessary_metrics` at the top of the decision tree? Can that be used instead?
