### ISSUE TITLE
Decision tree step incorrectly assumes a sorted component table

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#923]
### Summary

There is a step in the decision tree where the first X remaining components should be used for something where the components are sorted by variance. MEICA sorted components by variance but tedana does not. That means tedana is incorrectly using a semi-random subset of components instead of the highest variance components.

### Additional Detail
These are the key lines
https://github.com/ME-ICA/tedana/blob/f00cb25152142611b8e289ab59c7b5b8ab6eaf08/tedana/selection/tedica.py#L388-L392

This will be fixed in #756 but we might want to also fix in the current code so that pre and post decision-tree- modularization results will perfectly match.

This is a bug, but it will not affect the denoised time series. The `new_varex_lower` threshold is used to decide if components are `accepted` or `ignored` With the current version, it's possible for more components than intended to end up `ignored` but they'll still be retained in the denoised time series.

### Next Steps

- Confirm this is a real bug
- I'm fairly sure MEICA sorted components with the highest variance being component 0 so the highest variance components should be retained (the comment in the code might be wrong). Look back at some MEICA outputs to confirm this correct
- Decide if we want to fix this in the current Main so that it will match the modularized output.

**Comment by tsalo** [comment]
This sounded familiar, so I searched around and found #295. Do you know if that PR fixed the issue?

**Comment by handwerkerd** [comment]
I did also remember having this issue before. Thank you for connecting these two. You solved the same issue in a different part of the code.
