### ISSUE TITLE
Revisit make_optcom

### ISSUE THREAD

**Issue by emdupre** [ME-ICA/tedana#93]
In #90, @tsalo pointed out that we could clean up the structure of [`make_optcom`](https://github.com/ME-ICA/tedana/blob/master/tedana/model/combine.py#L11) by [converting `t2s` to a keyword argument](https://github.com/ME-ICA/tedana/pull/90#discussion_r203093336).

One open question: are there additional combination modes (beyond `t2s` and `paid`) that we foresee incorporating ? This will impact our strategy, I imagine.

**Comment by tsalo** [comment]
What about linear interpolation at -T2* using the log-transformed data? I'll admit that I haven't thought too deeply about it, but I have noticed that the optimally combined data doesn't have the same scale as one would expect for data at the T2*. If you look at the plot of the fitted curve, the echo-specific values, and the OC values from the processing pipeline details page [here](https://tedana.readthedocs.io/en/latest/_images/09_optimal_combination_value_distributions.png), you'll see the read points for the OC data floating above the curve.

If we instead use `np.interp` to predict the log(BOLD) value at -T2*, then the re-transformed OC values lie right on that curve (as expected). You can see that in the plot below:
![oc_value_distributions](https://user-images.githubusercontent.com/8228902/48315935-8dbd6200-e5aa-11e8-9b2e-6de1698a745f.png)

The correlation coefficients between the voxel-wise time series for the original OC and linear OC data tend to be high, but still vary widely. You can see the distribution in the next plot:
![oc_correlation_distribution](https://user-images.githubusercontent.com/8228902/48315942-b6ddf280-e5aa-11e8-9fc8-9a230f6a1cac.png)

**Comment by tsalo** [comment]
Actually, I think `np.interp` will only use the two surrounding points rather than the full line. Perhaps a solution is to use the FIT method. We can use the regular decay model (`tedana.decay.fit_decay`) to estimate voxel-wise T2*, and then we can use FIT (`tedana.decay.fit_decay_ts`) to get T2* and S0 time series. We then convert those into voxel- and volume-wise slopes and intercepts, respectively, to predict a given voxel's value at T2* for a given volume. Here's a mockup of the code:

```
def _combine_linear(data, tes, t2s):
    """
    Predict values for data at voxel-wise estimates of T2*.

    Parameters
    ----------
    data : (M x E x T) array_like
        Masked data.
    tes : (1 x E) array_like
        Echo times in milliseconds.
    t2s : (M X 1) array_like
        Voxel-wise estimates of T2*.

    Returns
    -------
    combined : (M x T) :obj:`numpy.ndarray`
        Data combined across echoes according to T2* estimates.
    """
    tes = np.squeeze(tes)
    n_mask, _, _ = data.shape
    mask = np.ones((n_mask))
    masksum = mask * len(tes)  # we optimally combine using data from all echoes
    _, _, t2s_ts, s0_ts = fit_decay_ts(data, tes, mask, masksum)

    intercepts = np.log(s0_ts)
    slopes = 1. / t2s_ts
    log_combined = intercepts + slopes * -t2s
    combined = np.exp(log_combined) - 1
    return combined
```

**Comment by tsalo** [comment]
I think that it's still worth it to dig into a FIT-based optimal combination, but I realized something when investigating #225. In cases where the T2* value is misspecified, the negative impact of that on the optimally combined data is reduced by the way that optimal combination is done now. Namely, it's currently done as a weighted average, but also one where one echo can never dominate the entire average. That's something I always found weird, honestly. I mean, if T2* is 30ms and TE2 is 30ms, then the optimal combination for that echo should just be TE2, right? But it isn't, and when T2* is like 5000ms, then the last echo will contribute most of the signal, but the others will contribute as well. What I realized about the FIT-based approach is that, if the T2* value is extreme, then the interpolation will predict optimally combined values that will be just as extreme, and thus completely invalid.

**Comment by emdupre** [comment]
So what do you think is the best path forward at this point ?

I see three possible paths (1) keep optcom as-is and update T2* first, (2) update both in tandem, or (3) update neither. For now, I personally am leaning towards (3) and focusing on the selection criteria. WDYT ?

**Comment by jbteves** [comment]
@emdupre @tsalo are there any discussions beyond what's up here on Issues? If so could we update this thread with a summarizing comment?

**Comment by jbteves** [comment]
@emdupre @tsalo would you mind commenting on the above?
Additionally, I will comment that personally I can't see a new optimal combination method taking priority over nearly anything else that I'm seeing. It seems to me like we should close this, and allow somebody to open an issue if they have a recommendation for a completely specified method.

**Comment by emdupre** [comment]
I think this is ready-to-close until a new method is on the horizon. @tsalo , please re-open if you disagree !
