### ISSUE TITLE
Updating contributor information

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#936]
### Summary

We haven't updated contributor information in a while. The readthedocs page is updated with version releases so now is a good time to check it over and make updates.

### Additional Detail

Contributor information is in a a few places
- https://github.com/ME-ICA/tedana/blob/main/.all-contributorsrc lists everyone's name and the types of contributions they've made This populates the grid of contributors and the emojis under their names at the bottom of our [frontpage readme](https://github.com/ME-ICA/tedana#contributors).
- https://github.com/ME-ICA/tedana/blob/main/contributions.md is a more narrative-style list of contributions
- https://github.com/ME-ICA/tedana/blob/main/docs/contributing.rst#leadership appears on [our readthedocs page](https://tedana.readthedocs.io/en/latest/contributing.html#leadership). According to that guide, "Once per year, there should be an explicit call to the larger contributor community asking if anyone wants to self nominate for a leadership role." This is that call. Will you answer the call!

### Next Steps

 Use this issue to request updates and then we'll open a PR with the updates. In theory we should vote at a dev call on anyone who is interested in a new leadership role.

For example:
- In .all-contributorsrc, my listed types of contributions are design, doc, example, & review. I'd like to add code, ideas, test, question, bug.
- In contributions.md "once in a while, even contributes to the code." should change to "contributes to the code"

**Comment by handwerkerd** [comment]
Will be (manually) closed with https://github.com/jbteves/tedana/pull/41
I'm planning to add this info to DTM so that that the release of v0.0.13 will have the older info and v23.0.0 (with the modularized decision tree) will have the new contributor info. If anyone thinks this info needs to also be in v0.0.13, speak up!

My plan is to keep that PR open until Tuesday, 4/25 at 5:00PM EST (9:00PM UTC) and then merge. If you have things you want to change, please try to do so before then. I'll also added @n-reddy, @marco7877, and @pmolfese to `.all-contributorsrc`, and updated `contributions.md` blurbs for @tsalo @jbteves & @eurunuela

**Comment by eurunuela** [comment]
Thank you @handwerkerd for taking the lead.
