### ISSUE TITLE
Allow for an inputted mask

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#96]
If I'm reading the code correctly, the volumes are always masked within the code:
https://github.com/ME-ICA/tedana/blob/bfaec0632b2e395b31cc830f62d16e4c057addc9/tedana/workflows/tedana.py#L203
There is no way for a user to create their own mask and use that instead. This issue came up when I was answering a question from J Dalenberg & realized I needed to make an entire dataset to make sure certain voxels were removed from the analysis (and I still wasn't be able to control if additional voxels would be removed).

I suggest adding an option for users to apply their own masks. I can take care of this if others agree it would be useful. My only hesitation on doing this immediately is I'm not sure how it might interact with @tsalo's pull requests, like #70

**Comment by tsalo** [comment]
I think that the ability to use manually specified masks is essential. #70 should probably be dealt with before adding in new masking stuff though. I'd be happy to revisit #70 (I'd taken a break from it because I got kind of stuck in the weeds with it) but knowing definitively whether we want to keep or drop gifti support would help a lot.

**Comment by handwerkerd** [comment]
I agree that it's worth waiting until #94 is done, but I don't think there's a reason to wait for #70.
At least for now, I think it would just require adding a new parser option to:
https://github.com/ME-ICA/tedana/blob/bfaec0632b2e395b31cc830f62d16e4c057addc9/tedana/cli/run_tedana.py#L170
adding maskname as an input variable to the tedana function, then an if clause to: https://github.com/ME-ICA/tedana/blob/bfaec0632b2e395b31cc830f62d16e4c057addc9/tedana/workflows/tedana.py#L203 that would load and create the `mask` and `masksum` variables if a mask filename was inputted.

**Comment by rmarkello** [comment]
Hey! So I know @emdupre is working on this now so I should have been paying closer attention to the issues and raised my concerns earlier&mdash;apologies for that!&mdash;but I'm a bit worried about this. If I'm interpreting this correctly, this would open up `tedana` to permit users to provide _any_ user-defined mask. (If I'm not interpreting this correctly, please let me know and/or disregard this concern!)

If I am understanding correctly, I worry that someone could provide a very conservative mask (e.g., a single ROI in visual cortex) that would limit the efficacy of the decomposition by drastically reducing the spatial information to which it has access. I think I understand the desire to ensure that certain voxels are excluded from the analytic pipeline, but I also think there is a delicate balance in permitting that flexibility. Would it be worthwhile to provide some guidance in documentation (e.g., "DON'T DO THIS WITH A VERY CONSERVATIVE MASK")? Or perhaps a very explicit example of when this would be acceptable (versus not)?

Sorry again for being a malcontent and posting my concerns after work has already begun... I'll try to do a better job of monitoring these issues in the future!

**Comment by emdupre** [comment]
I'd be happy to add a disclaimer to the documentation and / or logger, but it'd be great to hear @handwerkerd's experience with this use case -- in your experience, Dan, have you seen individuals wanting to use very restrictive masks ? If so, maybe we should be making other changes to the selection criteria (or at least noting that they _will_ need to be made) if a mask is supplied.

**Comment by handwerkerd** [comment]
I haven't dealt with anyone wanting to use very restrictive masks. If someone does feed this a small ROI, the ICA and other steps will fail in multiple ways so I'm not too worried that they'll get believable, but wrong results. That said, it wouldn't hurt to add a warning and eventually to add checks to highlight if something bad is happening in processing (i.e. only "10 ICA components found. Too few to use for denoising")

**Comment by emdupre** [comment]
re the ICA failing: right now we have warnings for too few accepted components here:

https://github.com/ME-ICA/tedana/blob/e0ee1cc139b25b9d515465ce067c542ed3db6cd2/tedana/workflows/tedana.py#L429

and here: 

https://github.com/ME-ICA/tedana/blob/6cec05349473a55725ab32115535d0538216bfcf/tedana/selection/select_comps.py#L613

Do you think we'd need another warning ?

I've gone ahead and added a note to the RTD site [here](https://github.com/ME-ICA/tedana/pull/108/files#diff-6b8768d928ef9ab4f13707da19516369R24), but please let me know @rmarkello and @handwerkerd  (and anyone else !), if you'd prefer to see something different.

Thanks for bringing up this concern, Ross !

**Comment by rmarkello** [comment]
I think the warning looks perfect! Sorry for bringing it up so last minute, but I think providing some direction with regards to the documentation is a good solution.
