### ISSUE TITLE
Proposal to add pre-commits to tedana

### ISSUE THREAD

**Issue by eurunuela** [ME-ICA/tedana#972]
### Summary

I am starting to go a bit crazy with the style checks. I find the error logs less and less informative and fixing them ends up taking longer than it should.

I propose that we start using [pre-commits](https://pre-commit.com/) to ensure the code style is always correct when pushing commits to GitHub.

### Additional Detail

Here's an example of a `pre-commit` configuration file I use in another project: https://github.com/eurunuela/pySPFM/blob/main/.pre-commit-config.yaml

### Next Steps

- Create the `.pre-commit-config.yaml` file and populate it with desired instructions and options.
- Update the installation file to make `pre-commit` a necessary dependency for devs.
- Update the docs to reflect that tedana devs use `pre-commit`.

Edit: I have opened #973 but I will keep it as a draft until the most active devs or those on the steering committee (mostly @handwerkerd, @tsalo, and @dowdlelt) give their opinion here.

**Comment by handwerkerd** [comment]
My concern is that we make things a bit easier for regular contributors at the expense of making it slightly harder for someone to submit their first PR. I haven't used pre-commits before so many this isn't a valid concern. At a base level, it looks like you're starting to edit `CONTRIBUTING.md` One you have that draft done, many we can have me and a few of the newer contributors give it a try to make sure the instructions are still clear and accessible.

**Comment by eurunuela** [comment]
The idea is that code styling would be taken care of automatically when pushing commits. So, as long as new contributors have pulled from `main` to get the pre-commit config file, they wouldn't have to do anything else.

Happy to update `CONTRIBUTING.md` to make it clearer for new contributors.

**Comment by handwerkerd** [comment]
I'm conceptually fine with this. Let me know when you want a review for #973. I'm not sure I'm the best person to make sure you did everything right, but I can check if it's functioning as intended.
