### ISSUE TITLE
Fragile dependencies

### ISSUE THREAD

**Issue by effigies** [ME-ICA/tedana#976]
### Summary

There are currently hard pins of bokeh and jinja2, which make it very difficult to install tedana alongside other tools that may require more recent versions. For example, installing jupyterlab into an environment with tedana installed produces:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tedana 23.0.1 requires jinja2==3.0.1, but you have jinja2 3.1.2 which is incompatible.
```

This is not currently a problem for me, as I am not using these features of tedana, but using `==`, or `<` pins tends to make it difficult to resolve dependencies.

It looks like these were added in https://github.com/ME-ICA/tedana/pull/793 and https://github.com/ME-ICA/tedana/pull/870, which are 2 and 1.5 years old, respectively. It is not uncommon for tools to only support dependencies released within the last 2 years or so, so it is going to become increasingly difficult to install tedana into the same environment as other tools in the near future.

A little related to #934, but not exactly the same.

### Next Steps

IIRC, there was a weirdness with Jinja 3.0.2, so possibly that pin can just be removed at this point (or updated to `jinja2 != 3.0.2`.

I don't know anything about bokeh and how hard it will be to accommodate a more recent version.

**Comment by handwerkerd** [comment]
I just updated to `jinja2`=3.1.2  and I'm getting the same error so we cannot just skip a version or two.
An issue that provides more detail is #869. The `jinja2` & `bokeh` issues are linked. `bokeh` was locked on older versions of `jinja2` & it looks like `bokeh` removed that limit about a year ago so we should able to remove our `jinja2` limit if we update `bokeh`.

The person who worked on the `bokeh` parts of the `tedana` reports moved on to other things so we'd benefit from someone with more `bokeh` experience to figure out what's still holding back a `bokeh` upgrade & fix that.

**Comment by eurunuela** [comment]
I have worked a bit on the bokeh side of things in our reports in the past. I can try to have a look and see if there is anything we can do with these dependencies.
