### ISSUE TITLE
Fix reference rendering in HTML report

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#986]
### Summary

In `tedana_report.html` files LaTeX formatting for references are not rendering correctly.

### Additional Detail

For example, see https://me-ica.github.io/ohbm-2023-multiecho/tedana/tedana_results_kundu_five-echo/tedana_report.html
The raw LaTeX typesetting appears in the HTML

**Comment by eurunuela** [comment]
Was it always like that?

I may be wrong but something tells me this is new after #875?

**Comment by crewalsh** [comment]
@eurunuela I poked around a bit to see if there was an easy option to fix the in-text citations in the report using pybtex (or any other package), but couldn't seem to find an easy solution. Have you had time to look at this any further? I think it might be possible to fix with some regex, but didn't want to re-invent the wheel if you've already had luck with this.

**Comment by eurunuela** [comment]
Hey @crewalsh , I haven't had much time but I think I may be able to work on it today.
