### ISSUE TITLE
Search on tedana.readthedocs.io is hanging

### ISSUE THREAD

**Issue by handwerkerd** [ME-ICA/tedana#993]
### Summary

If you go to https://tedana.readthedocs.io/en/stable/ and try to search using the search box in the left column it hangs forever without giving results

### Additional Detail

- Both @n-reddy and @eurunuela have observed the same problem
- Looking online, some people say things hang when you search for terms not in the documentation, but it also hangs for terms in the documents, like `fMRI`
- Using Google search for `site://tedana.readthedocs.io fmri` works
- `https://readthedocs.org/search/?q=project%3Atedana` also works
- There are a couple of online discussions like https://stackoverflow.com/questions/68709496/searching-takes-forever-on-readthedocs-when-the-phrase-is-not-present-on-th that say some older versions of `sphinx_rtd_theme` had this issue, but we're well past those versions and I don't think anything connected to RTD is pinned to older versions. I'm not sure which versions RTD uses when it actually builds the site.

### Next Steps

- Figure out what's wrong.
- Fix it. 😄

**Comment by eurunuela** [comment]
I am unable to observe this issue as of Nov 22, 2023.

Could you try again @n-reddy @handwerkerd and see if the issue persists for you?

**Comment by tsalo** [comment]
Same. I think the problem may have resolved itself. My guess is that it was an issue on RTD's side.

**Comment by eurunuela** [comment]
@handwerkerd, could you please close the issue when you confirm it works on your side? Thanks!

**Comment by handwerkerd** [comment]
It's working for me now as well. I guess this was on their end, not ours.
